function [covarianceHistory,dOptimalityHistory] = ...
    propagateNetworkCovariance( ...
        initialCovariance, ...
        stateTransitionHistory, ...
        processNoiseHistory, ...
        measurementJacobianHistory, ...
        measurementAvailable, ...
        selectedSensors, ...
        measurementCovariances, ...
        stateScales)
% PROPAGATENETWORKCOVARIANCE Run a covariance-only network EKF.
%
% Inputs:
%   initialCovariance          - 6x6 fixed covariance at the initial epoch
%   stateTransitionHistory     - 6x6xN interval STMs
%   processNoiseHistory        - 6x6xN discrete process covariances
%   measurementJacobianHistory - 2x6xSxN measurement Jacobians
%   measurementAvailable       - SxN LOS gates
%   selectedSensors            - Sx1 binary/logical sensor-selection vector
%   measurementCovariances     - 2x2 or 2x2xS RA/Dec covariances
%   stateScales                - 6x1 state normalization scales
%
% Outputs:
%   covarianceHistory  - 6x6xN posterior covariance history
%   dOptimalityHistory - Nx1 values of -log(det(normalized covariance))
%
% Every call begins from the same initialCovariance. Covariance is not
% carried between separate candidate-network evaluations.

arguments
    initialCovariance (6,6) double
    stateTransitionHistory (6,6,:) double
    processNoiseHistory (6,6,:) double
    measurementJacobianHistory (2,6,:,:) double
    measurementAvailable (:,:) logical
    selectedSensors (:,1)
    measurementCovariances double
    stateScales (6,1) double {mustBePositive}
end

numberOfTimes = ...
    size(stateTransitionHistory,3);

numberOfSensors = ...
    size(measurementJacobianHistory,3);

if size(processNoiseHistory,3) ~= numberOfTimes || ...
        size(measurementJacobianHistory,4) ~= numberOfTimes || ...
        size(measurementAvailable,2) ~= numberOfTimes

    error( ...
        "propagateNetworkCovariance:InvalidTimeDimensions", ...
        "All time histories must contain the same number of epochs.");
end

if size(measurementAvailable,1) ~= numberOfSensors || ...
        length(selectedSensors) ~= numberOfSensors

    error( ...
        "propagateNetworkCovariance:InvalidSensorDimensions", ...
        "Sensor dimensions are inconsistent.");
end

if size(measurementCovariances,1) ~= 2 || ...
        size(measurementCovariances,2) ~= 2

    error( ...
        "propagateNetworkCovariance:InvalidMeasurementCovariance", ...
        "Measurement covariance must begin with dimensions 2x2.");
end

numberOfMeasurementCovariances = ...
    size(measurementCovariances,3);

if numberOfMeasurementCovariances ~= 1 && ...
        numberOfMeasurementCovariances ~= numberOfSensors

    error( ...
        "propagateNetworkCovariance:InvalidMeasurementCovariance", ...
        "Provide one shared covariance or one covariance per sensor.");
end

selectedSensors = ...
    logical(selectedSensors);

currentCovariance = ...
    0.5*(initialCovariance + initialCovariance');

[~,initialCovarianceFlag] = ...
    chol(currentCovariance,"lower");

if initialCovarianceFlag ~= 0
    error( ...
        "propagateNetworkCovariance:InvalidInitialCovariance", ...
        "The initial covariance must be positive definite.");
end

% Validate all supplied measurement covariances once.
for covarianceIndex = 1:numberOfMeasurementCovariances

    measurementCovariance = ...
        measurementCovariances(:,:,covarianceIndex);

    measurementCovariance = ...
        0.5*(measurementCovariance + ...
        measurementCovariance');

    [~,measurementCovarianceFlag] = ...
        chol(measurementCovariance,"lower");

    if measurementCovarianceFlag ~= 0
        error( ...
            "propagateNetworkCovariance:InvalidMeasurementCovariance", ...
            "Every measurement covariance must be positive definite.");
    end
end

covarianceHistory = ...
    zeros(6,6,numberOfTimes);

dOptimalityHistory = ...
    zeros(numberOfTimes,1);

identityMatrix = eye(6);

normalizationMatrix = ...
    diag(1./stateScales);

for timeIndex = 1:numberOfTimes

    %% Covariance prediction

    stateTransitionMatrix = ...
        stateTransitionHistory(:,:,timeIndex);

    processNoise = ...
        processNoiseHistory(:,:,timeIndex);

    predictedCovariance = ...
        stateTransitionMatrix*currentCovariance* ...
        stateTransitionMatrix' + processNoise;

    predictedCovariance = ...
        0.5*(predictedCovariance + ...
        predictedCovariance');

    %% Determine active measurements

    activeSensors = find( ...
        selectedSensors & ...
        measurementAvailable(:,timeIndex));

    numberOfActiveSensors = ...
        length(activeSensors);

    if numberOfActiveSensors > 0

        stackedJacobian = ...
            zeros(2*numberOfActiveSensors,6);

        stackedMeasurementCovariance = ...
            zeros(2*numberOfActiveSensors);

        for activeIndex = 1:numberOfActiveSensors

            sensorIndex = ...
                activeSensors(activeIndex);

            measurementRows = ...
                2*activeIndex - 1 : 2*activeIndex;

            stackedJacobian(measurementRows,:) = ...
                measurementJacobianHistory( ...
                    :,:,sensorIndex,timeIndex);

            if numberOfMeasurementCovariances == 1
                sensorMeasurementCovariance = ...
                    measurementCovariances(:,:,1);
            else
                sensorMeasurementCovariance = ...
                    measurementCovariances(:,:,sensorIndex);
            end

            stackedMeasurementCovariance( ...
                measurementRows,measurementRows) = ...
                sensorMeasurementCovariance;
        end

        %% Joseph-stabilized covariance update

        innovationCovariance = ...
            stackedJacobian*predictedCovariance* ...
            stackedJacobian' + ...
            stackedMeasurementCovariance;

        kalmanGain = ...
            (predictedCovariance*stackedJacobian') / ...
            innovationCovariance;

        covarianceFactor = ...
            identityMatrix - ...
            kalmanGain*stackedJacobian;

        updatedCovariance = ...
            covarianceFactor*predictedCovariance* ...
            covarianceFactor' + ...
            kalmanGain*stackedMeasurementCovariance* ...
            kalmanGain';
    else
        updatedCovariance = predictedCovariance;
    end

    updatedCovariance = ...
        0.5*(updatedCovariance + ...
        updatedCovariance');

    %% D-optimality

    normalizedCovariance = ...
        normalizationMatrix*updatedCovariance* ...
        normalizationMatrix';

    normalizedCovariance = ...
        0.5*(normalizedCovariance + ...
        normalizedCovariance');

    [covarianceFactor,cholFlag] = ...
        chol(normalizedCovariance,"lower");

    if cholFlag ~= 0
        error( ...
            "propagateNetworkCovariance:NonPositiveCovariance", ...
            "Covariance is not positive definite at time index %d.", ...
            timeIndex);
    end

    logDeterminant = ...
        2*sum(log(diag(covarianceFactor)));

    dOptimalityHistory(timeIndex) = ...
        -logDeterminant;

    covarianceHistory(:,:,timeIndex) = ...
        updatedCovariance;

    currentCovariance = updatedCovariance;
end

end