function [filteredAvailability,diagnostics] = ...
    buildFilteredVisibilityDatabase( ...
        times, ...
        targetStateHistories, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        horizonAzimuths, ...
        maximumTerrainElevation, ...
        earthPositionsMci, ...
        sunPositionsMci, ...
        instrumentMinimumElevation, ...
        horizonMargin, ...
        earthRadius, ...
        sunRadius, ...
        earthLimbMargin, ...
        sunLimbMargin, ...
        moonRadius, ...
        theta0, ...
        angularRate)
% BUILDFILTEREDVISIBILITYDATABASE Apply terrain and celestial constraints.
%
% Inputs:
%   times                       - Nx1 observation times, s
%   targetStateHistories        - 6xNxO target MCI state histories
%   candidateLatitudes          - Sx1 sensor latitudes, rad
%   candidateLongitudes         - Sx1 east-positive longitudes, rad
%   dem                         - Processed lunar griddedInterpolant
%   horizonAzimuths             - Ax1 terrain-horizon azimuth bins, rad
%   maximumTerrainElevation     - SxA terrain-horizon angles, rad
%   earthPositionsMci           - 3xN Earth-center MCI positions, km
%   sunPositionsMci             - 3xN Sun-center MCI positions, km
%   instrumentMinimumElevation  - Instrument elevation threshold, rad
%   horizonMargin               - Additional terrain-horizon margin, rad
%   earthRadius                 - Earth radius, km
%   sunRadius                   - Sun radius, km
%   earthLimbMargin             - Keep-out angle beyond Earth limb, rad
%   sunLimbMargin               - Keep-out angle beyond Sun limb, rad
%   moonRadius                  - Lunar reference radius, km
%   theta0                      - Initial Moon rotation angle, rad
%   angularRate                 - Lunar rotation rate, rad/s
%
% Outputs:
%   filteredAvailability - SxNxO fully filtered measurement gate
%   diagnostics          - Constraint masks and geometry histories
%
% The final gate is
%
%   G = Gterrain AND NOT(Goccultation) AND NOT(Gexclusion).
%
% Mutually exclusive rejection masks are also returned so that
%
%   geometric opportunities = terrain rejected + occlusion rejected
%                           + exclusion rejected + accepted.

arguments
    times (:,1) double
    targetStateHistories (6,:,:) double
    candidateLatitudes (:,1) double
    candidateLongitudes (:,1) double
    dem (1,1) griddedInterpolant
    horizonAzimuths double
    maximumTerrainElevation (:,:) double
    earthPositionsMci (3,:) double
    sunPositionsMci (3,:) double
    instrumentMinimumElevation (1,1) double = 0
    horizonMargin (1,1) double {mustBeNonnegative} = 0
    earthRadius (1,1) double {mustBePositive} = 6378.1366
    sunRadius (1,1) double {mustBePositive} = 695700
    earthLimbMargin (1,1) double {mustBeNonnegative} = 0
    sunLimbMargin (1,1) double {mustBeNonnegative} = 0
    moonRadius (1,1) double {mustBePositive} = 1737.4
    theta0 (1,1) double = 0
    angularRate (1,1) double = 2*pi/(27.321661*86400)
end

numberOfTimes = length(times);
numberOfSensors = length(candidateLatitudes);
numberOfObjects = size(targetStateHistories,3);

if size(targetStateHistories,2) ~= numberOfTimes
    error( ...
        "buildFilteredVisibilityDatabase:InvalidTargetDimensions", ...
        "targetStateHistories must contain one state per time.");
end

if length(candidateLongitudes) ~= numberOfSensors
    error( ...
        "buildFilteredVisibilityDatabase:InvalidSensorDimensions", ...
        "Candidate latitude and longitude arrays must have equal length.");
end

if size(maximumTerrainElevation,1) ~= numberOfSensors
    error( ...
        "buildFilteredVisibilityDatabase:InvalidHorizonDimensions", ...
        "maximumTerrainElevation must contain one row per sensor.");
end

if size(earthPositionsMci,2) ~= numberOfTimes || ...
        size(sunPositionsMci,2) ~= numberOfTimes

    error( ...
        "buildFilteredVisibilityDatabase:InvalidEphemerisDimensions", ...
        "Earth and Sun histories must contain one position per time.");
end

%% Terrain-aware visibility

[terrainAvailability, ...
    targetAzimuths, ...
    targetElevations, ...
    targetRanges, ...
    limitingTerrainElevations] = ...
    optimization.buildTerrainAwareLosDatabase( ...
        times, ...
        targetStateHistories, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        horizonAzimuths, ...
        maximumTerrainElevation, ...
        instrumentMinimumElevation, ...
        horizonMargin, ...
        moonRadius, ...
        theta0, ...
        angularRate);

terrainAvailability = reshape( ...
    terrainAvailability, ...
    numberOfSensors,numberOfTimes,numberOfObjects);

targetAzimuths = reshape( ...
    targetAzimuths, ...
    numberOfSensors,numberOfTimes,numberOfObjects);

targetElevations = reshape( ...
    targetElevations, ...
    numberOfSensors,numberOfTimes,numberOfObjects);

targetRanges = reshape( ...
    targetRanges, ...
    numberOfSensors,numberOfTimes,numberOfObjects);

limitingTerrainElevations = reshape( ...
    limitingTerrainElevations, ...
    numberOfSensors,numberOfTimes,numberOfObjects);

geometricAvailability = ...
    targetElevations >= instrumentMinimumElevation;

%% Allocate celestial diagnostics

earthOccluded = false(numberOfSensors,numberOfTimes,numberOfObjects);
sunOccluded = false(numberOfSensors,numberOfTimes,numberOfObjects);
earthExcluded = false(numberOfSensors,numberOfTimes,numberOfObjects);
sunExcluded = false(numberOfSensors,numberOfTimes,numberOfObjects);

earthSeparation = zeros(numberOfSensors,numberOfTimes,numberOfObjects);
sunSeparation = zeros(numberOfSensors,numberOfTimes,numberOfObjects);

earthRequiredSeparation = ...
    zeros(numberOfSensors,numberOfTimes,numberOfObjects);

sunRequiredSeparation = ...
    zeros(numberOfSensors,numberOfTimes,numberOfObjects);

%% Fixed sensor states in the Moon-rotating frame

sensorStatesMoonRotating = zeros(6,numberOfSensors);

for sensorIndex = 1:numberOfSensors
    sensorStatesMoonRotating(:,sensorIndex) = ...
        referenceFrames.topographic( ...
            zeros(6,1), ...
            candidateLatitudes(sensorIndex), ...
            mod(candidateLongitudes(sensorIndex),2*pi), ...
            dem, ...
            moonRadius, ...
            "toRotating");
end

%% Celestial visibility at every sensor, time, and object

for timeIndex = 1:numberOfTimes
    observationTime = times(timeIndex);
    earthPosition = earthPositionsMci(:,timeIndex);
    sunPosition = sunPositionsMci(:,timeIndex);

    sensorPositionsMci = zeros(3,numberOfSensors);

    for sensorIndex = 1:numberOfSensors
        sensorStateMci = referenceFrames.moonRotating( ...
            sensorStatesMoonRotating(:,sensorIndex), ...
            observationTime, ...
            theta0, ...
            angularRate, ...
            "toInertial");

        sensorPositionsMci(:,sensorIndex) = sensorStateMci(1:3);
    end

    for objectIndex = 1:numberOfObjects
        targetPosition = targetStateHistories(1:3,timeIndex,objectIndex);

        for sensorIndex = 1:numberOfSensors
            [~,objectEarthOccluded,objectSunOccluded, ...
                objectEarthExcluded,objectSunExcluded, ...
                objectEarthSeparation,objectSunSeparation, ...
                objectEarthRequiredSeparation, ...
                objectSunRequiredSeparation] = ...
                constraints.celestialVisibility( ...
                    sensorPositionsMci(:,sensorIndex), ...
                    targetPosition, ...
                    earthPosition, ...
                    sunPosition, ...
                    earthRadius, ...
                    sunRadius, ...
                    earthLimbMargin, ...
                    sunLimbMargin);

            earthOccluded(sensorIndex,timeIndex,objectIndex) = ...
                objectEarthOccluded;

            sunOccluded(sensorIndex,timeIndex,objectIndex) = ...
                objectSunOccluded;

            earthExcluded(sensorIndex,timeIndex,objectIndex) = ...
                objectEarthExcluded;

            sunExcluded(sensorIndex,timeIndex,objectIndex) = ...
                objectSunExcluded;

            earthSeparation(sensorIndex,timeIndex,objectIndex) = ...
                objectEarthSeparation;

            sunSeparation(sensorIndex,timeIndex,objectIndex) = ...
                objectSunSeparation;

            earthRequiredSeparation(sensorIndex,timeIndex,objectIndex) = ...
                objectEarthRequiredSeparation;

            sunRequiredSeparation(sensorIndex,timeIndex,objectIndex) = ...
                objectSunRequiredSeparation;
        end
    end
end

%% Final and diagnostic gates

occlusionFailure = earthOccluded | sunOccluded;
exclusionFailure = earthExcluded | sunExcluded;

celestialAvailability = ...
    ~occlusionFailure & ~exclusionFailure;

filteredAvailability = ...
    terrainAvailability & celestialAvailability;

% These masks are mutually exclusive and are defined only among epochs
% that satisfy the basic geometric minimum-elevation requirement.
terrainRejected = ...
    geometricAvailability & ~terrainAvailability;

occlusionRejected = ...
    terrainAvailability & occlusionFailure;

exclusionRejected = ...
    terrainAvailability & ~occlusionFailure & exclusionFailure;

accepted = filteredAvailability;

reconstructedGeometricAvailability = ...
    terrainRejected | occlusionRejected | exclusionRejected | accepted;

if ~isequal( ...
        reconstructedGeometricAvailability, ...
        geometricAvailability)

    error( ...
        "buildFilteredVisibilityDatabase:GateAccountingFailure", ...
        "The mutually exclusive gate masks do not reconstruct geometric availability.");
end

diagnostics = struct();

diagnostics.geometricAvailability = geometricAvailability;
diagnostics.terrainAvailability = terrainAvailability;
diagnostics.celestialAvailability = celestialAvailability;

diagnostics.earthOccluded = earthOccluded;
diagnostics.sunOccluded = sunOccluded;
diagnostics.earthExcluded = earthExcluded;
diagnostics.sunExcluded = sunExcluded;

diagnostics.terrainRejected = terrainRejected;
diagnostics.occlusionRejected = occlusionRejected;
diagnostics.exclusionRejected = exclusionRejected;
diagnostics.accepted = accepted;

diagnostics.targetAzimuths = targetAzimuths;
diagnostics.targetElevations = targetElevations;
diagnostics.targetRanges = targetRanges;
diagnostics.limitingTerrainElevations = limitingTerrainElevations;

diagnostics.earthSeparation = earthSeparation;
diagnostics.sunSeparation = sunSeparation;
diagnostics.earthRequiredSeparation = earthRequiredSeparation;
diagnostics.sunRequiredSeparation = sunRequiredSeparation;

end
