function chunkMetadata = buildFinalCandidateChunks( ...
    chunkMetadata, ...
    candidateKeepMask, ...
    retainedIndexByOriginal, ...
    referenceStateHistories, ...
    optimizationTimes, ...
    dem, ...
    earthPositionsMci, ...
    sunPositionsMci, ...
    visibilityConfig, ...
    terrainConfig, ...
    moonRadius, ...
    theta0, ...
    moonAngularRate, ...
    useParallel, ...
    maximumParallelWorkers, ...
    reuseExisting)
% BUILDFINALCANDIDATECHUNKS Build final visibility and full 2x6 Jacobians.
%
% Each candidate chunk remains independent from production start to finish.
% Full Jacobians are written to the v7.3 chunk file one object at a time so
% no worker needs to hold an entire ~11-GiB chunk Jacobian array in memory.

arguments
    chunkMetadata (:,1) struct
    candidateKeepMask (:,1) logical
    retainedIndexByOriginal (:,1) uint32
    referenceStateHistories (6,:,:) double
    optimizationTimes (:,1) double
    dem (1,1) griddedInterpolant
    earthPositionsMci (3,:) double
    sunPositionsMci (3,:) double
    visibilityConfig (1,1) struct
    terrainConfig (1,1) struct
    moonRadius (1,1) double {mustBePositive}
    theta0 (1,1) double
    moonAngularRate (1,1) double
    useParallel (1,1) logical = false
    maximumParallelWorkers (1,1) double {mustBeInteger,mustBePositive} = 2
    reuseExisting (1,1) logical = false
end

numberOfChunks = numel(chunkMetadata);
retainedCounts = zeros(numberOfChunks,1);

for chunkIndex = 1:numberOfChunks
    firstIndex = chunkMetadata(chunkIndex).firstOriginalCandidateIndex;
    lastIndex = chunkMetadata(chunkIndex).lastOriginalCandidateIndex;
    retainedCounts(chunkIndex) = nnz(candidateKeepMask(firstIndex:lastIndex));
    chunkMetadata(chunkIndex).numberOfRetainedCandidates = ...
        retainedCounts(chunkIndex);
end

fprintf("\n9/9 Building final visibility and Jacobian chunks...\n");
fprintf("  Retained candidates by chunk: ");
fprintf("%d ",retainedCounts);
fprintf("\n");
fprintf("  Parallel: %d (max workers %d)\n", ...
    useParallel,maximumParallelWorkers);

if useParallel
    parfor (chunkIndex = 1:numberOfChunks,maximumParallelWorkers)
        buildOneFinalChunk( ...
            chunkMetadata(chunkIndex), ...
            candidateKeepMask, ...
            retainedIndexByOriginal, ...
            referenceStateHistories, ...
            optimizationTimes, ...
            dem, ...
            earthPositionsMci, ...
            sunPositionsMci, ...
            visibilityConfig, ...
            terrainConfig, ...
            moonRadius, ...
            theta0, ...
            moonAngularRate, ...
            reuseExisting);
    end
else
    for chunkIndex = 1:numberOfChunks
        buildOneFinalChunk( ...
            chunkMetadata(chunkIndex), ...
            candidateKeepMask, ...
            retainedIndexByOriginal, ...
            referenceStateHistories, ...
            optimizationTimes, ...
            dem, ...
            earthPositionsMci, ...
            sunPositionsMci, ...
            visibilityConfig, ...
            terrainConfig, ...
            moonRadius, ...
            theta0, ...
            moonAngularRate, ...
            reuseExisting);
    end
end

end

function buildOneFinalChunk( ...
    metadata,candidateKeepMask,retainedIndexByOriginal, ...
    referenceStateHistories,optimizationTimes,dem,earthPositionsMci, ...
    sunPositionsMci,visibilityConfig,terrainConfig,moonRadius,theta0, ...
    moonAngularRate,reuseExisting)

chunkFile = string(metadata.filePath);

originalIndices = ...
    (metadata.firstOriginalCandidateIndex: ...
     metadata.lastOriginalCandidateIndex).';

localKeepMask = candidateKeepMask(originalIndices);

retainedOriginalCandidateIndices = ...
    uint32(originalIndices(localKeepMask));

retainedGlobalCandidateIndices = ...
    retainedIndexByOriginal(originalIndices(localKeepMask));

numberOfCandidates = numel(retainedGlobalCandidateIndices);
numberOfTimes = numel(optimizationTimes);
numberOfObjects = size(referenceStateHistories,3);

if reuseExisting && isfile(chunkFile)
    variableNames = string(who("-file",chunkFile));

    requiredVariables = [ ...
        "retainedOriginalCandidateIndices", ...
        "retainedGlobalCandidateIndices", ...
        "filteredAvailability"];

    if numberOfCandidates > 0
        requiredVariables(end+1) = "measurementJacobianHistories";
    end

    if all(ismember(requiredVariables,variableNames))
        chunkMat = matfile(chunkFile);

        storedOriginal = ...
            double(chunkMat.retainedOriginalCandidateIndices(:,1));

        storedGlobal = ...
            double(chunkMat.retainedGlobalCandidateIndices(:,1));

        availabilitySize = ...
            size(chunkMat,"filteredAvailability");

        complete = ...
            isequal(storedOriginal,double(retainedOriginalCandidateIndices)) && ...
            isequal(storedGlobal,double(retainedGlobalCandidateIndices)) && ...
            isequal(availabilitySize, ...
                [numberOfCandidates,numberOfTimes,numberOfObjects]);

        if complete && numberOfCandidates > 0
            jacobianSize = ...
                size(chunkMat,"measurementJacobianHistories");

            complete = isequal( ...
                jacobianSize, ...
                [2,6,numberOfCandidates,numberOfTimes,numberOfObjects]);
        end

        if complete
            fprintf("  Reusing final chunk %d (%d retained sites)\n", ...
                metadata.chunkNumber,numberOfCandidates);
            return
        end
    end
end

data = load( ...
    chunkFile, ...
    "originalCandidateIndices", ...
    "candidateLatitudesRad", ...
    "candidateLongitudesRad", ...
    "horizonAzimuthsRad", ...
    "maximumTerrainElevationRad");

assert(isequal(double(data.originalCandidateIndices(:)),originalIndices), ...
    "Chunk %d original candidate indices are inconsistent.", ...
    metadata.chunkNumber);

candidateLatitudesRad = data.candidateLatitudesRad(localKeepMask);
candidateLongitudesRad = data.candidateLongitudesRad(localKeepMask);
retainedMaximumTerrainElevationRad = ...
    data.maximumTerrainElevationRad(localKeepMask,:);

fprintf("  Final chunk %d: %d retained sites\n", ...
    metadata.chunkNumber,numberOfCandidates);

if numberOfCandidates == 0
    filteredAvailability = false(0,numberOfTimes,numberOfObjects); %#ok<NASGU>
    save( ...
        chunkFile, ...
        "retainedOriginalCandidateIndices", ...
        "retainedGlobalCandidateIndices", ...
        "filteredAvailability", ...
        "-append");
    return
end

filteredAvailability = optimization.buildFilteredVisibilityMasks( ...
    optimizationTimes, ...
    referenceStateHistories, ...
    candidateLatitudesRad, ...
    candidateLongitudesRad, ...
    dem, ...
    data.horizonAzimuthsRad, ...
    retainedMaximumTerrainElevationRad, ...
    earthPositionsMci, ...
    sunPositionsMci, ...
    visibilityConfig.minimumElevationRad, ...
    terrainConfig.horizonMarginRad, ...
    visibilityConfig.earthRadiusKm, ...
    visibilityConfig.sunRadiusKm, ...
    visibilityConfig.sunMinimumAngularSeparationRad, ...
    moonRadius, ...
    theta0, ...
    moonAngularRate, ...
    visibilityConfig.earthMinimumAngularSeparationRad);

save( ...
    chunkFile, ...
    "retainedOriginalCandidateIndices", ...
    "retainedGlobalCandidateIndices", ...
    "filteredAvailability", ...
    "-append");

chunkMat = matfile(chunkFile,"Writable",true);

% Preallocate the on-disk full-state Jacobian array without allocating the
% complete chunk in worker memory.
chunkMat.measurementJacobianHistories( ...
    2,6,numberOfCandidates,numberOfTimes,numberOfObjects) = 0;

for objectIndex = 1:numberOfObjects
    objectJacobians = zeros(2,6,numberOfCandidates,numberOfTimes);

    for timeIndex = 1:numberOfTimes
        targetState = referenceStateHistories(:,timeIndex,objectIndex);
        observationTime = optimizationTimes(timeIndex);

        for localIndex = 1:numberOfCandidates
            objectJacobians(:,:,localIndex,timeIndex) = ...
                measurements.surfaceRaDecJacobian( ...
                    targetState, ...
                    observationTime, ...
                    candidateLatitudesRad(localIndex), ...
                    candidateLongitudesRad(localIndex), ...
                    dem, ...
                    moonRadius, ...
                    theta0, ...
                    moonAngularRate);
        end
    end

    chunkMat.measurementJacobianHistories( ...
        :,:,:,:,objectIndex) = objectJacobians;

    fprintf("    Chunk %d Jacobians: object %d/%d\n", ...
        metadata.chunkNumber,objectIndex,numberOfObjects);
end

end
