function [chunkMetadata,candidateChunkIndex,candidateLocalIndex] = ...
    buildMeasurementJacobianChunks( ...
        chunkDirectory, ...
        numberOfChunks, ...
        useParallel, ...
        maximumParallelWorkers, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        referenceStateHistories, ...
        observationTimes, ...
        dem, ...
        moonRadius, ...
        theta0, ...
        angularRate, ...
        overwriteExisting)
% BUILDMEASUREMENTJACOBIANCHUNKS Build equal-count full-state RA/Dec chunks.
%
% The retained global candidate list is partitioned into contiguous chunks
% containing as nearly equal a number of candidates as possible. Each chunk
% stores the original full 2x6 RA/Dec Jacobian, including the identically
% zero direct-velocity columns. This keeps objective evaluation as a lookup
% while avoiding one MATLAB array larger than the maximum-array preference.
%
% Files contain top-level variables for efficient MATFILE partial indexing:
%   measurementJacobianHistories - 2x6xNcChunkxNtxNobj double
%   globalCandidateIndices       - NcChunkx1 uint32
%   chunkNumber                  - scalar uint16
%
% candidateChunkIndex/globalCandidateIndex are one-to-one maps from the
% retained optimization candidate index to its chunk and local index.

arguments
    chunkDirectory (1,1) string
    numberOfChunks (1,1) double {mustBeInteger,mustBePositive}
    useParallel (1,1) logical = false
    maximumParallelWorkers (1,1) double {mustBeInteger,mustBePositive} = 2
    candidateLatitudes (:,1) double
    candidateLongitudes (:,1) double
    referenceStateHistories (6,:,:) double
    observationTimes (:,1) double
    dem (1,1) griddedInterpolant
    moonRadius (1,1) double {mustBePositive} = 1737.4
    theta0 (1,1) double = 0
    angularRate (1,1) double = 2*pi/(27.321661*86400)
    overwriteExisting (1,1) logical = false
end

numberOfCandidates = numel(candidateLatitudes);
numberOfTimes = numel(observationTimes);
numberOfObjects = size(referenceStateHistories,3);

assert(numel(candidateLongitudes) == numberOfCandidates, ...
    "Candidate latitude and longitude arrays must have equal length.");
assert(size(referenceStateHistories,2) == numberOfTimes, ...
    "Reference-state and observation-time dimensions are inconsistent.");
assert(numberOfChunks <= numberOfCandidates, ...
    "Number of chunks cannot exceed the retained candidate count.");

if ~isfolder(chunkDirectory)
    mkdir(chunkDirectory);
end

baseChunkSize = floor(numberOfCandidates/numberOfChunks);
remainder = mod(numberOfCandidates,numberOfChunks);
chunkCounts = baseChunkSize*ones(numberOfChunks,1);
chunkCounts(1:remainder) = chunkCounts(1:remainder) + 1;

chunkStarts = cumsum([1;chunkCounts(1:end-1)]);
chunkEnds = cumsum(chunkCounts);

candidateChunkIndex = zeros(numberOfCandidates,1,"uint16");
candidateLocalIndex = zeros(numberOfCandidates,1,"uint32");
chunkMetadata = repmat(struct( ...
    "chunkNumber",0, ...
    "filePath","", ...
    "firstGlobalCandidateIndex",0, ...
    "lastGlobalCandidateIndex",0, ...
    "numberOfCandidates",0),numberOfChunks,1);

chunkFiles = strings(numberOfChunks,1);
globalIndexCells = cell(numberOfChunks,1);

for chunkIndex = 1:numberOfChunks
    globalIndices = (chunkStarts(chunkIndex):chunkEnds(chunkIndex)).';
    globalIndexCells{chunkIndex} = globalIndices;

    candidateChunkIndex(globalIndices) = uint16(chunkIndex);
    candidateLocalIndex(globalIndices) = uint32((1:numel(globalIndices)).');

    chunkFile = fullfile(chunkDirectory, ...
        sprintf("measurement_jacobian_chunk_%02d.mat",chunkIndex));
    chunkFiles(chunkIndex) = string(chunkFile);

    if isfile(chunkFile) && ~overwriteExisting
        error( ...
            "buildMeasurementJacobianChunks:ChunkExists", ...
            "Jacobian chunk already exists: %s",chunkFile);
    end

    chunkMetadata(chunkIndex).chunkNumber = chunkIndex;
    chunkMetadata(chunkIndex).filePath = string(chunkFile);
    chunkMetadata(chunkIndex).firstGlobalCandidateIndex = globalIndices(1);
    chunkMetadata(chunkIndex).lastGlobalCandidateIndex = globalIndices(end);
    chunkMetadata(chunkIndex).numberOfCandidates = numel(globalIndices);
end

fprintf("\nBuilding %d equal-count Jacobian chunks.\n",numberOfChunks);
fprintf("  Retained candidates: %d\n",numberOfCandidates);
fprintf("  Chunk sizes: ");
fprintf("%d ",chunkCounts);
fprintf("\n");

parallelAvailable = useParallel && ...
    license("test","Distrib_Computing_Toolbox");

if useParallel && ~parallelAvailable
    warning( ...
        "buildMeasurementJacobianChunks:ParallelUnavailable", ...
        "Parallel Computing Toolbox is unavailable; building chunks serially.");
end

if parallelAvailable
    fprintf("  Parallel chunk workers: up to %d\n",maximumParallelWorkers);
    parfor (chunkIndex = 1:numberOfChunks,maximumParallelWorkers)
        buildOneChunk( ...
            chunkFiles(chunkIndex), ...
            chunkIndex, ...
            globalIndexCells{chunkIndex}, ...
            candidateLatitudes, ...
            candidateLongitudes, ...
            referenceStateHistories, ...
            observationTimes, ...
            dem, ...
            moonRadius, ...
            theta0, ...
            angularRate);
    end
else
    for chunkIndex = 1:numberOfChunks
        buildOneChunk( ...
            chunkFiles(chunkIndex), ...
            chunkIndex, ...
            globalIndexCells{chunkIndex}, ...
            candidateLatitudes, ...
            candidateLongitudes, ...
            referenceStateHistories, ...
            observationTimes, ...
            dem, ...
            moonRadius, ...
            theta0, ...
            angularRate);
    end
end

for chunkIndex = 1:numberOfChunks
    assert(isfile(chunkFiles(chunkIndex)), ...
        "Expected Jacobian chunk was not created: %s",chunkFiles(chunkIndex));
end

end

function buildOneChunk( ...
    outputFile,chunkIndex,globalIndices,candidateLatitudes, ...
    candidateLongitudes,referenceStateHistories,observationTimes, ...
    dem,moonRadius,theta0,angularRate)

numberOfChunkCandidates = numel(globalIndices);
numberOfTimes = numel(observationTimes);
numberOfObjects = size(referenceStateHistories,3);

fprintf("  Chunk %d: candidates %d-%d (%d sites)\n", ...
    chunkIndex,globalIndices(1),globalIndices(end),numberOfChunkCandidates);

measurementJacobianHistories = zeros( ...
    2,6,numberOfChunkCandidates,numberOfTimes,numberOfObjects);

for objectIndex = 1:numberOfObjects
    for timeIndex = 1:numberOfTimes
        state = referenceStateHistories(:,timeIndex,objectIndex);
        observationTime = observationTimes(timeIndex);

        for localIndex = 1:numberOfChunkCandidates
            globalIndex = globalIndices(localIndex);

            measurementJacobianHistories(:,:,localIndex,timeIndex,objectIndex) = ...
                measurements.surfaceRaDecJacobian( ...
                    state, ...
                    observationTime, ...
                    candidateLatitudes(globalIndex), ...
                    candidateLongitudes(globalIndex), ...
                    dem, ...
                    moonRadius, ...
                    theta0, ...
                    angularRate);
        end
    end
end

globalCandidateIndices = uint32(globalIndices); %#ok<NASGU>
chunkNumber = uint16(chunkIndex); %#ok<NASGU>

save( ...
    outputFile, ...
    "measurementJacobianHistories", ...
    "globalCandidateIndices", ...
    "chunkNumber", ...
    "-v7.3");

end
