function [horizonAzimuths,sensorElevationsAll] = ...
    buildCandidateTerrainChunks( ...
        chunkMetadata, ...
        candidateLatitudesAll, ...
        candidateLongitudesAll, ...
        dem, ...
        terrainConfig, ...
        moonRadius, ...
        useParallel, ...
        maximumParallelWorkers, ...
        overwriteExisting)
% BUILDCANDIDATETERRAINCHUNKS Build terrain horizons from the start in chunks.

arguments
    chunkMetadata (:,1) struct
    candidateLatitudesAll (:,1) double
    candidateLongitudesAll (:,1) double
    dem (1,1) griddedInterpolant
    terrainConfig (1,1) struct
    moonRadius (1,1) double {mustBePositive}
    useParallel (1,1) logical = false
    maximumParallelWorkers (1,1) double {mustBeInteger,mustBePositive} = 2
    overwriteExisting (1,1) logical = false
end

numberOfChunks = numel(chunkMetadata);
numberOfCandidates = numel(candidateLatitudesAll);

assert(numel(candidateLongitudesAll) == numberOfCandidates);

chunkSensorElevation = cell(numberOfChunks,1);
chunkAzimuths = cell(numberOfChunks,1);

fprintf("\n3/9 Building terrain-horizon chunks...\n");
fprintf("  Chunks: %d\n",numberOfChunks);
fprintf("  Parallel: %d (max workers %d)\n", ...
    useParallel,maximumParallelWorkers);

if useParallel
    parfor (chunkIndex = 1:numberOfChunks,maximumParallelWorkers)
        [chunkAzimuths{chunkIndex},chunkSensorElevation{chunkIndex}] = ...
            buildOneTerrainChunk( ...
                chunkMetadata(chunkIndex), ...
                candidateLatitudesAll, ...
                candidateLongitudesAll, ...
                dem, ...
                terrainConfig, ...
                moonRadius, ...
                overwriteExisting);
    end
else
    for chunkIndex = 1:numberOfChunks
        [chunkAzimuths{chunkIndex},chunkSensorElevation{chunkIndex}] = ...
            buildOneTerrainChunk( ...
                chunkMetadata(chunkIndex), ...
                candidateLatitudesAll, ...
                candidateLongitudesAll, ...
                dem, ...
                terrainConfig, ...
                moonRadius, ...
                overwriteExisting);
    end
end

horizonAzimuths = chunkAzimuths{1};

for chunkIndex = 2:numberOfChunks
    assert(isequal(chunkAzimuths{chunkIndex},horizonAzimuths), ...
        "Terrain chunks do not share the same azimuth grid.");
end

sensorElevationsAll = vertcat(chunkSensorElevation{:});

assert(numel(sensorElevationsAll) == numberOfCandidates);
assert(all(isfinite(sensorElevationsAll)));

end

function [horizonAzimuths,sensorElevations] = buildOneTerrainChunk( ...
    metadata,candidateLatitudesAll,candidateLongitudesAll,dem, ...
    terrainConfig,moonRadius,overwriteExisting)

firstIndex = metadata.firstOriginalCandidateIndex;
lastIndex = metadata.lastOriginalCandidateIndex;
originalCandidateIndices = (firstIndex:lastIndex).';

chunkFile = string(metadata.filePath);

if isfile(chunkFile)
    if overwriteExisting
        delete(chunkFile);
    else
        error( ...
            "buildCandidateTerrainChunks:ChunkExists", ...
            "Candidate chunk already exists: %s",chunkFile);
    end
end

candidateLatitudesRad = candidateLatitudesAll(originalCandidateIndices);
candidateLongitudesRad = candidateLongitudesAll(originalCandidateIndices);

fprintf("  Terrain chunk %d: original candidates %d-%d (%d sites)\n", ...
    metadata.chunkNumber,firstIndex,lastIndex,numel(originalCandidateIndices));

[horizonAzimuths,maximumTerrainElevationRad,~,sensorElevations] = ...
    digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
        candidateLatitudesRad, ...
        candidateLongitudesRad, ...
        dem, ...
        terrainConfig.maximumRangeKm, ...
        terrainConfig.rangeStepKm, ...
        terrainConfig.horizonAzimuthStepRad, ...
        moonRadius);

assert(all(isfinite(maximumTerrainElevationRad),"all"));
assert(all(isfinite(sensorElevations)));

chunkNumber = uint16(metadata.chunkNumber); %#ok<NASGU>
originalCandidateIndices = uint32(originalCandidateIndices); %#ok<NASGU>
sensorElevationsKm = sensorElevations; %#ok<NASGU>
horizonAzimuthsRad = horizonAzimuths; %#ok<NASGU>

save( ...
    chunkFile, ...
    "chunkNumber", ...
    "originalCandidateIndices", ...
    "candidateLatitudesRad", ...
    "candidateLongitudesRad", ...
    "sensorElevationsKm", ...
    "horizonAzimuthsRad", ...
    "maximumTerrainElevationRad", ...
    "-v7.3");

end
