function database = buildOptimizationDatabase(dem,userConfig)
% BUILDOPTIMIZATIONDATABASE
% Build the deterministic database used by the lunar-surface global
% sensor-network optimization study.
%
% Architecture:
%   1. Build the fixed RSO population.
%   2. Build candidate surface locations.
%   3. Build terrain-horizon database.
%   4. Propagate RSO truth trajectories.
%   5. Build fixed Earth and Sun histories.
%   6. Build fully filtered truth visibility and candidate prefilter.
%   7. Estimate ONE fixed P0 from an independent reference IOD case.
%   8. Precompute dynamics, process noise, and measurement Jacobians.
%   9. Build fully filtered nominal optimization availability.
%
% The IOD calibration does NOT determine whether an RSO is retained.
% One reference IOD case estimates a single fixed initial covariance P0.
% That same P0 is then applied to every RSO in every network-size,
% objective, optimizer, and independent-run comparison.
%
% The nominal state for each RSO is its truth state at the common
% optimization reference epoch. This allows the information objective to
% isolate covariance evolution caused by geometry, visibility, process
% noise, and the selected sensor network.
%
% Inputs:
%   dem        - Lunar DEM griddedInterpolant using radians and km
%   userConfig - Optional structure overriding default settings
%
% Output:
%   database   - Deterministic optimization database

arguments
    dem (1,1) griddedInterpolant
    userConfig (1,1) struct = struct()
end

%% ========================================================================
%  Configuration
%  ========================================================================

config = mergeStruct( ...
    defaultConfiguration(), ...
    userConfig);

config = validateConfiguration(config);

fprintf("\n");
fprintf("============================================================\n");
fprintf("Building lunar surface optimization database\n");
fprintf("============================================================\n");

buildTimer = tic;

%% ========================================================================
%  Constants
%  ========================================================================

moonRadius = ...
    config.moon.radiusKm;

moonMu = ...
    config.moon.muKm3S2;

moonAngularRate = ...
    2*pi/config.moon.siderealPeriodSeconds;

theta0 = ...
    config.moon.theta0Rad;

%% ========================================================================
%  1/9 RSO population
%  ========================================================================

fprintf("\n1/9 Building RSO population...\n");

if ~isempty(config.rso.customInitialStatesMoonInertial)

    initialStatesMoonInertial = ...
        config.rso.customInitialStatesMoonInertial;

    assert(size(initialStatesMoonInertial,1) == 6, ...
        "Custom RSO states must be 6xN.");

    numberOfObjects = ...
        size(initialStatesMoonInertial,2);

    if isempty(config.rso.customCatalog)

        rsoNames = ...
            compose( ...
                "RSO %02d", ...
                (1:numberOfObjects).');

        rsoCatalog = ...
            table( ...
                rsoNames, ...
                'VariableNames',{'Name'});

    else

        rsoCatalog = ...
            config.rso.customCatalog;

        assert(height(rsoCatalog) == numberOfObjects, ...
            "Custom RSO states and catalog must contain the same objects.");
    end

else

    [initialStatesMoonInertial,rsoCatalog] = ...
        rsoGeneration.buildRsoSet( ...
            config.rso.selection, ...
            config.rso.numberOfGeneratedObjects, ...
            config.rso.periapsisAltitudeLimitsKm, ...
            config.rso.inclinationLimitsRad, ...
            config.rso.eccentricityLimits, ...
            moonRadius, ...
            moonMu);

    numberOfObjects = ...
        size(initialStatesMoonInertial,2);
end

assert(numberOfObjects >= 1, ...
    "The RSO population is empty.");

assert(height(rsoCatalog) == numberOfObjects, ...
    "The RSO state matrix and catalog are inconsistent.");

fprintf("  RSOs: %d\n",numberOfObjects);

%% ========================================================================
%  Object weights
%  ========================================================================

if isempty(config.estimation.objectWeights)

    objectWeights = ...
        ones(numberOfObjects,1);

else

    objectWeights = ...
        config.estimation.objectWeights(:);

    assert(length(objectWeights) == numberOfObjects, ...
        "Provide one object weight per RSO.");

    assert(all(objectWeights >= 0), ...
        "Object weights must be nonnegative.");

    assert(sum(objectWeights) > 0, ...
        "At least one object weight must be positive.");
end

%% ========================================================================
%  2/9 Candidate surface locations
%  ========================================================================

fprintf("\n2/9 Building candidate sensor set...\n");

if ~isempty(config.candidates.customLatitudesRad)

    candidateLatitudesAll = ...
        config.candidates.customLatitudesRad(:);

    candidateLongitudesAll = ...
        config.candidates.customLongitudesRad(:);

    assert(length(candidateLatitudesAll) == ...
        length(candidateLongitudesAll), ...
        "Custom candidate latitude and longitude arrays must match.");

else

    [candidateLatitudesAll,candidateLongitudesAll] = ...
        digitalElevationModel.buildCandidateSensorGrid( ...
            config.candidates.latitudeBandRad, ...
            config.candidates.longitudeBandRad, ...
            config.candidates.spacingKm, ...
            moonRadius);
end

numberOfCandidatesAll = ...
    length(candidateLatitudesAll);

assert(numberOfCandidatesAll >= max(config.study.networkSizes), ...
    "Candidate set is smaller than the largest requested network.");

fprintf("  Initial candidates: %d\n",numberOfCandidatesAll);

%% ========================================================================
%  3/9 Terrain-horizon database
%  ========================================================================

fprintf("\n3/9 Building terrain-horizon database...\n");

[horizonAzimuths, ...
    maximumTerrainElevationAll, ...
    ~, ...
    sensorElevationsAll] = ...
    digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
        candidateLatitudesAll, ...
        candidateLongitudesAll, ...
        dem, ...
        config.terrain.maximumRangeKm, ...
        config.terrain.rangeStepKm, ...
        config.terrain.horizonAzimuthStepRad, ...
        moonRadius);

assert(all(isfinite(maximumTerrainElevationAll),"all"), ...
    "Terrain-horizon database contains nonfinite values.");

assert(all(isfinite(sensorElevationsAll)), ...
    "Candidate sensor elevations contain nonfinite values.");

%% ========================================================================
%  4/9 Propagate fixed RSO truth population
%  ========================================================================

fprintf("\n4/9 Propagating RSO truth population...\n");

times = ...
    ( ...
    0: ...
    config.tracking.outputStepSeconds: ...
    config.tracking.finalTimeSeconds ...
    ).';

if times(end) < config.tracking.finalTimeSeconds

    times(end+1,1) = ...
        config.tracking.finalTimeSeconds;
end

numberOfTimes = ...
    length(times);

truthStateHistories = ...
    zeros(6,numberOfTimes,numberOfObjects);

for objectIndex = 1:numberOfObjects

    fprintf( ...
        "  Truth propagation %d/%d\n", ...
        objectIndex, ...
        numberOfObjects);

    [propagatedTimes,propagatedStates] = ...
        orbitDynamics.propagateLunarOrbit( ...
            initialStatesMoonInertial(:,objectIndex), ...
            times, ...
            moonMu=moonMu);

    assert(max(abs(propagatedTimes-times)) < 1e-9, ...
        "Truth time grid changed for RSO %d.",objectIndex);

    truthStateHistories(:,:,objectIndex) = ...
        propagatedStates.';
end

%% ========================================================================
%  5/9 Fixed Earth and Sun histories
%  ========================================================================

fprintf("\n5/9 Building Earth and Sun histories...\n");

[earthPositionsMci,sunPositionsMci] = ...
    buildCelestialHistories( ...
        times, ...
        moonAngularRate, ...
        config.ephemeris);

%% ========================================================================
%  6/9 Fully filtered truth visibility
%  ========================================================================

fprintf("\n6/9 Building truth visibility database...\n");

[truthFilteredAvailabilityAll,truthVisibilityDiagnostics] = ...
    optimization.buildFilteredVisibilityDatabase( ...
        times, ...
        truthStateHistories, ...
        candidateLatitudesAll, ...
        candidateLongitudesAll, ...
        dem, ...
        horizonAzimuths, ...
        maximumTerrainElevationAll, ...
        earthPositionsMci, ...
        sunPositionsMci, ...
        config.visibility.minimumElevationRad, ...
        config.terrain.horizonMarginRad, ...
        config.visibility.earthRadiusKm, ...
        config.visibility.sunRadiusKm, ...
        config.visibility.minimumAngularSeparationRad, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate);

assert(isequal( ...
    truthFilteredAvailabilityAll, ...
    truthVisibilityDiagnostics.accepted), ...
    "Truth filtered visibility is inconsistent.");

%% ========================================================================
%  Candidate prefilter
%  ========================================================================

geometricCountsByObjectAll = ...
    reshape( ...
        sum( ...
            truthVisibilityDiagnostics.geometricAvailability, ...
            2), ...
        numberOfCandidatesAll, ...
        numberOfObjects);

filteredCountsByObjectAll = ...
    reshape( ...
        sum( ...
            truthFilteredAvailabilityAll, ...
            2), ...
        numberOfCandidatesAll, ...
        numberOfObjects);

candidateKeepMask = ...
    true(numberOfCandidatesAll,1);

if config.candidateFilter.enabled

    maximumGeometricEpochs = ...
        max( ...
            geometricCountsByObjectAll, ...
            [], ...
            2);

    totalFilteredEpochs = ...
        sum( ...
            filteredCountsByObjectAll, ...
            2);

    candidateKeepMask = ...
        maximumGeometricEpochs >= ...
        config.candidateFilter.minimumGeometricEpochsForAnyObject;

    candidateKeepMask = ...
        candidateKeepMask & ...
        totalFilteredEpochs >= ...
        config.candidateFilter.minimumFilteredEpochsTotal;
end

candidateOriginalIndices = ...
    find(candidateKeepMask);

candidateLatitudes = ...
    candidateLatitudesAll(candidateKeepMask);

candidateLongitudes = ...
    candidateLongitudesAll(candidateKeepMask);

sensorElevations = ...
    sensorElevationsAll(candidateKeepMask);

maximumTerrainElevation = ...
    maximumTerrainElevationAll(candidateKeepMask,:);

truthFilteredAvailability = ...
    truthFilteredAvailabilityAll(candidateKeepMask,:,:);

numberOfCandidates = ...
    length(candidateLatitudes);

fprintf( ...
    "  Retained candidates: %d of %d\n", ...
    numberOfCandidates, ...
    numberOfCandidatesAll);

assert(numberOfCandidates >= max(config.study.networkSizes), ...
    "Candidate screening retained too few locations.");

assert(any(truthFilteredAvailability,"all"), ...
    "No accepted candidate observations remain.");

% The full-candidate diagnostic arrays can be large.
clear truthVisibilityDiagnostics
clear truthFilteredAvailabilityAll
clear maximumTerrainElevationAll
clear sensorElevationsAll

%% ========================================================================
%  Measurement covariance
%  ========================================================================

measurementCovariance = ...
    diag([ ...
        config.measurement.rightAscensionSigmaRad^2
        config.measurement.declinationSigmaRad^2
    ]);

%% ========================================================================
%  7/9 ONE representative IOD calibration -> fixed P0
%  ========================================================================

fprintf("\n7/9 Calibrating fixed P0 from reference IOD case...\n");

[fixedInitialCovariance,iodCalibration] = ...
    buildFixedIodPrior( ...
        dem, ...
        measurementCovariance, ...
        config, ...
        moonRadius, ...
        moonMu, ...
        theta0, ...
        moonAngularRate);

fixedInitialCovariance = ...
    0.5*( ...
        fixedInitialCovariance + ...
        fixedInitialCovariance.');

[~,positiveDefiniteFlag] = ...
    chol( ...
        fixedInitialCovariance, ...
        "lower");

assert(positiveDefiniteFlag == 0, ...
    "IOD-derived fixed P0 is not positive definite.");

% The optimization reference epoch is the truth-population initial epoch.
% The IOD calibration is used only to determine the fixed covariance.
commonReferenceTime = ...
    times(1);

assert(abs(commonReferenceTime) < 1e-12, ...
    "The expected optimization reference epoch is t = 0.");

fixedInitialStates = ...
    initialStatesMoonInertial;

fixedInitialCovariances = ...
    repmat( ...
        fixedInitialCovariance, ...
        1,1,numberOfObjects);

% precomputeTrackingData requires observation times after the initial time.
optimizationIndices = ...
    find(times > commonReferenceTime);

optimizationTimes = ...
    times(optimizationIndices);

numberOfOptimizationTimes = ...
    length(optimizationTimes);

assert(numberOfOptimizationTimes >= 1, ...
    "No optimization epochs remain.");

truthOptimizationStateHistories = ...
    truthStateHistories(:,optimizationIndices,:);

truthFilteredOptimizationAvailability = ...
    truthFilteredAvailability(:,optimizationIndices,:);

earthOptimizationPositionsMci = ...
    earthPositionsMci(:,optimizationIndices);

sunOptimizationPositionsMci = ...
    sunPositionsMci(:,optimizationIndices);

fprintf( ...
    "  Reference IOD sensor:       %.6f deg, %.6f deg\n", ...
    rad2deg(iodCalibration.sensorLatitudeRad), ...
    rad2deg(iodCalibration.sensorLongitudeRad));

fprintf( ...
    "  Reference IOD cadence:      %.1f s\n", ...
    iodCalibration.outputStepSeconds);

fprintf( ...
    "  Reference IOD observations: %d/%d\n", ...
    length(iodCalibration.acquisitionIndices), ...
    config.iod.desiredObservationCount);

fprintf( ...
    "  IOD MC convergence:         %d/%d\n", ...
    iodCalibration.diagnostics.numberOfSuccessfulSamples, ...
    iodCalibration.diagnostics.numberOfRequestedSamples);

fprintf( ...
    "  Optimization reference:     %.3f hr\n", ...
    commonReferenceTime/3600);

fprintf( ...
    "  Optimization epochs:        %d\n", ...
    numberOfOptimizationTimes);

%% ========================================================================
%  8/9 Tracking dynamics and Jacobians
%  ========================================================================

fprintf("\n8/9 Precomputing tracking dynamics and Jacobians...\n");

referenceStateHistories = ...
    zeros( ...
        6, ...
        numberOfOptimizationTimes, ...
        numberOfObjects);

stateTransitionHistories = ...
    zeros( ...
        6,6, ...
        numberOfOptimizationTimes, ...
        numberOfObjects);

processNoiseHistories = ...
    zeros( ...
        6,6, ...
        numberOfOptimizationTimes, ...
        numberOfObjects);

measurementJacobianHistories = ...
    zeros( ...
        2,6, ...
        numberOfCandidates, ...
        numberOfOptimizationTimes, ...
        numberOfObjects);

for objectIndex = 1:numberOfObjects

    fprintf( ...
        "  Tracking precompute %d/%d\n", ...
        objectIndex, ...
        numberOfObjects);

    [objectReferenceStates, ...
        objectStateTransitions, ...
        objectProcessNoise, ...
        objectMeasurementJacobians] = ...
        optimization.precomputeTrackingData( ...
            commonReferenceTime, ...
            optimizationTimes, ...
            fixedInitialStates(:,objectIndex), ...
            candidateLatitudes, ...
            candidateLongitudes, ...
            dem, ...
            config.visibility.minimumElevationRad, ...
            config.estimation.accelerationNoiseIntensity, ...
            moonMu, ...
            moonRadius, ...
            theta0, ...
            moonAngularRate);

    referenceStateHistories(:,:,objectIndex) = ...
        objectReferenceStates;

    stateTransitionHistories(:,:,:,objectIndex) = ...
        objectStateTransitions;

    processNoiseHistories(:,:,:,objectIndex) = ...
        objectProcessNoise;

    measurementJacobianHistories(:,:,:,:,objectIndex) = ...
        objectMeasurementJacobians;
end

%% ========================================================================
%  Confirm nominal propagation agrees with truth
%  ========================================================================

maximumReferenceTruthError = ...
    max( ...
        abs( ...
            referenceStateHistories - ...
            truthOptimizationStateHistories), ...
        [], ...
        "all");

assert(maximumReferenceTruthError < 1e-6, ...
    "Nominal tracking propagation does not reproduce truth.");

%% ========================================================================
%  9/9 Final fully filtered nominal availability
%  ========================================================================

fprintf("\n9/9 Building final optimization visibility database...\n");

[filteredAvailability,nominalVisibilityDiagnostics] = ...
    optimization.buildFilteredVisibilityDatabase( ...
        optimizationTimes, ...
        referenceStateHistories, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        horizonAzimuths, ...
        maximumTerrainElevation, ...
        earthOptimizationPositionsMci, ...
        sunOptimizationPositionsMci, ...
        config.visibility.minimumElevationRad, ...
        config.terrain.horizonMarginRad, ...
        config.visibility.earthRadiusKm, ...
        config.visibility.sunRadiusKm, ...
        config.visibility.minimumAngularSeparationRad, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate);

assert(isequal( ...
    filteredAvailability, ...
    nominalVisibilityDiagnostics.accepted), ...
    "Final filtered availability is inconsistent.");

assert(all( ...
    filteredAvailability <= ...
    nominalVisibilityDiagnostics.terrainAvailability, ...
    "all"), ...
    "Filtered availability exceeds terrain visibility.");

%% ========================================================================
%  Extract only required visibility diagnostics
%  ========================================================================

geometricAvailability = ...
    nominalVisibilityDiagnostics.geometricAvailability;

terrainAvailability = ...
    nominalVisibilityDiagnostics.terrainAvailability;

earthBlocked = ...
    nominalVisibilityDiagnostics.earthBlocked;

sunBlocked = ...
    nominalVisibilityDiagnostics.sunBlocked;

visibilitySummary = ...
    buildVisibilitySummary( ...
        filteredAvailability, ...
        nominalVisibilityDiagnostics);

clear nominalVisibilityDiagnostics

%% ========================================================================
%  Final database
%  ========================================================================

database = struct();

database.meta = struct();

database.meta.version = ...
    "lunar_surface_optimization_database_v2_fixed_p0";

database.meta.created = ...
    string(datetime("now"));

database.meta.buildRuntimeSeconds = ...
    toc(buildTimer);

database.meta.demSource = ...
    string(config.demSource);

database.meta.numberOfObjects = ...
    numberOfObjects;

database.meta.numberOfCandidatesBeforeFiltering = ...
    numberOfCandidatesAll;

database.meta.numberOfCandidates = ...
    numberOfCandidates;

database.meta.numberOfTruthEpochs = ...
    numberOfTimes;

database.meta.numberOfOptimizationEpochs = ...
    numberOfOptimizationTimes;

%% Study

database.study = struct();

database.study.networkSizes = ...
    config.study.networkSizes(:).';

database.study.objectiveModes = ...
    config.study.objectiveModes(:).';

%% Configuration

database.config = ...
    config;

%% RSO population

database.rso = struct();

database.rso.catalog = ...
    rsoCatalog;

database.rso.initialStatesMoonInertial = ...
    initialStatesMoonInertial;

database.rso.objectWeights = ...
    objectWeights;

%% Candidates

database.candidates = struct();

database.candidates.latitudesRad = ...
    candidateLatitudes;

database.candidates.longitudesRad = ...
    candidateLongitudes;

database.candidates.sensorElevationsKm = ...
    sensorElevations;

database.candidates.originalIndices = ...
    candidateOriginalIndices;

database.candidates.prefilter = struct();

database.candidates.prefilter.latitudesRad = ...
    candidateLatitudesAll;

database.candidates.prefilter.longitudesRad = ...
    candidateLongitudesAll;

database.candidates.prefilter.keepMask = ...
    candidateKeepMask;

database.candidates.prefilter.geometricCountsByObject = ...
    geometricCountsByObjectAll;

database.candidates.prefilter.filteredCountsByObject = ...
    filteredCountsByObjectAll;

%% Terrain

database.terrain = struct();

database.terrain.horizonAzimuthsRad = ...
    horizonAzimuths;

database.terrain.maximumTerrainElevationRad = ...
    maximumTerrainElevation;

%% Ephemerides

database.ephemeris = struct();

database.ephemeris.earthPositionsMci = ...
    earthPositionsMci;

database.ephemeris.sunPositionsMci = ...
    sunPositionsMci;

%% Truth

database.truth = struct();

database.truth.times = ...
    times;

database.truth.stateHistories = ...
    truthStateHistories;

database.truth.optimizationStateHistories = ...
    truthOptimizationStateHistories;

database.truth.filteredOptimizationAvailability = ...
    truthFilteredOptimizationAvailability;

%% IOD calibration provenance

database.iod = struct();

database.iod.calibration = ...
    iodCalibration;

database.iod.fixedInitialCovariance = ...
    fixedInitialCovariance;

%% Fixed prior used by EVERY RSO

database.prior = struct();

database.prior.referenceTime = ...
    commonReferenceTime;

database.prior.initialCovariance = ...
    fixedInitialCovariance;

database.prior.initialCovariances = ...
    fixedInitialCovariances;

database.prior.initialStates = ...
    fixedInitialStates;

database.prior.source = ...
    "single_reference_angles_only_iod_monte_carlo";

%% Tracking data

database.tracking = struct();

database.tracking.times = ...
    optimizationTimes;

database.tracking.referenceStateHistories = ...
    referenceStateHistories;

database.tracking.stateTransitionHistories = ...
    stateTransitionHistories;

database.tracking.processNoiseHistories = ...
    processNoiseHistories;

database.tracking.measurementJacobianHistories = ...
    measurementJacobianHistories;

%% Visibility

database.visibility = struct();

database.visibility.filteredAvailability = ...
    filteredAvailability;

database.visibility.geometricAvailability = ...
    geometricAvailability;

database.visibility.terrainAvailability = ...
    terrainAvailability;

database.visibility.earthBlocked = ...
    earthBlocked;

database.visibility.sunBlocked = ...
    sunBlocked;

database.visibility.summary = ...
    visibilitySummary;

%% Measurement model

database.measurement = struct();

database.measurement.covariance = ...
    measurementCovariance;

database.measurement.rightAscensionSigmaRad = ...
    config.measurement.rightAscensionSigmaRad;

database.measurement.declinationSigmaRad = ...
    config.measurement.declinationSigmaRad;

%% Estimation

database.estimation = struct();

database.estimation.accelerationNoiseIntensity = ...
    config.estimation.accelerationNoiseIntensity;

database.estimation.stateScales = ...
    config.estimation.stateScales(:);

database.estimation.objectWeights = ...
    objectWeights;

%% Objective

database.objective = struct();

database.objective.infeasiblePenalty = ...
    config.objective.infeasiblePenalty;

database.objective.supportedModes = ...
    config.study.objectiveModes(:).';

%% ========================================================================
%  Save
%  ========================================================================

if strlength(string(config.outputFile)) > 0

    outputFile = ...
        string(config.outputFile);

    outputDirectory = ...
        fileparts(outputFile);

    if strlength(outputDirectory) > 0 && ...
            ~isfolder(outputDirectory)

        mkdir(outputDirectory);
    end

    if isfile(outputFile) && ...
            ~config.overwriteOutput

        error( ...
            "buildOptimizationDatabase:OutputExists", ...
            "Output already exists: %s", ...
            outputFile);
    end

    fprintf( ...
        "\nSaving optimization database:\n  %s\n", ...
        outputFile);

    save( ...
        outputFile, ...
        "database", ...
        "-v7.3");
end

fprintf("\n");
fprintf("Optimization database complete.\n");
fprintf("  RSOs:                 %d\n",numberOfObjects);
fprintf("  Candidates retained:  %d\n",numberOfCandidates);
fprintf("  Optimization epochs:  %d\n",numberOfOptimizationTimes);
fprintf("  Fixed P0 source:      reference IOD Monte Carlo\n");
fprintf("  Build runtime:        %.2f min\n", ...
    database.meta.buildRuntimeSeconds/60);
fprintf("\n");

end

%% =========================================================================
%  Default configuration
%  =========================================================================

function config = defaultConfiguration()

config = struct();

config.outputFile = "";
config.overwriteOutput = false;
config.demSource = "";

%% Study

config.study = struct();

config.study.networkSizes = ...
    [3,5,7];

config.study.objectiveModes = ...
    ["information","coverage"];

%% Moon

config.moon = struct();

config.moon.radiusKm = ...
    1737.4;

config.moon.muKm3S2 = ...
    4902.800066;

config.moon.siderealPeriodSeconds = ...
    27.321661*86400;

config.moon.theta0Rad = ...
    0;

%% RSO population

config.rso = struct();

config.rso.selection = ...
    "generated";

config.rso.numberOfGeneratedObjects = ...
    20;

config.rso.periapsisAltitudeLimitsKm = ...
    [50,5000];

config.rso.inclinationLimitsRad = ...
    deg2rad([0,180]);

config.rso.eccentricityLimits = ...
    [0,0.8];

config.rso.customInitialStatesMoonInertial = ...
    zeros(6,0);

config.rso.customCatalog = ...
    table();

%% Candidates

config.candidates = struct();

config.candidates.latitudeBandRad = ...
    deg2rad([-90,-75]);

config.candidates.longitudeBandRad = ...
    deg2rad([0,360]);

config.candidates.spacingKm = ...
    15;

config.candidates.customLatitudesRad = ...
    [];

config.candidates.customLongitudesRad = ...
    [];

%% Candidate prefilter

config.candidateFilter = struct();

config.candidateFilter.enabled = ...
    true;

config.candidateFilter.minimumGeometricEpochsForAnyObject = ...
    1;

config.candidateFilter.minimumFilteredEpochsTotal = ...
    1;

%% Terrain

config.terrain = struct();

config.terrain.maximumRangeKm = ...
    100;

config.terrain.rangeStepKm = ...
    0.5;

config.terrain.horizonAzimuthStepRad = ...
    deg2rad(0.1);

config.terrain.horizonMarginRad = ...
    0;

%% Visibility

config.visibility = struct();

config.visibility.minimumElevationRad = ...
    0;

config.visibility.minimumAngularSeparationRad = ...
    deg2rad(20);

config.visibility.earthRadiusKm = ...
    6378.1366;

config.visibility.sunRadiusKm = ...
    695700;

%% Generic Earth / Sun histories

config.ephemeris = struct();

config.ephemeris.earthMoonDistanceKm = ...
    384400;

config.ephemeris.sunMoonDistanceKm = ...
    149597870.7;

config.ephemeris.earthPhase0Rad = ...
    deg2rad(20);

config.ephemeris.sunPhase0Rad = ...
    deg2rad(145);

config.ephemeris.solarInclinationRad = ...
    deg2rad(5.145);

config.ephemeris.sunOrbitalPeriodSeconds = ...
    365.256363004*86400;

%% Tracking

config.tracking = struct();

config.tracking.outputStepSeconds = ...
    60;

config.tracking.finalTimeSeconds = ...
    8*3600;

%% Measurement

config.measurement = struct();

config.measurement.rightAscensionSigmaRad = ...
    deg2rad(1/3600);

config.measurement.declinationSigmaRad = ...
    deg2rad(1/3600);

%% Fixed-P0 IOD calibration

config.iod = struct();

config.iod.referenceInitialStateMoonInertial = ...
    [];

config.iod.referencePeriapsisAltitudeKm = ...
    50;

config.iod.referenceEccentricity = ...
    0;

config.iod.referenceInclinationRad = ...
    deg2rad(90);

config.iod.referenceRaanRad = ...
    deg2rad(37);

config.iod.referenceArgumentOfPeriapsisRad = ...
    0;

config.iod.referenceTrueAnomalyRad = ...
    0;

config.iod.referenceSensorLatitudeRad = ...
    deg2rad(-89.505332);

config.iod.referenceSensorLongitudeRad = ...
    deg2rad(102.857143);

% The IOD calibration has its own measurement cadence. It is independent
% of the optimization tracking cadence.
config.iod.outputStepSeconds = ...
    10;

config.iod.desiredObservationCount = ...
    15;

config.iod.searchEndFraction = ...
    0.40;

config.iod.numberOfMonteCarloSamples = ...
    500;

config.iod.measurementNoiseSeedBase = ...
    1000;

config.iod.monteCarloSeedBase = ...
    2000;

% These names are retained for compatibility with the previously written
% production configuration script.
config.iod.measurementNoiseSeedBase = ...
    1000;

config.iod.monteCarloSeedBase = ...
    2000;

%% Estimation

config.estimation = struct();

config.estimation.accelerationNoiseIntensity = ...
    1e-15;

config.estimation.stateScales = ...
    [1;1;1;1e-3;1e-3;1e-3];

config.estimation.objectWeights = ...
    [];

%% Objective

config.objective = struct();

config.objective.infeasiblePenalty = ...
    1e12;

end

%% =========================================================================
%  Validate configuration
%  =========================================================================

function config = validateConfiguration(config)

config.study.networkSizes = ...
    unique( ...
        round(config.study.networkSizes(:).'), ...
        "stable");

validateattributes( ...
    config.study.networkSizes, ...
    {'numeric'}, ...
    {'vector','integer','positive'});

config.study.objectiveModes = ...
    lower(string(config.study.objectiveModes(:).'));

validModes = ...
    ["information","coverage"];

assert(all(ismember( ...
    config.study.objectiveModes, ...
    validModes)), ...
    "Objective modes must be information and/or coverage.");

validateattributes( ...
    config.iod.outputStepSeconds, ...
    {'numeric'}, ...
    {'scalar','positive','finite'});

assert( ...
    config.iod.outputStepSeconds <= ...
    config.tracking.finalTimeSeconds, ...
    "IOD output step must be shorter than the complete tracking arc.");

validateattributes( ...
    config.tracking.finalTimeSeconds, ...
    {'numeric'}, ...
    {'scalar','positive','finite'});

validateattributes( ...
    config.iod.searchEndFraction, ...
    {'numeric'}, ...
    {'scalar','>',0,'<',1});

validateattributes( ...
    config.iod.desiredObservationCount, ...
    {'numeric'}, ...
    {'scalar','integer','>=',3});

validateattributes( ...
    config.iod.numberOfMonteCarloSamples, ...
    {'numeric'}, ...
    {'scalar','integer','positive'});

validateattributes( ...
    config.iod.referenceSensorLatitudeRad, ...
    {'numeric'}, ...
    {'scalar','>=',-pi/2,'<=',pi/2});

validateattributes( ...
    config.iod.referenceSensorLongitudeRad, ...
    {'numeric'}, ...
    {'scalar','finite'});

validateattributes( ...
    config.visibility.minimumAngularSeparationRad, ...
    {'numeric'}, ...
    {'scalar','nonnegative','finite'});

validateattributes( ...
    config.objective.infeasiblePenalty, ...
    {'numeric'}, ...
    {'scalar','positive','finite'});

if ~isempty(config.iod.referenceInitialStateMoonInertial)

    validateattributes( ...
        config.iod.referenceInitialStateMoonInertial, ...
        {'numeric'}, ...
        {'size',[6,1],'finite'});
end

end

%% =========================================================================
%  Fixed-P0 IOD calibration
%  =========================================================================

function [fixedInitialCovariance,calibration] = ...
    buildFixedIodPrior( ...
        dem, ...
        measurementCovariance, ...
        config, ...
        moonRadius, ...
        moonMu, ...
        theta0, ...
        moonAngularRate)
% BUILDFIXEDIODPRIOR
% Estimate one fixed P0 from one independent reference IOD acquisition.
%
% The IOD time grid is independent of the optimization tracking time grid.
% The resulting covariance is reused identically for every RSO and every
% network optimization.

%% ========================================================================
%  Independent IOD time grid
%  ========================================================================

iodTimes = ...
    ( ...
    0: ...
    config.iod.outputStepSeconds: ...
    config.tracking.finalTimeSeconds ...
    ).';

if iodTimes(end) < config.tracking.finalTimeSeconds

    iodTimes(end+1,1) = ...
        config.tracking.finalTimeSeconds;
end

numberOfIodTimes = ...
    length(iodTimes);

%% ========================================================================
%  Celestial histories on IOD time grid
%  ========================================================================

[iodEarthPositionsMci,iodSunPositionsMci] = ...
    buildCelestialHistories( ...
        iodTimes, ...
        moonAngularRate, ...
        config.ephemeris);

%% ========================================================================
%  Reference orbit
%  ========================================================================

if isempty(config.iod.referenceInitialStateMoonInertial)

    referenceInitialState = ...
        referenceOrbitState( ...
            config.iod.referencePeriapsisAltitudeKm, ...
            config.iod.referenceEccentricity, ...
            config.iod.referenceInclinationRad, ...
            config.iod.referenceRaanRad, ...
            config.iod.referenceArgumentOfPeriapsisRad, ...
            config.iod.referenceTrueAnomalyRad, ...
            moonRadius, ...
            moonMu);

else

    referenceInitialState = ...
        config.iod.referenceInitialStateMoonInertial;
end

[referenceTimes,referenceStates] = ...
    orbitDynamics.propagateLunarOrbit( ...
        referenceInitialState, ...
        iodTimes, ...
        moonMu=moonMu);

assert(max(abs(referenceTimes-iodTimes)) < 1e-9, ...
    "Reference IOD trajectory time grid changed.");

referenceStateHistory = ...
    reshape( ...
        referenceStates.', ...
        6,numberOfIodTimes,1);

%% ========================================================================
%  Fixed reference sensor
%  ========================================================================

referenceSensorLatitude = ...
    config.iod.referenceSensorLatitudeRad;

referenceSensorLongitude = ...
    mod( ...
        config.iod.referenceSensorLongitudeRad, ...
        2*pi);

[referenceHorizonAzimuths, ...
    referenceMaximumTerrainElevation] = ...
    digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
        referenceSensorLatitude, ...
        referenceSensorLongitude, ...
        dem, ...
        config.terrain.maximumRangeKm, ...
        config.terrain.rangeStepKm, ...
        config.terrain.horizonAzimuthStepRad, ...
        moonRadius);

%% ========================================================================
%  Fully filtered reference visibility
%  ========================================================================

[referenceAvailability,referenceVisibilityDiagnostics] = ...
    optimization.buildFilteredVisibilityDatabase( ...
        iodTimes, ...
        referenceStateHistory, ...
        referenceSensorLatitude, ...
        referenceSensorLongitude, ...
        dem, ...
        referenceHorizonAzimuths, ...
        referenceMaximumTerrainElevation, ...
        iodEarthPositionsMci, ...
        iodSunPositionsMci, ...
        config.visibility.minimumElevationRad, ...
        config.terrain.horizonMarginRad, ...
        config.visibility.earthRadiusKm, ...
        config.visibility.sunRadiusKm, ...
        config.visibility.minimumAngularSeparationRad, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate);

referenceAvailability = ...
    reshape( ...
        referenceAvailability, ...
        1,numberOfIodTimes);

%% ========================================================================
%  Select required acquisition pass
%  ========================================================================

iodSearchEndTime = ...
    iodTimes(1) + ...
    config.iod.searchEndFraction* ...
    (iodTimes(end)-iodTimes(1));

[acquisitionIndices, ...
    bestConsecutiveRunLength, ...
    acceptedEpochsInSearchWindow] = ...
    selectReferenceIodPass( ...
        referenceAvailability, ...
        iodTimes, ...
        iodSearchEndTime, ...
        config.iod.desiredObservationCount);

if bestConsecutiveRunLength < ...
        config.iod.desiredObservationCount

    errorMessage = ...
        "Reference IOD calibration requires %d fully filtered " + ...
        "observations from one continuous pass. The longest pass " + ...
        "before %.3f hr contains only %d epochs at the %.1f s IOD " + ...
        "cadence. Accepted epochs in the full search window = %d.";

    error( ...
        "buildOptimizationDatabase:InsufficientReferenceIodVisibility", ...
        errorMessage, ...
        config.iod.desiredObservationCount, ...
        iodSearchEndTime/3600, ...
        bestConsecutiveRunLength, ...
        config.iod.outputStepSeconds, ...
        acceptedEpochsInSearchWindow);
end

assert( ...
    length(acquisitionIndices) == ...
    config.iod.desiredObservationCount, ...
    "Reference IOD did not return exactly the requested observations.");

%% ========================================================================
%  Simulate fixed noisy reference measurements
%  ========================================================================

measurementNoiseFactor = ...
    chol( ...
        measurementCovariance, ...
        "lower");

[observerPositionsMci, ...
    rightAscension, ...
    declination] = ...
    simulateSingleSensorMeasurements( ...
        iodTimes, ...
        referenceStateHistory(:,:,1), ...
        referenceSensorLatitude, ...
        referenceSensorLongitude, ...
        dem, ...
        referenceAvailability.', ...
        measurementNoiseFactor, ...
        config.iod.measurementNoiseSeedBase, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate);

%% ========================================================================
%  One Monte Carlo IOD
%  ========================================================================

[iodState, ...
    fixedInitialCovariance, ...
    iodReferenceTime, ...
    iodDiagnostics] = ...
    iod.anglesOnlyIod( ...
        iodTimes, ...
        rightAscension, ...
        declination, ...
        observerPositionsMci, ...
        acquisitionIndices, ...
        measurementCovariance, ...
        config.iod.numberOfMonteCarloSamples, ...
        config.iod.monteCarloSeedBase, ...
        moonMu);

fixedInitialCovariance = ...
    0.5*( ...
        fixedInitialCovariance + ...
        fixedInitialCovariance.');

[~,positiveDefiniteFlag] = ...
    chol( ...
        fixedInitialCovariance, ...
        "lower");

assert(positiveDefiniteFlag == 0, ...
    "Reference IOD produced a non-positive-definite P0.");

%% ========================================================================
%  Calibration provenance
%  ========================================================================

calibration = struct();

calibration.outputStepSeconds = ...
    config.iod.outputStepSeconds;

calibration.desiredObservationCount = ...
    config.iod.desiredObservationCount;

calibration.referenceInitialStateMoonInertial = ...
    referenceInitialState;

calibration.referenceStateHistory = ...
    referenceStateHistory(:,:,1);

calibration.times = ...
    iodTimes;

calibration.sensorLatitudeRad = ...
    referenceSensorLatitude;

calibration.sensorLongitudeRad = ...
    referenceSensorLongitude;

calibration.acquisitionIndices = ...
    acquisitionIndices;

calibration.acquisitionTimes = ...
    iodTimes(acquisitionIndices);

calibration.bestConsecutiveRunLength = ...
    bestConsecutiveRunLength;

calibration.acceptedEpochsInSearchWindow = ...
    acceptedEpochsInSearchWindow;

calibration.iodState = ...
    iodState;

calibration.iodReferenceTime = ...
    iodReferenceTime;

calibration.diagnostics = ...
    iodDiagnostics;

calibration.visibility = struct();

calibration.visibility.geometricAvailability = ...
    referenceVisibilityDiagnostics.geometricAvailability;

calibration.visibility.terrainAvailability = ...
    referenceVisibilityDiagnostics.terrainAvailability;

calibration.visibility.filteredAvailability = ...
    referenceAvailability;

end

%% =========================================================================
%  Reference IOD pass
%  =========================================================================

function [acquisitionIndices, ...
    bestConsecutiveRunLength, ...
    acceptedEpochsInSearchWindow] = ...
    selectReferenceIodPass( ...
        availability, ...
        times, ...
        searchEndTime, ...
        desiredCount)

availability = ...
    logical(availability(:).');

iodWindowMask = ...
    (times <= searchEndTime).';

eligible = ...
    availability & ...
    iodWindowMask;

acceptedEpochsInSearchWindow = ...
    nnz(eligible);

changes = ...
    diff([false,eligible,false]);

runStarts = ...
    find(changes == 1);

runEnds = ...
    find(changes == -1)-1;

bestRun = ...
    zeros(0,1);

for runIndex = 1:length(runStarts)

    currentRun = ...
        ( ...
        runStarts(runIndex): ...
        runEnds(runIndex) ...
        ).';

    if length(currentRun) > length(bestRun)

        bestRun = ...
            currentRun;
    end
end

bestConsecutiveRunLength = ...
    length(bestRun);

if bestConsecutiveRunLength < desiredCount

    acquisitionIndices = ...
        zeros(0,1);

    return
end

selectionLocations = ...
    round(linspace( ...
        1, ...
        bestConsecutiveRunLength, ...
        desiredCount));

acquisitionIndices = ...
    bestRun(selectionLocations);

acquisitionIndices = ...
    acquisitionIndices(:);

assert(length(acquisitionIndices) == desiredCount, ...
    "IOD acquisition selection returned the wrong number of observations.");

assert(length(unique(acquisitionIndices)) == desiredCount, ...
    "IOD acquisition selection contains duplicate epochs.");

end

%% =========================================================================
%  Simulate fixed IOD measurements
%  =========================================================================

function [observerPositionsMci,rightAscension,declination] = ...
    simulateSingleSensorMeasurements( ...
        times, ...
        truthStateHistory, ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        measurementAvailable, ...
        measurementNoiseFactor, ...
        measurementNoiseSeed, ...
        moonRadius, ...
        theta0, ...
        angularRate)

numberOfTimes = ...
    length(times);

observerPositionsMci = ...
    zeros(numberOfTimes,3);

rightAscension = ...
    NaN(numberOfTimes,1);

declination = ...
    NaN(numberOfTimes,1);

sensorMoonRotatingState = ...
    referenceFrames.topographic( ...
        zeros(6,1), ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        moonRadius, ...
        "toRotating");

noiseStream = ...
    RandStream( ...
        'mt19937ar', ...
        'Seed',measurementNoiseSeed);

for timeIndex = 1:numberOfTimes

    observationTime = ...
        times(timeIndex);

    sensorMciState = ...
        referenceFrames.moonRotating( ...
            sensorMoonRotatingState, ...
            observationTime, ...
            theta0, ...
            angularRate, ...
            "toInertial");

    observerPositionsMci(timeIndex,:) = ...
        sensorMciState(1:3).';

    if ~measurementAvailable(timeIndex)
        continue
    end

    idealMeasurement = ...
        measurements.surfaceRaDecMeasurement( ...
            truthStateHistory(:,timeIndex), ...
            observationTime, ...
            sensorLatitude, ...
            sensorLongitude, ...
            dem, ...
            moonRadius, ...
            theta0, ...
            angularRate);

    noisyMeasurement = ...
        idealMeasurement + ...
        measurementNoiseFactor* ...
        randn(noiseStream,2,1);

    rightAscension(timeIndex) = ...
        wrapAngle(noisyMeasurement(1));

    declination(timeIndex) = ...
        noisyMeasurement(2);
end

end

%% =========================================================================
%  Reference orbital state
%  =========================================================================

function state = ...
    referenceOrbitState( ...
        periapsisAltitudeKm, ...
        eccentricity, ...
        inclination, ...
        raan, ...
        argumentOfPeriapsis, ...
        trueAnomaly, ...
        moonRadius, ...
        moonMu)

periapsisRadius = ...
    moonRadius + periapsisAltitudeKm;

semiMajorAxis = ...
    periapsisRadius/(1-eccentricity);

semilatusRectum = ...
    semiMajorAxis*(1-eccentricity^2);

radius = ...
    semilatusRectum / ...
    (1+eccentricity*cos(trueAnomaly));

positionPerifocal = ...
    radius*[ ...
        cos(trueAnomaly)
        sin(trueAnomaly)
        0
    ];

velocityPerifocal = ...
    sqrt(moonMu/semilatusRectum)*[ ...
        -sin(trueAnomaly)
         eccentricity+cos(trueAnomaly)
         0
    ];

rotationRaan = [ ...
     cos(raan),-sin(raan),0
     sin(raan), cos(raan),0
     0,0,1
];

rotationInclination = [ ...
    1,0,0
    0,cos(inclination),-sin(inclination)
    0,sin(inclination), cos(inclination)
];

rotationPeriapsis = [ ...
     cos(argumentOfPeriapsis),-sin(argumentOfPeriapsis),0
     sin(argumentOfPeriapsis), cos(argumentOfPeriapsis),0
     0,0,1
];

perifocalToMci = ...
    rotationRaan * ...
    rotationInclination * ...
    rotationPeriapsis;

state = [ ...
    perifocalToMci*positionPerifocal
    perifocalToMci*velocityPerifocal
];

end

%% =========================================================================
%  Generic Earth / Sun histories
%  =========================================================================

function [earthPositionsMci,sunPositionsMci] = ...
    buildCelestialHistories( ...
        times, ...
        moonAngularRate, ...
        ephemeris)

numberOfTimes = ...
    length(times);

earthPhase = ...
    ephemeris.earthPhase0Rad + ...
    moonAngularRate*times.';

earthPositionsMci = ...
    ephemeris.earthMoonDistanceKm*[ ...
        cos(earthPhase)
        sin(earthPhase)
        zeros(1,numberOfTimes)
    ];

sunRate = ...
    2*pi/ephemeris.sunOrbitalPeriodSeconds;

sunPhase = ...
    ephemeris.sunPhase0Rad + ...
    sunRate*times.';

sunPlanarPositions = ...
    ephemeris.sunMoonDistanceKm*[ ...
        cos(sunPhase)
        sin(sunPhase)
        zeros(1,numberOfTimes)
    ];

solarInclination = ...
    ephemeris.solarInclinationRad;

solarRotation = [ ...
    1,0,0
    0,cos(solarInclination),-sin(solarInclination)
    0,sin(solarInclination), cos(solarInclination)
];

sunPositionsMci = ...
    solarRotation*sunPlanarPositions;

end

%% =========================================================================
%  Visibility summary
%  =========================================================================

function summary = ...
    buildVisibilitySummary( ...
        filteredAvailability, ...
        diagnostics)

numberOfCandidates = ...
    size(filteredAvailability,1);

numberOfObjects = ...
    size(filteredAvailability,3);

summary = struct();

summary.totalGeometric = ...
    nnz(diagnostics.geometricAvailability);

summary.totalTerrainAccepted = ...
    nnz(diagnostics.terrainAvailability);

summary.totalEarthBlocked = ...
    nnz(diagnostics.earthBlocked);

summary.totalSunBlocked = ...
    nnz(diagnostics.sunBlocked);

summary.totalAccepted = ...
    nnz(filteredAvailability);

summary.acceptedByCandidateObject = ...
    reshape( ...
        sum(filteredAvailability,2), ...
        numberOfCandidates, ...
        numberOfObjects);

summary.acceptedByObject = ...
    reshape( ...
        sum(filteredAvailability,[1,2]), ...
        numberOfObjects, ...
        1);

end

%% =========================================================================
%  Recursive configuration merge
%  =========================================================================

function output = ...
    mergeStruct(defaults,override)

output = ...
    defaults;

overrideFields = ...
    fieldnames(override);

for fieldIndex = 1:length(overrideFields)

    fieldName = ...
        overrideFields{fieldIndex};

    overrideValue = ...
        override.(fieldName);

    if isfield(output,fieldName) && ...
            isstruct(output.(fieldName)) && ...
            isscalar(output.(fieldName)) && ...
            isstruct(overrideValue) && ...
            isscalar(overrideValue)

        output.(fieldName) = ...
            mergeStruct( ...
                output.(fieldName), ...
                overrideValue);

    else

        output.(fieldName) = ...
            overrideValue;
    end
end

end

%% =========================================================================
%  Angle wrapping
%  =========================================================================

function wrappedAngle = wrapAngle(angle)

wrappedAngle = ...
    atan2( ...
        sin(angle), ...
        cos(angle));

end