function [geometricCountsByObjectAll,filteredCountsByObjectAll] = ...
    buildTruthVisibilityChunks( ...
        chunkMetadata, ...
        times, ...
        truthStateHistories, ...
        dem, ...
        earthPositionsMci, ...
        sunPositionsMci, ...
        visibilityConfig, ...
        terrainConfig, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate, ...
        useParallel, ...
        maximumParallelWorkers, ...
        reuseExisting)
% BUILDTRUTHVISIBILITYCHUNKS Build truth visibility and prefilter counts by chunk.

arguments
    chunkMetadata (:,1) struct
    times (:,1) double
    truthStateHistories (6,:,:) double
    dem (1,1) griddedInterpolant
    earthPositionsMci (3,:) double
    sunPositionsMci (3,:) double
    visibilityConfig (1,1) struct
    terrainConfig (1,1) struct
    moonRadius (1,1) double {mustBePositive}
    theta0 (1,1) double
    moonAngularRate (1,1) double
    useParallel (1,1) logical = false
    maximumParallelWorkers (1,1) double {mustBeInteger,mustBePositive} = 2
    reuseExisting (1,1) logical = false
end

numberOfChunks = numel(chunkMetadata);
numberOfObjects = size(truthStateHistories,3);

geometricCountCells = cell(numberOfChunks,1);
filteredCountCells = cell(numberOfChunks,1);

fprintf("\n6/9 Building truth visibility chunks...\n");
fprintf("  Parallel: %d (max workers %d)\n", ...
    useParallel,maximumParallelWorkers);

if useParallel
    parfor (chunkIndex = 1:numberOfChunks,maximumParallelWorkers)
        [geometricCountCells{chunkIndex},filteredCountCells{chunkIndex}] = ...
            buildOneTruthVisibilityChunk( ...
                chunkMetadata(chunkIndex), ...
                times, ...
                truthStateHistories, ...
                dem, ...
                earthPositionsMci, ...
                sunPositionsMci, ...
                visibilityConfig, ...
                terrainConfig, ...
                moonRadius, ...
                theta0, ...
                moonAngularRate, ...
                numberOfObjects, ...
                reuseExisting);
    end
else
    for chunkIndex = 1:numberOfChunks
        [geometricCountCells{chunkIndex},filteredCountCells{chunkIndex}] = ...
            buildOneTruthVisibilityChunk( ...
                chunkMetadata(chunkIndex), ...
                times, ...
                truthStateHistories, ...
                dem, ...
                earthPositionsMci, ...
                sunPositionsMci, ...
                visibilityConfig, ...
                terrainConfig, ...
                moonRadius, ...
                theta0, ...
                moonAngularRate, ...
                numberOfObjects, ...
                reuseExisting);
    end
end

geometricCountsByObjectAll = vertcat(geometricCountCells{:});
filteredCountsByObjectAll = vertcat(filteredCountCells{:});

end

function [geometricCounts,filteredCounts] = buildOneTruthVisibilityChunk( ...
    metadata,times,truthStateHistories,dem,earthPositionsMci, ...
    sunPositionsMci,visibilityConfig,terrainConfig,moonRadius,theta0, ...
    moonAngularRate,numberOfObjects,reuseExisting)

chunkFile = string(metadata.filePath);

if reuseExisting && isfile(chunkFile)
    variableNames = string(who("-file",chunkFile));

    if all(ismember( ...
            ["geometricCountsByObject","filteredCountsByObject"], ...
            variableNames))

        existing = load( ...
            chunkFile, ...
            "geometricCountsByObject", ...
            "filteredCountsByObject");

        if isequal(size(existing.geometricCountsByObject), ...
                [metadata.numberOfOriginalCandidates,numberOfObjects]) && ...
                isequal(size(existing.filteredCountsByObject), ...
                [metadata.numberOfOriginalCandidates,numberOfObjects])

            geometricCounts = existing.geometricCountsByObject;
            filteredCounts = existing.filteredCountsByObject;

            fprintf("  Reusing truth visibility chunk %d (%d sites)\n", ...
                metadata.chunkNumber,metadata.numberOfOriginalCandidates);
            return
        end
    end
end

data = load( ...
    chunkFile, ...
    "candidateLatitudesRad", ...
    "candidateLongitudesRad", ...
    "horizonAzimuthsRad", ...
    "maximumTerrainElevationRad");

fprintf("  Truth visibility chunk %d (%d sites)\n", ...
    metadata.chunkNumber,metadata.numberOfOriginalCandidates);

[filteredAvailability,geometricAvailability] = ...
    optimization.buildFilteredVisibilityMasks( ...
        times, ...
        truthStateHistories, ...
        data.candidateLatitudesRad, ...
        data.candidateLongitudesRad, ...
        dem, ...
        data.horizonAzimuthsRad, ...
        data.maximumTerrainElevationRad, ...
        earthPositionsMci, ...
        sunPositionsMci, ...
        visibilityConfig.minimumElevationRad, ...
        terrainConfig.horizonMarginRad, ...
        visibilityConfig.earthRadiusKm, ...
        visibilityConfig.sunRadiusKm, ...
        visibilityConfig.sunMinimumAngularSeparationRad, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate, ...
        visibilityConfig.earthMinimumAngularSeparationRad);

numberOfChunkCandidates = numel(data.candidateLatitudesRad);

geometricCounts = reshape( ...
    sum(geometricAvailability,2), ...
    numberOfChunkCandidates,numberOfObjects);

filteredCounts = reshape( ...
    sum(filteredAvailability,2), ...
    numberOfChunkCandidates,numberOfObjects);

geometricCountsByObject = geometricCounts; %#ok<NASGU>
filteredCountsByObject = filteredCounts; %#ok<NASGU>

save( ...
    chunkFile, ...
    "geometricCountsByObject", ...
    "filteredCountsByObject", ...
    "-append");

end
