function [measurementAvailability, ...
    targetAzimuths, ...
    targetElevations, ...
    targetRanges, ...
    limitingElevations] = ...
    buildTerrainAwareLosDatabase( ...
        times, ...
        rsoStateHistories, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        horizonAzimuths, ...
        maximumTerrainElevation, ...
        instrumentMinimumElevation, ...
        horizonMargin, ...
        moonRadius, ...
        theta0, ...
        angularRate)
% BUILDTERRAINAWARELOSDATABASE Evaluate terrain LOS for an RSO set.
%
% Inputs:
%   times                     - Nx1 common observation times, s
%   rsoStateHistories         - 6xNxO MCI state histories
%   candidateLatitudes        - Sx1 candidate latitudes, rad
%   candidateLongitudes       - Sx1 east-positive longitudes, rad
%   dem                       - DEM griddedInterpolant
%   horizonAzimuths           - Ax1 azimuth database grid, rad
%   maximumTerrainElevation   - SxA terrain horizon database, rad
%   instrumentMinimumElevation- Instrument mask angle, rad
%   horizonMargin             - Terrain discretization margin, rad
%   moonRadius                - Lunar reference radius, km
%   theta0                    - Initial Moon rotation angle, rad
%   angularRate               - Lunar rotation rate, rad/s
%
% Outputs:
%   measurementAvailability - SxNxO terrain LOS gates
%   targetAzimuths          - SxNxO target azimuths, rad
%   targetElevations        - SxNxO target elevations, rad
%   targetRanges            - SxNxO target slant ranges, km
%   limitingElevations      - SxNxO applied elevation limits, rad
%
% The terrain database is static. These outputs are rebuilt whenever the
% RSO candidate set or observation arc changes.

arguments
    times (:,1) double
    rsoStateHistories (6,:,:) double
    candidateLatitudes (:,1) double
    candidateLongitudes (:,1) double
    dem (1,1) griddedInterpolant
    horizonAzimuths (:,1) double
    maximumTerrainElevation (:,:) double
    instrumentMinimumElevation (1,1) double
    horizonMargin (1,1) double {mustBeNonnegative}
    moonRadius (1,1) double {mustBePositive} = 1737.4
    theta0 (1,1) double = 0
    angularRate (1,1) double = ...
        2*pi/(27.321661*86400)
end

numberOfTimes = ...
    length(times);

numberOfObjects = ...
    size(rsoStateHistories,3);

numberOfSensors = ...
    length(candidateLatitudes);

numberOfAzimuths = ...
    length(horizonAzimuths);

if size(rsoStateHistories,2) ~= numberOfTimes
    error( ...
        "buildTerrainAwareLosDatabase:InvalidStateHistory", ...
        "The state history must contain one state per observation time.");
end

if length(candidateLongitudes) ~= numberOfSensors
    error( ...
        "buildTerrainAwareLosDatabase:InvalidSensors", ...
        "Candidate latitude and longitude arrays must have equal length.");
end

if size(maximumTerrainElevation,1) ~= numberOfSensors || ...
        size(maximumTerrainElevation,2) ~= numberOfAzimuths

    error( ...
        "buildTerrainAwareLosDatabase:InvalidHorizonDatabase", ...
        "Horizon database dimensions do not match the sensor and azimuth grids.");
end

if horizonAzimuths(1) ~= 0 || ...
        abs(horizonAzimuths(end) - 2*pi) > 1e-12

    error( ...
        "buildTerrainAwareLosDatabase:InvalidAzimuthGrid", ...
        "The horizon azimuth grid must include 0 and 2*pi.");
end

measurementAvailability = ...
    false(numberOfSensors,numberOfTimes,numberOfObjects);

targetAzimuths = ...
    zeros(numberOfSensors,numberOfTimes,numberOfObjects);

targetElevations = ...
    zeros(numberOfSensors,numberOfTimes,numberOfObjects);

targetRanges = ...
    zeros(numberOfSensors,numberOfTimes,numberOfObjects);

limitingElevations = ...
    zeros(numberOfSensors,numberOfTimes,numberOfObjects);

for objectIndex = 1:numberOfObjects

    for timeIndex = 1:numberOfTimes

        observationTime = ...
            times(timeIndex);

        stateMci = ...
            rsoStateHistories(:,timeIndex,objectIndex);

        stateMoonRotating = ...
            referenceFrames.moonRotating( ...
                stateMci, ...
                observationTime, ...
                theta0, ...
                angularRate, ...
                "fromInertial");

        for sensorIndex = 1:numberOfSensors

            sensorLatitude = ...
                candidateLatitudes(sensorIndex);

            sensorLongitude = mod( ...
                candidateLongitudes(sensorIndex), ...
                2*pi);

            [~,topographicMeasurement] = ...
                referenceFrames.topographic( ...
                    stateMoonRotating, ...
                    sensorLatitude, ...
                    sensorLongitude, ...
                    dem, ...
                    moonRadius, ...
                    "fromRotating");

            targetAzimuth = ...
                topographicMeasurement(1);

            targetElevation = ...
                topographicMeasurement(2);

            targetRange = ...
                topographicMeasurement(3);

            terrainElevationLimit = interp1( ...
                horizonAzimuths, ...
                maximumTerrainElevation(sensorIndex,:).', ...
                targetAzimuth, ...
                "linear");

            limitingElevation = max( ...
                instrumentMinimumElevation, ...
                terrainElevationLimit + horizonMargin);

            targetAzimuths( ...
                sensorIndex,timeIndex,objectIndex) = ...
                targetAzimuth;

            targetElevations( ...
                sensorIndex,timeIndex,objectIndex) = ...
                targetElevation;

            targetRanges( ...
                sensorIndex,timeIndex,objectIndex) = ...
                targetRange;

            limitingElevations( ...
                sensorIndex,timeIndex,objectIndex) = ...
                limitingElevation;

            measurementAvailability( ...
                sensorIndex,timeIndex,objectIndex) = ...
                targetElevation >= limitingElevation;
        end
    end
end

end