function [filteredAvailability,geometricAvailability] = ...
    buildFilteredVisibilityMasks( ...
        times, ...
        targetStateHistories, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        horizonAzimuths, ...
        maximumTerrainElevation, ...
        earthPositionsMci, ...
        sunPositionsMci, ...
        instrumentMinimumElevation, ...
        horizonMargin, ...
        earthRadius, ...
        sunRadius, ...
        sunMinimumAngularSeparation, ...
        moonRadius, ...
        theta0, ...
        angularRate, ...
        earthMinimumAngularSeparation)
% BUILDFILTEREDVISIBILITYMASKS Memory-lean terrain/celestial visibility.
%
% This production helper computes only the logical masks required by the
% candidate prefilter and optimization database. Unlike the diagnostic
% visibility builder, it does not retain large azimuth, elevation, range,
% terrain-limit, or angular-separation histories.

arguments
    times (:,1) double
    targetStateHistories (6,:,:) double
    candidateLatitudes (:,1) double
    candidateLongitudes (:,1) double
    dem (1,1) griddedInterpolant
    horizonAzimuths (:,1) double
    maximumTerrainElevation (:,:) double
    earthPositionsMci (3,:) double
    sunPositionsMci (3,:) double
    instrumentMinimumElevation (1,1) double = 0
    horizonMargin (1,1) double {mustBeNonnegative} = 0
    earthRadius (1,1) double {mustBePositive} = 6378.1366
    sunRadius (1,1) double {mustBePositive} = 695700
    sunMinimumAngularSeparation (1,1) double {mustBeNonnegative} = 0
    moonRadius (1,1) double {mustBePositive} = 1737.4
    theta0 (1,1) double = 0
    angularRate (1,1) double = 2*pi/(27.321661*86400)
    earthMinimumAngularSeparation (1,1) double {mustBeNonnegative} = 0
end

numberOfTimes = numel(times);
numberOfSensors = numel(candidateLatitudes);
numberOfObjects = size(targetStateHistories,3);

assert(size(targetStateHistories,2) == numberOfTimes, ...
    "Target state histories have the wrong time dimension.");
assert(numel(candidateLongitudes) == numberOfSensors, ...
    "Candidate latitude and longitude arrays must match.");
assert(size(maximumTerrainElevation,1) == numberOfSensors, ...
    "Terrain horizon candidate dimension is inconsistent.");
assert(size(maximumTerrainElevation,2) == numel(horizonAzimuths), ...
    "Terrain horizon azimuth dimension is inconsistent.");
assert(size(earthPositionsMci,2) == numberOfTimes && ...
    size(sunPositionsMci,2) == numberOfTimes, ...
    "Celestial histories have the wrong time dimension.");

filteredAvailability = false(numberOfSensors,numberOfTimes,numberOfObjects);

if nargout > 1
    geometricAvailability = false(numberOfSensors,numberOfTimes,numberOfObjects);
else
    geometricAvailability = false(0,0,0);
end

sensorStatesMoonRotating = zeros(6,numberOfSensors);

for sensorIndex = 1:numberOfSensors
    sensorStatesMoonRotating(:,sensorIndex) = ...
        referenceFrames.topographic( ...
            zeros(6,1), ...
            candidateLatitudes(sensorIndex), ...
            mod(candidateLongitudes(sensorIndex),2*pi), ...
            dem, ...
            moonRadius, ...
            "toRotating");
end

for timeIndex = 1:numberOfTimes
    observationTime = times(timeIndex);
    earthPosition = earthPositionsMci(:,timeIndex);
    sunPosition = sunPositionsMci(:,timeIndex);

    sensorPositionsMci = zeros(3,numberOfSensors);

    for sensorIndex = 1:numberOfSensors
        sensorStateMci = referenceFrames.moonRotating( ...
            sensorStatesMoonRotating(:,sensorIndex), ...
            observationTime, ...
            theta0, ...
            angularRate, ...
            "toInertial");

        sensorPositionsMci(:,sensorIndex) = sensorStateMci(1:3);
    end

    for objectIndex = 1:numberOfObjects
        stateMci = targetStateHistories(:,timeIndex,objectIndex);
        stateMoonRotating = referenceFrames.moonRotating( ...
            stateMci, ...
            observationTime, ...
            theta0, ...
            angularRate, ...
            "fromInertial");

        targetPosition = stateMci(1:3);

        for sensorIndex = 1:numberOfSensors
            [~,topographicMeasurement] = referenceFrames.topographic( ...
                stateMoonRotating, ...
                candidateLatitudes(sensorIndex), ...
                mod(candidateLongitudes(sensorIndex),2*pi), ...
                dem, ...
                moonRadius, ...
                "fromRotating");

            targetAzimuth = topographicMeasurement(1);
            targetElevation = topographicMeasurement(2);

            if nargout > 1
                geometricAvailability(sensorIndex,timeIndex,objectIndex) = ...
                    targetElevation >= instrumentMinimumElevation;
            end

            terrainElevationLimit = interp1( ...
                horizonAzimuths, ...
                maximumTerrainElevation(sensorIndex,:).', ...
                targetAzimuth, ...
                "linear");

            limitingElevation = max( ...
                instrumentMinimumElevation, ...
                terrainElevationLimit + horizonMargin);

            if targetElevation < limitingElevation
                continue
            end

            [celestialAvailable,~,~] = constraints.celestialVisibility( ...
                sensorPositionsMci(:,sensorIndex), ...
                targetPosition, ...
                earthPosition, ...
                sunPosition, ...
                earthRadius, ...
                sunRadius, ...
                sunMinimumAngularSeparation, ...
                earthMinimumAngularSeparation);

            filteredAvailability(sensorIndex,timeIndex,objectIndex) = ...
                celestialAvailable;
        end
    end
end

end
