function [results,diagnostics] = evaluatePerturbedNetwork( ...
    sensorLatitudesRad,sensorLongitudesRad,database,dem)
% EVALUATEPERTURBEDNETWORK Evaluate one arbitrary off-grid surface network.
%
% This is the continuous counterpart to optimization.networkObjective. The
% target dynamics, STM/process-noise histories, P0, measurement covariance,
% state scales, object weights, and stored Earth/Sun ephemerides are reused
% from the production database. Every quantity that depends on the perturbed
% sensor positions is rebuilt: DEM elevation, terrain horizon, visibility,
% celestial screening, measurement availability, and RA/Dec Jacobians.

arguments
    sensorLatitudesRad (:,1) double
    sensorLongitudesRad (:,1) double
    database (1,1) struct
    dem (1,1) griddedInterpolant
end

numberOfSensors = numel(sensorLatitudesRad);
assert(numberOfSensors >= 1,"At least one sensor is required.");
assert(numel(sensorLongitudesRad) == numberOfSensors, ...
    "Latitude and longitude vectors must have equal length.");
assert(all(isfinite(sensorLatitudesRad)),"Sensor latitudes must be finite.");
assert(all(isfinite(sensorLongitudesRad)),"Sensor longitudes must be finite.");
assert(all(sensorLatitudesRad >= -pi/2) && ...
    all(sensorLatitudesRad <= deg2rad(-75)), ...
    "Sensor latitude lies outside the allowed south-polar region.");
sensorLongitudesRad = mod(sensorLongitudesRad,2*pi);

config = database.config;
moonRadiusKm = config.moon.radiusKm;
theta0Rad = config.moon.theta0Rad;
angularRateRadS = 2*pi/config.moon.siderealPeriodSeconds;
times = database.tracking.times(:);
targetStateHistories = database.tracking.referenceStateHistories;
numberOfTimes = numel(times);
numberOfObjects = size(targetStateHistories,3);
assert(size(targetStateHistories,2) == numberOfTimes, ...
    "Tracking state-history dimensions are inconsistent.");

% Rebuild local terrain horizons for the arbitrary off-grid sites.
[horizonAzimuthsRad,maximumTerrainElevationRad,~,sensorElevationsKm] = ...
    digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
        sensorLatitudesRad, ...
        sensorLongitudesRad, ...
        dem, ...
        config.terrain.maximumRangeKm, ...
        config.terrain.rangeStepKm, ...
        config.terrain.horizonAzimuthStepRad, ...
        moonRadiusKm);
assert(all(isfinite(sensorElevationsKm)), ...
    "One or more sensor elevations are nonfinite.");
assert(all(isfinite(maximumTerrainElevationRad),"all"), ...
    "Terrain-horizon database contains nonfinite values.");

% Match the tracking epochs to the fixed ephemeris grid.
truthTimes = database.truth.times(:);
[timeFound,ephemerisIndices] = ismember(times,truthTimes);
assert(all(timeFound), ...
    "Tracking times were not found in the stored ephemeris time grid.");
earthPositionsMci = database.ephemeris.earthPositionsMci(:,ephemerisIndices);
sunPositionsMci = database.ephemeris.sunPositionsMci(:,ephemerisIndices);

sunMinimumSeparationRad = config.visibility.minimumAngularSeparationRad;
if isfield(config.visibility,"sunMinimumAngularSeparationRad")
    sunMinimumSeparationRad = config.visibility.sunMinimumAngularSeparationRad;
end
earthMinimumSeparationRad = sunMinimumSeparationRad;
if isfield(config.visibility,"earthMinimumAngularSeparationRad")
    earthMinimumSeparationRad = config.visibility.earthMinimumAngularSeparationRad;
end

% Rebuild terrain-aware and celestial-screened measurement availability.
[filteredAvailability,visibilityDiagnostics] = ...
    optimization.buildFilteredVisibilityDatabase( ...
        times, ...
        targetStateHistories, ...
        sensorLatitudesRad, ...
        sensorLongitudesRad, ...
        dem, ...
        horizonAzimuthsRad, ...
        maximumTerrainElevationRad, ...
        earthPositionsMci, ...
        sunPositionsMci, ...
        config.visibility.minimumElevationRad, ...
        config.terrain.horizonMarginRad, ...
        config.visibility.earthRadiusKm, ...
        config.visibility.sunRadiusKm, ...
        sunMinimumSeparationRad, ...
        moonRadiusKm, ...
        theta0Rad, ...
        angularRateRadS, ...
        earthMinimumSeparationRad);
assert(isequal(size(filteredAvailability), ...
    [numberOfSensors,numberOfTimes,numberOfObjects]), ...
    "Unexpected measurement-availability dimensions.");

% Rebuild RA/Dec Jacobians because the perturbed sites are off-grid.
measurementJacobians = zeros( ...
    2,6,numberOfSensors,numberOfTimes,numberOfObjects);
for objectIndex = 1:numberOfObjects
    for timeIndex = 1:numberOfTimes
        targetState = targetStateHistories(:,timeIndex,objectIndex);
        observationTime = times(timeIndex);
        for sensorIndex = 1:numberOfSensors
            measurementJacobians(:,:,sensorIndex,timeIndex,objectIndex) = ...
                measurements.surfaceRaDecJacobian( ...
                    targetState, ...
                    observationTime, ...
                    sensorLatitudesRad(sensorIndex), ...
                    sensorLongitudesRad(sensorIndex), ...
                    dem, ...
                    moonRadiusKm, ...
                    theta0Rad, ...
                    angularRateRadS);
        end
    end
end

selectedSensors = true(numberOfSensors,1);
measurementCovariance = database.measurement.covariance;
assert(size(measurementCovariance,3) == 1, ...
    ["The continuous evaluator expects one common measurement " ...
     "covariance for the lunar surface sensors."]);

[informationObjectiveValue,informationByObject] = ...
    optimization.informationObjective( ...
        selectedSensors, ...
        database.prior.initialCovariances, ...
        database.tracking.stateTransitionHistories, ...
        database.tracking.processNoiseHistories, ...
        measurementJacobians, ...
        filteredAvailability, ...
        measurementCovariance, ...
        database.estimation.stateScales, ...
        database.estimation.objectWeights);

[coverageObjectiveValue,coverageByObject] = ...
    optimization.coverageObjective( ...
        selectedSensors, ...
        filteredAvailability, ...
        database.estimation.objectWeights);

results = struct();
results.sensorLatitudesRad = sensorLatitudesRad;
results.sensorLongitudesRad = sensorLongitudesRad;
results.sensorElevationsKm = sensorElevationsKm;
results.informationObjectiveValue = informationObjectiveValue;
results.informationScore = -informationObjectiveValue;
results.coverageObjectiveValue = coverageObjectiveValue;
results.coverageScore = -coverageObjectiveValue;
results.informationByObject = informationByObject;
results.coverageByObject = coverageByObject;
results.numberOfAcceptedMeasurements = nnz(filteredAvailability);
results.numberOfPossibleMeasurements = numel(filteredAvailability);

if nargout > 1
    diagnostics = struct();
    diagnostics.filteredAvailability = filteredAvailability;
    diagnostics.visibility = visibilityDiagnostics;
    diagnostics.horizonAzimuthsRad = horizonAzimuthsRad;
    diagnostics.maximumTerrainElevationRad = maximumTerrainElevationRad;
    diagnostics.measurementJacobians = measurementJacobians;
else
    diagnostics = struct();
end

end
