function [objectiveValue,objectScores] = ...
    informationObjective( ...
        selectedSensors, ...
        initialCovariances, ...
        stateTransitionHistories, ...
        processNoiseHistories, ...
        measurementJacobianHistories, ...
        measurementAvailability, ...
        measurementCovariances, ...
        stateScales, ...
        objectWeights)
% INFORMATIONOBJECTIVE Evaluate network EKF D-optimality.
%
% Inputs:
%   selectedSensors             - Sx1 binary/logical selection vector
%   initialCovariances          - 6x6xO fixed IOD covariances
%   stateTransitionHistories    - 6x6xNxO interval STMs
%   processNoiseHistories       - 6x6xNxO process covariances
%   measurementJacobianHistories- 2x6xSxNxO Jacobians
%   measurementAvailability     - SxNxO LOS gates
%   measurementCovariances      - 2x2 or 2x2xS measurement covariances
%   stateScales                 - 6x1 normalization scales
%   objectWeights               - Ox1 nonnegative weights
%
% Outputs:
%   objectiveValue - Negative weighted information score for minimization
%   objectScores   - Ox1 mean D-optimality scores
%
% A larger D-optimality score is better. The negative weighted score is
% returned because most MATLAB optimization routines minimize.

arguments
    selectedSensors (:,1)
    initialCovariances (6,6,:) double
    stateTransitionHistories (6,6,:,:) double
    processNoiseHistories (6,6,:,:) double
    measurementJacobianHistories (2,6,:,:,:) double
    measurementAvailability (:,:,:) logical
    measurementCovariances double
    stateScales (6,1) double {mustBePositive}
    objectWeights (:,1) double {mustBeNonnegative}
end

numberOfObjects = ...
    size(initialCovariances,3);

numberOfSensors = ...
    size(measurementAvailability,1);

numberOfTimes = ...
    size(measurementAvailability,2);

if length(selectedSensors) ~= numberOfSensors
    error( ...
        "informationObjective:InvalidSensorDimensions", ...
        "selectedSensors must contain one entry per candidate sensor.");
end

if length(objectWeights) ~= numberOfObjects
    error( ...
        "informationObjective:InvalidObjectWeights", ...
        "Provide one weight per tracked object.");
end

if sum(objectWeights) <= 0
    error( ...
        "informationObjective:InvalidObjectWeights", ...
        "At least one object weight must be positive.");
end

if size(stateTransitionHistories,3) ~= numberOfTimes || ...
        size(stateTransitionHistories,4) ~= numberOfObjects || ...
        size(processNoiseHistories,3) ~= numberOfTimes || ...
        size(processNoiseHistories,4) ~= numberOfObjects || ...
        size(measurementJacobianHistories,3) ~= numberOfSensors || ...
        size(measurementJacobianHistories,4) ~= numberOfTimes || ...
        size(measurementJacobianHistories,5) ~= numberOfObjects || ...
        size(measurementAvailability,3) ~= numberOfObjects

    error( ...
        "informationObjective:InvalidDatabaseDimensions", ...
        "Tracking database dimensions are inconsistent.");
end

objectScores = ...
    zeros(numberOfObjects,1);

for objectIndex = 1:numberOfObjects

    objectStateTransitions = reshape( ...
        stateTransitionHistories( ...
            :,:,:,objectIndex), ...
        6,6,numberOfTimes);

    objectProcessNoise = reshape( ...
        processNoiseHistories( ...
            :,:,:,objectIndex), ...
        6,6,numberOfTimes);

    objectJacobians = reshape( ...
        measurementJacobianHistories( ...
            :,:,:,:,objectIndex), ...
        2,6,numberOfSensors,numberOfTimes);

    objectAvailability = reshape( ...
        measurementAvailability( ...
            :,:,objectIndex), ...
        numberOfSensors,numberOfTimes);

    [~,dOptimalityHistory] = ...
        estimation.propagateNetworkCovariance( ...
            initialCovariances(:,:,objectIndex), ...
            objectStateTransitions, ...
            objectProcessNoise, ...
            objectJacobians, ...
            objectAvailability, ...
            selectedSensors, ...
            measurementCovariances, ...
            stateScales);

    % Mean information over the complete tracking arc.
    objectScores(objectIndex) = ...
        mean(dOptimalityHistory);
end

normalizedWeights = ...
    objectWeights/sum(objectWeights);

informationScore = ...
    sum(normalizedWeights.*objectScores);

objectiveValue = ...
    -informationScore;

end