function [objectiveValue,details] = ...
    networkObjectiveFromConstant( ...
        sensorDecision, ...
        databaseConstant, ...
        objectiveMode)
% NETWORKOBJECTIVEFROMCONSTANT Evaluate a network using worker-local data.
%
% This wrapper is intended for Global Optimization Toolbox parallel runs.
% The frozen optimization database is stored in a parallel.pool.Constant so
% the GA objective handle does not capture and repeatedly serialize the full
% database for every independent optimization run.

arguments
    sensorDecision double
    databaseConstant (1,1) parallel.pool.Constant
    objectiveMode (1,1) string
end

[objectiveValue,details] = ...
    optimization.networkObjective( ...
        sensorDecision, ...
        databaseConstant.Value, ...
        objectiveMode);

end
