function [referenceStateHistory, ...
    stateTransitionHistory, ...
    processNoiseHistory, ...
    measurementJacobianHistory, ...
    measurementAvailable, ...
    topographicElevation] = ...
    precomputeTrackingData( ...
        initialTime, ...
        observationTimes, ...
        initialState, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        minimumElevation, ...
        accelerationNoiseIntensity, ...
        moonMu, ...
        moonRadius, ...
        theta0, ...
        angularRate)
% PRECOMPUTETRACKINGDATA Build deterministic tracking data for optimization.
%
% Inputs:
%   initialTime                - Epoch associated with initialState, s
%   observationTimes           - Nx1 observation times after initialTime, s
%   initialState               - 6x1 nominal MCI state at initialTime
%   candidateLatitudes         - Sx1 candidate sensor latitudes, rad
%   candidateLongitudes        - Sx1 east-positive longitudes, rad
%   dem                        - Processed lunar griddedInterpolant
%   minimumElevation           - Minimum geometric elevation, rad
%   accelerationNoiseIntensity - Acceleration-noise PSD, km^2/s^3
%   moonMu                     - Lunar gravitational parameter, km^3/s^2
%   moonRadius                 - Lunar reference radius, km
%   theta0                     - Initial Moon rotation angle, rad
%   angularRate                - Lunar rotation rate, rad/s
%
% Outputs:
%   referenceStateHistory      - 6xN nominal MCI states
%   stateTransitionHistory     - 6x6xN interval STMs
%   processNoiseHistory        - 6x6xN discrete process covariances
%   measurementJacobianHistory - 2x6xSxN RA/Dec Jacobians
%   measurementAvailable       - SxN geometric LOS gates
%   topographicElevation       - SxN target elevations, rad
%
% The STM at index k maps the state and covariance from the previous epoch
% to observationTimes(k). At k = 1, the previous epoch is initialTime.
%
% The geometric LOS gate used here can later be replaced by the terrain
% horizon database without changing the covariance propagation function.

arguments
    initialTime (1,1) double
    observationTimes (:,1) double
    initialState (6,1) double
    candidateLatitudes (:,1) double
    candidateLongitudes (:,1) double
    dem (1,1) griddedInterpolant
    minimumElevation (1,1) double
    accelerationNoiseIntensity (1,1) double ...
        {mustBeNonnegative}
    moonMu (1,1) double {mustBePositive} = 4902.800066
    moonRadius (1,1) double {mustBePositive} = 1737.4
    theta0 (1,1) double = 0
    angularRate (1,1) double = ...
        2*pi/(27.321661*86400)
end

numberOfTimes = length(observationTimes);
numberOfSensors = length(candidateLatitudes);

if length(candidateLongitudes) ~= numberOfSensors
    error( ...
        "precomputeTrackingData:InvalidSensorDimensions", ...
        "Candidate latitude and longitude arrays must have equal length.");
end

if isempty(observationTimes)
    error( ...
        "precomputeTrackingData:EmptyTimes", ...
        "At least one observation time is required.");
end

if observationTimes(1) <= initialTime || ...
        any(diff(observationTimes) <= 0)

    error( ...
        "precomputeTrackingData:InvalidTimes", ...
        "Observation times must be strictly increasing and after initialTime.");
end

referenceStateHistory = ...
    zeros(6,numberOfTimes);

stateTransitionHistory = ...
    zeros(6,6,numberOfTimes);

processNoiseHistory = ...
    zeros(6,6,numberOfTimes);

measurementJacobianHistory = ...
    zeros(2,6,numberOfSensors,numberOfTimes);

measurementAvailable = ...
    false(numberOfSensors,numberOfTimes);

topographicElevation = ...
    zeros(numberOfSensors,numberOfTimes);

identityMatrix = eye(6);

odeOptions = odeset( ...
    "RelTol",1e-11, ...
    "AbsTol",1e-12);

currentTime = initialTime;
currentState = initialState;

for timeIndex = 1:numberOfTimes

    observationTime = ...
        observationTimes(timeIndex);

    timeStep = ...
        observationTime - currentTime;

    %% Propagate nominal state and interval STM

    augmentedInitialState = [
        currentState
        reshape(identityMatrix,36,1)
    ];

    [~,augmentedHistory] = ode45( ...
        @(time,augmentedState) ...
            orbitDynamics.lunarStateAndStmDynamics( ...
                time,augmentedState,moonMu), ...
        [currentTime,observationTime], ...
        augmentedInitialState, ...
        odeOptions);

    augmentedFinalState = ...
        augmentedHistory(end,:).';

    propagatedState = ...
        augmentedFinalState(1:6);

    stateTransitionMatrix = reshape( ...
        augmentedFinalState(7:end),6,6);

    processNoise = ...
        estimation.isotropicProcessNoise( ...
            timeStep, ...
            accelerationNoiseIntensity);

    referenceStateHistory(:,timeIndex) = ...
        propagatedState;

    stateTransitionHistory(:,:,timeIndex) = ...
        stateTransitionMatrix;

    processNoiseHistory(:,:,timeIndex) = ...
        processNoise;

    %% Convert target state to the Moon-rotating frame

    stateMoonRotating = ...
        referenceFrames.moonRotating( ...
            propagatedState, ...
            observationTime, ...
            theta0, ...
            angularRate, ...
            "fromInertial");

    %% Calculate every candidate sensor Jacobian and LOS gate

    for sensorIndex = 1:numberOfSensors

        sensorLatitude = ...
            candidateLatitudes(sensorIndex);

        sensorLongitude = mod( ...
            candidateLongitudes(sensorIndex), ...
            2*pi);

        measurementJacobianHistory( ...
            :,:,sensorIndex,timeIndex) = ...
            measurements.surfaceRaDecJacobian( ...
                propagatedState, ...
                observationTime, ...
                sensorLatitude, ...
                sensorLongitude, ...
                dem, ...
                moonRadius, ...
                theta0, ...
                angularRate);

        [~,topographicMeasurement] = ...
            referenceFrames.topographic( ...
                stateMoonRotating, ...
                sensorLatitude, ...
                sensorLongitude, ...
                dem, ...
                moonRadius, ...
                "fromRotating");

        elevation = ...
            topographicMeasurement(2);

        topographicElevation( ...
            sensorIndex,timeIndex) = elevation;

        measurementAvailable( ...
            sensorIndex,timeIndex) = ...
            elevation >= minimumElevation;
    end

    currentTime = observationTime;
    currentState = propagatedState;
end

end