function [initialStatesMoonInertial,rsoCatalog] = ...
    buildRsoSet( ...
        selection, ...
        numberOfGeneratedObjects, ...
        periapsisAltitudeLimitsKm, ...
        inclinationLimitsRad, ...
        eccentricityLimits, ...
        moonRadius, ...
        moonMu)
% BUILDRSOSET Return operational, generated, or combined RSO sets.
%
% Inputs:
%   selection                   - "operational", "generated", or "both"
%   numberOfGeneratedObjects    - Exact number of generated RSOs
%   periapsisAltitudeLimitsKm   - Generated altitude limits, km
%   inclinationLimitsRad        - Generated inclination limits, rad
%   eccentricityLimits          - Generated eccentricity limits
%   moonRadius                  - Lunar reference radius, km
%   moonMu                      - Lunar gravitational parameter, km^3/s^2
%
% Outputs:
%   initialStatesMoonInertial   - 6xN initial MCI states
%   rsoCatalog                  - N-row catalog matching state columns
%
% With CAPSTONE excluded:
%   "operational" returns 4 objects.
%   "generated",10 returns 10 objects.
%   "both",10 returns 14 objects.

arguments
    selection (1,1) string = "both"

    numberOfGeneratedObjects (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0

    periapsisAltitudeLimitsKm (1,2) double = [50,1000]

    inclinationLimitsRad (1,2) double = [0,pi]

    eccentricityLimits (1,2) double = [0,0.8]

    moonRadius (1,1) double {mustBePositive} = 1737.4

    moonMu (1,1) double {mustBePositive} = 4902.800066
end

selection = lower(selection);

validSelections = [
    "operational"
    "generated"
    "both"
];

if ~any(selection == validSelections)
    error( ...
        "buildRsoSet:InvalidSelection", ...
        "selection must be operational, generated, or both.");
end

includeOperational = ...
    selection == "operational" || ...
    selection == "both";

includeGenerated = ...
    selection == "generated" || ...
    selection == "both";

if includeGenerated && numberOfGeneratedObjects < 1
    error( ...
        "buildRsoSet:MissingGeneratedCount", ...
        "A generated or combined set requires at least one generated RSO.");
end

initialStatesMoonInertial = ...
    zeros(6,0);

rsoCatalog = ...
    emptyCatalog();

%% Add operational objects

if includeOperational

    [operationalStates,operationalCatalog] = ...
        rsoGeneration.operationalRsos( ...
            moonRadius,moonMu);

    initialStatesMoonInertial = [
        initialStatesMoonInertial, ...
        operationalStates
    ];

    rsoCatalog = [
        rsoCatalog
        operationalCatalog
    ];
end

%% Add generated objects

if includeGenerated

    [generatedStates,generatedCatalog] = ...
        rsoGeneration.elementDistributedRsos( ...
            numberOfGeneratedObjects, ...
            periapsisAltitudeLimitsKm, ...
            inclinationLimitsRad, ...
            eccentricityLimits, ...
            moonRadius, ...
            moonMu);

    initialStatesMoonInertial = [
        initialStatesMoonInertial, ...
        generatedStates
    ];

    rsoCatalog = [
        rsoCatalog
        generatedCatalog
    ];
end

assert( ...
    size(initialStatesMoonInertial,2) == height(rsoCatalog), ...
    "The state and catalog object counts do not match.");

end


function catalog = emptyCatalog()

catalog = table( ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    false(0,1), ...
    strings(0,1), ...
    'VariableNames',{ ...
        'Name', ...
        'SourceType', ...
        'OrbitModel', ...
        'PeriapsisAltitudeKm', ...
        'ApoapsisAltitudeKm', ...
        'SemiMajorAxisKm', ...
        'Eccentricity', ...
        'InclinationRad', ...
        'RaanRad', ...
        'ArgumentOfPeriapsisRad', ...
        'TrueAnomalyRad', ...
        'PeriodSeconds', ...
        'RequiresMultiBodyDynamics', ...
        'SourceReference'});

end