function [initialStatesMoonInertial,rsoCatalog] = ...
    elementDistributedRsos( ...
        numberOfObjects, ...
        periapsisAltitudeLimitsKm, ...
        inclinationLimitsRad, ...
        eccentricityLimits, ...
        moonRadius, ...
        moonMu)
% ELEMENTDISTRIBUTEDRSOS Generate an orbital-element-distributed RSO set.
%
% Inputs:
%   numberOfObjects             - Exact number of generated RSOs
%   periapsisAltitudeLimitsKm   - [minimum maximum], km
%   inclinationLimitsRad        - [minimum maximum], rad
%   eccentricityLimits          - [minimum maximum]
%   moonRadius                  - Lunar reference radius, km
%   moonMu                      - Lunar gravitational parameter, km^3/s^2
%
% Outputs:
%   initialStatesMoonInertial   - 6xN MCI state matrix
%   rsoCatalog                  - N-row orbital-element catalog
%
% Periapsis altitude, inclination, and eccentricity each use N equally
% spaced levels. Inclination and eccentricity are deterministically
% permuted so the objects do not lie along one correlated diagonal.

arguments
    numberOfObjects (1,1) double ...
        {mustBeInteger,mustBePositive}

    periapsisAltitudeLimitsKm (1,2) double = [50,5000]

    inclinationLimitsRad (1,2) double = [0,pi]

    eccentricityLimits (1,2) double = [0,0.8]

    moonRadius (1,1) double {mustBePositive} = 1737.4

    moonMu (1,1) double {mustBePositive} = 4902.800066
end

%% Validate requested ranges

validateLimits( ...
    periapsisAltitudeLimitsKm, ...
    "periapsisAltitudeLimitsKm", ...
    0,inf,false);

validateLimits( ...
    inclinationLimitsRad, ...
    "inclinationLimitsRad", ...
    0,pi,false);

validateLimits( ...
    eccentricityLimits, ...
    "eccentricityLimits", ...
    0,1,true);

%% Build evenly spaced levels

periapsisLevels = ...
    equallySpacedLevels( ...
        periapsisAltitudeLimitsKm, ...
        numberOfObjects);

inclinationLevels = ...
    equallySpacedLevels( ...
        inclinationLimitsRad, ...
        numberOfObjects);

eccentricityLevels = ...
    equallySpacedLevels( ...
        eccentricityLimits, ...
        numberOfObjects);

sampleIndices = ...
    (0:numberOfObjects-1).';

%% Permute inclination and eccentricity pairings

inclinationStride = ...
    chooseCoprimeStride( ...
        numberOfObjects, ...
        max(1,round(numberOfObjects/3)));

eccentricityStride = ...
    chooseCoprimeStride( ...
        numberOfObjects, ...
        max(1,round(2*numberOfObjects/3)));

inclinationPermutation = ...
    mod( ...
        sampleIndices*inclinationStride, ...
        numberOfObjects) + 1;

eccentricityPermutation = ...
    mod( ...
        sampleIndices*eccentricityStride + ...
        floor(numberOfObjects/2), ...
        numberOfObjects) + 1;

periapsisAltitudeKm = ...
    periapsisLevels;

inclinationRad = ...
    inclinationLevels(inclinationPermutation);

eccentricity = ...
    eccentricityLevels(eccentricityPermutation);

%% Distribute the remaining orientation elements

raanRad = ...
    2*pi*sampleIndices/numberOfObjects;

goldenAngle = ...
    pi*(3 - sqrt(5));

argumentOfPeriapsisRad = ...
    mod(sampleIndices*goldenAngle,2*pi);

phaseStride = ...
    chooseCoprimeStride( ...
        numberOfObjects, ...
        max(1,round(numberOfObjects/2)));

trueAnomalyRad = ...
    2*pi*mod( ...
        sampleIndices*phaseStride, ...
        numberOfObjects) / numberOfObjects;

%% Complete the orbit elements

periapsisRadiusKm = ...
    moonRadius + periapsisAltitudeKm;

semiMajorAxisKm = ...
    periapsisRadiusKm./(1 - eccentricity);

apoapsisRadiusKm = ...
    semiMajorAxisKm.*(1 + eccentricity);

moonSoiRadius = 66100;  % km from lunar center

if any(apoapsisRadiusKm >= moonSoiRadius)

    invalidObject = find( ...
        apoapsisRadiusKm >= moonSoiRadius, ...
        1,"first");

    error( ...
        "elementDistributedRsos:OutsideLunarSoi", ...
        ["Generated RSO %d has an apocenter radius of " ...
        "%.3f km, outside the %.3f km lunar SOI."], ...
        invalidObject, ...
        apoapsisRadiusKm(invalidObject), ...
        moonSoiRadius);
end

apoapsisAltitudeKm = ...
    apoapsisRadiusKm - moonRadius;

periodSeconds = ...
    2*pi*sqrt(semiMajorAxisKm.^3/moonMu);

%% Build identifiers

names = compose( ...
    "Generated RSO %02d", ...
    (1:numberOfObjects).');

sourceTypes = ...
    repmat("Generated",numberOfObjects,1);

orbitModels = ...
    repmat( ...
        "Two-body element-distributed", ...
        numberOfObjects,1);

requiresMultiBodyDynamics = ...
    false(numberOfObjects,1);

sourceReferences = ...
    repmat( ...
        "Deterministic element-space design", ...
        numberOfObjects,1);

%% Convert orbital elements to MCI states

initialStatesMoonInertial = ...
    zeros(6,numberOfObjects);

for objectIndex = 1:numberOfObjects

    initialStatesMoonInertial(:,objectIndex) = ...
        keplerianToState( ...
            semiMajorAxisKm(objectIndex), ...
            eccentricity(objectIndex), ...
            inclinationRad(objectIndex), ...
            raanRad(objectIndex), ...
            argumentOfPeriapsisRad(objectIndex), ...
            trueAnomalyRad(objectIndex), ...
            moonMu);
end

%% Build catalog

rsoCatalog = table( ...
    names, ...
    sourceTypes, ...
    orbitModels, ...
    periapsisAltitudeKm, ...
    apoapsisAltitudeKm, ...
    semiMajorAxisKm, ...
    eccentricity, ...
    inclinationRad, ...
    raanRad, ...
    argumentOfPeriapsisRad, ...
    trueAnomalyRad, ...
    periodSeconds, ...
    requiresMultiBodyDynamics, ...
    sourceReferences, ...
    'VariableNames',{ ...
        'Name', ...
        'SourceType', ...
        'OrbitModel', ...
        'PeriapsisAltitudeKm', ...
        'ApoapsisAltitudeKm', ...
        'SemiMajorAxisKm', ...
        'Eccentricity', ...
        'InclinationRad', ...
        'RaanRad', ...
        'ArgumentOfPeriapsisRad', ...
        'TrueAnomalyRad', ...
        'PeriodSeconds', ...
        'RequiresMultiBodyDynamics', ...
        'SourceReference'});

end


function levels = equallySpacedLevels(limits,numberOfLevels)

if numberOfLevels == 1
    levels = mean(limits);
else
    levels = linspace( ...
        limits(1), ...
        limits(2), ...
        numberOfLevels).';
end

end


function stride = ...
    chooseCoprimeStride(numberOfObjects,preferredStride)

if numberOfObjects == 1
    stride = 1;
    return
end

stride = ...
    mod(preferredStride - 1,numberOfObjects) + 1;

while gcd(stride,numberOfObjects) ~= 1

    stride = stride + 1;

    if stride >= numberOfObjects
        stride = 1;
    end
end

end


function validateLimits( ...
    limits,name,minimumValue,maximumValue,strictUpper)

if limits(1) > limits(2)
    error( ...
        "elementDistributedRsos:ReversedLimits", ...
        "%s must be ordered [minimum maximum].",name);
end

if limits(1) < minimumValue
    error( ...
        "elementDistributedRsos:InvalidLowerLimit", ...
        "%s is below its allowable lower bound.",name);
end

if strictUpper
    invalidUpper = limits(2) >= maximumValue;
else
    invalidUpper = limits(2) > maximumValue;
end

if invalidUpper
    error( ...
        "elementDistributedRsos:InvalidUpperLimit", ...
        "%s exceeds its allowable upper bound.",name);
end

end


function state = keplerianToState( ...
    semiMajorAxis, ...
    eccentricity, ...
    inclination, ...
    raan, ...
    argumentOfPeriapsis, ...
    trueAnomaly, ...
    moonMu)

semilatusRectum = ...
    semiMajorAxis*(1 - eccentricity^2);

radius = semilatusRectum / ...
    (1 + eccentricity*cos(trueAnomaly));

positionPerifocal = radius*[
    cos(trueAnomaly)
    sin(trueAnomaly)
    0
];

velocityPerifocal = ...
    sqrt(moonMu/semilatusRectum)*[
        -sin(trueAnomaly)
         eccentricity + cos(trueAnomaly)
         0
    ];

rotationRaan = [
     cos(raan),-sin(raan),0
     sin(raan), cos(raan),0
     0,0,1
];

rotationInclination = [
    1,0,0
    0,cos(inclination),-sin(inclination)
    0,sin(inclination), cos(inclination)
];

rotationPeriapsis = [
     cos(argumentOfPeriapsis),-sin(argumentOfPeriapsis),0
     sin(argumentOfPeriapsis), cos(argumentOfPeriapsis),0
     0,0,1
];

perifocalToMci = ...
    rotationRaan * ...
    rotationInclination * ...
    rotationPeriapsis;

state = [
    perifocalToMci*positionPerifocal
    perifocalToMci*velocityPerifocal
];

end