%% testTerrainRayClearance
% Compares the precomputed terrain-horizon measurement gate against a
% direct, range-aware terrain clearance calculation.
%
% The precomputed database searches terrain out to maximumTerrainRange.
%
% The direct calculation searches only terrain that lies:
%
%   1. Along the spacecraft azimuth.
%   2. Within maximumTerrainRange.
%   3. Before the spacecraft's subpoint angular distance.
%
% The test reports:
%   - Exact agreement epochs.
%   - Conservative horizon-database rejections.
%   - False clearances, which should be zero.

clear;
close all;
clc;

%% Add source directory

testDirectory = fileparts(mfilename("fullpath"));
repositoryDirectory = fileparts(testDirectory);
sourceDirectory = fullfile(repositoryDirectory, "src");

addpath(sourceDirectory);

requiredFunctions = [
    "orbitDynamics.propagateLunarOrbit"
    "digitalElevationModel.buildMaximumTerrainHorizonDatabase"
    "optimization.buildTerrainAwareLosDatabase"
];

for functionIndex = 1:length(requiredFunctions)

    functionName = requiredFunctions(functionIndex);

    assert(~isempty(which(functionName)), ...
        "%s was not found.", functionName);
end

%% Lunar constants

moonRadius = 1737.4;                  % km
moonMu = 4902.800066;                 % km^3/s^2

moonSiderealPeriod = ...
    27.321661 * 86400;                % s

moonAngularRate = ...
    2*pi / moonSiderealPeriod;        % rad/s

theta0 = 0;                           % rad

%% Load DEM

demFile = fullfile( ...
    repositoryDirectory, ...
    "data", ...
    "new_lunar_interpolant_model.mat");

if ~isfile(demFile)

    demFile = fullfile( ...
        repositoryDirectory, ...
        "new_lunar_interpolant_model.mat");
end

assert(isfile(demFile), ...
    "new_lunar_interpolant_model.mat was not found.");

demData = load(demFile);

assert(isfield(demData, "F"), ...
    "The DEM MAT-file must contain the interpolant F.");

sourceInterpolant = demData.F;

%% Convert DEM coordinates to radians

latitudeGridDegrees = ...
    sourceInterpolant.GridVectors{1}(:);

longitudeGridDegrees = ...
    sourceInterpolant.GridVectors{2}(:);

elevationGrid = ...
    sourceInterpolant.Values;

latitudeGrid = ...
    deg2rad(latitudeGridDegrees);

longitudeGrid = ...
    deg2rad(longitudeGridDegrees);

% Add periodic longitude seam if necessary.

if longitudeGrid(end) - longitudeGrid(1) < ...
        2*pi - 1e-10

    longitudeGrid = [
        longitudeGrid
        longitudeGrid(1) + 2*pi
    ];

    elevationGrid = [
        elevationGrid, elevationGrid(:,1)
    ];
end

dem = griddedInterpolant( ...
    {latitudeGrid, longitudeGrid}, ...
    elevationGrid, ...
    "linear", ...
    "nearest");

%% Test sensor

% This is the terrain-obstructed sensor selected by the previous test.

sensorLatitude = ...
    deg2rad(-89.50533170674788);

sensorLongitude = ...
    deg2rad(102.85714285714286);

candidateLatitudes = sensorLatitude;
candidateLongitudes = sensorLongitude;

%% Build high-resolution terrain horizon

maximumTerrainRange = 100;            % km
terrainRangeStep = 0.1;               % km
horizonAzimuthStep = deg2rad(0.5);    % rad

[ ...
    horizonAzimuths, ...
    maximumTerrainElevation, ...
    maximumFeatureRange, ...
    sensorElevations, ...
    maximumFeatureElevations ...
] = digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
    candidateLatitudes, ...
    candidateLongitudes, ...
    dem, ...
    maximumTerrainRange, ...
    terrainRangeStep, ...
    horizonAzimuthStep, ...
    moonRadius);

sensorElevation = sensorElevations(1);

assert(all(isfinite(maximumTerrainElevation), "all"), ...
    "The terrain-horizon profile contains nonfinite values.");

assert(all(isfinite(maximumFeatureRange), "all"), ...
    "The maximum-feature ranges contain nonfinite values.");

assert(all(isfinite(maximumFeatureElevations), "all"), ...
    "The maximum-feature elevations contain nonfinite values.");

%% Construct LRO-like orbit

orbitAltitude = 50;                   % km
orbitRadius = moonRadius + orbitAltitude;

orbitInclination = deg2rad(90);
rightAscensionAscendingNode = deg2rad(37);

circularVelocity = ...
    sqrt(moonMu / orbitRadius);

initialPerifocalState = [
    orbitRadius
    0
    0
    0
    circularVelocity
    0
];

rotationZ = @(angle) [
     cos(angle), -sin(angle), 0
     sin(angle),  cos(angle), 0
              0,           0, 1
];

rotationX = @(angle) [
    1,          0,           0
    0, cos(angle), -sin(angle)
    0, sin(angle),  cos(angle)
];

perifocalToMoonInertial = ...
    rotationZ(rightAscensionAscendingNode) * ...
    rotationX(orbitInclination);

initialState = [
    perifocalToMoonInertial * initialPerifocalState(1:3)
    perifocalToMoonInertial * initialPerifocalState(4:6)
];

orbitPeriod = ...
    2*pi * sqrt(orbitRadius^3 / moonMu);

numberOfPeriods = 3;
outputStep = 20;                      % s

requestedTimes = ...
    (0:outputStep:numberOfPeriods*orbitPeriod).';

if requestedTimes(end) < numberOfPeriods*orbitPeriod

    requestedTimes(end + 1,1) = ...
        numberOfPeriods*orbitPeriod;
end

[times, propagatedStates] = ...
    orbitDynamics.propagateLunarOrbit( ...
        initialState, ...
        requestedTimes, ...
        moonMu = moonMu);

if size(propagatedStates,2) == 6

    truthStateHistory = propagatedStates.';
else

    truthStateHistory = propagatedStates;
end

numberOfTimes = numel(times);

assert( ...
    isequal(size(truthStateHistory), [6, numberOfTimes]), ...
    "Unexpected propagated state-history dimensions.");

rsoStateHistories = reshape( ...
    truthStateHistory, ...
    6, ...
    numberOfTimes, ...
    1);

%% Evaluate precomputed horizon gate

instrumentMinimumElevation = deg2rad(0);
horizonMargin = deg2rad(0.1);

[ ...
    databaseAvailability, ...
    targetAzimuths, ...
    targetElevations, ...
    targetRanges, ...
    databaseLimitingElevations ...
] = optimization.buildTerrainAwareLosDatabase( ...
    times, ...
    rsoStateHistories, ...
    candidateLatitudes, ...
    candidateLongitudes, ...
    dem, ...
    horizonAzimuths, ...
    maximumTerrainElevation, ...
    instrumentMinimumElevation, ...
    horizonMargin, ...
    moonRadius, ...
    theta0, ...
    moonAngularRate);

databaseAvailability = reshape( ...
    databaseAvailability(1,:,1), ...
    [], 1);

targetAzimuths = reshape( ...
    targetAzimuths(1,:,1), ...
    [], 1);

targetElevations = reshape( ...
    targetElevations(1,:,1), ...
    [], 1);

targetRanges = reshape( ...
    targetRanges(1,:,1), ...
    [], 1);

databaseLimitingElevations = reshape( ...
    databaseLimitingElevations(1,:,1), ...
    [], 1);

geometricAvailability = ...
    targetElevations >= instrumentMinimumElevation;

assert(any(geometricAvailability), ...
    "The sensor has no geometric visibility to the test orbit.");

%% Direct range-aware terrain clearance

terrainSearchRanges = ...
    (terrainRangeStep:terrainRangeStep:maximumTerrainRange).';

sensorRadius = ...
    moonRadius + sensorElevation;

directAvailability = false(numberOfTimes,1);

directLimitingElevations = nan(numberOfTimes,1);
directMaximumTerrainAngles = nan(numberOfTimes,1);
minimumRayClearances = nan(numberOfTimes,1);
targetSurfaceDistances = nan(numberOfTimes,1);

rawRayClearanceGate = false(numberOfTimes,1);
rawAngleClearanceGate = false(numberOfTimes,1);

for timeIndex = 1:numberOfTimes

    if ~geometricAvailability(timeIndex)

        directAvailability(timeIndex) = false;
        continue;
    end

    targetAzimuth = ...
        mod(targetAzimuths(timeIndex), 2*pi);

    targetElevation = ...
        targetElevations(timeIndex);

    targetSlantRange = ...
        targetRanges(timeIndex);

    % The target's central angular separation from the sensor follows from
    % its local horizontal and vertical components.

    targetHorizontalDistance = ...
        targetSlantRange * cos(targetElevation);

    targetRadialCoordinate = ...
        sensorRadius + ...
        targetSlantRange * sin(targetElevation);

    targetCentralAngle = atan2( ...
        targetHorizontalDistance, ...
        targetRadialCoordinate);

    targetSurfaceDistance = ...
        moonRadius * targetCentralAngle;

    targetSurfaceDistances(timeIndex) = ...
        targetSurfaceDistance;

    % Only terrain before the target and within the 100 km database radius
    % can physically obstruct the ray.

    directMaximumRange = min( ...
        maximumTerrainRange, ...
        targetSurfaceDistance);

    sampledRanges = terrainSearchRanges( ...
        terrainSearchRanges <= ...
        directMaximumRange + 1e-12);

    if isempty(sampledRanges)

        directMaximumTerrainAngle = -pi/2;
        minimumRayClearance = inf;
        rawRayIsClear = true;

    else

        centralAngles = ...
            sampledRanges / moonRadius;

        sinTerrainLatitudes = ...
            sin(sensorLatitude) .* cos(centralAngles) + ...
            cos(sensorLatitude) .* sin(centralAngles) .* ...
            cos(targetAzimuth);

        sinTerrainLatitudes = max( ...
            -1, ...
            min(1, sinTerrainLatitudes));

        terrainLatitudes = ...
            asin(sinTerrainLatitudes);

        terrainLongitudes = ...
            sensorLongitude + ...
            atan2( ...
                sin(targetAzimuth) .* ...
                    sin(centralAngles) .* ...
                    cos(sensorLatitude), ...
                cos(centralAngles) - ...
                    sin(sensorLatitude) .* ...
                    sinTerrainLatitudes);

        terrainLongitudesForDem = ...
            wrapLongitudeForDem( ...
                terrainLongitudes, ...
                dem.GridVectors{2});

        terrainElevations = dem( ...
            terrainLatitudes, ...
            terrainLongitudesForDem);

        terrainRadii = ...
            moonRadius + terrainElevations;

        %% Direct apparent terrain angles

        terrainHorizontalDistances = ...
            terrainRadii .* sin(centralAngles);

        terrainVerticalDistances = ...
            terrainRadii .* cos(centralAngles) - ...
            sensorRadius;

        terrainApparentAngles = atan2( ...
            terrainVerticalDistances, ...
            terrainHorizontalDistances);

        directMaximumTerrainAngle = ...
            max(terrainApparentAngles);

        %% Direct ray radii

        % The radial distance of the sensor-to-spacecraft ray at central
        % angle delta is:
        %
        %   rRay(delta) =
        %       rSensor*cos(elevation)/cos(elevation + delta)

        rayRadii = ...
            sensorRadius * cos(targetElevation) ./ ...
            cos(targetElevation + centralAngles);

        rayClearances = ...
            rayRadii - terrainRadii;

        minimumRayClearance = ...
            min(rayClearances);

        clearanceTolerance = 1e-10;  % km

        rawRayIsClear = ...
            minimumRayClearance >= -clearanceTolerance;
    end

    directMaximumTerrainAngles(timeIndex) = ...
        directMaximumTerrainAngle;

    minimumRayClearances(timeIndex) = ...
        minimumRayClearance;

    directLimitingElevation = max( ...
        instrumentMinimumElevation, ...
        directMaximumTerrainAngle + horizonMargin);

    directLimitingElevations(timeIndex) = ...
        directLimitingElevation;

    directAvailability(timeIndex) = ...
        targetElevation >= directLimitingElevation;

    rawRayClearanceGate(timeIndex) = ...
        rawRayIsClear;

    rawAngleClearanceGate(timeIndex) = ...
        targetElevation >= directMaximumTerrainAngle - 1e-12;
end

%% Verify ray and angular terrain geometry agree

rawComparisonEpochs = geometricAvailability;

assert( ...
    all( ...
        rawRayClearanceGate(rawComparisonEpochs) == ...
        rawAngleClearanceGate(rawComparisonEpochs)), ...
    ["The direct ray-radius test and direct apparent-angle test " ...
     "do not agree."]);

%% Compare database and direct range-aware results

exactAgreement = ...
    databaseAvailability == directAvailability;

% A false clearance is important: the precomputed database accepted a
% measurement that direct terrain sampling says is blocked.

falseClearances = ...
    databaseAvailability & ...
    ~directAvailability;

% A conservative rejection means the 100 km database rejected a
% measurement even though all terrain before the spacecraft was clear.

conservativeRejections = ...
    ~databaseAvailability & ...
    directAvailability & ...
    geometricAvailability;

numberOfGeometricEpochs = ...
    sum(geometricAvailability);

numberOfDatabaseMeasurements = ...
    sum(databaseAvailability);

numberOfDirectMeasurements = ...
    sum(directAvailability);

numberOfExactAgreements = ...
    sum(exactAgreement);

numberOfFalseClearances = ...
    sum(falseClearances);

numberOfConservativeRejections = ...
    sum(conservativeRejections);

%% Print results

fprintf("\nDirect terrain ray-clearance comparison\n");

fprintf( ...
    "  Sensor latitude:                 %.6f deg\n", ...
    rad2deg(sensorLatitude));

fprintf( ...
    "  Sensor longitude:                %.6f deg\n", ...
    rad2deg(sensorLongitude));

fprintf( ...
    "  Sensor elevation:                %.6f km\n", ...
    sensorElevation);

fprintf( ...
    "  Geometrically visible epochs:    %d\n", ...
    numberOfGeometricEpochs);

fprintf( ...
    "  Horizon-database measurements:   %d\n", ...
    numberOfDatabaseMeasurements);

fprintf( ...
    "  Direct range-aware measurements: %d\n", ...
    numberOfDirectMeasurements);

fprintf( ...
    "  Exact gate agreements:           %d of %d epochs\n", ...
    numberOfExactAgreements, ...
    numberOfTimes);

fprintf( ...
    "  Conservative rejections:         %d\n", ...
    numberOfConservativeRejections);

fprintf( ...
    "  False clearances:                %d\n", ...
    numberOfFalseClearances);

%% Important safety assertion

assert( ...
    numberOfFalseClearances == 0, ...
    ["The precomputed terrain database accepted at least one " ...
     "measurement that direct ray sampling found to be obstructed."]);

%% Plot target and limiting elevation profiles

timeHours = times / 3600;

figure( ...
    Name = "Terrain Horizon and Direct Ray Comparison", ...
    Color = "white");

plot( ...
    timeHours, ...
    rad2deg(targetElevations), ...
    Color = [0, 0.4470, 0.7410], ...
    LineWidth = 1.5);

hold on;

plot( ...
    timeHours, ...
    rad2deg(databaseLimitingElevations), ...
    Color = [0.8500, 0.3250, 0.0980], ...
    LineWidth = 1.5);

plot( ...
    timeHours, ...
    rad2deg(directLimitingElevations), ...
    "--", ...
    Color = [0.4940, 0.1840, 0.5560], ...
    LineWidth = 1.5);

scatter( ...
    timeHours(databaseAvailability), ...
    rad2deg(targetElevations(databaseAvailability)), ...
    18, ...
    [0.2, 0.65, 0.2], ...
    "filled");

scatter( ...
    timeHours(conservativeRejections), ...
    rad2deg(targetElevations(conservativeRejections)), ...
    35, ...
    [0.9290, 0.6940, 0.1250], ...
    "x", ...
    LineWidth = 1.5);

scatter( ...
    timeHours(falseClearances), ...
    rad2deg(targetElevations(falseClearances)), ...
    45, ...
    [0.85, 0.1, 0.1], ...
    "x", ...
    LineWidth = 2);

grid on;

xlabel("Time (hr)");
ylabel("Apparent elevation (deg)");

title( ...
    sprintf( ...
        "LRO-like %.0f km Orbit | Precomputed Horizon vs Direct Ray", ...
        orbitAltitude));

legend( ...
    "LRO-like target elevation", ...
    "100 km horizon-database limit", ...
    "Direct range-aware limit", ...
    "Database-accepted measurement", ...
    "Conservative database rejection", ...
    "False database clearance", ...
    Location = "best");

fprintf("\ntestTerrainRayClearance passed.\n");

%% Local function

function wrappedLongitudes = wrapLongitudeForDem( ...
    longitudes, ...
    demLongitudeGrid)
% Wrap longitude to match a 0-to-2*pi or -pi-to-pi DEM.

demLongitudeGrid = demLongitudeGrid(:);

if demLongitudeGrid(1) >= -1e-10 && ...
        demLongitudeGrid(end) > pi

    wrappedLongitudes = ...
        mod(longitudes, 2*pi);

else

    wrappedLongitudes = ...
        mod(longitudes + pi, 2*pi) - pi;
end
end