%% testSyntheticLunarDemCompatibility
% Validate the synthetic griddedInterpolant DEM against the optimization
% workflow without running a full production database build.
%
% The test verifies that the DEM can be loaded and used by:
%   1. Surface/topographic reference-frame transformations.
%   2. Terrain-horizon construction.
%   3. RA/Dec measurement and measurement-Jacobian models.
%   4. Tracking-data precomputation used by the information objective.
%   5. Fully filtered visibility with independent Earth/Sun exclusion angles.

clear;
close all;
clc;

%% ========================================================================
%  Project paths
%  ========================================================================

testDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testDirectory);
sourceDirectory = fullfile(projectRoot,"src");
dataDirectory = fullfile(projectRoot,"data");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

%% ========================================================================
%  Resolve and load synthetic DEM
%  ========================================================================

moonRadiusKm = 1737.4;
moonMuKm3S2 = 4902.800066;
moonAngularRate = 2*pi/(27.321661*86400);
theta0Rad = 0;

demPath = resolveSyntheticDemPath(dataDirectory);

[dem,demModel] = ...
    digitalElevationModel.loadTriaxialLunarDem( ...
        string(demPath),moonRadiusKm,24,48);

assert(isa(dem,"griddedInterpolant"), ...
    "Synthetic DEM loader did not return a griddedInterpolant.");
assert(numel(dem.GridVectors) == 2, ...
    "Synthetic DEM must be two-dimensional.");
assert(all(isfinite(dem.Values),"all"), ...
    "Synthetic DEM contains nonfinite elevations.");

latitudeGrid = dem.GridVectors{1}(:);
longitudeGrid = dem.GridVectors{2}(:);

assert(abs(latitudeGrid(1)+pi/2) < 1e-10 && ...
    abs(latitudeGrid(end)-pi/2) < 1e-10, ...
    "Synthetic DEM does not cover both lunar poles.");
assert(abs(longitudeGrid(1)) < 1e-10 && ...
    abs(longitudeGrid(end)-2*pi) < 1e-10, ...
    "Synthetic DEM does not contain an exact 0/360-degree seam.");
assert(all(diff(latitudeGrid) > 0), ...
    "Synthetic DEM latitude grid is not strictly increasing.");
assert(all(diff(longitudeGrid) > 0), ...
    "Synthetic DEM longitude grid is not strictly increasing.");

%% ========================================================================
%  Representative south-polar candidate locations
%  ========================================================================

candidateLatitudes = deg2rad([ ...
    -89.5
    -85.0
    -80.0
    -75.5]);

candidateLongitudes = deg2rad([ ...
     15
    105
    205
    305]);

sampleElevationsKm = dem(candidateLatitudes,candidateLongitudes);

assert(all(isfinite(sampleElevationsKm)), ...
    "Synthetic DEM returned nonfinite south-polar elevations.");

%% ========================================================================
%  Topographic-frame compatibility
%  ========================================================================

sensorLatitude = candidateLatitudes(1);
sensorLongitude = candidateLongitudes(1);

sensorRotatingState = ...
    referenceFrames.topographic( ...
        zeros(6,1), ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        moonRadiusKm, ...
        "toRotating");

expectedSensorRadiusKm = ...
    moonRadiusKm + dem(sensorLatitude,sensorLongitude);

assert(abs(norm(sensorRotatingState(1:3))-expectedSensorRadiusKm) < 1e-9, ...
    "Topographic surface position is inconsistent with the synthetic DEM.");

[localState,~] = ...
    referenceFrames.topographic( ...
        sensorRotatingState, ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        moonRadiusKm, ...
        "fromRotating");

assert(norm(localState) < 1e-9, ...
    "Topographic round-trip failed with the synthetic DEM.");

%% ========================================================================
%  Terrain-horizon compatibility
%  ========================================================================

[horizonAzimuths,maximumTerrainElevation] = ...
    digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        20, ...
        5, ...
        deg2rad(30), ...
        moonRadiusKm);

assert(all(isfinite(maximumTerrainElevation),"all"), ...
    "Terrain horizon contains nonfinite values with the synthetic DEM.");
assert(size(maximumTerrainElevation,1) == numel(candidateLatitudes), ...
    "Terrain-horizon sensor dimension is inconsistent.");

%% ========================================================================
%  Representative target trajectory
%  ========================================================================

initialRadiusKm = moonRadiusKm + 300;
initialState = [ ...
    initialRadiusKm
    0
    0
    0
    0
    sqrt(moonMuKm3S2/initialRadiusKm)];

trackingTimes = (600:600:3600).';

[~,propagatedStates] = ...
    orbitDynamics.propagateLunarOrbit( ...
        initialState, ...
        [0;trackingTimes], ...
        moonMu=moonMuKm3S2);

targetStateHistories = ...
    reshape( ...
        propagatedStates(2:end,:).', ...
        6,numel(trackingTimes),1);

%% ========================================================================
%  RA/Dec measurement and Jacobian compatibility
%  ========================================================================

measurement = ...
    measurements.surfaceRaDecMeasurement( ...
        targetStateHistories(:,1,1), ...
        trackingTimes(1), ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        moonRadiusKm, ...
        theta0Rad, ...
        moonAngularRate);

measurementJacobian = ...
    measurements.surfaceRaDecJacobian( ...
        targetStateHistories(:,1,1), ...
        trackingTimes(1), ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        moonRadiusKm, ...
        theta0Rad, ...
        moonAngularRate);

assert(all(isfinite(measurement)), ...
    "RA/Dec measurement is nonfinite with the synthetic DEM.");
assert(all(isfinite(measurementJacobian),"all"), ...
    "RA/Dec Jacobian is nonfinite with the synthetic DEM.");

%% ========================================================================
%  Optimization tracking-data precompute
%  ========================================================================

[referenceStateHistory,stateTransitionHistory,processNoiseHistory, ...
    measurementJacobianHistory] = ...
    optimization.precomputeTrackingData( ...
        0, ...
        trackingTimes, ...
        initialState, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        0, ...
        1e-15, ...
        moonMuKm3S2, ...
        moonRadiusKm, ...
        theta0Rad, ...
        moonAngularRate);

assert(all(isfinite(referenceStateHistory),"all"), ...
    "Tracking reference states are nonfinite.");
assert(all(isfinite(stateTransitionHistory),"all"), ...
    "Tracking STM history is nonfinite.");
assert(all(isfinite(processNoiseHistory),"all"), ...
    "Tracking process-noise history is nonfinite.");
assert(all(isfinite(measurementJacobianHistory),"all"), ...
    "Tracking measurement-Jacobian history is nonfinite.");

%% ========================================================================
%  Filtered visibility and independent exclusion angles
%  ========================================================================

numberOfTimes = numel(trackingTimes);

earthPositionsMci = repmat([384400;0;0],1,numberOfTimes);
sunPositionsMci = repmat([0;149597870.7;0],1,numberOfTimes);

sunMinimumAngularSeparationRad = deg2rad(20);
earthMinimumAngularSeparationRad = deg2rad(10);

[filteredAvailability,visibilityDiagnostics] = ...
    optimization.buildFilteredVisibilityDatabase( ...
        trackingTimes, ...
        targetStateHistories, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        horizonAzimuths, ...
        maximumTerrainElevation, ...
        earthPositionsMci, ...
        sunPositionsMci, ...
        0, ...
        0, ...
        6378.1366, ...
        695700, ...
        sunMinimumAngularSeparationRad, ...
        moonRadiusKm, ...
        theta0Rad, ...
        moonAngularRate, ...
        earthMinimumAngularSeparationRad);

assert( ...
    size(filteredAvailability,1) == numel(candidateLatitudes) && ...
    size(filteredAvailability,2) == numberOfTimes && ...
    size(filteredAvailability,3) == 1, ...
    "Filtered visibility dimensions are inconsistent.");
assert(abs( ...
    visibilityDiagnostics.configuredEarthMinimumAngularSeparation - ...
    earthMinimumAngularSeparationRad) < 1e-12, ...
    "Earth exclusion angle was not propagated correctly.");
assert(abs( ...
    visibilityDiagnostics.configuredSunMinimumAngularSeparation - ...
    sunMinimumAngularSeparationRad) < 1e-12, ...
    "Sun exclusion angle was not propagated correctly.");

%% ========================================================================
%  Summary
%  ========================================================================

fprintf("\n");
fprintf("Synthetic lunar DEM compatibility summary\n");
fprintf("-----------------------------------------\n");
fprintf("Source:              %s\n",demPath);
fprintf("Source variable:     %s\n",demModel.sourceVariable);
fprintf("Representation:      %s\n",demModel.workflowRepresentation);
fprintf("Grid size:           %d x %d\n",size(dem.Values,1),size(dem.Values,2));
fprintf("Elevation range:     [%.6f, %.6f] km\n", ...
    min(dem.Values,[],"all"),max(dem.Values,[],"all"));
fprintf("Earth exclusion:     %.1f deg\n", ...
    rad2deg(earthMinimumAngularSeparationRad));
fprintf("Sun exclusion:       %.1f deg\n", ...
    rad2deg(sunMinimumAngularSeparationRad));
fprintf("Topographic frame:   passed\n");
fprintf("Terrain horizon:     passed\n");
fprintf("RA/Dec model:        passed\n");
fprintf("Tracking precompute: passed\n");
fprintf("Visibility filter:   passed\n");
fprintf("\ntestSyntheticLunarDemCompatibility passed.\n");

%% ========================================================================
%  Local helper
%  ========================================================================

function demPath = resolveSyntheticDemPath(dataDirectory)

candidateNames = [ ...
    "Synthetic:LunarDEM.mat"
    "Synthetic_LunarDEM.mat"
    "SyntheticLunarDEM.mat"
    ];

for candidateIndex = 1:numel(candidateNames)
    candidatePath = fullfile(dataDirectory,candidateNames(candidateIndex));
    if isfile(candidatePath)
        demPath = candidatePath;
        return
    end
end

error( ...
    "testSyntheticLunarDemCompatibility:DemNotFound", ...
    [ ...
    "Synthetic lunar DEM was not found in %s. Expected one of:\n" + ...
    "  Synthetic:LunarDEM.mat\n" + ...
    "  Synthetic_LunarDEM.mat\n" + ...
    "  SyntheticLunarDEM.mat" ...
    ], ...
    dataDirectory);

end
