%% testMultiRsoTerrainAwareCandidateNetwork
% End-to-end terrain-aware network test for multiple independent RSOs.
%
% Workflow:
%   1. Propagate truth trajectories for every RSO.
%   2. Build one sensor/DEM terrain-horizon database.
%   3. Perform one representative, terrain-gated IOD for each RSO.
%   4. Propagate every IOD state and P0 to a common reference epoch.
%   5. Hold those RSO-specific priors fixed during network evaluation.
%   6. Build candidate-dependent Jacobian and terrain-LOS databases.
%   7. Evaluate coverage and EKF D-optimality for candidate networks.
%   8. Run one final state-updating EKF per RSO with the selected network.

clear;
close all;
clc;

rng(11,"twister");

%% Project paths and required functions

testDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testDirectory);
sourceDirectory = fullfile(projectRoot,"src");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

requiredFunctions = [
    "orbitDynamics.propagateLunarOrbit"
    "orbitDynamics.lunarStateAndStmDynamics"
    "referenceFrames.moonRotating"
    "referenceFrames.topographic"
    "measurements.surfaceRaDecMeasurement"
    "measurements.surfaceRaDecJacobian"
    "iod.anglesOnlyIod"
    "estimation.isotropicProcessNoise"
    "estimation.propagateNetworkCovariance"
    "estimation.lunarSurfaceEkf"
    "optimization.precomputeTrackingData"
    "optimization.buildTerrainAwareLosDatabase"
    "optimization.informationObjective"
    "optimization.coverageObjective"
    "digitalElevationModel.buildMaximumTerrainHorizonDatabase"
    "lsqnonlin"
];

for functionIndex = 1:length(requiredFunctions)
    functionName = requiredFunctions(functionIndex);

    assert(~isempty(which(functionName)), ...
        "%s was not found.",functionName);
end

%% Load the DEM and convert its angular grid to radians

demPath = fullfile( ...
    projectRoot,"data","new_lunar_interpolant_model.mat");

if ~isfile(demPath)
    demPath = fullfile( ...
        testDirectory,"new_lunar_interpolant_model.mat");
end

assert(isfile(demPath),"DEM file was not found.");

demData = load(demPath,"F");

assert(isfield(demData,"F"), ...
    "DEM file must contain a variable named F.");

sourceDem = demData.F;

latitudeGrid = deg2rad(sourceDem.GridVectors{1}(:));
longitudeGrid = deg2rad(sourceDem.GridVectors{2}(:));
elevationGrid = sourceDem.Values;

if longitudeGrid(end) < 2*pi
    longitudeGrid = [longitudeGrid;2*pi];
    elevationGrid = [elevationGrid,elevationGrid(:,1)];
end

dem = griddedInterpolant( ...
    {latitudeGrid,longitudeGrid}, ...
    elevationGrid,"linear","nearest");

%% Constants and estimation settings

moonRadius = 1737.4;                 % km
moonMu = 4902.800066;                % km^3/s^2
moonAngularRate = 2*pi/(27.321661*86400);
theta0 = 0;

minimumElevation = deg2rad(0);
horizonMargin = deg2rad(0);

rightAscensionSigma = deg2rad(1/3600);
declinationSigma = deg2rad(1/3600);

measurementCovariance = diag([ ...
    rightAscensionSigma^2
    declinationSigma^2
]);

measurementNoiseFactor = ...
    chol(measurementCovariance,"lower");

accelerationNoiseIntensity = 1e-15; % km^2/s^3

stateScales = [1;1;1;1e-3;1e-3;1e-3];

%% Candidate surface sensors
% A small, deliberately varied set is used so this remains a test rather
% than a production-scale optimization.

candidateNames = [
    "Candidate 1"
    "Candidate 2"
    "Candidate 3"
    "Candidate 4"
];

candidateLatitudes = deg2rad([ ...
    -84.000000
    -89.505332
    -76.149000
    -76.000000
]);

candidateLongitudes = deg2rad([ ...
     37.000000
    102.857143
    115.200000
    300.000000
]);

numberOfCandidates = length(candidateLatitudes);

measurementCovariances = repmat( ...
    measurementCovariance,1,1,numberOfCandidates);

%% Build the terrain database once for the candidate sensors

maximumTerrainRange = 100;           % km
terrainRangeStep = 0.5;              % km
horizonAzimuthStep = deg2rad(1);     % rad

[horizonAzimuths, ...
    maximumTerrainElevation, ...
    maximumFeatureRange, ...
    sensorElevations, ...
    maximumFeatureElevations] = ...
    digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        maximumTerrainRange, ...
        terrainRangeStep, ...
        horizonAzimuthStep, ...
        moonRadius);

assert(all(isfinite(maximumTerrainElevation),"all"), ...
    "The terrain-horizon database contains nonfinite angles.");

%% Define the RSO set

rsoNames = [
    "LRO-like 50 km polar"
    "Chandrayaan-1-like 100 km polar"
    "200 km, 60 deg inclined"
];

numberOfObjects = length(rsoNames);

truthInitialStates = zeros(6,numberOfObjects);

truthInitialStates(:,1) = circularOrbitState( ...
    moonRadius + 50,deg2rad(90),deg2rad(37),0,moonMu);

truthInitialStates(:,2) = circularOrbitState( ...
    moonRadius + 100,deg2rad(90),deg2rad(120),deg2rad(35),moonMu);

% This orientation places a low southern pass near the south-polar
% candidate longitudes early in the test arc.
truthInitialStates(:,3) = circularOrbitState( ...
    moonRadius + 200,deg2rad(60),deg2rad(205.2),deg2rad(-90),moonMu);

objectWeights = ones(numberOfObjects,1);

%% Propagate all truth trajectories on the same time grid

outputStep = 30;                     % s
finalTime = 8*3600;                  % s
times = (0:outputStep:finalTime).';

numberOfTimes = length(times);
truthStateHistories = zeros(6,numberOfTimes,numberOfObjects);

for objectIndex = 1:numberOfObjects
    [propagatedTimes,propagatedStates] = ...
        orbitDynamics.propagateLunarOrbit( ...
            truthInitialStates(:,objectIndex), ...
            times, ...
            moonMu=moonMu);

    assert(max(abs(propagatedTimes - times)) < 1e-9, ...
        "The propagated time grid changed for object %d.",objectIndex);

    truthStateHistories(:,:,objectIndex) = propagatedStates.';
end

%% Terrain-aware truth visibility for all sensors and RSOs

[truthTerrainAvailability, ...
    truthAzimuths, ...
    truthElevations, ...
    truthRanges, ...
    truthLimitingElevations] = ...
    optimization.buildTerrainAwareLosDatabase( ...
        times, ...
        truthStateHistories, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        horizonAzimuths, ...
        maximumTerrainElevation, ...
        minimumElevation, ...
        horizonMargin, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate);

truthGeometricAvailability = ...
    truthElevations >= minimumElevation;

assert(all( ...
    truthTerrainAvailability <= truthGeometricAvailability, ...
    "all"), ...
    "Terrain-aware LOS cannot exceed geometric LOS.");

assert(all(any(truthTerrainAvailability,[1,2]),"all"), ...
    "At least one RSO has no terrain-approved observations.");

%% One representative terrain-gated IOD for each RSO
% Each object receives its own fixed state and covariance. The IOD sensor
% may differ by object because IOD geometry is object/sensor dependent.

desiredIodObservationCount = 15;
numberOfMonteCarloSamples = 50;
iodSearchEndTime = 0.40*finalTime;

iodStates = zeros(6,numberOfObjects);
iodCovariances = zeros(6,6,numberOfObjects);
iodReferenceTimes = zeros(numberOfObjects,1);
iodSensorIndices = zeros(numberOfObjects,1);
iodObservationCounts = zeros(numberOfObjects,1);
iodDiagnostics = cell(numberOfObjects,1);

for objectIndex = 1:numberOfObjects
    objectAvailability = reshape( ...
        truthTerrainAvailability(:,:,objectIndex), ...
        numberOfCandidates,numberOfTimes);

    [iodSensorIndices(objectIndex),acquisitionIndices] = ...
        selectRepresentativeIodPass( ...
            objectAvailability, ...
            times, ...
            iodSearchEndTime, ...
            desiredIodObservationCount);

    iodObservationCounts(objectIndex) = length(acquisitionIndices);

    sensorIndex = iodSensorIndices(objectIndex);

    [observerPositionsMci,rightAscension,declination] = ...
        simulateSingleSensorMeasurements( ...
            times, ...
            truthStateHistories(:,:,objectIndex), ...
            sensorIndex, ...
            candidateLatitudes, ...
            candidateLongitudes, ...
            dem, ...
            objectAvailability(sensorIndex,:).', ...
            measurementNoiseFactor, ...
            moonRadius, ...
            theta0, ...
            moonAngularRate);

    [iodState,iodCovariance,iodReferenceTime,objectIodDiagnostics] = ...
        iod.anglesOnlyIod( ...
            times, ...
            rightAscension, ...
            declination, ...
            observerPositionsMci, ...
            acquisitionIndices, ...
            measurementCovariance, ...
            numberOfMonteCarloSamples, ...
            100 + objectIndex, ...
            moonMu);

    iodStates(:,objectIndex) = iodState;
    iodCovariances(:,:,objectIndex) = iodCovariance;
    iodReferenceTimes(objectIndex) = iodReferenceTime;
    iodDiagnostics{objectIndex} = objectIodDiagnostics;

    iodCovariances(:,:,objectIndex) = 0.5*( ...
        iodCovariances(:,:,objectIndex) + ...
        iodCovariances(:,:,objectIndex).');

    [~,positiveDefiniteFlag] = chol( ...
        iodCovariances(:,:,objectIndex),"lower");

    assert(positiveDefiniteFlag == 0, ...
        "IOD covariance is not positive definite for object %d.", ...
        objectIndex);
end

%% Move all fixed IOD priors to one common optimization epoch
% The latest IOD reference epoch is used. Earlier priors are propagated to
% that epoch once, before any candidate network is evaluated.

commonReferenceTime = max(iodReferenceTimes);

fixedInitialStates = zeros(6,numberOfObjects);
fixedInitialCovariances = zeros(6,6,numberOfObjects);

for objectIndex = 1:numberOfObjects
    [commonEpochState,commonEpochCovariance] = ...
        propagatePriorToTime( ...
            iodReferenceTimes(objectIndex), ...
            commonReferenceTime, ...
            iodStates(:,objectIndex), ...
            iodCovariances(:,:,objectIndex), ...
            accelerationNoiseIntensity, ...
            moonMu);

    fixedInitialStates(:,objectIndex) = commonEpochState;
    fixedInitialCovariances(:,:,objectIndex) = ...
        commonEpochCovariance;
end

optimizationIndices = find(times > commonReferenceTime);
optimizationTimes = times(optimizationIndices);
numberOfOptimizationTimes = length(optimizationTimes);

assert(numberOfOptimizationTimes > 0, ...
    "No optimization arc remains after the IOD stage.");

truthOptimizationHistories = ...
    truthStateHistories(:,optimizationIndices,:);

%% Precompute candidate-dependent tracking data for every RSO

referenceStateHistories = ...
    zeros(6,numberOfOptimizationTimes,numberOfObjects);

stateTransitionHistories = ...
    zeros(6,6,numberOfOptimizationTimes,numberOfObjects);

processNoiseHistories = ...
    zeros(6,6,numberOfOptimizationTimes,numberOfObjects);

measurementJacobianHistories = ...
    zeros(2,6,numberOfCandidates, ...
    numberOfOptimizationTimes,numberOfObjects);

geometricAvailabilityDatabase = ...
    false(numberOfCandidates, ...
    numberOfOptimizationTimes,numberOfObjects);

for objectIndex = 1:numberOfObjects
    [objectReferenceStates, ...
        objectStateTransitions, ...
        objectProcessNoise, ...
        objectMeasurementJacobians, ...
        objectGeometricAvailability] = ...
        optimization.precomputeTrackingData( ...
            commonReferenceTime, ...
            optimizationTimes, ...
            fixedInitialStates(:,objectIndex), ...
            candidateLatitudes, ...
            candidateLongitudes, ...
            dem, ...
            minimumElevation, ...
            accelerationNoiseIntensity, ...
            moonMu, ...
            moonRadius, ...
            theta0, ...
            moonAngularRate);

    referenceStateHistories(:,:,objectIndex) = ...
        objectReferenceStates;

    stateTransitionHistories(:,:,:,objectIndex) = ...
        objectStateTransitions;

    processNoiseHistories(:,:,:,objectIndex) = ...
        objectProcessNoise;

    measurementJacobianHistories(:,:,:,:,objectIndex) = ...
        objectMeasurementJacobians;

    geometricAvailabilityDatabase(:,:,objectIndex) = ...
        objectGeometricAvailability;
end

%% Apply the reusable terrain horizon to each nominal RSO trajectory

[terrainAvailabilityDatabase, ...
    nominalAzimuths, ...
    nominalElevations, ...
    nominalRanges, ...
    nominalLimitingElevations] = ...
    optimization.buildTerrainAwareLosDatabase( ...
        optimizationTimes, ...
        referenceStateHistories, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        horizonAzimuths, ...
        maximumTerrainElevation, ...
        minimumElevation, ...
        horizonMargin, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate);

assert(all( ...
    terrainAvailabilityDatabase <= geometricAvailabilityDatabase, ...
    "all"), ...
    "Terrain-aware availability exceeds geometric availability.");

%% Build the candidate networks: none, singles, and every two-sensor pair

sensorPairs = nchoosek(1:numberOfCandidates,2);

numberOfNetworks = ...
    1 + numberOfCandidates + size(sensorPairs,1);

networkSelections = false(numberOfCandidates,numberOfNetworks);
networkNames = strings(numberOfNetworks,1);

networkNames(1) = "No sensors";
networkIndex = 1;

for sensorIndex = 1:numberOfCandidates
    networkIndex = networkIndex + 1;
    networkSelections(sensorIndex,networkIndex) = true;
    networkNames(networkIndex) = candidateNames(sensorIndex);
end

pairNetworkIndices = zeros(size(sensorPairs,1),1);

for pairIndex = 1:size(sensorPairs,1)
    networkIndex = networkIndex + 1;
    pairNetworkIndices(pairIndex) = networkIndex;

    sensorOne = sensorPairs(pairIndex,1);
    sensorTwo = sensorPairs(pairIndex,2);

    networkSelections([sensorOne,sensorTwo],networkIndex) = true;

    networkNames(networkIndex) = sprintf( ...
        "Candidates %d + %d",sensorOne,sensorTwo);
end


%% Evaluate terrain-aware coverage and information objectives

informationScores = zeros(numberOfNetworks,1);
coverageScores = zeros(numberOfNetworks,1);

informationByObject = zeros(numberOfNetworks,numberOfObjects);
coverageByObject = zeros(numberOfNetworks,numberOfObjects);

for networkIndex = 1:numberOfNetworks
    selectedSensors = networkSelections(:,networkIndex);

    [informationObjective,objectInformation] = ...
        optimization.informationObjective( ...
            selectedSensors, ...
            fixedInitialCovariances, ...
            stateTransitionHistories, ...
            processNoiseHistories, ...
            measurementJacobianHistories, ...
            terrainAvailabilityDatabase, ...
            measurementCovariances, ...
            stateScales, ...
            objectWeights);

    [coverageObjective,objectCoverage] = ...
        optimization.coverageObjective( ...
            selectedSensors, ...
            terrainAvailabilityDatabase, ...
            objectWeights);

    informationScores(networkIndex) = -informationObjective;
    coverageScores(networkIndex) = -coverageObjective;
    informationByObject(networkIndex,:) = objectInformation.';
    coverageByObject(networkIndex,:) = objectCoverage.';
end

assert(coverageScores(1) == 0, ...
    "The no-sensor coverage score must be zero.");

assert(all(coverageByObject(1,:) == 0), ...
    "The no-sensor network covered an RSO.");

%% Select the best pair for each separate objective

minimumFinalUpdatesPerObject = 3;

feasiblePairMask = all( ...
    coverageByObject(pairNetworkIndices,:) >= ...
    minimumFinalUpdatesPerObject, ...
    2);

assert(any(feasiblePairMask), ...
    "No two-sensor network observes every RSO at least %d times.", ...
    minimumFinalUpdatesPerObject);

feasiblePairNetworkIndices = ...
    pairNetworkIndices(feasiblePairMask);

[~,informationPairLocation] = max( ...
    informationScores(feasiblePairNetworkIndices));

bestInformationNetworkIndex = ...
    feasiblePairNetworkIndices(informationPairLocation);

[~,coveragePairLocation] = max( ...
    coverageScores(feasiblePairNetworkIndices));

bestCoverageNetworkIndex = ...
    feasiblePairNetworkIndices(coveragePairLocation);

% Run the final EKFs for the information-optimal network. Change this one
% line to bestCoverageNetworkIndex to test the coverage-optimal network.
finalNetworkIndex = bestInformationNetworkIndex;
finalSensorSelection = networkSelections(:,finalNetworkIndex);
finalSensorIndices = find(finalSensorSelection);

%% Build truth measurements and run one final EKF per RSO

[truthOptimizationAvailability,~,~,~,~] = ...
    optimization.buildTerrainAwareLosDatabase( ...
        optimizationTimes, ...
        truthOptimizationHistories, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        horizonAzimuths, ...
        maximumTerrainElevation, ...
        minimumElevation, ...
        horizonMargin, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate);

positionErrorNorms = zeros(numberOfObjects,numberOfOptimizationTimes);
velocityErrorNorms = zeros(numberOfObjects,numberOfOptimizationTimes);
positionThreeSigmaNorms = zeros(numberOfObjects,numberOfOptimizationTimes);
velocityThreeSigmaNorms = zeros(numberOfObjects,numberOfOptimizationTimes);

finalStateHistories = cell(numberOfObjects,1);
finalCovarianceHistories = cell(numberOfObjects,1);
finalInnovationHistories = cell(numberOfObjects,1);

for objectIndex = 1:numberOfObjects
    objectTruthHistory = reshape( ...
        truthOptimizationHistories(:,:,objectIndex), ...
        6,numberOfOptimizationTimes);

    objectTruthAvailability = reshape( ...
        truthOptimizationAvailability(:,:,objectIndex), ...
        numberOfCandidates,numberOfOptimizationTimes);

    [observationTimes, ...
        rightAscension, ...
        declination, ...
        sensorLatitudes, ...
        sensorLongitudes, ...
        measurementAvailable] = ...
        simulateSelectedNetwork( ...
            optimizationTimes, ...
            objectTruthHistory, ...
            finalSensorIndices, ...
            candidateLatitudes, ...
            candidateLongitudes, ...
            dem, ...
            objectTruthAvailability, ...
            measurementNoiseFactor, ...
            moonRadius, ...
            theta0, ...
            moonAngularRate);

    [objectFinalStates, ...
        objectFinalCovariances, ...
        objectFinalInnovations] = ...
        estimation.lunarSurfaceEkf( ...
            commonReferenceTime, ...
            observationTimes, ...
            rightAscension, ...
            declination, ...
            sensorLatitudes, ...
            sensorLongitudes, ...
            dem, ...
            measurementAvailable, ...
            fixedInitialStates(:,objectIndex), ...
            fixedInitialCovariances(:,:,objectIndex), ...
            measurementCovariance, ...
            accelerationNoiseIntensity, ...
            moonMu, ...
            moonRadius, ...
            theta0, ...
            moonAngularRate);

    finalStateHistories{objectIndex} = objectFinalStates;
    finalCovarianceHistories{objectIndex} = ...
        objectFinalCovariances;
    finalInnovationHistories{objectIndex} = ...
        objectFinalInnovations;

    assert(any(all(isfinite( ...
        finalInnovationHistories{objectIndex}),1)), ...
        "The final EKF performed no updates for object %d.",objectIndex);

    numberOfSelectedSensors = length(finalSensorIndices);

    posteriorIndices = ...
        numberOfSelectedSensors : ...
        numberOfSelectedSensors : ...
        length(observationTimes);

    posteriorStates = ...
        finalStateHistories{objectIndex}(:,posteriorIndices);

    posteriorCovariances = ...
        finalCovarianceHistories{objectIndex}(:,:,posteriorIndices);

    stateError = posteriorStates - objectTruthHistory;

    positionErrorNorms(objectIndex,:) = ...
        vecnorm(stateError(1:3,:),2,1);

    velocityErrorNorms(objectIndex,:) = ...
        vecnorm(stateError(4:6,:),2,1);

    for timeIndex = 1:numberOfOptimizationTimes
        covariance = posteriorCovariances(:,:,timeIndex);
        covariance = 0.5*(covariance + covariance.');

        positionThreeSigmaNorms(objectIndex,timeIndex) = ...
            3*sqrt(trace(covariance(1:3,1:3)));

        velocityThreeSigmaNorms(objectIndex,timeIndex) = ...
            3*sqrt(trace(covariance(4:6,4:6)));
    end
end

%% Print results

resultsTable = table( ...
    networkNames(:), ...
    informationScores(:), ...
    coverageScores(:), ...
    'VariableNames', ...
    {'Network','WeightedMeanDOptimality','WeightedMeanCoverage'});

disp(resultsTable);

fprintf("\nRepresentative IOD results\n");

for objectIndex = 1:numberOfObjects
    fprintf("\n%s\n",char(rsoNames(objectIndex)));
    fprintf("  IOD sensor:              %s\n", ...
        char(candidateNames(iodSensorIndices(objectIndex))));
    fprintf("  IOD observations:        %d\n", ...
        iodObservationCounts(objectIndex));
    fprintf("  IOD reference time:      %.3f hr\n", ...
        iodReferenceTimes(objectIndex)/3600);
    fprintf("  Monte Carlo convergence: %d of %d\n", ...
        iodDiagnostics{objectIndex}.numberOfSuccessfulSamples, ...
        iodDiagnostics{objectIndex}.numberOfRequestedSamples);
end

fprintf("\nCommon fixed-prior epoch: %.3f hr\n", ...
    commonReferenceTime/3600);

fprintf("Best information pair: %s\n", ...
    char(networkNames(bestInformationNetworkIndex)));

fprintf("Best coverage pair:    %s\n", ...
    char(networkNames(bestCoverageNetworkIndex)));

fprintf("Final EKF network:     %s\n", ...
    char(networkNames(finalNetworkIndex)));

fprintf("\nFinal-network object results\n");

for objectIndex = 1:numberOfObjects
    fprintf("\n%s\n",char(rsoNames(objectIndex)));
    fprintf("  Covered epochs:       %.0f\n", ...
        coverageByObject(finalNetworkIndex,objectIndex));
    fprintf("  Mean D-optimality:    %.6f\n", ...
        informationByObject(finalNetworkIndex,objectIndex));
    fprintf("  Final position error: %.6f km\n", ...
        positionErrorNorms(objectIndex,end));
    fprintf("  Final velocity error: %.6e km/s\n", ...
        velocityErrorNorms(objectIndex,end));
end

fprintf("\ntestMultiRsoTerrainAwareCandidateNetwork passed.\n");

%% Plot network objectives

networkCategories = categorical(networkNames,networkNames);

figure( ...
    "Color","white", ...
    "Name","Multi-RSO Terrain-Aware Network Objectives");

objectiveLayout = tiledlayout( ...
    2,1,"TileSpacing","compact","Padding","compact");

nexttile(objectiveLayout,1);
bar(networkCategories,informationScores);
grid on;
ylabel("Weighted mean D-optimality");
title("Information Objective");
xtickangle(30);

nexttile(objectiveLayout,2);
bar(networkCategories,coverageScores);
grid on;
ylabel("Weighted mean covered epochs");
title("Coverage Objective");
xtickangle(30);

title(objectiveLayout, ...
    "Terrain-Aware Multiple-RSO Candidate Networks");

%% Plot final EKF errors for every RSO

optimizationTimeHours = optimizationTimes/3600;

figure( ...
    "Color","white", ...
    "Name","Multi-RSO Final EKF Results");

ekfLayout = tiledlayout( ...
    numberOfObjects,2, ...
    "TileSpacing","compact", ...
    "Padding","compact");

for objectIndex = 1:numberOfObjects
    nexttile(ekfLayout,2*objectIndex - 1);

    errorHandle = plot( ...
        optimizationTimeHours, ...
        positionErrorNorms(objectIndex,:), ...
        "b","LineWidth",1.2);

    hold on;

    sigmaHandle = plot( ...
        optimizationTimeHours, ...
        positionThreeSigmaNorms(objectIndex,:), ...
        "k--","LineWidth",1.1);

    grid on;
    ylabel("Position error (km)");
    title(char(rsoNames(objectIndex)));

    if objectIndex == 1
        legend([errorHandle,sigmaHandle], ...
            "Estimation error", ...
            "3\sigma covariance norm", ...
            "Location","best");
    end

    nexttile(ekfLayout,2*objectIndex);

    plot( ...
        optimizationTimeHours, ...
        velocityErrorNorms(objectIndex,:), ...
        "b","LineWidth",1.2);

    hold on;

    plot( ...
        optimizationTimeHours, ...
        velocityThreeSigmaNorms(objectIndex,:), ...
        "k--","LineWidth",1.1);

    grid on;
    ylabel("Velocity error (km/s)");
    title(char(rsoNames(objectIndex)));
end

xlabel(ekfLayout,"Time (hr)");

title(ekfLayout,sprintf( ...
    "Final Independent EKFs | %s", ...
    char(networkNames(finalNetworkIndex))));

%% Local functions

function state = circularOrbitState( ...
    orbitRadius,inclination,raan,trueAnomaly,moonMu)

rotationZ = [ ...
     cos(raan),-sin(raan),0
     sin(raan), cos(raan),0
     0,0,1
];

rotationX = [ ...
    1,0,0
    0,cos(inclination),-sin(inclination)
    0,sin(inclination), cos(inclination)
];

perifocalPosition = orbitRadius*[ ...
    cos(trueAnomaly)
    sin(trueAnomaly)
    0
];

circularSpeed = sqrt(moonMu/orbitRadius);

perifocalVelocity = circularSpeed*[ ...
    -sin(trueAnomaly)
     cos(trueAnomaly)
     0
];

rotation = rotationZ*rotationX;

state = [ ...
    rotation*perifocalPosition
    rotation*perifocalVelocity
];

end

function [sensorIndex,acquisitionIndices] = ...
    selectRepresentativeIodPass( ...
        availability,times,searchEndTime,desiredCount)

numberOfSensors = size(availability,1);
bestRun = zeros(0,1);
sensorIndex = NaN;

for candidateIndex = 1:numberOfSensors
    eligible = availability(candidateIndex,:) & ...
        (times.' <= searchEndTime);

    changes = diff([false,eligible,false]);
    runStarts = find(changes == 1);
    runEnds = find(changes == -1) - 1;

    for runIndex = 1:length(runStarts)
        currentRun = (runStarts(runIndex):runEnds(runIndex)).';

        if length(currentRun) > length(bestRun)
            bestRun = currentRun;
            sensorIndex = candidateIndex;
        end
    end
end

assert(length(bestRun) >= 3, ...
    "No candidate has three terrain-approved IOD observations.");

numberToUse = min(desiredCount,length(bestRun));

selectionLocations = unique(round(linspace( ...
    1,length(bestRun),numberToUse)));

acquisitionIndices = bestRun(selectionLocations);
acquisitionIndices = acquisitionIndices(:);

end

function [observerPositionsMci,rightAscension,declination] = ...
    simulateSingleSensorMeasurements( ...
        times,truthStateHistory,sensorIndex, ...
        candidateLatitudes,candidateLongitudes,dem, ...
        measurementAvailable,measurementNoiseFactor, ...
        moonRadius,theta0,angularRate)

numberOfTimes = length(times);
sensorLatitude = candidateLatitudes(sensorIndex);
sensorLongitude = mod(candidateLongitudes(sensorIndex),2*pi);

observerPositionsMci = zeros(numberOfTimes,3);
rightAscension = NaN(numberOfTimes,1);
declination = NaN(numberOfTimes,1);

sensorMoonRotatingState = referenceFrames.topographic( ...
    zeros(6,1), ...
    sensorLatitude, ...
    sensorLongitude, ...
    dem, ...
    moonRadius, ...
    "toRotating");

for timeIndex = 1:numberOfTimes
    observationTime = times(timeIndex);

    sensorMciState = referenceFrames.moonRotating( ...
        sensorMoonRotatingState, ...
        observationTime, ...
        theta0, ...
        angularRate, ...
        "toInertial");

    observerPositionsMci(timeIndex,:) = sensorMciState(1:3).';

    if ~measurementAvailable(timeIndex)
        continue
    end

    idealMeasurement = measurements.surfaceRaDecMeasurement( ...
        truthStateHistory(:,timeIndex), ...
        observationTime, ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        moonRadius, ...
        theta0, ...
        angularRate);

    noisyMeasurement = idealMeasurement + ...
        measurementNoiseFactor*randn(2,1);

    rightAscension(timeIndex) = wrapAngle(noisyMeasurement(1));
    declination(timeIndex) = noisyMeasurement(2);
end

end

function [propagatedState,propagatedCovariance] = ...
    propagatePriorToTime( ...
        initialTime,finalTime,initialState,initialCovariance, ...
        accelerationNoiseIntensity,moonMu)

if abs(finalTime - initialTime) < 1e-12
    propagatedState = initialState;
    propagatedCovariance = initialCovariance;
    return
end

augmentedInitialState = [initialState;reshape(eye(6),36,1)];

odeOptions = odeset("RelTol",1e-11,"AbsTol",1e-12);

[~,augmentedHistory] = ode45( ...
    @(time,augmentedState) ...
        orbitDynamics.lunarStateAndStmDynamics( ...
            time,augmentedState,moonMu), ...
    [initialTime,finalTime], ...
    augmentedInitialState, ...
    odeOptions);

augmentedFinalState = augmentedHistory(end,:).';
propagatedState = augmentedFinalState(1:6);
stateTransitionMatrix = reshape(augmentedFinalState(7:end),6,6);

processNoise = estimation.isotropicProcessNoise( ...
    finalTime - initialTime, ...
    accelerationNoiseIntensity);

propagatedCovariance = ...
    stateTransitionMatrix*initialCovariance* ...
    stateTransitionMatrix.' + processNoise;

propagatedCovariance = 0.5*( ...
    propagatedCovariance + propagatedCovariance.');

end

function [observationTimes,rightAscension,declination, ...
    sensorLatitudes,sensorLongitudes,measurementAvailable] = ...
    simulateSelectedNetwork( ...
        times,truthStateHistory,selectedSensorIndices, ...
        candidateLatitudes,candidateLongitudes,dem, ...
        terrainAvailability,measurementNoiseFactor, ...
        moonRadius,theta0,angularRate)

numberOfTimes = length(times);
numberOfSelectedSensors = length(selectedSensorIndices);
numberOfObservations = numberOfTimes*numberOfSelectedSensors;

observationTimes = zeros(numberOfObservations,1);
rightAscension = NaN(numberOfObservations,1);
declination = NaN(numberOfObservations,1);
sensorLatitudes = zeros(numberOfObservations,1);
sensorLongitudes = zeros(numberOfObservations,1);
measurementAvailable = false(numberOfObservations,1);

observationIndex = 0;

for timeIndex = 1:numberOfTimes
    for selectedIndex = 1:numberOfSelectedSensors
        observationIndex = observationIndex + 1;
        sensorIndex = selectedSensorIndices(selectedIndex);

        sensorLatitude = candidateLatitudes(sensorIndex);
        sensorLongitude = mod(candidateLongitudes(sensorIndex),2*pi);

        observationTimes(observationIndex) = times(timeIndex);
        sensorLatitudes(observationIndex) = sensorLatitude;
        sensorLongitudes(observationIndex) = sensorLongitude;

        measurementAvailable(observationIndex) = ...
            terrainAvailability(sensorIndex,timeIndex);

        if ~measurementAvailable(observationIndex)
            continue
        end

        idealMeasurement = measurements.surfaceRaDecMeasurement( ...
            truthStateHistory(:,timeIndex), ...
            times(timeIndex), ...
            sensorLatitude, ...
            sensorLongitude, ...
            dem, ...
            moonRadius, ...
            theta0, ...
            angularRate);

        noisyMeasurement = idealMeasurement + ...
            measurementNoiseFactor*randn(2,1);

        rightAscension(observationIndex) = ...
            wrapAngle(noisyMeasurement(1));

        declination(observationIndex) = noisyMeasurement(2);
    end
end

end

function wrappedAngle = wrapAngle(angle)

wrappedAngle = atan2(sin(angle),cos(angle));

end
