%% testLroTerrainAwareLos
% Terrain-aware LOS test for an LRO-like lunar orbit.
%
% The test:
%   1. Loads the lunar DEM.
%   2. Builds a 15 km south-polar candidate grid.
%   3. Computes the terrain-horizon database.
%   4. Propagates an LRO-like circular polar orbit.
%   5. Selects a sufficiently visible, terrain-obstructed sensor.
%   6. Plots elevation profiles and measurement availability.

clear;
close all;
clc;

%% Add source directory

testDirectory = fileparts(mfilename("fullpath"));
repositoryDirectory = fileparts(testDirectory);
sourceDirectory = fullfile(repositoryDirectory, "src");

addpath(sourceDirectory);

requiredFunctions = [
    "orbitDynamics.propagateLunarOrbit"
    "digitalElevationModel.buildCandidateSensorGrid"
    "digitalElevationModel.buildMaximumTerrainHorizonDatabase"
    "optimization.buildTerrainAwareLosDatabase"
    "optimization.coverageObjective"
];

for functionIndex = 1:length(requiredFunctions)

    functionName = requiredFunctions(functionIndex);

    assert(~isempty(which(functionName)), ...
        "%s was not found.", functionName);
end

%% Lunar constants

moonRadius = 1737.4;                  % km
moonMu = 4902.800066;                 % km^3/s^2

moonSiderealPeriod = ...
    27.321661 * 86400;                % s

moonAngularRate = ...
    2*pi / moonSiderealPeriod;        % rad/s

theta0 = 0;                           % rad

%% Load DEM

demFile = fullfile( ...
    repositoryDirectory, ...
    "data", ...
    "new_lunar_interpolant_model.mat");

if ~isfile(demFile)

    demFile = fullfile( ...
        repositoryDirectory, ...
        "new_lunar_interpolant_model.mat");
end

assert(isfile(demFile), ...
    "new_lunar_interpolant_model.mat was not found.");

demData = load(demFile);

assert(isfield(demData, "F"), ...
    "The DEM MAT-file must contain the interpolant F.");

sourceInterpolant = demData.F;

%% Convert DEM coordinates from degrees to radians

latitudeGridDegrees = ...
    sourceInterpolant.GridVectors{1}(:);

longitudeGridDegrees = ...
    sourceInterpolant.GridVectors{2}(:);

elevationGrid = sourceInterpolant.Values;

latitudeGrid = deg2rad(latitudeGridDegrees);
longitudeGrid = deg2rad(longitudeGridDegrees);

% Add a periodic longitude boundary if necessary.

longitudePeriod = 2*pi;

if longitudeGrid(end) - longitudeGrid(1) < ...
        longitudePeriod - 1e-10

    longitudeGrid = [
        longitudeGrid
        longitudeGrid(1) + longitudePeriod
    ];

    elevationGrid = [
        elevationGrid, elevationGrid(:,1)
    ];
end

dem = griddedInterpolant( ...
    {latitudeGrid, longitudeGrid}, ...
    elevationGrid, ...
    "linear", ...
    "nearest");

%% Build south-polar candidate grid

latitudeBand = deg2rad([-90, -75]);
longitudeBand = deg2rad([0, 360]);

candidateSpacing = 15;                % km

[candidateLatitudes, candidateLongitudes] = ...
    digitalElevationModel.buildCandidateSensorGrid( ...
        latitudeBand, ...
        longitudeBand, ...
        candidateSpacing, ...
        moonRadius);

numberOfCandidates = numel(candidateLatitudes);

assert(numberOfCandidates > 0, ...
    "The candidate sensor grid is empty.");

fprintf( ...
    "Candidate sensor locations: %d\n", ...
    numberOfCandidates);

%% Build terrain-horizon database

maximumTerrainRange = 100;            % km

% Higher radial resolution is important for nearby terrain features.

terrainRangeStep = 0.5;               % km
horizonAzimuthStep = deg2rad(2);      % rad

terrainTimer = tic;

[ ...
    horizonAzimuths, ...
    maximumTerrainElevation, ...
    maximumFeatureRange, ...
    sensorElevations, ...
    maximumFeatureElevations ...
] = digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
    candidateLatitudes, ...
    candidateLongitudes, ...
    dem, ...
    maximumTerrainRange, ...
    terrainRangeStep, ...
    horizonAzimuthStep, ...
    moonRadius);

terrainBuildTime = toc(terrainTimer);

assert(all(isfinite(maximumTerrainElevation), "all"), ...
    "The terrain-horizon angles contain nonfinite values.");

assert(all(isfinite(maximumFeatureRange), "all"), ...
    "The maximum-feature ranges contain nonfinite values.");

assert(all(isfinite(sensorElevations)), ...
    "The sensor elevations contain nonfinite values.");

assert(all(isfinite(maximumFeatureElevations), "all"), ...
    "The maximum-feature elevations contain nonfinite values.");

fprintf( ...
    "Terrain database build time: %.2f seconds\n", ...
    terrainBuildTime);

%% Construct an LRO-like circular polar orbit

orbitAltitude = 50;                   % km
orbitRadius = moonRadius + orbitAltitude;

orbitInclination = deg2rad(90);
rightAscensionAscendingNode = deg2rad(37);

circularVelocity = sqrt(moonMu / orbitRadius);

initialPerifocalState = [
    orbitRadius
    0
    0
    0
    circularVelocity
    0
];

rotationZ = @(angle) [
     cos(angle), -sin(angle), 0
     sin(angle),  cos(angle), 0
              0,           0, 1
];

rotationX = @(angle) [
    1,          0,           0
    0, cos(angle), -sin(angle)
    0, sin(angle),  cos(angle)
];

perifocalToMoonInertial = ...
    rotationZ(rightAscensionAscendingNode) * ...
    rotationX(orbitInclination);

initialState = [
    perifocalToMoonInertial * initialPerifocalState(1:3)
    perifocalToMoonInertial * initialPerifocalState(4:6)
];

orbitPeriod = ...
    2*pi * sqrt(orbitRadius^3 / moonMu);

numberOfPeriods = 3;
outputStep = 20;                      % s

requestedTimes = ...
    (0:outputStep:numberOfPeriods*orbitPeriod).';

if requestedTimes(end) < numberOfPeriods*orbitPeriod

    requestedTimes(end + 1,1) = ...
        numberOfPeriods*orbitPeriod;
end

[times, propagatedStates] = ...
    orbitDynamics.propagateLunarOrbit( ...
        initialState, ...
        requestedTimes, ...
        moonMu = moonMu);

if size(propagatedStates,2) == 6

    truthStateHistory = propagatedStates.';
else

    truthStateHistory = propagatedStates;
end

numberOfTimes = numel(times);

assert( ...
    isequal(size(truthStateHistory), [6, numberOfTimes]), ...
    "Unexpected propagated state-history dimensions.");

rsoStateHistories = reshape( ...
    truthStateHistory, ...
    6, ...
    numberOfTimes, ...
    1);

%% Build terrain-aware measurement database

instrumentMinimumElevation = deg2rad(0);
horizonMargin = deg2rad(0.1);

[ ...
    measurementAvailability, ...
    ~, ...
    targetElevations, ...
    targetRanges, ...
    limitingElevations ...
] = optimization.buildTerrainAwareLosDatabase( ...
    times, ...
    rsoStateHistories, ...
    candidateLatitudes, ...
    candidateLongitudes, ...
    dem, ...
    horizonAzimuths, ...
    maximumTerrainElevation, ...
    instrumentMinimumElevation, ...
    horizonMargin, ...
    moonRadius, ...
    theta0, ...
    moonAngularRate);

assert(all(isfinite(targetElevations), "all"), ...
    "The target elevations contain nonfinite values.");

assert(all(isfinite(targetRanges), "all"), ...
    "The target ranges contain nonfinite values.");

assert(all(isfinite(limitingElevations), "all"), ...
    "The limiting elevations contain nonfinite values.");

%% Apply geometric measurement gate

geometricAvailability = ...
    targetElevations >= instrumentMinimumElevation;

invalidMeasurements = ...
    measurementAvailability & ...
    ~geometricAvailability;

assert(~any(invalidMeasurements, "all"), ...
    "Terrain filtering created a geometrically invalid measurement.");

%% Count accepted and terrain-rejected measurements

geometricCoverageCounts = reshape( ...
    sum(geometricAvailability(:,:,1), 2), ...
    [], 1);

terrainCoverageCounts = reshape( ...
    sum(measurementAvailability(:,:,1), 2), ...
    [], 1);

terrainRejectedCounts = reshape( ...
    sum( ...
        geometricAvailability(:,:,1) & ...
        ~measurementAvailability(:,:,1), ...
        2), ...
    [], 1);

terrainRejectionFraction = zeros(numberOfCandidates,1);

hasGeometricVisibility = ...
    geometricCoverageCounts > 0;

terrainRejectionFraction(hasGeometricVisibility) = ...
    terrainRejectedCounts(hasGeometricVisibility) ./ ...
    geometricCoverageCounts(hasGeometricVisibility);

%% Select a sufficiently visible terrain-obstructed sensor

% Exclude the exact pole because longitude and local azimuth are
% convention-dependent at exactly +/-90 degrees latitude.

notExactPole = ...
    abs(candidateLatitudes) < deg2rad(89.9);

% Require at least 50 percent of the best geometric visibility count.
% This prevents candidates with only a few visibility epochs from being
% selected solely because they have a large rejection fraction.

minimumGeometricEpochs = max( ...
    3, ...
    ceil(0.5 * max(geometricCoverageCounts)));

eligibleCandidates = ...
    notExactPole & ...
    geometricCoverageCounts >= minimumGeometricEpochs & ...
    terrainCoverageCounts > 0 & ...
    terrainRejectedCounts > 0;

if any(eligibleCandidates)

    candidateScores = terrainRejectionFraction;
    candidateScores(~eligibleCandidates) = -Inf;

    [~, selectedSensorIndex] = ...
        max(candidateScores);

else

    error( ...
        ["No sufficiently visible terrain-obstructed candidate was " ...
         "found. Decrease the candidate spacing, reduce the minimum " ...
         "visibility fraction, or increase the terrain search range."]);
end

selectedLatitude = ...
    candidateLatitudes(selectedSensorIndex);

selectedLongitude = ...
    candidateLongitudes(selectedSensorIndex);

selectedSensorElevation = ...
    sensorElevations(selectedSensorIndex);

selectedTargetElevation = reshape( ...
    targetElevations(selectedSensorIndex,:,1), ...
    [], 1);

selectedLimitingElevation = reshape( ...
    limitingElevations(selectedSensorIndex,:,1), ...
    [], 1);

selectedGeometricAvailability = reshape( ...
    geometricAvailability(selectedSensorIndex,:,1), ...
    [], 1);

selectedTerrainAvailability = reshape( ...
    measurementAvailability(selectedSensorIndex,:,1), ...
    [], 1);

selectedGeometricCount = ...
    geometricCoverageCounts(selectedSensorIndex);

selectedTerrainCount = ...
    terrainCoverageCounts(selectedSensorIndex);

selectedRejectedCount = ...
    terrainRejectedCounts(selectedSensorIndex);

selectedRejectionFraction = ...
    terrainRejectionFraction(selectedSensorIndex);

%% Find maximum horizon and corresponding feature

[ ...
    maximumHorizonAngle, ...
    maximumHorizonAzimuthIndex ...
] = max( ...
    maximumTerrainElevation(selectedSensorIndex,:));

maximumHorizonAzimuth = ...
    horizonAzimuths(maximumHorizonAzimuthIndex);

maximumHorizonFeatureElevation = ...
    maximumFeatureElevations( ...
        selectedSensorIndex, ...
        maximumHorizonAzimuthIndex);

maximumHorizonFeatureRange = ...
    maximumFeatureRange( ...
        selectedSensorIndex, ...
        maximumHorizonAzimuthIndex);

maximumHorizonFeatureHeightAboveSensor = ...
    maximumHorizonFeatureElevation - ...
    selectedSensorElevation;

%% Verify coverage objective

selectedSensors = false(numberOfCandidates,1);
selectedSensors(selectedSensorIndex) = true;

[coverageObjectiveValue, objectCoverageCounts] = ...
    optimization.coverageObjective( ...
        selectedSensors, ...
        measurementAvailability, ...
        1);

assert( ...
    objectCoverageCounts(1) == selectedTerrainCount, ...
    "The coverage objective does not match the LOS database.");

%% Print results

fprintf("\nSelected terrain-obstructed sensor\n");

fprintf( ...
    "  Latitude:                         %.3f deg\n", ...
    rad2deg(selectedLatitude));

fprintf( ...
    "  Longitude:                        %.3f deg\n", ...
    rad2deg(selectedLongitude));

fprintf( ...
    "  Sensor DEM elevation:             %.3f km\n", ...
    selectedSensorElevation);

fprintf( ...
    "  Minimum required geometric epochs: %d\n", ...
    minimumGeometricEpochs);

fprintf( ...
    "  Maximum horizon angle:            %.3f deg\n", ...
    rad2deg(maximumHorizonAngle));

fprintf( ...
    "  Maximum horizon azimuth:          %.3f deg\n", ...
    rad2deg(maximumHorizonAzimuth));

fprintf( ...
    "  Corresponding feature elevation:  %.3f km\n", ...
    maximumHorizonFeatureElevation);

fprintf( ...
    "  Feature height above sensor:      %.3f km\n", ...
    maximumHorizonFeatureHeightAboveSensor);

fprintf( ...
    "  Distance to feature:              %.3f km\n", ...
    maximumHorizonFeatureRange);

fprintf( ...
    "  Geometrically visible epochs:     %d\n", ...
    selectedGeometricCount);

fprintf( ...
    "  Accepted measurement epochs:      %d\n", ...
    selectedTerrainCount);

fprintf( ...
    "  Terrain-rejected epochs:          %d\n", ...
    selectedRejectedCount);

fprintf( ...
    "  Terrain-rejection fraction:       %.3f\n", ...
    selectedRejectionFraction);

fprintf( ...
    "  Coverage objective:               %.3f\n", ...
    coverageObjectiveValue);

%% Classify measurements

% Status:
%   0 = no geometric LOS
%   1 = geometric LOS but blocked by terrain
%   2 = accepted measurement

terrainBlocked = ...
    selectedGeometricAvailability & ...
    ~selectedTerrainAvailability;

acceptedMeasurements = ...
    selectedTerrainAvailability;

measurementStatus = zeros(numberOfTimes,1);

measurementStatus(terrainBlocked) = 1;
measurementStatus(acceptedMeasurements) = 2;

%% Plot elevation and measurement profiles

timeHours = times / 3600;

figure( ...
    Name = "LRO Terrain-Aware Measurements", ...
    Color = "white");

layout = tiledlayout(2,1);

layout.TileSpacing = "compact";
layout.Padding = "compact";

%% Angular elevation profile

nexttile;

plot( ...
    timeHours, ...
    rad2deg(selectedTargetElevation), ...
    Color = [0, 0.4470, 0.7410], ...
    LineWidth = 1.5);

hold on;

plot( ...
    timeHours, ...
    rad2deg(selectedLimitingElevation), ...
    Color = [0.8500, 0.3250, 0.0980], ...
    LineWidth = 1.5);

yline( ...
    rad2deg(instrumentMinimumElevation), ...
    "--k", ...
    "Instrument minimum");

scatter( ...
    timeHours(acceptedMeasurements), ...
    rad2deg( ...
        selectedTargetElevation(acceptedMeasurements)), ...
    18, ...
    [0.2, 0.65, 0.2], ...
    "filled");

scatter( ...
    timeHours(terrainBlocked), ...
    rad2deg( ...
        selectedTargetElevation(terrainBlocked)), ...
    30, ...
    [0.85, 0.1, 0.1], ...
    "x", ...
    LineWidth = 1.5);

grid on;

xlabel("Time (hr)");
ylabel("Apparent elevation (deg)");
title("Target Elevation and Terrain-Aware Elevation Limit");

legend( ...
    "LRO-like target", ...
    "Terrain-aware limit", ...
    "Instrument minimum", ...
    "Accepted measurement", ...
    "Terrain rejected", ...
    Location = "best");

%% Measurement status

nexttile;

stairs( ...
    timeHours, ...
    measurementStatus, ...
    Color = [0, 0.4470, 0.7410], ...
    LineWidth = 1.5);

hold on;

scatter( ...
    timeHours(acceptedMeasurements), ...
    2*ones(sum(acceptedMeasurements),1), ...
    18, ...
    [0.2, 0.65, 0.2], ...
    "filled");

scatter( ...
    timeHours(terrainBlocked), ...
    ones(sum(terrainBlocked),1), ...
    30, ...
    [0.85, 0.1, 0.1], ...
    "x", ...
    LineWidth = 1.5);

ylim([-0.25, 2.25]);

yticks([0, 1, 2]);

yticklabels({ ...
    "No geometric LOS", ...
    "Terrain blocked", ...
    "Measurement accepted"});

grid on;

xlabel("Time (hr)");
ylabel("Measurement status");
title("Terrain-Filtered Measurement Availability");

title( ...
    layout, ...
    sprintf( ...
        "LRO-like %.0f km Orbit | Sensor %.2f deg Lat, %.2f deg Lon", ...
        orbitAltitude, ...
        rad2deg(selectedLatitude), ...
        rad2deg(selectedLongitude)));

fprintf("\ntestLroTerrainAwareLos passed.\n");