%% testProductionConvergence12000Fe
% Quick post-run convergence and sensor-placement diagnostic for the
% 12000-FE production campaign.
%
% This script does NOT rerun the optimizer and produces no figures. It finds
% the newest complete 12000-FE / 20-run production study for every objective
% and network size, verifies the saved histories, then reports:
%
%   1) convergence consistency and terminal slopes,
%   2) exact-network and exact-site diversity,
%   3) repeated/common sensor locations,
%   4) latitude-band preferences,
%   5) whether solutions accumulate at either latitude-domain boundary, and
%   6) longitude separation within the optimized networks.
%
% "Consistent plateau" is a practical diagnostic, not proof of the global
% optimum. Thresholds are explicit below.

clear;
clc;

%% ========================================================================
%  Project paths and production definition
%  ========================================================================

testDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testDirectory);
runRoot = fullfile(projectRoot,"results","optimization_runs");
resultsDirectory = fullfile(projectRoot,"results");

assert(isfolder(runRoot), ...
    "Optimization result directory was not found: %s",runRoot);

networkSizes = [3 5 7 10];
objectiveModes = ["information","coverage"];

numberOfRuns = 20;
functionEvaluationBudget = 12000;
populationSize = 60;
baseSeed = 1000;
studyName = "lunar_surface_production_optimization";

latitudeDomainDeg = [-90,0];

%% ========================================================================
%  Diagnostic settings
%  ========================================================================

% Linear terminal slope is fitted over the final quarter of each history.
terminalWindowFraction = 0.25;

% Convergence consistency heuristic:
%   - 90% of runs must have a terminal slope magnitude below this fraction
%     of their total optimization gain per 1000 FE,
%   - 90% of runs must obtain no more than this fraction of their total gain
%     during the final quarter of the FE budget,
%   - final run-to-run standard deviation must be small relative to the mean
%     optimization gain.
maximumP90AbsNormalizedSlopePctPer1000Fe = 0.50;
maximumP90LateImprovementPct = 5.0;
maximumFinalStdToMeanGainPct = 5.0;

% Placement diagnostics.
boundaryBandDeg = 5;
latitudeBinWidthDeg = 5;
numberOfCommonSitesToPrint = 5;
numberOfLatitudeBandsToPrint = 3;

writeCsv = true;

%% ========================================================================
%  Discover completed studies
%  ========================================================================

summaryFiles = dir(fullfile(runRoot,"*","study_summary.mat"));

assert(~isempty(summaryFiles), ...
    "No production study summaries were found.");

[~,order] = sort([summaryFiles.datenum],"descend");
summaryFiles = summaryFiles(order);

numberOfCases = numel(networkSizes)*numel(objectiveModes);

%% ========================================================================
%  Allocate convergence summary
%  ========================================================================

objectiveColumn = strings(numberOfCases,1);
networkSizeColumn = zeros(numberOfCases,1);

finalMeanObjective = zeros(numberOfCases,1);
finalStdObjective = zeros(numberOfCases,1);
bestWorstGap = zeros(numberOfCases,1);
meanTotalGain = zeros(numberOfCases,1);

meanTerminalSlopePer1000Fe = zeros(numberOfCases,1);
p90AbsNormalizedSlopePctPer1000Fe = zeros(numberOfCases,1);
p90LateImprovementPct = zeros(numberOfCases,1);
finalStdToMeanGainPct = zeros(numberOfCases,1);

consistentPlateau = false(numberOfCases,1);
convergenceDiagnostic = strings(numberOfCases,1);

%% ========================================================================
%  Allocate placement summary
%  ========================================================================

uniqueNetworkCount = zeros(numberOfCases,1);
mostRepeatedNetworkRuns = zeros(numberOfCases,1);

totalPlacements = zeros(numberOfCases,1);
uniqueSiteCount = zeros(numberOfCases,1);
mostCommonSiteRuns = zeros(numberOfCases,1);
mostCommonSiteLatitudeDeg = zeros(numberOfCases,1);
mostCommonSiteLongitudeDeg = zeros(numberOfCases,1);

exactBoundaryPlacementPct = zeros(numberOfCases,1);
withinBoundaryBandPlacementPct = zeros(numberOfCases,1);
nearEquatorPlacementPct = zeros(numberOfCases,1);
nearSouthPolePlacementPct = zeros(numberOfCases,1);

latitudeP10Deg = zeros(numberOfCases,1);
latitudeMedianDeg = zeros(numberOfCases,1);
latitudeP90Deg = zeros(numberOfCases,1);

meanPairwiseLongitudeSeparationDeg = zeros(numberOfCases,1);

topLatitudeBand = strings(numberOfCases,1);
topLatitudeBandPlacementPct = zeros(numberOfCases,1);

studyFileColumn = strings(numberOfCases,1);

commonSiteTables = cell(numberOfCases,1);
latitudeBandTables = cell(numberOfCases,1);

%% ========================================================================
%  Process all eight production cases
%  ========================================================================

row = 0;

for objectiveIndex = 1:numel(objectiveModes)

    objectiveMode = objectiveModes(objectiveIndex);

    for networkIndex = 1:numel(networkSizes)

        networkSize = networkSizes(networkIndex);
        row = row + 1;

        [studyState,summaryFile] = findStudy( ...
            summaryFiles, ...
            networkSize, ...
            objectiveMode, ...
            numberOfRuns, ...
            functionEvaluationBudget, ...
            populationSize, ...
            baseSeed, ...
            studyName);

        assert(numel(studyState.runStates) == numberOfRuns, ...
            "Study contains the wrong number of runs.");

        referenceFe = ...
            double(studyState.runStates{1}.history.fe(:));

        assert(referenceFe(end) == functionEvaluationBudget, ...
            "Convergence history does not reach 12000 FE.");

        assert(all(diff(referenceFe) > 0), ...
            "FE history is not strictly increasing.");

        terminalStartFe = ...
            functionEvaluationBudget*(1-terminalWindowFraction);

        terminalMask = ...
            referenceFe >= terminalStartFe;

        assert(nnz(terminalMask) >= 3, ...
            "Too few terminal convergence points.");

        terminalFe = referenceFe(terminalMask);

        historyMatrix = zeros(numel(referenceFe),numberOfRuns);
        runFinalObjectives = zeros(numberOfRuns,1);
        runTotalGain = zeros(numberOfRuns,1);
        runLateImprovementPct = zeros(numberOfRuns,1);
        runAbsNormalizedSlopePctPer1000Fe = zeros(numberOfRuns,1);

        sensorIndexMatrix = zeros(numberOfRuns,networkSize);
        sensorLatitudeMatrix = zeros(numberOfRuns,networkSize);
        sensorLongitudeMatrix = zeros(numberOfRuns,networkSize);
        runMeanPairwiseLongitudeSeparation = zeros(numberOfRuns,1);

        terminalStartIndex = find(terminalMask,1,"first");

        for runIndex = 1:numberOfRuns

            runState = studyState.runStates{runIndex};

            runFe = double(runState.history.fe(:));
            runBest = double(runState.history.bestJ(:));

            assert(isequal(runFe,referenceFe), ...
                "Run FE histories are not aligned.");

            assert(numel(runBest) == numel(referenceFe), ...
                "Run best-objective history has the wrong length.");

            assert(all(isfinite(runBest)), ...
                "Run convergence history contains nonfinite values.");

            assert(all(diff(runBest) <= 1e-12), ...
                "Saved best-so-far history increased within a run.");

            assert(runState.searchFunctionEvaluations == ...
                functionEvaluationBudget, ...
                "Saved run did not use the full 12000-FE budget.");

            objectiveTolerance = ...
                1e-10*max(1,abs(runState.bestObjective));

            assert(abs(runBest(end)-runState.bestObjective) <= ...
                objectiveTolerance, ...
                "Run history does not terminate at the stored incumbent.");

            historyMatrix(:,runIndex) = runBest;
            runFinalObjectives(runIndex) = runBest(end);

            totalGain = runBest(1)-runBest(end);
            lateGain = runBest(terminalStartIndex)-runBest(end);

            gainTolerance = ...
                1e-12*max(1,abs(runBest(1)));

            if totalGain > gainTolerance
                runLateImprovementPct(runIndex) = ...
                    100*lateGain/totalGain;
                gainScale = totalGain;
            else
                runLateImprovementPct(runIndex) = 0;
                gainScale = max(gainTolerance,eps);
            end

            terminalCoefficients = ...
                polyfit(terminalFe,runBest(terminalMask),1);

            runAbsNormalizedSlopePctPer1000Fe(runIndex) = ...
                100*abs(terminalCoefficients(1)*1000)/gainScale;

            runTotalGain(runIndex) = totalGain;

            %% Sensor placement for this run

            sensorIndices = ...
                double(runState.bestSensorIndices(:).');

            sensorLatitudesDeg = ...
                rad2deg(double(runState.bestSensorLatitudesRad(:).'));

            sensorLongitudesDeg = ...
                mod( ...
                    rad2deg(double(runState.bestSensorLongitudesRad(:).')), ...
                    360);

            assert(numel(sensorIndices) == networkSize, ...
                "Stored best network has the wrong sensor count.");

            assert(numel(unique(sensorIndices)) == networkSize, ...
                "Stored best network contains duplicate sensors.");

            sensorIndexMatrix(runIndex,:) = sensorIndices;
            sensorLatitudeMatrix(runIndex,:) = sensorLatitudesDeg;
            sensorLongitudeMatrix(runIndex,:) = sensorLongitudesDeg;

            runMeanPairwiseLongitudeSeparation(runIndex) = ...
                meanPairwiseCircularSeparationDeg(sensorLongitudesDeg);
        end

        %% ----------------------------------------------------------------
        %  Convergence metrics
        %  ----------------------------------------------------------------

        meanHistory = mean(historyMatrix,2);
        meanTerminalCoefficients = ...
            polyfit(terminalFe,meanHistory(terminalMask),1);

        finalMean = mean(runFinalObjectives);
        finalStd = std(runFinalObjectives);
        caseMeanGain = mean(runTotalGain);

        meanGainScale = max( ...
            caseMeanGain, ...
            1e-12*max(1,abs(finalMean)));

        caseP90SlopePct = ...
            localPercentile( ...
                runAbsNormalizedSlopePctPer1000Fe,90);

        caseP90LatePct = ...
            localPercentile(runLateImprovementPct,90);

        caseStdToGainPct = ...
            100*finalStd/meanGainScale;

        caseConsistentPlateau = ...
            caseP90SlopePct <= ...
                maximumP90AbsNormalizedSlopePctPer1000Fe && ...
            caseP90LatePct <= ...
                maximumP90LateImprovementPct && ...
            caseStdToGainPct <= ...
                maximumFinalStdToMeanGainPct;

        caseDiagnostic = classifyConvergence( ...
            caseP90SlopePct, ...
            caseP90LatePct, ...
            caseStdToGainPct, ...
            maximumP90AbsNormalizedSlopePctPer1000Fe, ...
            maximumP90LateImprovementPct, ...
            maximumFinalStdToMeanGainPct);

        %% ----------------------------------------------------------------
        %  Exact network/site diversity
        %  ----------------------------------------------------------------

        [~,~,networkGroup] = ...
            unique(sensorIndexMatrix,"rows");

        networkCounts = ...
            accumarray(networkGroup,1);

        caseUniqueNetworkCount = ...
            numel(networkCounts);

        caseMostRepeatedNetworkRuns = ...
            max(networkCounts);

        allSensorIndices = sensorIndexMatrix(:);
        allLatitudesDeg = sensorLatitudeMatrix(:);
        allLongitudesDeg = sensorLongitudeMatrix(:);

        [uniqueSites,~,siteGroup] = ...
            unique(allSensorIndices);

        siteCounts = ...
            accumarray(siteGroup,1);

        [sortedSiteCounts,siteOrder] = ...
            sort(siteCounts,"descend");

        sortedUniqueSites = ...
            uniqueSites(siteOrder);

        numberOfCommonSites = min( ...
            numberOfCommonSitesToPrint, ...
            numel(sortedUniqueSites));

        commonSiteRank = (1:numberOfCommonSites).';
        commonSiteIndex = ...
            sortedUniqueSites(1:numberOfCommonSites);

        commonSiteCount = ...
            sortedSiteCounts(1:numberOfCommonSites);

        commonSiteRunPct = ...
            100*commonSiteCount/numberOfRuns;

        commonSiteLatitude = ...
            zeros(numberOfCommonSites,1);

        commonSiteLongitude = ...
            zeros(numberOfCommonSites,1);

        for siteRank = 1:numberOfCommonSites

            occurrenceIndex = find( ...
                allSensorIndices == commonSiteIndex(siteRank), ...
                1, ...
                "first");

            commonSiteLatitude(siteRank) = ...
                allLatitudesDeg(occurrenceIndex);

            commonSiteLongitude(siteRank) = ...
                allLongitudesDeg(occurrenceIndex);
        end

        commonSiteTable = table( ...
            repmat(objectiveMode,numberOfCommonSites,1), ...
            repmat(networkSize,numberOfCommonSites,1), ...
            commonSiteRank, ...
            commonSiteIndex, ...
            commonSiteLatitude, ...
            commonSiteLongitude, ...
            commonSiteCount, ...
            commonSiteRunPct, ...
            'VariableNames',{ ...
                'Objective', ...
                'NetworkSize', ...
                'Rank', ...
                'CandidateIndex', ...
                'LatitudeDeg', ...
                'LongitudeDeg', ...
                'Occurrences', ...
                'RunsPct'});

        commonSiteTables{row} = commonSiteTable;

        %% ----------------------------------------------------------------
        %  Boundary and geographic-distribution diagnostics
        %  ----------------------------------------------------------------

        latitudeDistanceToBoundary = min( ...
            abs(allLatitudesDeg-latitudeDomainDeg(1)), ...
            abs(allLatitudesDeg-latitudeDomainDeg(2)));

        exactBoundaryToleranceDeg = 1e-10;

        caseExactBoundaryPct = ...
            100*mean( ...
                latitudeDistanceToBoundary <= ...
                exactBoundaryToleranceDeg);

        caseWithinBoundaryBandPct = ...
            100*mean( ...
                latitudeDistanceToBoundary <= ...
                boundaryBandDeg);

        caseNearEquatorPct = ...
            100*mean( ...
                allLatitudesDeg >= ...
                latitudeDomainDeg(2)-boundaryBandDeg);

        caseNearSouthPolePct = ...
            100*mean( ...
                allLatitudesDeg <= ...
                latitudeDomainDeg(1)+boundaryBandDeg);

        caseLatitudeP10 = ...
            localPercentile(allLatitudesDeg,10);

        caseLatitudeMedian = ...
            median(allLatitudesDeg);

        caseLatitudeP90 = ...
            localPercentile(allLatitudesDeg,90);

        caseMeanLongitudeSeparation = ...
            mean(runMeanPairwiseLongitudeSeparation);

        %% ----------------------------------------------------------------
        %  Latitude-band frequency
        %  ----------------------------------------------------------------

        [latitudeBandTable,caseTopBand,caseTopBandPct] = ...
            buildLatitudeBandTable( ...
                allLatitudesDeg, ...
                objectiveMode, ...
                networkSize, ...
                latitudeDomainDeg, ...
                latitudeBinWidthDeg, ...
                numberOfLatitudeBandsToPrint);

        latitudeBandTables{row} = latitudeBandTable;

        %% ----------------------------------------------------------------
        %  Store summaries
        %  ----------------------------------------------------------------

        objectiveColumn(row) = objectiveMode;
        networkSizeColumn(row) = networkSize;

        finalMeanObjective(row) = finalMean;
        finalStdObjective(row) = finalStd;
        bestWorstGap(row) = ...
            max(runFinalObjectives)-min(runFinalObjectives);
        meanTotalGain(row) = caseMeanGain;

        meanTerminalSlopePer1000Fe(row) = ...
            meanTerminalCoefficients(1)*1000;

        p90AbsNormalizedSlopePctPer1000Fe(row) = ...
            caseP90SlopePct;

        p90LateImprovementPct(row) = ...
            caseP90LatePct;

        finalStdToMeanGainPct(row) = ...
            caseStdToGainPct;

        consistentPlateau(row) = ...
            caseConsistentPlateau;

        convergenceDiagnostic(row) = ...
            caseDiagnostic;

        uniqueNetworkCount(row) = ...
            caseUniqueNetworkCount;

        mostRepeatedNetworkRuns(row) = ...
            caseMostRepeatedNetworkRuns;

        totalPlacements(row) = ...
            numel(allSensorIndices);

        uniqueSiteCount(row) = ...
            numel(uniqueSites);

        mostCommonSiteRuns(row) = ...
            sortedSiteCounts(1);

        mostCommonSiteLatitudeDeg(row) = ...
            commonSiteLatitude(1);

        mostCommonSiteLongitudeDeg(row) = ...
            commonSiteLongitude(1);

        exactBoundaryPlacementPct(row) = ...
            caseExactBoundaryPct;

        withinBoundaryBandPlacementPct(row) = ...
            caseWithinBoundaryBandPct;

        nearEquatorPlacementPct(row) = ...
            caseNearEquatorPct;

        nearSouthPolePlacementPct(row) = ...
            caseNearSouthPolePct;

        latitudeP10Deg(row) = ...
            caseLatitudeP10;

        latitudeMedianDeg(row) = ...
            caseLatitudeMedian;

        latitudeP90Deg(row) = ...
            caseLatitudeP90;

        meanPairwiseLongitudeSeparationDeg(row) = ...
            caseMeanLongitudeSeparation;

        topLatitudeBand(row) = ...
            caseTopBand;

        topLatitudeBandPlacementPct(row) = ...
            caseTopBandPct;

        studyFileColumn(row) = ...
            string(summaryFile);
    end
end

%% ========================================================================
%  Compact convergence table
%  ========================================================================

convergenceTable = table( ...
    objectiveColumn, ...
    networkSizeColumn, ...
    finalMeanObjective, ...
    finalStdObjective, ...
    bestWorstGap, ...
    meanTerminalSlopePer1000Fe, ...
    p90AbsNormalizedSlopePctPer1000Fe, ...
    p90LateImprovementPct, ...
    finalStdToMeanGainPct, ...
    consistentPlateau, ...
    convergenceDiagnostic, ...
    'VariableNames',{ ...
        'Objective', ...
        'NetworkSize', ...
        'FinalMeanJ', ...
        'FinalStdJ', ...
        'BestWorstGap', ...
        'MeanTerminalSlopePer1000FE', ...
        'P90AbsNormalizedSlopePctPer1000FE', ...
        'P90LateImprovementPct', ...
        'FinalStdToMeanGainPct', ...
        'ConsistentPlateau', ...
        'Diagnostic'});

fprintf("\n");
fprintf("============================================================\n");
fprintf("12000-FE convergence consistency check\n");
fprintf("============================================================\n");
fprintf("Terminal slope window: final %.0f%% of FE history\n", ...
    100*terminalWindowFraction);
fprintf("Slope criterion:       P90 <= %.2f%% of run gain / 1000 FE\n", ...
    maximumP90AbsNormalizedSlopePctPer1000Fe);
fprintf("Late-gain criterion:   P90 <= %.1f%% of total run gain\n", ...
    maximumP90LateImprovementPct);
fprintf("Run-spread criterion:  std <= %.1f%% of mean optimization gain\n", ...
    maximumFinalStdToMeanGainPct);
fprintf("============================================================\n\n");

disp(convergenceTable);

%% ========================================================================
%  Compact sensor-placement table
%  ========================================================================

placementTable = table( ...
    objectiveColumn, ...
    networkSizeColumn, ...
    uniqueNetworkCount, ...
    mostRepeatedNetworkRuns, ...
    totalPlacements, ...
    uniqueSiteCount, ...
    mostCommonSiteRuns, ...
    mostCommonSiteLatitudeDeg, ...
    mostCommonSiteLongitudeDeg, ...
    exactBoundaryPlacementPct, ...
    withinBoundaryBandPlacementPct, ...
    nearEquatorPlacementPct, ...
    nearSouthPolePlacementPct, ...
    latitudeP10Deg, ...
    latitudeMedianDeg, ...
    latitudeP90Deg, ...
    meanPairwiseLongitudeSeparationDeg, ...
    topLatitudeBand, ...
    topLatitudeBandPlacementPct, ...
    'VariableNames',{ ...
        'Objective', ...
        'NetworkSize', ...
        'UniqueNetworksOf20', ...
        'MostRepeatedNetworkRuns', ...
        'TotalSensorPlacements', ...
        'UniqueExactSites', ...
        'MostCommonSiteRuns', ...
        'MostCommonSiteLatitudeDeg', ...
        'MostCommonSiteLongitudeDeg', ...
        'ExactLatitudeBoundaryPct', ...
        'Within5DegLatitudeBoundaryPct', ...
        'Within5DegEquatorPct', ...
        'Within5DegSouthPolePct', ...
        'LatitudeP10Deg', ...
        'LatitudeMedianDeg', ...
        'LatitudeP90Deg', ...
        'MeanPairwiseLongitudeSeparationDeg', ...
        'Top5DegLatitudeBand', ...
        'TopLatitudeBandPlacementPct'});

fprintf("\n");
fprintf("============================================================\n");
fprintf("Sensor-placement diversity check\n");
fprintf("============================================================\n");
fprintf("Boundary band: %.1f deg from either latitude-domain edge\n", ...
    boundaryBandDeg);
fprintf("Latitude bands: %.1f deg\n",latitudeBinWidthDeg);
fprintf("============================================================\n\n");

disp(placementTable);

%% ========================================================================
%  Most common exact sites by case
%  ========================================================================

fprintf("\n");
fprintf("============================================================\n");
fprintf("Most common exact candidate sites\n");
fprintf("============================================================\n");

for caseIndex = 1:numberOfCases

    fprintf("\n%s, N = %d\n", ...
        upperFirst(objectiveColumn(caseIndex)), ...
        networkSizeColumn(caseIndex));

    disp(commonSiteTables{caseIndex});
end

%% ========================================================================
%  Most common latitude bands by case
%  ========================================================================

fprintf("\n");
fprintf("============================================================\n");
fprintf("Most common 5-deg latitude bands\n");
fprintf("============================================================\n");

for caseIndex = 1:numberOfCases

    fprintf("\n%s, N = %d\n", ...
        upperFirst(objectiveColumn(caseIndex)), ...
        networkSizeColumn(caseIndex));

    disp(latitudeBandTables{caseIndex});
end

%% ========================================================================
%  Save tabular diagnostics
%  ========================================================================

if writeCsv

    convergenceCsv = fullfile( ...
        resultsDirectory, ...
        "production_convergence_12000fe_summary.csv");

    placementCsv = fullfile( ...
        resultsDirectory, ...
        "production_sensor_placement_12000fe_summary.csv");

    commonSitesCsv = fullfile( ...
        resultsDirectory, ...
        "production_sensor_common_sites_12000fe.csv");

    latitudeBandsCsv = fullfile( ...
        resultsDirectory, ...
        "production_sensor_latitude_bands_12000fe.csv");

    writetable(convergenceTable,convergenceCsv);
    writetable(placementTable,placementCsv);

    writetable( ...
        vertcat(commonSiteTables{:}), ...
        commonSitesCsv);

    writetable( ...
        vertcat(latitudeBandTables{:}), ...
        latitudeBandsCsv);

    fprintf("\nSaved tabular diagnostics:\n");
    fprintf("  %s\n",convergenceCsv);
    fprintf("  %s\n",placementCsv);
    fprintf("  %s\n",commonSitesCsv);
    fprintf("  %s\n",latitudeBandsCsv);
end

fprintf("\n");
fprintf("Interpretation:\n");
fprintf("  MeanTerminalSlopePer1000FE should approach zero from below.\n");
fprintf("  P90AbsNormalizedSlopePctPer1000FE checks that nearly all runs, not\n");
fprintf("  only the mean history, have flattened late in the search.\n");
fprintf("  UniqueNetworksOf20 and UniqueExactSites quantify exact-solution\n");
fprintf("  diversity. Repeated latitude bands with many unique exact sites imply\n");
fprintf("  a repeatable architecture rather than one identical discrete solution.\n");
fprintf("  Boundary percentages reveal whether the optimizer is accumulating at\n");
fprintf("  the -90/0-deg design-space limits. Mean pairwise longitude separation\n");
fprintf("  indicates whether selected sensors are longitudinally distributed.\n");
fprintf("\n");
fprintf("testProductionConvergence12000Fe passed all structural checks.\n");

%% =========================================================================
%  Local helpers
%  =========================================================================

function [studyState,summaryFile] = findStudy( ...
    summaryFiles, ...
    networkSize, ...
    objectiveMode, ...
    numberOfRuns, ...
    functionEvaluationBudget, ...
    populationSize, ...
    baseSeed, ...
    studyName)

for fileIndex = 1:numel(summaryFiles)

    candidateFile = fullfile( ...
        summaryFiles(fileIndex).folder, ...
        summaryFiles(fileIndex).name);

    data = load(candidateFile,"studyState");

    if ~isfield(data,"studyState")
        continue
    end

    candidate = data.studyState;

    if ~isfield(candidate,"config") || ...
            ~isfield(candidate,"numberOfRuns") || ...
            candidate.numberOfRuns ~= numberOfRuns
        continue
    end

    cfg = candidate.config;

    requiredFields = [ ...
        "networkSize", ...
        "objectiveMode", ...
        "functionEvaluationBudget", ...
        "populationSize", ...
        "baseSeed", ...
        "studyName"];

    if ~all(isfield(cfg,cellstr(requiredFields)))
        continue
    end

    if cfg.networkSize ~= networkSize || ...
            lower(string(cfg.objectiveMode)) ~= objectiveMode || ...
            cfg.functionEvaluationBudget ~= functionEvaluationBudget || ...
            cfg.populationSize ~= populationSize || ...
            cfg.baseSeed ~= baseSeed || ...
            string(cfg.studyName) ~= studyName
        continue
    end

    studyState = candidate;
    summaryFile = candidateFile;
    return
end

error( ...
    "testProductionConvergence12000Fe:StudyNotFound", ...
    "No complete 12000-FE production study found for N=%d, %s.", ...
    networkSize,objectiveMode);

end

function value = localPercentile(values,percent)

values = sort(values(:));
numberOfValues = numel(values);

assert(numberOfValues >= 1, ...
    "Cannot evaluate a percentile of an empty array.");

if numberOfValues == 1
    value = values(1);
    return
end

position = 1 + (numberOfValues-1)*(percent/100);
lowerIndex = floor(position);
upperIndex = ceil(position);

if lowerIndex == upperIndex
    value = values(lowerIndex);
else
    interpolationFraction = position-lowerIndex;
    value = ...
        values(lowerIndex) + ...
        interpolationFraction*( ...
            values(upperIndex)-values(lowerIndex));
end

end

function label = classifyConvergence( ...
    p90SlopePct, ...
    p90LatePct, ...
    stdToGainPct, ...
    slopeThresholdPct, ...
    lateThresholdPct, ...
    spreadThresholdPct)

slopeOkay = ...
    p90SlopePct <= slopeThresholdPct;

lateOkay = ...
    p90LatePct <= lateThresholdPct;

spreadOkay = ...
    stdToGainPct <= spreadThresholdPct;

if slopeOkay && lateOkay && spreadOkay
    label = "consistent plateau";
elseif ~slopeOkay && ~lateOkay
    label = "still improving";
elseif slopeOkay && lateOkay && ~spreadOkay
    label = "plateau, run spread remains";
elseif ~slopeOkay
    label = "terminal slope remains";
elseif ~lateOkay
    label = "late improvements remain";
else
    label = "mixed";
end

end

function meanSeparationDeg = ...
    meanPairwiseCircularSeparationDeg(longitudesDeg)

longitudesDeg = mod(longitudesDeg(:),360);
numberOfLongitudes = numel(longitudesDeg);

if numberOfLongitudes < 2
    meanSeparationDeg = 0;
    return
end

separations = zeros( ...
    numberOfLongitudes*(numberOfLongitudes-1)/2, ...
    1);

pairIndex = 0;

for firstIndex = 1:numberOfLongitudes-1
    for secondIndex = firstIndex+1:numberOfLongitudes

        pairIndex = pairIndex + 1;

        delta = ...
            longitudesDeg(secondIndex)- ...
            longitudesDeg(firstIndex);

        separations(pairIndex) = ...
            abs(mod(delta+180,360)-180);
    end
end

meanSeparationDeg = mean(separations);

end

function [topTable,topBandLabel,topBandPct] = ...
    buildLatitudeBandTable( ...
        latitudesDeg, ...
        objectiveMode, ...
        networkSize, ...
        latitudeDomainDeg, ...
        binWidthDeg, ...
        numberToReturn)

minimumLatitude = latitudeDomainDeg(1);
maximumLatitude = latitudeDomainDeg(2);

numberOfBins = round( ...
    (maximumLatitude-minimumLatitude)/binWidthDeg);

assert(abs( ...
    minimumLatitude + ...
    numberOfBins*binWidthDeg - ...
    maximumLatitude) < 1e-12, ...
    "Latitude bin width must exactly divide the latitude domain.");

binCounts = zeros(numberOfBins,1);
binLabels = strings(numberOfBins,1);

for binIndex = 1:numberOfBins

    lowerEdge = ...
        minimumLatitude + ...
        (binIndex-1)*binWidthDeg;

    upperEdge = ...
        lowerEdge + binWidthDeg;

    if binIndex < numberOfBins
        inBin = ...
            latitudesDeg >= lowerEdge & ...
            latitudesDeg < upperEdge;

        binLabels(binIndex) = sprintf( ...
            "[%.0f, %.0f)", ...
            lowerEdge, ...
            upperEdge);
    else
        inBin = ...
            latitudesDeg >= lowerEdge & ...
            latitudesDeg <= upperEdge;

        binLabels(binIndex) = sprintf( ...
            "[%.0f, %.0f]", ...
            lowerEdge, ...
            upperEdge);
    end

    binCounts(binIndex) = nnz(inBin);
end

[sortedCounts,order] = ...
    sort(binCounts,"descend");

numberToReturn = min(numberToReturn,numberOfBins);

selectedOrder = ...
    order(1:numberToReturn);

rank = (1:numberToReturn).';
band = binLabels(selectedOrder);
count = sortedCounts(1:numberToReturn);
placementPct = 100*count/numel(latitudesDeg);

topTable = table( ...
    repmat(objectiveMode,numberToReturn,1), ...
    repmat(networkSize,numberToReturn,1), ...
    rank, ...
    band, ...
    count, ...
    placementPct, ...
    'VariableNames',{ ...
        'Objective', ...
        'NetworkSize', ...
        'Rank', ...
        'LatitudeBandDeg', ...
        'Placements', ...
        'PlacementPct'});

topBandLabel = band(1);
topBandPct = placementPct(1);

end

function output = upperFirst(input)

input = string(input);

if strlength(input) == 0
    output = input;
    return
end

characters = char(input);
characters(1) = upper(characters(1));
output = string(characters);

end
