%% testNetworkCovariance
% Test covariance-only network evaluation and both optimization objectives.

clear;
close all;
clc;

%% Project path

testDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testDirectory);
sourceDirectory = fullfile(projectRoot,"src");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

requiredFunctions = [
    "estimation.isotropicProcessNoise"
    "estimation.propagateNetworkCovariance"
    "optimization.informationObjective"
    "optimization.coverageObjective"
];

for functionIndex = 1:length(requiredFunctions)

    functionName = requiredFunctions(functionIndex);

    assert(~isempty(which(functionName)), ...
        "%s was not found.",functionName);
end

%% Synthetic tracking database

numberOfTimes = 60;
numberOfSensors = 3;
timeStep = 60;                        % s

initialPositionSigma = 2;             % km
initialVelocitySigma = 2e-3;          % km/s

initialCovariance = diag([
    initialPositionSigma^2
    initialPositionSigma^2
    initialPositionSigma^2
    initialVelocitySigma^2
    initialVelocitySigma^2
    initialVelocitySigma^2
]);

accelerationNoiseIntensity = 1e-14;   % km^2/s^3

stateTransitionMatrix = [
    eye(3), timeStep*eye(3)
    zeros(3), eye(3)
];

processNoise = ...
    estimation.isotropicProcessNoise( ...
        timeStep, ...
        accelerationNoiseIntensity);

stateTransitionHistory = ...
    repmat( ...
        stateTransitionMatrix, ...
        1,1,numberOfTimes);

processNoiseHistory = ...
    repmat( ...
        processNoise, ...
        1,1,numberOfTimes);

%% Synthetic RA/Dec-like Jacobians

measurementJacobianHistory = ...
    zeros(2,6,numberOfSensors,numberOfTimes);

sensorOneJacobian = [
    1e-3,0,0,0,0,0
    0,1e-3,0,0,0,0
];

sensorTwoJacobian = [
    0,1e-3,0,0,0,0
    0,0,1e-3,0,0,0
];

for timeIndex = 1:numberOfTimes

    measurementJacobianHistory( ...
        :,:,1,timeIndex) = ...
        sensorOneJacobian;

    measurementJacobianHistory( ...
        :,:,2,timeIndex) = ...
        sensorTwoJacobian;

    % Sensor three has valid geometry but is always blocked by LOS.
    measurementJacobianHistory( ...
        :,:,3,timeIndex) = ...
        sensorOneJacobian;
end

%% Availability histories

measurementAvailable = ...
    false(numberOfSensors,numberOfTimes);

% Sensor one is always available.
measurementAvailable(1,:) = true;

% Sensor two is available at alternating epochs.
measurementAvailable(2,1:2:end) = true;

% Sensor three is never available.
measurementAvailable(3,:) = false;

%% Measurement covariance

angleSigma = 5e-5;                    % rad

singleMeasurementCovariance = diag([
    angleSigma^2
    angleSigma^2
]);

measurementCovariances = ...
    repmat( ...
        singleMeasurementCovariance, ...
        1,1,numberOfSensors);

stateScales = [
    1
    1
    1
    1e-3
    1e-3
    1e-3
];

%% Candidate networks

noSensors = [
    0
    0
    0
];

sensorOneOnly = [
    1
    0
    0
];

sensorTwoOnly = [
    0
    1
    0
];

bothUsefulSensors = [
    1
    1
    0
];

blockedSensorOnly = [
    0
    0
    1
];

%% Propagate candidate covariances

[covarianceNone,dOptimalityNone] = ...
    estimation.propagateNetworkCovariance( ...
        initialCovariance, ...
        stateTransitionHistory, ...
        processNoiseHistory, ...
        measurementJacobianHistory, ...
        measurementAvailable, ...
        noSensors, ...
        measurementCovariances, ...
        stateScales);

[covarianceOne,dOptimalityOne] = ...
    estimation.propagateNetworkCovariance( ...
        initialCovariance, ...
        stateTransitionHistory, ...
        processNoiseHistory, ...
        measurementJacobianHistory, ...
        measurementAvailable, ...
        sensorOneOnly, ...
        measurementCovariances, ...
        stateScales);

[covarianceTwo,dOptimalityTwo] = ...
    estimation.propagateNetworkCovariance( ...
        initialCovariance, ...
        stateTransitionHistory, ...
        processNoiseHistory, ...
        measurementJacobianHistory, ...
        measurementAvailable, ...
        sensorTwoOnly, ...
        measurementCovariances, ...
        stateScales);

[covarianceBoth,dOptimalityBoth] = ...
    estimation.propagateNetworkCovariance( ...
        initialCovariance, ...
        stateTransitionHistory, ...
        processNoiseHistory, ...
        measurementJacobianHistory, ...
        measurementAvailable, ...
        bothUsefulSensors, ...
        measurementCovariances, ...
        stateScales);

[covarianceBlocked,dOptimalityBlocked] = ...
    estimation.propagateNetworkCovariance( ...
        initialCovariance, ...
        stateTransitionHistory, ...
        processNoiseHistory, ...
        measurementJacobianHistory, ...
        measurementAvailable, ...
        blockedSensorOnly, ...
        measurementCovariances, ...
        stateScales);

%% Validate covariance behavior

scoreNone = mean(dOptimalityNone);
scoreOne = mean(dOptimalityOne);
scoreTwo = mean(dOptimalityTwo);
scoreBoth = mean(dOptimalityBoth);
scoreBlocked = mean(dOptimalityBlocked);

assert(scoreOne > scoreNone, ...
    "A useful sensor did not improve information.");

assert(scoreTwo > scoreNone, ...
    "The second useful sensor did not improve information.");

assert(scoreBoth >= max(scoreOne,scoreTwo), ...
    "Two useful sensors performed worse than one useful sensor.");

assert(abs(scoreBlocked - scoreNone) < 1e-10, ...
    "A sensor without LOS changed the information score.");

blockedDifference = norm( ...
    covarianceBlocked(:) - covarianceNone(:));

assert(blockedDifference < 1e-10, ...
    "A sensor without LOS changed the covariance history.");

for timeIndex = 1:numberOfTimes

    covariance = ...
        covarianceBoth(:,:,timeIndex);

    symmetryError = ...
        norm(covariance - covariance',"fro");

    assert(symmetryError < 1e-10, ...
        "Covariance lost symmetry at index %d.", ...
        timeIndex);

    [~,positiveDefiniteFlag] = ...
        chol(covariance,"lower");

    assert(positiveDefiniteFlag == 0, ...
        "Covariance is not positive definite at index %d.", ...
        timeIndex);
end

%% Test information objective

initialCovariances = reshape( ...
    initialCovariance, ...
    6,6,1);

stateTransitionHistories = reshape( ...
    stateTransitionHistory, ...
    6,6,numberOfTimes,1);

processNoiseHistories = reshape( ...
    processNoiseHistory, ...
    6,6,numberOfTimes,1);

measurementJacobianHistories = reshape( ...
    measurementJacobianHistory, ...
    2,6,numberOfSensors,numberOfTimes,1);

measurementAvailability = reshape( ...
    measurementAvailable, ...
    numberOfSensors,numberOfTimes,1);

objectWeights = 1;

[objectiveNone,~] = ...
    optimization.informationObjective( ...
        noSensors, ...
        initialCovariances, ...
        stateTransitionHistories, ...
        processNoiseHistories, ...
        measurementJacobianHistories, ...
        measurementAvailability, ...
        measurementCovariances, ...
        stateScales, ...
        objectWeights);

[objectiveOne,~] = ...
    optimization.informationObjective( ...
        sensorOneOnly, ...
        initialCovariances, ...
        stateTransitionHistories, ...
        processNoiseHistories, ...
        measurementJacobianHistories, ...
        measurementAvailability, ...
        measurementCovariances, ...
        stateScales, ...
        objectWeights);

[objectiveBoth,~] = ...
    optimization.informationObjective( ...
        bothUsefulSensors, ...
        initialCovariances, ...
        stateTransitionHistories, ...
        processNoiseHistories, ...
        measurementJacobianHistories, ...
        measurementAvailability, ...
        measurementCovariances, ...
        stateScales, ...
        objectWeights);

assert(objectiveOne < objectiveNone, ...
    "The information objective did not prefer a useful sensor.");

assert(objectiveBoth <= objectiveOne, ...
    "The information objective did not prefer two useful sensors.");

%% Test coverage objective

[coverageObjectiveNone,coverageNone] = ...
    optimization.coverageObjective( ...
        noSensors, ...
        measurementAvailability, ...
        objectWeights);

[coverageObjectiveOne,coverageOne] = ...
    optimization.coverageObjective( ...
        sensorOneOnly, ...
        measurementAvailability, ...
        objectWeights);

[coverageObjectiveBoth,coverageBoth] = ...
    optimization.coverageObjective( ...
        bothUsefulSensors, ...
        measurementAvailability, ...
        objectWeights);

[coverageObjectiveBlocked,coverageBlocked] = ...
    optimization.coverageObjective( ...
        blockedSensorOnly, ...
        measurementAvailability, ...
        objectWeights);

assert(coverageNone == 0, ...
    "No-sensor coverage should be zero.");

assert(coverageBlocked == 0, ...
    "A blocked sensor should provide no coverage.");

assert(coverageOne == numberOfTimes, ...
    "The always-visible sensor should cover every epoch.");

assert(coverageBoth >= coverageOne, ...
    "Adding a sensor reduced coverage.");

assert(coverageObjectiveOne < coverageObjectiveNone, ...
    "The coverage objective did not prefer a useful sensor.");

assert(coverageObjectiveBoth <= coverageObjectiveOne, ...
    "Adding a sensor worsened the coverage objective.");

assert(coverageObjectiveBlocked == coverageObjectiveNone, ...
    "A blocked sensor changed the coverage objective.");

%% Print results

fprintf("Mean D-optimality, no sensors:      %.6f\n", ...
    scoreNone);

fprintf("Mean D-optimality, sensor one:      %.6f\n", ...
    scoreOne);

fprintf("Mean D-optimality, sensor two:      %.6f\n", ...
    scoreTwo);

fprintf("Mean D-optimality, both sensors:    %.6f\n", ...
    scoreBoth);

fprintf("Mean D-optimality, blocked sensor:  %.6f\n", ...
    scoreBlocked);

fprintf("Coverage epochs, no sensors:        %d\n", ...
    coverageNone);

fprintf("Coverage epochs, sensor one:        %d\n", ...
    coverageOne);

fprintf("Coverage epochs, both sensors:      %d\n", ...
    coverageBoth);

fprintf("testNetworkCovariance passed.\n");