%% testFinalLunarDemCompatibility
% Validate Final_Lunar_DEM.mat against the current lunar-surface workflow.
%
% The test verifies:
%   1. The file is a finite global 2:1 raster.
%   2. The 2880-by-5760 raster convention is north-to-south,
%      east-positive, cell-centered, and 0.0625 deg/pixel.
%   3. A translated triaxial ellipsoid can be fit with lsqnonlin using
%      p = [x0,y0,z0,a,b,c].
%   4. Removing the fitted ellipsoid produces a lower-RMS residual terrain
%      field while preserving the physical radial surface exactly.
%   5. The workflow-compatible interpolant covers the poles and periodic
%      longitude seam.
%   6. The DEM works with the current topographic, terrain-horizon,
%      RA/Dec measurement, and measurement-Jacobian functions.
%
% The physical decomposition is
%
%   H_residual(lat,lon)
%       = H_current(lat,lon) - H_ellipsoid(lat,lon)
%
% with
%
%   H_ellipsoid = r_ellipsoid - R_Moon.
%
% Therefore
%
%   R_Moon + H_current
%       = r_ellipsoid + H_residual.
%
% The current workflow can continue to use the sphere-referenced radial
% height interpolant without loss of triaxial geometry.

clear;
close all;
clc;

%% ========================================================================
%  Project paths
%  ========================================================================

testDirectory = ...
    fileparts(mfilename("fullpath"));

projectRoot = ...
    fileparts(testDirectory);

sourceDirectory = ...
    fullfile(projectRoot,"src");

dataDirectory = ...
    fullfile(projectRoot,"data");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

requiredFunctions = [ ...
    "digitalElevationModel.loadTriaxialLunarDem"
    "digitalElevationModel.fitTriaxialEllipsoid"
    "digitalElevationModel.triaxialEllipsoidRadius"
    "digitalElevationModel.buildMaximumTerrainHorizonDatabase"
    "referenceFrames.topographic"
    "referenceFrames.moonRotating"
    "measurements.surfaceRaDecMeasurement"
    "measurements.surfaceRaDecJacobian"
    "lsqnonlin"
];

for functionIndex = 1:length(requiredFunctions)

    functionName = ...
        requiredFunctions(functionIndex);

    assert(~isempty(which(functionName)), ...
        "%s was not found.",functionName);
end

%% ========================================================================
%  Load new DEM
%  ========================================================================

moonRadiusKm = ...
    1737.4;

newDemPath = ...
    fullfile( ...
        dataDirectory, ...
        "Final_Lunar_DEM.mat");

assert(isfile(newDemPath), ...
    [ ...
    "Final_Lunar_DEM.mat was not found. Copy the new DEM to:\n%s" ...
    ], ...
    newDemPath);

fileVariables = ...
    whos("-file",newDemPath);

variableNames = ...
    string({fileVariables.name});

assert(any(variableNames == "DEM"), ...
    "Final_Lunar_DEM.mat must contain a numeric variable named DEM.");

rawData = ...
    load(newDemPath,"DEM");

rawDem = ...
    double(rawData.DEM);

[numberOfLatitudes,numberOfLongitudes] = ...
    size(rawDem);

assert(numberOfLongitudes == 2*numberOfLatitudes, ...
    "The new DEM is not a global 2:1 raster.");

assert(all(isfinite(rawDem),"all"), ...
    "The new DEM contains nonfinite elevations.");

latitudeSpacingDeg = ...
    180/numberOfLatitudes;

longitudeSpacingDeg = ...
    360/numberOfLongitudes;

assert(abs(latitudeSpacingDeg-longitudeSpacingDeg) < 1e-12, ...
    "The new DEM does not have equal angular sampling.");

%% ========================================================================
%  Build workflow interpolant and fit reference ellipsoid
%  ========================================================================

[dem,triaxialModel] = ...
    digitalElevationModel.loadTriaxialLunarDem( ...
        string(newDemPath), ...
        moonRadiusKm, ...
        24, ...
        48);

assert(isa(dem,"griddedInterpolant"), ...
    "The DEM loader did not return a griddedInterpolant.");

%% ========================================================================
%  Raster and orientation checks
%  ========================================================================

assert(isequal( ...
    triaxialModel.rawRasterSize, ...
    [numberOfLatitudes,numberOfLongitudes]), ...
    "Stored raster metadata is inconsistent.");

assert(abs(triaxialModel.latitudeSpacingDeg-0.0625) < 1e-12, ...
    "Unexpected latitude resolution for Final_Lunar_DEM.mat.");

assert(abs(triaxialModel.longitudeSpacingDeg-0.0625) < 1e-12, ...
    "Unexpected longitude resolution for Final_Lunar_DEM.mat.");

assert(triaxialModel.rowOrder == "north_to_south", ...
    "The expected DEM row orientation changed.");

% The global minimum should lie in the southern far-side basin region.
% This is a useful orientation sanity check for this particular global DEM.
assert(triaxialModel.rawMinimumLatitudeDeg < -50, ...
    "DEM row orientation appears to be reversed.");

assert(triaxialModel.rawMinimumLongitudeDeg > 150 && ...
    triaxialModel.rawMinimumLongitudeDeg < 230, ...
    "DEM longitude orientation appears inconsistent with the expected map.");

%% ========================================================================
%  Triaxial-fit checks
%  ========================================================================

centerOffsetKm = ...
    triaxialModel.centerOffsetKm;

semiAxesKm = ...
    triaxialModel.semiAxesKm;

assert(all(isfinite(centerOffsetKm)) && ...
    all(isfinite(semiAxesKm)), ...
    "The triaxial fit contains nonfinite parameters.");

assert(all(abs(centerOffsetKm) < 5), ...
    "The fitted ellipsoid center offset is unexpectedly large.");

assert(all(semiAxesKm > 1730) && ...
    all(semiAxesKm < 1745), ...
    "The fitted lunar semi-axes are outside a physically plausible range.");

assert(triaxialModel.axisSpreadKm > 0.5, ...
    [ ...
    "The uploaded DEM does not contain a measurable triaxial figure. " ...
    "It may already be an ellipsoid-referenced residual DEM." ...
    ]);

assert(triaxialModel.axisSpreadKm < 10, ...
    "The fitted triaxial axis spread is implausibly large.");

assert(triaxialModel.residualHeightRmsKm < ...
    triaxialModel.rawHeightRmsKm, ...
    "Removing the fitted ellipsoid did not reduce global height RMS.");

assert(triaxialModel.maximumReconstructionErrorKm < 1e-10, ...
    "Ellipsoid + residual does not reconstruct the source DEM.");

%% ========================================================================
%  Interpolant coverage and periodicity
%  ========================================================================

latitudeGrid = ...
    dem.GridVectors{1}(:);

longitudeGrid = ...
    dem.GridVectors{2}(:);

assert(abs(latitudeGrid(1)+pi/2) < 1e-12 && ...
    abs(latitudeGrid(end)-pi/2) < 1e-12, ...
    "Workflow DEM does not include both poles.");

assert(abs(longitudeGrid(1)) < 1e-12 && ...
    abs(longitudeGrid(end)-2*pi) < 1e-12, ...
    "Workflow DEM does not include the periodic 0/360 seam.");

sampleLatitudes = ...
    deg2rad([ ...
    -89.505332
    -87.0
    -82.0
    -75.5
    ]);

sampleLongitudes = ...
    deg2rad([ ...
    102.857143
    0
    180
    359.5
    ]);

sampleElevations = ...
    dem(sampleLatitudes,sampleLongitudes);

assert(all(isfinite(sampleElevations)), ...
    "The DEM returned nonfinite south-polar elevations.");

seamLatitudes = ...
    deg2rad([-89,-85,-80,-76]);

seamZero = ...
    dem(seamLatitudes,zeros(size(seamLatitudes)));

seamTwoPi = ...
    dem(seamLatitudes,2*pi*ones(size(seamLatitudes)));

assert(max(abs(seamZero-seamTwoPi)) < 1e-12, ...
    "The DEM longitude seam is not periodic.");

%% ========================================================================
%  Explicit ellipsoid/residual reconstruction at workflow sample points
%  ========================================================================

ellipsoidRadiusKm = ...
    digitalElevationModel.triaxialEllipsoidRadius( ...
        sampleLatitudes, ...
        sampleLongitudes, ...
        triaxialModel.centerOffsetKm, ...
        triaxialModel.semiAxesKm);

ellipsoidHeightKm = ...
    ellipsoidRadiusKm - moonRadiusKm;

residualHeightKm = ...
    sampleElevations - ellipsoidHeightKm;

surfaceRadiusFromCurrentDemKm = ...
    moonRadiusKm + sampleElevations;

surfaceRadiusFromTriaxialDecompositionKm = ...
    ellipsoidRadiusKm + residualHeightKm;

assert(max(abs( ...
    surfaceRadiusFromCurrentDemKm - ...
    surfaceRadiusFromTriaxialDecompositionKm)) < 1e-10, ...
    "Triaxial residual decomposition changed the physical lunar radius.");

%% ========================================================================
%  Topographic-frame compatibility
%  ========================================================================

sensorLatitude = ...
    sampleLatitudes(1);

sensorLongitude = ...
    sampleLongitudes(1);

sensorRotatingState = ...
    referenceFrames.topographic( ...
        zeros(6,1), ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        moonRadiusKm, ...
        "toRotating");

expectedSensorRadiusKm = ...
    moonRadiusKm + ...
    dem(sensorLatitude,sensorLongitude);

assert(abs( ...
    norm(sensorRotatingState(1:3))- ...
    expectedSensorRadiusKm) < 1e-10, ...
    "Topographic sensor radius is inconsistent with the new DEM.");

[localState,localMeasurement] = ...
    referenceFrames.topographic( ...
        sensorRotatingState, ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        moonRadiusKm, ...
        "fromRotating");

assert(norm(localState) < 1e-10, ...
    "Topographic round-trip failed at the new DEM surface.");

assert(abs(localMeasurement(3)) < 1e-10, ...
    "Surface sensor did not return zero local range.");

%% ========================================================================
%  Terrain-horizon compatibility
%  ========================================================================

candidateLatitudes = ...
    sampleLatitudes;

candidateLongitudes = ...
    sampleLongitudes;

[horizonAzimuths,maximumTerrainElevation,maximumFeatureRange, ...
    sensorElevations,maximumFeatureElevations] = ...
    digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        100, ...
        5, ...
        deg2rad(10), ...
        moonRadiusKm);

assert(all(isfinite(maximumTerrainElevation),"all"), ...
    "Terrain horizon contains nonfinite angles with the new DEM.");

assert(all(isfinite(maximumFeatureRange),"all"), ...
    "Terrain horizon contains nonfinite feature ranges.");

assert(all(isfinite(sensorElevations)), ...
    "Terrain horizon returned nonfinite sensor elevations.");

assert(all(isfinite(maximumFeatureElevations),"all"), ...
    "Terrain horizon returned nonfinite feature elevations.");

assert(max(abs( ...
    maximumTerrainElevation(:,1)- ...
    maximumTerrainElevation(:,end))) < 1e-12, ...
    "Terrain horizon is not periodic in azimuth.");

assert(abs(horizonAzimuths(1)) < 1e-12 && ...
    abs(horizonAzimuths(end)-2*pi) < 1e-12, ...
    "Terrain horizon azimuth grid is not periodic.");

%% ========================================================================
%  RA/Dec model and Jacobian compatibility
%  ========================================================================

time = ...
    0;

theta0 = ...
    0;

angularRate = ...
    2*pi/(27.321661*86400);

sensorMciState = ...
    referenceFrames.moonRotating( ...
        sensorRotatingState, ...
        time, ...
        theta0, ...
        angularRate, ...
        "toInertial");

targetState = [ ...
    sensorMciState(1:3) + [120;80;150]
    0
    0
    0
];

measurement = ...
    measurements.surfaceRaDecMeasurement( ...
        targetState, ...
        time, ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        moonRadiusKm, ...
        theta0, ...
        angularRate);

measurementJacobian = ...
    measurements.surfaceRaDecJacobian( ...
        targetState, ...
        time, ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        moonRadiusKm, ...
        theta0, ...
        angularRate);

assert(all(isfinite(measurement)), ...
    "RA/Dec measurement is nonfinite with the new DEM.");

assert(all(isfinite(measurementJacobian),"all"), ...
    "RA/Dec Jacobian is nonfinite with the new DEM.");

%% ========================================================================
%  Summary
%  ========================================================================

fprintf("\n");
fprintf("Final lunar DEM compatibility summary\n");
fprintf("-------------------------------------\n");
fprintf("Raster size:             %d x %d\n", ...
    numberOfLatitudes,numberOfLongitudes);
fprintf("Angular resolution:      %.4f deg\n", ...
    latitudeSpacingDeg);
fprintf("Raw elevation range:     [%.3f, %.3f] km\n", ...
    triaxialModel.rawMinimumElevationKm, ...
    triaxialModel.rawMaximumElevationKm);
fprintf("Global minimum location: %.3f deg, %.3f deg E\n", ...
    triaxialModel.rawMinimumLatitudeDeg, ...
    triaxialModel.rawMinimumLongitudeDeg);

fprintf("\nFitted center offset [km]\n");
fprintf("  x0 = % .6f\n",centerOffsetKm(1));
fprintf("  y0 = % .6f\n",centerOffsetKm(2));
fprintf("  z0 = % .6f\n",centerOffsetKm(3));

fprintf("\nFitted semi-axes [km]\n");
fprintf("  a  = %.6f\n",semiAxesKm(1));
fprintf("  b  = %.6f\n",semiAxesKm(2));
fprintf("  c  = %.6f\n",semiAxesKm(3));
fprintf("Axis spread:              %.6f km\n", ...
    triaxialModel.axisSpreadKm);

fprintf("\nHeight decomposition\n");
fprintf("  Raw RMS:                %.6f km\n", ...
    triaxialModel.rawHeightRmsKm);
fprintf("  Ellipsoid signal RMS:   %.6f km\n", ...
    triaxialModel.ellipsoidSignalRmsKm);
fprintf("  Residual RMS:           %.6f km\n", ...
    triaxialModel.residualHeightRmsKm);
fprintf("  Reconstruction error:   %.3e km\n", ...
    triaxialModel.maximumReconstructionErrorKm);

fprintf("\n");
fprintf("Global raster checks:       passed\n");
fprintf("Triaxial least-squares fit: passed\n");
fprintf("Ellipsoid decomposition:    passed\n");
fprintf("Periodic interpolation:     passed\n");
fprintf("Topographic frame:          passed\n");
fprintf("Terrain horizon:            passed\n");
fprintf("RA/Dec measurement model:   passed\n");
fprintf("\n");
fprintf("testFinalLunarDemCompatibility passed.\n");
