%% testThreeDayTrackingPropagation
% Regression test for the production three-day / ten-minute tracking arc.
%
% This specifically protects against numerical drift between the canonical
% truth propagation and the nominal state history generated while the STM is
% precomputed. The production database requires these histories to represent
% the same nominal trajectory.

clear;
close all;
clc;

%% ========================================================================
%  Project paths
%  ========================================================================

testDirectory = ...
    fileparts(mfilename("fullpath"));

projectRoot = ...
    fileparts(testDirectory);

sourceDirectory = ...
    fullfile(projectRoot,"src");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

%% ========================================================================
%  Constants and production time grid
%  ========================================================================

moonRadiusKm = ...
    1737.4;

moonMuKm3S2 = ...
    4902.800066;

trackingStepSeconds = ...
    10*60;

finalTimeSeconds = ...
    3*24*3600;

observationTimes = ...
    (trackingStepSeconds:trackingStepSeconds:finalTimeSeconds).';

assert(numel(observationTimes) == 432, ...
    "Three-day production grid must contain 432 optimization epochs.");

%% ========================================================================
%  Representative circular lunar orbit
%  ========================================================================

orbitRadiusKm = ...
    moonRadiusKm + 100;

circularSpeedKmS = ...
    sqrt(moonMuKm3S2/orbitRadiusKm);

initialState = [ ...
    orbitRadiusKm
    0
    0
    0
    circularSpeedKmS
    0
    ];

%% ========================================================================
%  Minimal synthetic DEM and one representative sensor
%  ========================================================================

latitudeGrid = ...
    deg2rad([-90,0,90]);

longitudeGrid = ...
    deg2rad([0,180,360]);

zeroElevationKm = ...
    zeros(3,3);

dem = ...
    griddedInterpolant( ...
        {latitudeGrid,longitudeGrid}, ...
        zeroElevationKm, ...
        "linear", ...
        "nearest");

candidateLatitudes = ...
    deg2rad(-85);

candidateLongitudes = ...
    deg2rad(45);

%% ========================================================================
%  Canonical truth propagation
%  ========================================================================

truthTimes = [ ...
    0
    observationTimes
    ];

[propagatedTruthTimes,truthStates] = ...
    orbitDynamics.propagateLunarOrbit( ...
        initialState, ...
        truthTimes, ...
        moonMu=moonMuKm3S2);

assert(max(abs(propagatedTruthTimes-truthTimes)) < 1e-9, ...
    "Canonical truth time grid changed.");

truthObservationStates = ...
    truthStates(2:end,:).';

%% ========================================================================
%  Tracking / STM precompute
%  ========================================================================

[referenceStates, ...
    stateTransitionHistory, ...
    processNoiseHistory, ...
    measurementJacobianHistory] = ...
    optimization.precomputeTrackingData( ...
        0, ...
        observationTimes, ...
        initialState, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        0, ...
        1e-15, ...
        moonMuKm3S2, ...
        moonRadiusKm, ...
        0, ...
        2*pi/(27.321661*86400));

%% ========================================================================
%  Regression checks
%  ========================================================================

maximumReferenceTruthError = ...
    max(abs(referenceStates-truthObservationStates),[],"all");

assert(maximumReferenceTruthError < 1e-12, ...
    "Three-day nominal tracking states do not reproduce canonical truth.");

assert(isequal(size(referenceStates),[6,432]), ...
    "Reference-state history has unexpected dimensions.");

assert(isequal(size(stateTransitionHistory),[6,6,432]), ...
    "STM history has unexpected dimensions.");

assert(isequal(size(processNoiseHistory),[6,6,432]), ...
    "Process-noise history has unexpected dimensions.");

assert(isequal(size(measurementJacobianHistory),[2,6,1,432]), ...
    "Measurement-Jacobian history has unexpected dimensions.");

assert(all(isfinite(referenceStates),"all"), ...
    "Reference-state history contains nonfinite values.");

assert(all(isfinite(stateTransitionHistory),"all"), ...
    "STM history contains nonfinite values.");

assert(all(isfinite(processNoiseHistory),"all"), ...
    "Process-noise history contains nonfinite values.");

assert(all(isfinite(measurementJacobianHistory),"all"), ...
    "Measurement-Jacobian history contains nonfinite values.");

fprintf("\n");
fprintf("Three-day tracking propagation regression\n");
fprintf("-----------------------------------------\n");
fprintf("Tracking horizon:              %.1f hr\n",finalTimeSeconds/3600);
fprintf("Tracking cadence:              %.1f min\n",trackingStepSeconds/60);
fprintf("Optimization epochs:           %d\n",numel(observationTimes));
fprintf("Maximum reference/truth error: %.3e\n",maximumReferenceTruthError);
fprintf("\n");
fprintf("testThreeDayTrackingPropagation passed.\n");
