%% testTerrainAwareNetworkObjectives
% Test terrain-aware coverage and information objectives.
%
% Workflow:
%   1. Construct representative lunar surface candidates.
%   2. Build the static terrain-horizon database.
%   3. Precompute dynamics, STMs, process noise, RA/Dec Jacobians, and
%      geometric LOS using optimization.precomputeTrackingData.
%   4. Replace the geometric LOS gates with terrain-aware gates.
%   5. Evaluate coverage and EKF D-optimality using the existing
%      optimization objective functions.
%
% This test uses a fixed representative P0 for each object. It plays the
% same role as the fixed IOD covariance in the full optimization pipeline.

clear;
close all;
clc;

%% Project paths

testDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testDirectory);
sourceDirectory = fullfile(projectRoot, "src");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s", sourceDirectory);

addpath(sourceDirectory);
rehash path;

requiredFunctions = [
    "orbitDynamics.lunarStateAndStmDynamics"
    "referenceFrames.moonRotating"
    "referenceFrames.topographic"
    "measurements.surfaceRaDecJacobian"
    "estimation.isotropicProcessNoise"
    "estimation.propagateNetworkCovariance"
    "optimization.precomputeTrackingData"
    "optimization.informationObjective"
    "optimization.coverageObjective"
    "digitalElevationModel.buildMaximumTerrainHorizonDatabase"
    "optimization.buildTerrainAwareLosDatabase"
];

for functionIndex = 1:length(requiredFunctions)

    functionName = requiredFunctions(functionIndex);

    assert(~isempty(which(functionName)), ...
        "%s was not found.", functionName);
end

%% Load and process DEM

demPath = fullfile( ...
    projectRoot, ...
    "data", ...
    "new_lunar_interpolant_model.mat");

if ~isfile(demPath)

    demPath = fullfile( ...
        testDirectory, ...
        "new_lunar_interpolant_model.mat");
end

assert(isfile(demPath), ...
    "DEM file was not found.");

demData = load(demPath, "F");

assert(isfield(demData, "F"), ...
    "DEM file must contain a variable named F.");

assert(isa(demData.F, "griddedInterpolant"), ...
    "F must be a griddedInterpolant.");

sourceDem = demData.F;

latitudeGrid = deg2rad( ...
    sourceDem.GridVectors{1}(:));

longitudeGrid = deg2rad( ...
    sourceDem.GridVectors{2}(:));

elevationGrid = sourceDem.Values;

if longitudeGrid(end) < 2*pi

    longitudeGrid = [
        longitudeGrid
        2*pi
    ];

    elevationGrid = [
        elevationGrid, ...
        elevationGrid(:,1)
    ];
end

dem = griddedInterpolant( ...
    {latitudeGrid, longitudeGrid}, ...
    elevationGrid, ...
    "linear", ...
    "nearest");

%% Lunar constants

moonRadius = 1737.4;                  % km
moonMu = 4902.800066;                 % km^3/s^2

moonSiderealPeriod = ...
    27.321661 * 86400;                % s

moonAngularRate = ...
    2*pi / moonSiderealPeriod;        % rad/s

theta0 = 0;                           % rad

%% Measurement and filter settings

minimumElevation = deg2rad(0);
horizonMargin = deg2rad(0.1);

rightAscensionSigma = ...
    deg2rad(1/3600);                  % 1 arcsecond

declinationSigma = ...
    deg2rad(1/3600);                  % 1 arcsecond

measurementCovariance = diag([
    rightAscensionSigma^2
    declinationSigma^2
]);

accelerationNoiseIntensity = ...
    1e-15;                            % km^2/s^3

stateScales = [
    1
    1
    1
    1e-3
    1e-3
    1e-3
];

%% Representative candidate sensor set

% This is the same 24-sensor sample used in the multi-RSO direct
% ray-clearance test.

sensorLatitudeLevels = [
    -89.5
    -87.0
    -84.0
    -81.0
    -78.0
    -75.5
];

baseLongitudes = [
    0
    90
    180
    270
];

numberOfLatitudeLevels = ...
    length(sensorLatitudeLevels);

numberOfLongitudesPerLevel = ...
    length(baseLongitudes);

numberOfCandidates = ...
    numberOfLatitudeLevels * ...
    numberOfLongitudesPerLevel;

candidateLatitudes = ...
    zeros(numberOfCandidates,1);

candidateLongitudes = ...
    zeros(numberOfCandidates,1);

candidateIndex = 0;

for latitudeIndex = 1:numberOfLatitudeLevels

    longitudeOffset = ...
        15 * (latitudeIndex - 1);

    for longitudeIndex = 1:numberOfLongitudesPerLevel

        candidateIndex = ...
            candidateIndex + 1;

        candidateLatitudes(candidateIndex) = ...
            deg2rad( ...
                sensorLatitudeLevels(latitudeIndex));

        candidateLongitudes(candidateIndex) = ...
            deg2rad( ...
                mod( ...
                    baseLongitudes(longitudeIndex) + ...
                    longitudeOffset, ...
                    360));
    end
end

fprintf( ...
    "Candidate surface sensors: %d\n", ...
    numberOfCandidates);

%% Build static terrain-horizon database

maximumTerrainRange = 100;            % km
terrainRangeStep = 0.5;               % km
horizonAzimuthStep = deg2rad(1);      % rad

terrainTimer = tic;

[ ...
    horizonAzimuths, ...
    maximumTerrainElevation, ...
    maximumFeatureRange, ...
    sensorElevations, ...
    maximumFeatureElevations ...
] = digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
    candidateLatitudes, ...
    candidateLongitudes, ...
    dem, ...
    maximumTerrainRange, ...
    terrainRangeStep, ...
    horizonAzimuthStep, ...
    moonRadius);

terrainBuildTime = toc(terrainTimer);

assert(all(isfinite(maximumTerrainElevation), "all"), ...
    "The terrain-horizon database contains nonfinite values.");

assert(all(isfinite(maximumFeatureRange), "all"), ...
    "The terrain feature ranges contain nonfinite values.");

assert(all(isfinite(sensorElevations)), ...
    "The sensor elevations contain nonfinite values.");

assert(all(isfinite(maximumFeatureElevations), "all"), ...
    "The terrain feature elevations contain nonfinite values.");

fprintf( ...
    "Terrain database build time: %.2f seconds\n", ...
    terrainBuildTime);

%% Define RSO set

objectNames = [
    "LRO-like 50 km polar"
    "Chandrayaan-1-like 100 km polar"
    "200 km, 60 deg inclined"
];

orbitAltitudes = [
    50
    100
    200
];

orbitInclinations = deg2rad([
    90
    90
    60
]);

orbitAscendingNodes = deg2rad([
    37
    120
    250
]);

numberOfObjects = ...
    length(orbitAltitudes);

%% Construct initial RSO states

initialStates = ...
    zeros(6, numberOfObjects);

rotationZ = @(angle) [
     cos(angle), -sin(angle), 0
     sin(angle),  cos(angle), 0
              0,           0, 1
];

rotationX = @(angle) [
    1,          0,           0
    0, cos(angle), -sin(angle)
    0, sin(angle),  cos(angle)
];

for objectIndex = 1:numberOfObjects

    orbitRadius = ...
        moonRadius + ...
        orbitAltitudes(objectIndex);

    circularVelocity = ...
        sqrt(moonMu / orbitRadius);

    perifocalToMoonInertial = ...
        rotationZ( ...
            orbitAscendingNodes(objectIndex)) * ...
        rotationX( ...
            orbitInclinations(objectIndex));

    initialStates(:,objectIndex) = [
        perifocalToMoonInertial * ...
            [orbitRadius; 0; 0]
        perifocalToMoonInertial * ...
            [0; circularVelocity; 0]
    ];
end

%% Observation arc

initialTime = 0;                      % s
observationArc = 6 * 3600;            % s
outputStep = 30;                      % s

observationTimes = ...
    (outputStep:outputStep:observationArc).';

numberOfTimes = ...
    length(observationTimes);

%% Allocate tracking database

referenceStateHistories = zeros( ...
    6, ...
    numberOfTimes, ...
    numberOfObjects);

stateTransitionHistories = zeros( ...
    6, ...
    6, ...
    numberOfTimes, ...
    numberOfObjects);

processNoiseHistories = zeros( ...
    6, ...
    6, ...
    numberOfTimes, ...
    numberOfObjects);

measurementJacobianHistories = zeros( ...
    2, ...
    6, ...
    numberOfCandidates, ...
    numberOfTimes, ...
    numberOfObjects);

geometricAvailability = false( ...
    numberOfCandidates, ...
    numberOfTimes, ...
    numberOfObjects);

precomputedElevations = zeros( ...
    numberOfCandidates, ...
    numberOfTimes, ...
    numberOfObjects);

%% Precompute dynamics and measurement Jacobians

precomputeTimer = tic;

for objectIndex = 1:numberOfObjects

    [ ...
        referenceStateHistory, ...
        stateTransitionHistory, ...
        processNoiseHistory, ...
        measurementJacobianHistory, ...
        objectGeometricAvailability, ...
        objectTopographicElevation ...
    ] = optimization.precomputeTrackingData( ...
        initialTime, ...
        observationTimes, ...
        initialStates(:,objectIndex), ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        minimumElevation, ...
        accelerationNoiseIntensity, ...
        moonMu, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate);

    referenceStateHistories(:,:,objectIndex) = ...
        referenceStateHistory;

    stateTransitionHistories(:,:,:,objectIndex) = ...
        stateTransitionHistory;

    processNoiseHistories(:,:,:,objectIndex) = ...
        processNoiseHistory;

    measurementJacobianHistories(:,:,:,:,objectIndex) = ...
        measurementJacobianHistory;

    geometricAvailability(:,:,objectIndex) = ...
        objectGeometricAvailability;

    precomputedElevations(:,:,objectIndex) = ...
        objectTopographicElevation;
end

precomputeTime = toc(precomputeTimer);

fprintf( ...
    "Tracking database build time: %.2f seconds\n", ...
    precomputeTime);

%% Apply terrain-aware LOS filtering

[ ...
    terrainAvailability, ...
    targetAzimuths, ...
    terrainTargetElevations, ...
    targetRanges, ...
    terrainLimitingElevations ...
] = optimization.buildTerrainAwareLosDatabase( ...
    observationTimes, ...
    referenceStateHistories, ...
    candidateLatitudes, ...
    candidateLongitudes, ...
    dem, ...
    horizonAzimuths, ...
    maximumTerrainElevation, ...
    minimumElevation, ...
    horizonMargin, ...
    moonRadius, ...
    theta0, ...
    moonAngularRate);

assert(all(isfinite(targetAzimuths), "all"), ...
    "The target azimuths contain nonfinite values.");

assert(all(isfinite(targetRanges), "all"), ...
    "The target ranges contain nonfinite values.");

assert(all(isfinite(terrainLimitingElevations), "all"), ...
    "The terrain limiting elevations contain nonfinite values.");

%% Verify precomputeTrackingData consistency

elevationDifference = max( ...
    abs( ...
        precomputedElevations - ...
        terrainTargetElevations), ...
    [], ...
    "all");

assert(elevationDifference < 1e-9, ...
    "The two topographic elevation calculations are inconsistent.");

assert( ...
    ~any( ...
        terrainAvailability & ...
        ~geometricAvailability, ...
        "all"), ...
    "Terrain filtering created a geometrically invalid measurement.");

terrainRejectedMeasurements = ...
    geometricAvailability & ...
    ~terrainAvailability;

%% Fixed representative initial covariance

% This is held fixed across every candidate-network evaluation, matching
% the representative-IOD P0 workflow used by testLroCandidateNetwork.

initialPositionSigma = 2;             % km
initialVelocitySigma = 2e-3;          % km/s

fixedInitialCovariance = diag([
    initialPositionSigma^2
    initialPositionSigma^2
    initialPositionSigma^2
    initialVelocitySigma^2
    initialVelocitySigma^2
    initialVelocitySigma^2
]);

initialCovariances = repmat( ...
    fixedInitialCovariance, ...
    1, ...
    1, ...
    numberOfObjects);

objectWeights = ...
    ones(numberOfObjects,1);

%% Identify terrain-sensitive sensor

terrainLossCounts = reshape( ...
    sum( ...
        terrainRejectedMeasurements, ...
        [2, 3]), ...
    numberOfCandidates, ...
    1);

[maximumTerrainLoss, terrainSensitiveSensor] = ...
    max(terrainLossCounts);

assert(maximumTerrainLoss > 0, ...
    "None of the candidate sensors lose measurements to terrain.");

%% Select complementary sensor using terrain-aware coverage

pairCoverageScores = ...
    -inf(numberOfCandidates,1);

for candidateIndex = 1:numberOfCandidates

    if candidateIndex == terrainSensitiveSensor
        continue;
    end

    trialSelection = ...
        false(numberOfCandidates,1);

    trialSelection(terrainSensitiveSensor) = true;
    trialSelection(candidateIndex) = true;

    [trialCoverageObjective, ~] = ...
        optimization.coverageObjective( ...
            trialSelection, ...
            terrainAvailability, ...
            objectWeights);

    pairCoverageScores(candidateIndex) = ...
        -trialCoverageObjective;
end

[~, complementarySensor] = ...
    max(pairCoverageScores);

assert(complementarySensor ~= terrainSensitiveSensor, ...
    "The complementary sensor selection is invalid.");

fprintf("\nSelected test sensors\n");

fprintf( ...
    "  Terrain-sensitive sensor: %d, %.3f deg lat, %.3f deg lon\n", ...
    terrainSensitiveSensor, ...
    rad2deg(candidateLatitudes(terrainSensitiveSensor)), ...
    rad2deg(candidateLongitudes(terrainSensitiveSensor)));

fprintf( ...
    "  Terrain-rejected opportunities: %d\n", ...
    maximumTerrainLoss);

fprintf( ...
    "  Complementary sensor:     %d, %.3f deg lat, %.3f deg lon\n", ...
    complementarySensor, ...
    rad2deg(candidateLatitudes(complementarySensor)), ...
    rad2deg(candidateLongitudes(complementarySensor)));

%% Candidate networks

networkNames = [
    "No sensors"
    "Terrain-sensitive sensor"
    "Complementary sensor"
    "Two-sensor network"
];

networkSelections = false( ...
    numberOfCandidates, ...
    4);

networkSelections( ...
    terrainSensitiveSensor, ...
    2) = true;

networkSelections( ...
    complementarySensor, ...
    3) = true;

networkSelections( ...
    [terrainSensitiveSensor, complementarySensor], ...
    4) = true;

numberOfNetworks = ...
    size(networkSelections,2);

%% Allocate objective results

geometricInformationScores = ...
    zeros(numberOfNetworks,1);

terrainInformationScores = ...
    zeros(numberOfNetworks,1);

geometricCoverageScores = ...
    zeros(numberOfNetworks,1);

terrainCoverageScores = ...
    zeros(numberOfNetworks,1);

geometricInformationByObject = ...
    zeros(numberOfNetworks, numberOfObjects);

terrainInformationByObject = ...
    zeros(numberOfNetworks, numberOfObjects);

geometricCoverageByObject = ...
    zeros(numberOfNetworks, numberOfObjects);

terrainCoverageByObject = ...
    zeros(numberOfNetworks, numberOfObjects);

%% Evaluate geometric and terrain-aware objectives

for networkIndex = 1:numberOfNetworks

    selectedSensors = ...
        networkSelections(:,networkIndex);

    [geometricInformationObjective, ...
        geometricObjectScores] = ...
        optimization.informationObjective( ...
            selectedSensors, ...
            initialCovariances, ...
            stateTransitionHistories, ...
            processNoiseHistories, ...
            measurementJacobianHistories, ...
            geometricAvailability, ...
            measurementCovariance, ...
            stateScales, ...
            objectWeights);

    [terrainInformationObjective, ...
        terrainObjectScores] = ...
        optimization.informationObjective( ...
            selectedSensors, ...
            initialCovariances, ...
            stateTransitionHistories, ...
            processNoiseHistories, ...
            measurementJacobianHistories, ...
            terrainAvailability, ...
            measurementCovariance, ...
            stateScales, ...
            objectWeights);

    geometricInformationScores(networkIndex) = ...
        -geometricInformationObjective;

    terrainInformationScores(networkIndex) = ...
        -terrainInformationObjective;

    geometricInformationByObject(networkIndex,:) = ...
        geometricObjectScores.';

    terrainInformationByObject(networkIndex,:) = ...
        terrainObjectScores.';

    [geometricCoverageObjective, ...
        geometricObjectCoverage] = ...
        optimization.coverageObjective( ...
            selectedSensors, ...
            geometricAvailability, ...
            objectWeights);

    [terrainCoverageObjective, ...
        terrainObjectCoverage] = ...
        optimization.coverageObjective( ...
            selectedSensors, ...
            terrainAvailability, ...
            objectWeights);

    geometricCoverageScores(networkIndex) = ...
        -geometricCoverageObjective;

    terrainCoverageScores(networkIndex) = ...
        -terrainCoverageObjective;

    geometricCoverageByObject(networkIndex,:) = ...
        geometricObjectCoverage.';

    terrainCoverageByObject(networkIndex,:) = ...
        terrainObjectCoverage.';
end

%% Validate terrain-aware objective behavior

%% Validate terrain-aware objective behavior

comparisonTolerance = 1e-8;

assert(all( ...
    terrainCoverageByObject <= ...
    geometricCoverageByObject, ...
    "all"), ...
    "Terrain filtering increased coverage.");

assert(all( ...
    terrainInformationByObject <= ...
    geometricInformationByObject + ...
    comparisonTolerance, ...
    "all"), ...
    "Terrain filtering increased information.");

assert(all( ...
    geometricCoverageByObject(1,:) == 0), ...
    "No-sensor geometric coverage should be zero.");

assert(all( ...
    terrainCoverageByObject(1,:) == 0), ...
    "No-sensor terrain coverage should be zero.");

assert( ...
    abs( ...
        geometricInformationScores(1) - ...
        terrainInformationScores(1)) < ...
    comparisonTolerance, ...
    "Terrain changed the no-sensor information score.");

assert( ...
    any( ...
        terrainCoverageByObject(2,:) < ...
        geometricCoverageByObject(2,:)), ...
    "The terrain-sensitive sensor did not lose network coverage.");

assert(all( ...
    terrainCoverageByObject(4,:) >= ...
    terrainCoverageByObject(2,:)), ...
    "Adding the complementary sensor reduced coverage.");

assert(all( ...
    terrainCoverageByObject(4,:) >= ...
    terrainCoverageByObject(3,:)), ...
    "The two-sensor network underperformed the complementary sensor.");

assert( ...
    terrainInformationScores(4) >= ...
    max(terrainInformationScores([2, 3])) - ...
    comparisonTolerance, ...
    "Adding the complementary sensor reduced information.");

%% Verify pair covariance histories

for objectIndex = 1:numberOfObjects

    objectStateTransitions = reshape( ...
        stateTransitionHistories(:,:,:,objectIndex), ...
        6, ...
        6, ...
        numberOfTimes);

    objectProcessNoise = reshape( ...
        processNoiseHistories(:,:,:,objectIndex), ...
        6, ...
        6, ...
        numberOfTimes);

    objectJacobians = reshape( ...
        measurementJacobianHistories( ...
            :,:,:,:,objectIndex), ...
        2, ...
        6, ...
        numberOfCandidates, ...
        numberOfTimes);

    objectTerrainAvailability = reshape( ...
        terrainAvailability(:,:,objectIndex), ...
        numberOfCandidates, ...
        numberOfTimes);

    [covarianceHistory, ~] = ...
        estimation.propagateNetworkCovariance( ...
            fixedInitialCovariance, ...
            objectStateTransitions, ...
            objectProcessNoise, ...
            objectJacobians, ...
            objectTerrainAvailability, ...
            networkSelections(:,4), ...
            measurementCovariance, ...
            stateScales);

    for timeIndex = 1:numberOfTimes

        covariance = ...
            covarianceHistory(:,:,timeIndex);

        symmetryError = ...
            norm(covariance - covariance.', "fro");

        assert(symmetryError < 1e-10, ...
            "Covariance lost symmetry.");

        [~, positiveDefiniteFlag] = ...
            chol(covariance, "lower");

        assert(positiveDefiniteFlag == 0, ...
            "Covariance is not positive definite.");
    end
end

%% Print terrain losses by object

fprintf("\nTerrain-filtered measurement opportunities\n");

for objectIndex = 1:numberOfObjects

    geometricOpportunityCount = sum( ...
        geometricAvailability(:,:,objectIndex), ...
        "all");

    terrainOpportunityCount = sum( ...
        terrainAvailability(:,:,objectIndex), ...
        "all");

    rejectedOpportunityCount = ...
        geometricOpportunityCount - ...
        terrainOpportunityCount;

    fprintf("\n%s\n", objectNames(objectIndex));

    fprintf( ...
        "  Geometric opportunities:  %d\n", ...
        geometricOpportunityCount);

    fprintf( ...
        "  Terrain opportunities:    %d\n", ...
        terrainOpportunityCount);

    fprintf( ...
        "  Terrain rejected:         %d\n", ...
        rejectedOpportunityCount);
end

%% Print network objective results

fprintf("\nNetwork objective comparison\n");

for networkIndex = 1:numberOfNetworks

    fprintf("\n%s\n", networkNames(networkIndex));

    fprintf( ...
        "  Geometric mean coverage:  %.3f epochs\n", ...
        geometricCoverageScores(networkIndex));

    fprintf( ...
        "  Terrain mean coverage:    %.3f epochs\n", ...
        terrainCoverageScores(networkIndex));

    fprintf( ...
        "  Geometric D-optimality:   %.6f\n", ...
        geometricInformationScores(networkIndex));

    fprintf( ...
        "  Terrain D-optimality:     %.6f\n", ...
        terrainInformationScores(networkIndex));
end

%% Plot objective comparison

figure( ...
    Name = "Terrain-Aware Network Objectives", ...
    Color = "white");

layout = tiledlayout(2,1);

layout.TileSpacing = "compact";
layout.Padding = "compact";

%% Coverage comparison

nexttile;

coverageComparison = [
    geometricCoverageScores, ...
    terrainCoverageScores
];

coverageBarHandles = bar( ...
    coverageComparison, ...
    "grouped");

coverageBarHandles(1).FaceColor = ...
    [0.3010, 0.7450, 0.9330];

coverageBarHandles(2).FaceColor = ...
    [0.8500, 0.3250, 0.0980];

grid on;

xticks(1:numberOfNetworks);
xticklabels(cellstr(networkNames));
xtickangle(15);

ylabel("Mean covered epochs per RSO");
title("Coverage Objective");

legend( ...
    coverageBarHandles, ...
    {"Geometric LOS", "Terrain-aware LOS"}, ...
    Location = "best");

%% Information comparison

nexttile;

informationComparison = [
    geometricInformationScores, ...
    terrainInformationScores
];

informationBarHandles = bar( ...
    informationComparison, ...
    "grouped");

informationBarHandles(1).FaceColor = ...
    [0.3010, 0.7450, 0.9330];

informationBarHandles(2).FaceColor = ...
    [0.8500, 0.3250, 0.0980];

grid on;

xticks(1:numberOfNetworks);
xticklabels(cellstr(networkNames));
xtickangle(15);

ylabel("Mean EKF D-optimality");
title("Information Objective");

legend( ...
    informationBarHandles, ...
    {"Geometric LOS", "Terrain-aware LOS"}, ...
    Location = "best");

title( ...
    layout, ...
    "Terrain-Aware Coverage and EKF Information Comparison");

fprintf("\ntestTerrainAwareNetworkObjectives passed.\n");