%% testProductionOptimizationDatabase
% Post-build validation of the frozen production optimization database.
%
% Run this after scripts/buildProductionOptimizationDatabase.m and before
% starting the optimization campaign. The test verifies the final temporal
% study definition, major database dimensions, and both network objectives.

clear;
close all;
clc;

%% ========================================================================
%  Project paths
%  ========================================================================

testDirectory = ...
    fileparts(mfilename("fullpath"));

projectRoot = ...
    fileparts(testDirectory);

sourceDirectory = ...
    fullfile(projectRoot,"src");

resultsDirectory = ...
    fullfile(projectRoot,"results");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

%% ========================================================================
%  Load frozen production database
%  ========================================================================

databaseFile = ...
    fullfile(resultsDirectory,"optimization_database.mat");

assert(isfile(databaseFile), ...
    [ ...
    "Production optimization database was not found. " ...
    "Run scripts/buildProductionOptimizationDatabase.m first.\n%s" ...
    ], ...
    databaseFile);

databaseData = ...
    load(databaseFile,"database");

assert(isfield(databaseData,"database"), ...
    "optimization_database.mat does not contain database.");

database = ...
    databaseData.database;

%% ========================================================================
%  Final production timing definition
%  ========================================================================

expectedTrackingStepSeconds = ...
    10*60;

expectedFinalTimeSeconds = ...
    3*24*3600;

expectedOptimizationEpochs = ...
    expectedFinalTimeSeconds / ...
    expectedTrackingStepSeconds;

assert(expectedOptimizationEpochs == 432);

assert(database.config.tracking.outputStepSeconds == ...
    expectedTrackingStepSeconds, ...
    "Production database does not use a 10-minute tracking cadence.");

assert(database.config.tracking.finalTimeSeconds == ...
    expectedFinalTimeSeconds, ...
    "Production database does not use a three-day tracking horizon.");

assert(database.meta.numberOfOptimizationEpochs == ...
    expectedOptimizationEpochs, ...
    "Production database does not contain 432 optimization epochs.");

trackingTimes = ...
    database.tracking.times(:);

assert(numel(trackingTimes) == expectedOptimizationEpochs, ...
    "Tracking time vector has the wrong number of epochs.");

assert(abs(trackingTimes(1)-expectedTrackingStepSeconds) < 1e-9, ...
    "First optimization epoch should occur at 600 seconds.");

assert(abs(trackingTimes(end)-expectedFinalTimeSeconds) < 1e-9, ...
    "Last optimization epoch should occur at exactly three days.");

assert(all(abs(diff(trackingTimes)-expectedTrackingStepSeconds) < 1e-9), ...
    "Tracking times are not uniformly separated by 600 seconds.");

%% ========================================================================
%  Major production database dimensions
%  ========================================================================

numberOfCandidates = ...
    database.meta.numberOfCandidates;

numberOfObjects = ...
    database.meta.numberOfObjects;

assert(numberOfCandidates >= 3, ...
    "Production candidate filter retained fewer than three sites.");

assert(numberOfObjects == 20, ...
    "Production database must contain the 20-object RSO population.");

assert(size(database.visibility.filteredAvailability,1) == ...
    numberOfCandidates, ...
    "Visibility candidate dimension is inconsistent.");

assert(size(database.visibility.filteredAvailability,2) == ...
    expectedOptimizationEpochs, ...
    "Visibility time dimension is inconsistent.");

assert(size(database.visibility.filteredAvailability,3) == ...
    numberOfObjects, ...
    "Visibility RSO dimension is inconsistent.");

assert(size(database.tracking.measurementJacobianHistories,3) == ...
    numberOfCandidates, ...
    "Measurement-Jacobian candidate dimension is inconsistent.");

assert(size(database.tracking.measurementJacobianHistories,4) == ...
    expectedOptimizationEpochs, ...
    "Measurement-Jacobian time dimension is inconsistent.");

assert(size(database.tracking.measurementJacobianHistories,5) == ...
    numberOfObjects, ...
    "Measurement-Jacobian RSO dimension is inconsistent.");

assert(size(database.tracking.stateTransitionHistories,3) == ...
    expectedOptimizationEpochs, ...
    "STM time dimension is inconsistent.");

assert(size(database.tracking.stateTransitionHistories,4) == ...
    numberOfObjects, ...
    "STM RSO dimension is inconsistent.");

assert(size(database.tracking.processNoiseHistories,3) == ...
    expectedOptimizationEpochs, ...
    "Process-noise time dimension is inconsistent.");

assert(size(database.tracking.processNoiseHistories,4) == ...
    numberOfObjects, ...
    "Process-noise RSO dimension is inconsistent.");

%% ========================================================================
%  Both study objectives remain enabled
%  ========================================================================

objectiveModes = ...
    lower(string(database.study.objectiveModes));

assert(all(ismember(["information","coverage"],objectiveModes)), ...
    "Production database must support both information and coverage.");

representativeNetwork = ...
    (1:3).';

[informationObjective,informationDetails] = ...
    optimization.networkObjective( ...
        representativeNetwork, ...
        database, ...
        "information");

coverageObjective = ...
    optimization.networkObjective( ...
        representativeNetwork, ...
        database, ...
        "coverage");

informationRepeat = ...
    optimization.networkObjective( ...
        representativeNetwork, ...
        database, ...
        "information");

assert(isfinite(informationObjective), ...
    "Representative information objective is nonfinite.");

assert(isfinite(coverageObjective), ...
    "Representative coverage objective is nonfinite.");

informationTolerance = ...
    1e-12*max(1,abs(informationObjective));

assert(abs(informationRepeat-informationObjective) <= ...
    informationTolerance, ...
    "Production information objective is not deterministic.");

assert(informationDetails.feasible, ...
    "Representative production network was classified as infeasible.");

assert(isfinite(informationDetails.informationScore), ...
    "Information diagnostic score is nonfinite.");

assert(isfinite(informationDetails.coverageScore), ...
    "Coverage diagnostic score is nonfinite.");

%% ========================================================================
%  Console summary
%  ========================================================================

fprintf("\n");
fprintf("Production optimization database validation\n");
fprintf("-------------------------------------------\n");
fprintf("Tracking horizon:       %.1f hr\n",expectedFinalTimeSeconds/3600);
fprintf("Tracking cadence:       %.1f min\n",expectedTrackingStepSeconds/60);
fprintf("Optimization epochs:    %d\n",expectedOptimizationEpochs);
fprintf("Candidate locations:    %d\n",numberOfCandidates);
fprintf("RSO population:         %d\n",numberOfObjects);
fprintf("Information objective:  %.8f\n",informationObjective);
fprintf("Coverage objective:     %.0f\n",coverageObjective);
fprintf("Both objective modes:   passed\n");
fprintf("Objective determinism:  passed\n");
fprintf("Database dimensions:    passed\n");
fprintf("\n");
fprintf("testProductionOptimizationDatabase passed.\n");
