%% testTerrainHorizonGeometry
% Unit test for the terrain-horizon geometry.
%
% Test 1:
%   Constant-elevation spherical lunar surface.
%
% Test 2:
%   A synthetic 0.2 km terrain wall beginning exactly 20 km east of
%   the sensor.
%
% The test verifies:
%   - Maximum apparent terrain angle.
%   - Range to the horizon-defining feature.
%   - DEM elevation of the feature.
%   - Periodic equality at 0 and 2*pi azimuth.

clear;
close all;
clc;

%% Add source directory

testDirectory = fileparts(mfilename("fullpath"));
repositoryDirectory = fileparts(testDirectory);
sourceDirectory = fullfile(repositoryDirectory, "src");

addpath(sourceDirectory);

requiredFunctions = [
    "digitalElevationModel.buildMaximumTerrainHorizonDatabase"
];

for functionIndex = 1:length(requiredFunctions)

    functionName = requiredFunctions(functionIndex);

    assert(~isempty(which(functionName)), ...
        "%s was not found.", functionName);
end

%% Test constants

moonRadius = 1737.4;                  % km

maximumTerrainRange = 50;             % km
terrainRangeStep = 0.5;               % km
horizonAzimuthStep = deg2rad(5);      % rad

sensorLatitude = 0;                   % rad
sensorLongitude = pi;                 % rad

candidateLatitudes = sensorLatitude;
candidateLongitudes = sensorLongitude;

%% Construct synthetic DEM grid

% Use a grid spacing that corresponds exactly to the radial search step.
% Along the equator, the longitude increment is:
%
%   deltaLongitude = terrainRangeStep / moonRadius.

angularGridStep = ...
    terrainRangeStep / moonRadius;

numberOfGridSteps = ...
    ceil(maximumTerrainRange / terrainRangeStep) + 2;

latitudeGrid = ...
    (-numberOfGridSteps:numberOfGridSteps).' * ...
    angularGridStep;

longitudeGrid = ...
    sensorLongitude + ...
    (-numberOfGridSteps:numberOfGridSteps).' * ...
    angularGridStep;

numberOfLatitudes = numel(latitudeGrid);
numberOfLongitudes = numel(longitudeGrid);

%% Test 1: Constant-elevation spherical surface

flatElevationGrid = zeros( ...
    numberOfLatitudes, ...
    numberOfLongitudes);

flatDem = griddedInterpolant( ...
    {latitudeGrid, longitudeGrid}, ...
    flatElevationGrid, ...
    "linear", ...
    "nearest");

[ ...
    flatHorizonAzimuths, ...
    flatMaximumTerrainAngles, ...
    flatMaximumFeatureRanges, ...
    flatSensorElevations, ...
    flatMaximumFeatureElevations ...
] = digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
    candidateLatitudes, ...
    candidateLongitudes, ...
    flatDem, ...
    maximumTerrainRange, ...
    terrainRangeStep, ...
    horizonAzimuthStep, ...
    moonRadius);

%% Analytic result for a flat spherical surface

% For terrain and sensor at the same lunar radius:
%
%   elevation = atan2(R*cos(delta) - R, R*sin(delta))
%
% which is equivalent to:
%
%   elevation = -delta/2.

firstCentralAngle = ...
    terrainRangeStep / moonRadius;

expectedFlatHorizonAngle = atan2( ...
    moonRadius*cos(firstCentralAngle) - moonRadius, ...
    moonRadius*sin(firstCentralAngle));

equivalentFlatHorizonAngle = ...
    -firstCentralAngle/2;

angleTolerance = 1e-10;               % rad
rangeTolerance = 1e-10;               % km
elevationTolerance = 1e-10;           % km

assert( ...
    abs( ...
        expectedFlatHorizonAngle - ...
        equivalentFlatHorizonAngle) < angleTolerance, ...
    "The two analytic flat-surface equations do not agree.");

assert( ...
    all( ...
        abs( ...
            flatMaximumTerrainAngles - ...
            expectedFlatHorizonAngle) < angleTolerance, ...
        "all"), ...
    "The flat-surface terrain horizon angle is incorrect.");

assert( ...
    all( ...
        abs( ...
            flatMaximumFeatureRanges - ...
            terrainRangeStep) < rangeTolerance, ...
        "all"), ...
    "The flat-surface maximum should occur at the closest range.");

assert( ...
    all( ...
        abs(flatMaximumFeatureElevations) < ...
        elevationTolerance, ...
        "all"), ...
    "The flat-surface feature elevation should be zero.");

assert( ...
    abs(flatSensorElevations) < elevationTolerance, ...
    "The flat-surface sensor elevation should be zero.");

assert( ...
    abs( ...
        flatMaximumTerrainAngles(1) - ...
        flatMaximumTerrainAngles(end)) < angleTolerance, ...
    "The flat horizon is not periodic at zero and 2*pi.");

%% Test 2: Known synthetic terrain wall

ridgeRange = 20;                      % km
ridgeHeight = 0.2;                    % km

ridgeStartLongitude = ...
    sensorLongitude + ...
    ridgeRange / moonRadius;

ridgeElevationGrid = zeros( ...
    numberOfLatitudes, ...
    numberOfLongitudes);

% Construct a north-south wall east of the sensor. The wall begins
% exactly 20 km east and remains at a constant 0.2 km elevation.

ridgeLongitudeMask = ...
    longitudeGrid >= ...
    ridgeStartLongitude - 1e-12;

ridgeElevationGrid(:, ridgeLongitudeMask) = ...
    ridgeHeight;

ridgeDem = griddedInterpolant( ...
    {latitudeGrid, longitudeGrid}, ...
    ridgeElevationGrid, ...
    "linear", ...
    "nearest");

[ ...
    ridgeHorizonAzimuths, ...
    ridgeMaximumTerrainAngles, ...
    ridgeMaximumFeatureRanges, ...
    ridgeSensorElevations, ...
    ridgeMaximumFeatureElevations ...
] = digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
    candidateLatitudes, ...
    candidateLongitudes, ...
    ridgeDem, ...
    maximumTerrainRange, ...
    terrainRangeStep, ...
    horizonAzimuthStep, ...
    moonRadius);

%% Find eastward azimuth

eastAzimuth = deg2rad(90);

[ ...
    eastAzimuthDifference, ...
    eastAzimuthIndex ...
] = min(abs(ridgeHorizonAzimuths - eastAzimuth));

assert( ...
    eastAzimuthDifference < angleTolerance, ...
    "The horizon azimuth grid does not contain 90 degrees.");

computedRidgeAngle = ...
    ridgeMaximumTerrainAngles(eastAzimuthIndex);

computedRidgeRange = ...
    ridgeMaximumFeatureRanges(eastAzimuthIndex);

computedRidgeElevation = ...
    ridgeMaximumFeatureElevations(eastAzimuthIndex);

%% Analytic ridge result

ridgeCentralAngle = ...
    ridgeRange / moonRadius;

expectedRidgeAngle = atan2( ...
    (moonRadius + ridgeHeight)*cos(ridgeCentralAngle) - ...
        moonRadius, ...
    (moonRadius + ridgeHeight)*sin(ridgeCentralAngle));

assert( ...
    abs( ...
        computedRidgeAngle - ...
        expectedRidgeAngle) < angleTolerance, ...
    "The synthetic-ridge apparent elevation angle is incorrect.");

assert( ...
    abs( ...
        computedRidgeRange - ...
        ridgeRange) < rangeTolerance, ...
    "The synthetic-ridge range is incorrect.");

assert( ...
    abs( ...
        computedRidgeElevation - ...
        ridgeHeight) < elevationTolerance, ...
    "The synthetic-ridge DEM elevation is incorrect.");

assert( ...
    abs(ridgeSensorElevations) < elevationTolerance, ...
    "The synthetic-ridge sensor elevation should be zero.");

assert( ...
    computedRidgeAngle > expectedFlatHorizonAngle, ...
    "The ridge horizon should exceed the flat-surface horizon.");

assert( ...
    abs( ...
        ridgeMaximumTerrainAngles(1) - ...
        ridgeMaximumTerrainAngles(end)) < angleTolerance, ...
    "The ridge horizon is not periodic at zero and 2*pi.");

%% Verify westward direction remains flat

westAzimuth = deg2rad(270);

[ ...
    westAzimuthDifference, ...
    westAzimuthIndex ...
] = min(abs(ridgeHorizonAzimuths - westAzimuth));

assert( ...
    westAzimuthDifference < angleTolerance, ...
    "The horizon azimuth grid does not contain 270 degrees.");

computedWestHorizonAngle = ...
    ridgeMaximumTerrainAngles(westAzimuthIndex);

assert( ...
    abs( ...
        computedWestHorizonAngle - ...
        expectedFlatHorizonAngle) < angleTolerance, ...
    "The terrain west of the sensor should remain flat.");

%% Print results

fprintf("\nFlat spherical surface\n");

fprintf( ...
    "  Expected horizon angle:    %.9f deg\n", ...
    rad2deg(expectedFlatHorizonAngle));

fprintf( ...
    "  Computed horizon angle:    %.9f deg\n", ...
    rad2deg(flatMaximumTerrainAngles(1)));

fprintf( ...
    "  Maximum-feature range:     %.3f km\n", ...
    flatMaximumFeatureRanges(1));

fprintf("\nSynthetic eastward terrain wall\n");

fprintf( ...
    "  Wall height:               %.3f km\n", ...
    ridgeHeight);

fprintf( ...
    "  Expected horizon angle:    %.9f deg\n", ...
    rad2deg(expectedRidgeAngle));

fprintf( ...
    "  Computed horizon angle:    %.9f deg\n", ...
    rad2deg(computedRidgeAngle));

fprintf( ...
    "  Computed feature range:    %.3f km\n", ...
    computedRidgeRange);

fprintf( ...
    "  Computed feature elevation: %.3f km\n", ...
    computedRidgeElevation);

%% Plot synthetic horizon profiles

figure( ...
    Name = "Synthetic Terrain Horizon Geometry", ...
    Color = "white");

plot( ...
    rad2deg(flatHorizonAzimuths), ...
    rad2deg(flatMaximumTerrainAngles), ...
    "--", ...
    Color = [0.3, 0.3, 0.3], ...
    LineWidth = 1.5);

hold on;

plot( ...
    rad2deg(ridgeHorizonAzimuths), ...
    rad2deg(ridgeMaximumTerrainAngles), ...
    Color = [0, 0.4470, 0.7410], ...
    LineWidth = 1.5);

scatter( ...
    rad2deg(eastAzimuth), ...
    rad2deg(computedRidgeAngle), ...
    55, ...
    [0.85, 0.1, 0.1], ...
    "filled");

xline( ...
    90, ...
    ":k", ...
    "Synthetic wall");

grid on;

xlim([0, 360]);

xlabel("Azimuth (deg)");
ylabel("Maximum apparent terrain angle (deg)");
title("Synthetic Terrain-Horizon Validation");

legend( ...
    "Flat spherical surface", ...
    "Synthetic terrain wall", ...
    "Analytic eastward result", ...
    Location = "best");

fprintf("\ntestTerrainHorizonGeometry passed.\n");