function report = testProductionOptimizationResults(userConfig)
% TESTPRODUCTIONOPTIMIZATIONRESULTS Verify the completed production campaign.
%
% This test discovers the newest complete 6000-FE, 20-run production study
% for each requested network-size/objective case, loads every individual
% run_###.mat result, re-processes the saved sensor network with the frozen
% optimization database, and verifies that the stored results are internally
% consistent and reproducible.
%
% Default production definition:
%   network sizes:  [3 5 7 10]
%   objectives:     information, coverage
%   runs/case:      20
%   FE/run:         6000
%   population:     60
%   seeds/case:     1000:1019
%
% The test checks, for every individual result file:
%   - required run fields and configuration metadata;
%   - run index and optimizer seed sequence;
%   - exact FE completion and monotonic best-so-far convergence;
%   - valid, unique, in-range, canonical sensor indices;
%   - stored sensor coordinates/table against the frozen candidate database;
%   - a fresh optimization.networkObjective evaluation of the saved network;
%   - stored objective, information, coverage, and per-RSO diagnostics;
%   - final-population dimensions and finite scores;
%   - consistency between each individual run file and study_summary.mat.
%
% It also verifies each study-level summary and the complete campaign count.
% With the defaults, exactly 8 study summaries and 160 run files are required.
%
% Usage
%   report = testProductionOptimizationResults;
%
% Optional overrides
%   config = struct();
%   config.maximumCampaignSpanHours = 168;
%   report = testProductionOptimizationResults(config);
%
% The function throws an assertion at the first failed verification. If it
% returns normally, report.allChecksPassed is true.

arguments
    userConfig (1,1) struct = struct()
end

%% ========================================================================
%  Project paths and configuration
%  ========================================================================

thisFile = mfilename("fullpath");
testDirectory = fileparts(thisFile);
projectRoot = fileparts(testDirectory);
sourceDirectory = fullfile(projectRoot,"src");
resultsDirectory = fullfile(projectRoot,"results");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

defaultConfig = struct();
defaultConfig.resultsDirectory = resultsDirectory;
defaultConfig.databaseFile = fullfile(resultsDirectory,"optimization_database.mat");
defaultConfig.networkSizes = [3 5 7 10];
defaultConfig.objectiveModes = ["information","coverage"];
defaultConfig.numberOfRuns = 20;
defaultConfig.functionEvaluationBudget = 6000;
defaultConfig.populationSize = 60;
defaultConfig.baseSeed = 1000;
defaultConfig.studyName = "lunar_surface_production_optimization";
defaultConfig.requireParallel = true;
defaultConfig.relativeTolerance = 1e-10;
defaultConfig.coordinateToleranceRad = 1e-12;
defaultConfig.maximumCampaignSpanHours = 168;

config = mergeStruct(defaultConfig,userConfig);
config.resultsDirectory = string(config.resultsDirectory);
config.databaseFile = string(config.databaseFile);
config.networkSizes = double(config.networkSizes(:).');
config.objectiveModes = lower(string(config.objectiveModes(:).'));
config.studyName = string(config.studyName);

validateattributes(config.networkSizes,{'numeric'}, ...
    {'vector','integer','positive','nonempty'});
validateattributes(config.numberOfRuns,{'numeric'}, ...
    {'scalar','integer','positive'});
validateattributes(config.functionEvaluationBudget,{'numeric'}, ...
    {'scalar','integer','positive'});
validateattributes(config.populationSize,{'numeric'}, ...
    {'scalar','integer','>=',2});
validateattributes(config.baseSeed,{'numeric'}, ...
    {'scalar','integer','nonnegative'});
validateattributes(config.relativeTolerance,{'numeric'}, ...
    {'scalar','real','finite','positive'});
validateattributes(config.coordinateToleranceRad,{'numeric'}, ...
    {'scalar','real','finite','positive'});
validateattributes(config.maximumCampaignSpanHours,{'numeric'}, ...
    {'scalar','real','positive'});
assert(islogical(config.requireParallel) && isscalar(config.requireParallel), ...
    "requireParallel must be a scalar logical.");
assert(all(ismember(config.objectiveModes,["information","coverage"])), ...
    "objectiveModes may contain only information and coverage.");
assert(mod(config.functionEvaluationBudget,config.populationSize) == 0, ...
    "functionEvaluationBudget must be divisible by populationSize.");

%% ========================================================================
%  Load frozen database
%  ========================================================================

assert(isfile(config.databaseFile), ...
    "Frozen optimization database was not found: %s",config.databaseFile);

databaseData = load(config.databaseFile,"database");
assert(isfield(databaseData,"database"), ...
    "optimization_database.mat does not contain database.");
database = databaseData.database;

numberOfCandidates = database.meta.numberOfCandidates;
numberOfObjects = database.meta.numberOfObjects;

%% ========================================================================
%  Expected production cases
%  ========================================================================

numberOfNetworkSizes = numel(config.networkSizes);
numberOfObjectiveModes = numel(config.objectiveModes);
numberOfCases = numberOfNetworkSizes*numberOfObjectiveModes;

caseNetworkSize = zeros(numberOfCases,1);
caseObjectiveMode = strings(numberOfCases,1);
caseCounter = 0;

for networkIndex = 1:numberOfNetworkSizes
    for objectiveIndex = 1:numberOfObjectiveModes
        caseCounter = caseCounter + 1;
        caseNetworkSize(caseCounter) = config.networkSizes(networkIndex);
        caseObjectiveMode(caseCounter) = config.objectiveModes(objectiveIndex);
    end
end

runRoot = fullfile(config.resultsDirectory,"optimization_runs");
assert(isfolder(runRoot), ...
    "Optimization result directory was not found: %s",runRoot);

[summaryFiles,campaignTimes] = resolveStudySummaries( ...
    runRoot,caseNetworkSize,caseObjectiveMode,config);

if all(~isnat(campaignTimes))
    assert(all(diff(campaignTimes) > seconds(0)), ...
        ["Selected production studies are not in the expected batch order. " ...
         "This usually means result directories from different launches " ...
         "were mixed."]);

    campaignSpanHours = hours(max(campaignTimes)-min(campaignTimes));
    assert(campaignSpanHours <= config.maximumCampaignSpanHours, ...
        ["Selected production studies span %.2f hours, exceeding the " ...
         "allowed %.2f-hour campaign window. Results may come from " ...
         "different launches."], ...
        campaignSpanHours,config.maximumCampaignSpanHours);
else
    campaignSpanHours = NaN;
end

%% ========================================================================
%  Allocate run and case reports
%  ========================================================================

expectedTotalRuns = numberOfCases*config.numberOfRuns;

runCase = zeros(expectedTotalRuns,1);
runNetworkSize = zeros(expectedTotalRuns,1);
runObjectiveMode = strings(expectedTotalRuns,1);
runIndexColumn = zeros(expectedTotalRuns,1);
seedColumn = zeros(expectedTotalRuns,1);
sensorIndicesColumn = cell(expectedTotalRuns,1);
savedObjectiveColumn = zeros(expectedTotalRuns,1);
recomputedObjectiveColumn = zeros(expectedTotalRuns,1);
informationScoreColumn = zeros(expectedTotalRuns,1);
coverageScoreColumn = zeros(expectedTotalRuns,1);
runtimeSecondsColumn = zeros(expectedTotalRuns,1);
parallelRetryCountColumn = zeros(expectedTotalRuns,1);
resultFileColumn = strings(expectedTotalRuns,1);

caseBestRun = zeros(numberOfCases,1);
caseBestObjective = zeros(numberOfCases,1);
caseInformationScore = zeros(numberOfCases,1);
caseCoverageScore = zeros(numberOfCases,1);
caseMeanObjective = zeros(numberOfCases,1);
caseStdObjective = zeros(numberOfCases,1);
caseMeanRuntimeSeconds = zeros(numberOfCases,1);
caseParallelRetries = zeros(numberOfCases,1);

runCounter = 0;

fprintf("\n");
fprintf("============================================================\n");
fprintf("Production optimization result verification\n");
fprintf("============================================================\n");
fprintf("Database:            %s\n",config.databaseFile);
fprintf("Cases:               %d\n",numberOfCases);
fprintf("Runs per case:       %d\n",config.numberOfRuns);
fprintf("Expected run files:  %d\n",expectedTotalRuns);
fprintf("FE per run:          %d\n",config.functionEvaluationBudget);
fprintf("\n");

%% ========================================================================
%  Process every study and every individual result file
%  ========================================================================

for caseIndex = 1:numberOfCases
    summaryFile = summaryFiles(caseIndex);
    studyDirectory = string(fileparts(summaryFile));

    summaryData = load(summaryFile,"studyState");
    assert(isfield(summaryData,"studyState"), ...
        "Study summary does not contain studyState: %s",summaryFile);
    studyState = summaryData.studyState;

    expectedNetworkSize = caseNetworkSize(caseIndex);
    expectedObjectiveMode = caseObjectiveMode(caseIndex);

    verifyStudyConfiguration( ...
        studyState,expectedNetworkSize,expectedObjectiveMode,config);

    runFiles = dir(fullfile(studyDirectory,"run_*.mat"));
    assert(numel(runFiles) == config.numberOfRuns, ...
        ["Case %d (%s, N=%d) contains %d run files; expected %d. " ...
         "Study directory: %s"], ...
        caseIndex,expectedObjectiveMode,expectedNetworkSize, ...
        numel(runFiles),config.numberOfRuns,studyDirectory);

    assert(numel(studyState.runStates) == config.numberOfRuns, ...
        "studyState.runStates has the wrong length for %s.",studyDirectory);

    savedObjectives = zeros(config.numberOfRuns,1);
    savedRunTimes = zeros(config.numberOfRuns,1);
    savedRetryCounts = zeros(config.numberOfRuns,1);

    fprintf("Case %d/%d: N=%d | %s\n", ...
        caseIndex,numberOfCases,expectedNetworkSize,expectedObjectiveMode);
    fprintf("  %s\n",studyDirectory);

    for runIndex = 1:config.numberOfRuns
        runFile = fullfile(studyDirectory,sprintf("run_%03d.mat",runIndex));
        assert(isfile(runFile), ...
            "Missing expected result file: %s",runFile);

        runData = load(runFile,"runState");
        assert(isfield(runData,"runState"), ...
            "Result file does not contain runState: %s",runFile);
        runState = runData.runState;

        verifyRunStateBasics( ...
            runState,runIndex,expectedNetworkSize,expectedObjectiveMode, ...
            numberOfCandidates,numberOfObjects,config,runFile);

        sensorIndices = double(runState.bestSensorIndices(:));

        %% Candidate-coordinate and table verification

        expectedLatitudesRad = ...
            double(database.candidates.latitudesRad(sensorIndices));
        expectedLongitudesRad = ...
            double(database.candidates.longitudesRad(sensorIndices));

        assertAbsoluteEqual( ...
            runState.bestSensorLatitudesRad(:),expectedLatitudesRad(:), ...
            config.coordinateToleranceRad, ...
            sprintf("Stored sensor latitudes disagree with database in %s",runFile));

        assertAbsoluteEqual( ...
            runState.bestSensorLongitudesRad(:),expectedLongitudesRad(:), ...
            config.coordinateToleranceRad, ...
            sprintf("Stored sensor longitudes disagree with database in %s",runFile));

        verifySensorTable( ...
            runState.bestSensorTable,sensorIndices, ...
            expectedLatitudesRad,expectedLongitudesRad, ...
            config.coordinateToleranceRad,runFile);

        %% Fresh objective re-evaluation of the saved sensor network

        [recomputedObjective,recomputedDetails] = ...
            optimization.networkObjective( ...
                sensorIndices,database,expectedObjectiveMode);

        assert(recomputedDetails.feasible, ...
            "Saved network was classified as infeasible when reprocessed: %s", ...
            runFile);

        assertRelativeEqual( ...
            runState.bestObjective,recomputedObjective, ...
            config.relativeTolerance, ...
            sprintf("Saved objective does not reproduce in %s",runFile));

        assertRelativeEqual( ...
            runState.bestInformationScore,recomputedDetails.informationScore, ...
            config.relativeTolerance, ...
            sprintf("Information score does not reproduce in %s",runFile));

        assertRelativeEqual( ...
            runState.bestCoverageScore,recomputedDetails.coverageScore, ...
            config.relativeTolerance, ...
            sprintf("Coverage score does not reproduce in %s",runFile));

        assertRelativeEqual( ...
            runState.informationByObject(:), ...
            recomputedDetails.informationByObject(:), ...
            config.relativeTolerance, ...
            sprintf("Per-RSO information results do not reproduce in %s",runFile));

        assertRelativeEqual( ...
            runState.coverageByObject(:), ...
            recomputedDetails.coverageByObject(:), ...
            config.relativeTolerance, ...
            sprintf("Per-RSO coverage results do not reproduce in %s",runFile));

        %% Individual-file versus study-summary consistency

        summaryRunState = studyState.runStates{runIndex};
        assert(summaryRunState.runIndex == runState.runIndex, ...
            "Run index differs between individual file and study summary.");
        assert(summaryRunState.seed == runState.seed, ...
            "Seed differs between individual file and study summary.");
        assert(isequal(summaryRunState.bestSensorIndices(:),sensorIndices(:)), ...
            "Sensor indices differ between individual file and study summary.");
        assertRelativeEqual( ...
            summaryRunState.bestObjective,runState.bestObjective, ...
            config.relativeTolerance, ...
            "Objective differs between individual file and study summary.");
        assert(isequal(summaryRunState.history.fe(:),runState.history.fe(:)), ...
            "FE history differs between individual file and study summary.");
        assertRelativeEqual( ...
            summaryRunState.history.bestJ(:),runState.history.bestJ(:), ...
            config.relativeTolerance, ...
            "Convergence history differs between individual file and study summary.");

        savedObjectives(runIndex) = runState.bestObjective;
        savedRunTimes(runIndex) = runState.runtimeSeconds;
        savedRetryCounts(runIndex) = runState.parallelRetryCount;

        runCounter = runCounter + 1;
        runCase(runCounter) = caseIndex;
        runNetworkSize(runCounter) = expectedNetworkSize;
        runObjectiveMode(runCounter) = expectedObjectiveMode;
        runIndexColumn(runCounter) = runIndex;
        seedColumn(runCounter) = runState.seed;
        sensorIndicesColumn{runCounter} = sensorIndices(:).';
        savedObjectiveColumn(runCounter) = runState.bestObjective;
        recomputedObjectiveColumn(runCounter) = recomputedObjective;
        informationScoreColumn(runCounter) = runState.bestInformationScore;
        coverageScoreColumn(runCounter) = runState.bestCoverageScore;
        runtimeSecondsColumn(runCounter) = runState.runtimeSeconds;
        parallelRetryCountColumn(runCounter) = runState.parallelRetryCount;
        resultFileColumn(runCounter) = string(runFile);

        fprintf("  Run %02d/%02d verified | seed %d | J = %.12g\n", ...
            runIndex,config.numberOfRuns,runState.seed,runState.bestObjective);
    end

    %% Study-level aggregate verification

    assertRelativeEqual( ...
        studyState.bestObjectives(:),savedObjectives, ...
        config.relativeTolerance, ...
        sprintf("studyState.bestObjectives is inconsistent for case %d",caseIndex));

    assertRelativeEqual( ...
        studyState.runTimesSeconds(:),savedRunTimes, ...
        config.relativeTolerance, ...
        sprintf("studyState.runTimesSeconds is inconsistent for case %d",caseIndex));

    assertRelativeEqual( ...
        studyState.meanBestObjective,mean(savedObjectives), ...
        config.relativeTolerance, ...
        sprintf("Mean objective is inconsistent for case %d",caseIndex));

    assertRelativeEqual( ...
        studyState.stdBestObjective,std(savedObjectives), ...
        config.relativeTolerance, ...
        sprintf("Objective standard deviation is inconsistent for case %d",caseIndex));

    assertRelativeEqual( ...
        studyState.meanRuntimeSeconds,mean(savedRunTimes), ...
        config.relativeTolerance, ...
        sprintf("Mean runtime is inconsistent for case %d",caseIndex));

    assertRelativeEqual( ...
        studyState.stdRuntimeSeconds,std(savedRunTimes), ...
        config.relativeTolerance, ...
        sprintf("Runtime standard deviation is inconsistent for case %d",caseIndex));

    [expectedBestObjective,expectedBestRunIndex] = min(savedObjectives);
    expectedBestRunState = studyState.runStates{expectedBestRunIndex};

    assert(studyState.overallBestRunIndex == expectedBestRunIndex, ...
        "overallBestRunIndex is inconsistent for case %d.",caseIndex);

    assertRelativeEqual( ...
        studyState.overallBestObjective,expectedBestObjective, ...
        config.relativeTolerance, ...
        sprintf("overallBestObjective is inconsistent for case %d",caseIndex));

    assert(isequal( ...
        studyState.overallBestSensorIndices(:), ...
        expectedBestRunState.bestSensorIndices(:)), ...
        "overallBestSensorIndices is inconsistent for case %d.",caseIndex);

    assertRelativeEqual( ...
        studyState.overallBestInformationScore, ...
        expectedBestRunState.bestInformationScore, ...
        config.relativeTolerance, ...
        sprintf("Overall-best information score is inconsistent for case %d",caseIndex));

    assertRelativeEqual( ...
        studyState.overallBestCoverageScore, ...
        expectedBestRunState.bestCoverageScore, ...
        config.relativeTolerance, ...
        sprintf("Overall-best coverage score is inconsistent for case %d",caseIndex));

    assert(isequal(studyState.parallelRetryCounts(:),savedRetryCounts(:)), ...
        "Parallel retry counts are inconsistent for case %d.",caseIndex);

    caseBestRun(caseIndex) = expectedBestRunIndex;
    caseBestObjective(caseIndex) = expectedBestObjective;
    caseInformationScore(caseIndex) = ...
        expectedBestRunState.bestInformationScore;
    caseCoverageScore(caseIndex) = ...
        expectedBestRunState.bestCoverageScore;
    caseMeanObjective(caseIndex) = mean(savedObjectives);
    caseStdObjective(caseIndex) = std(savedObjectives);
    caseMeanRuntimeSeconds(caseIndex) = mean(savedRunTimes);
    caseParallelRetries(caseIndex) = sum(savedRetryCounts);

    fprintf("  Case verified: %d/%d run files complete.\n\n", ...
        config.numberOfRuns,config.numberOfRuns);
end

assert(runCounter == expectedTotalRuns, ...
    "Processed %d run files; expected %d.",runCounter,expectedTotalRuns);

%% ========================================================================
%  Build returned verification report
%  ========================================================================

runTable = table( ...
    runCase, ...
    runNetworkSize, ...
    runObjectiveMode, ...
    runIndexColumn, ...
    seedColumn, ...
    sensorIndicesColumn, ...
    savedObjectiveColumn, ...
    recomputedObjectiveColumn, ...
    informationScoreColumn, ...
    coverageScoreColumn, ...
    runtimeSecondsColumn, ...
    parallelRetryCountColumn, ...
    resultFileColumn, ...
    'VariableNames',{ ...
        'Case', ...
        'NetworkSize', ...
        'ObjectiveMode', ...
        'RunIndex', ...
        'Seed', ...
        'SensorIndices', ...
        'SavedObjective', ...
        'RecomputedObjective', ...
        'InformationScore', ...
        'CoverageScore', ...
        'RuntimeSeconds', ...
        'ParallelRetryCount', ...
        'ResultFile'});

caseTable = table( ...
    (1:numberOfCases).', ...
    caseNetworkSize, ...
    caseObjectiveMode, ...
    summaryFiles, ...
    caseBestRun, ...
    caseBestObjective, ...
    caseInformationScore, ...
    caseCoverageScore, ...
    caseMeanObjective, ...
    caseStdObjective, ...
    caseMeanRuntimeSeconds, ...
    caseParallelRetries, ...
    'VariableNames',{ ...
        'Case', ...
        'NetworkSize', ...
        'ObjectiveMode', ...
        'StudySummaryFile', ...
        'BestRun', ...
        'BestObjective', ...
        'BestInformationScore', ...
        'BestCoverageScore', ...
        'MeanObjective', ...
        'StdObjective', ...
        'MeanRuntimeSeconds', ...
        'ParallelRetries'});

report = struct();
report.version = "production_optimization_result_verification_v1";
report.created = string(datetime("now"));
report.databaseFile = config.databaseFile;
report.configuration = config;
report.numberOfCases = numberOfCases;
report.numberOfRunFiles = runCounter;
report.expectedNumberOfRunFiles = expectedTotalRuns;
report.campaignSpanHours = campaignSpanHours;
report.studySummaryFiles = summaryFiles;
report.caseTable = caseTable;
report.runTable = runTable;
report.allChecksPassed = true;

fprintf("============================================================\n");
fprintf("Production result verification PASSED\n");
fprintf("============================================================\n");
fprintf("Study summaries verified: %d\n",numberOfCases);
if isfinite(campaignSpanHours)
    fprintf("Campaign span:            %.2f hr\n",campaignSpanHours);
end
fprintf("Run files verified:       %d\n",runCounter);
fprintf("Sensor networks replayed: %d\n",runCounter);
fprintf("Expected run files:       %d\n",expectedTotalRuns);
fprintf("Total parallel retries:   %d\n",sum(parallelRetryCountColumn));
fprintf("\nCase summary:\n");
disp(caseTable);
fprintf("All production optimization results were generated consistently.\n");

end

%% ========================================================================
%  Local helpers
%  ========================================================================

function [summaryFiles,campaignTimes] = resolveStudySummaries( ...
    runRoot,caseNetworkSize,caseObjectiveMode,config)

allSummaryFiles = dir(fullfile(runRoot,"*","study_summary.mat"));
assert(~isempty(allSummaryFiles), ...
    "No study_summary.mat files were found under %s.",runRoot);

[~,sortOrder] = sort([allSummaryFiles.datenum],"descend");
allSummaryFiles = allSummaryFiles(sortOrder);

numberOfCases = numel(caseNetworkSize);
summaryFiles = strings(numberOfCases,1);
campaignTimes = NaT(numberOfCases,1);

for caseIndex = 1:numberOfCases
    expectedNetworkSize = caseNetworkSize(caseIndex);
    expectedObjectiveMode = caseObjectiveMode(caseIndex);
    matchFound = false;

    for fileIndex = 1:numel(allSummaryFiles)
        candidateFile = string(fullfile( ...
            allSummaryFiles(fileIndex).folder,allSummaryFiles(fileIndex).name));

        candidateData = load(candidateFile,"studyState");
        if ~isfield(candidateData,"studyState")
            continue
        end

        candidateStudy = candidateData.studyState;

        if ~matchesStudyConfiguration( ...
                candidateStudy,expectedNetworkSize,expectedObjectiveMode,config)
            continue
        end

        candidateDirectory = string(fileparts(candidateFile));
        complete = true;
        for runIndex = 1:config.numberOfRuns
            if ~isfile(fullfile( ...
                    candidateDirectory,sprintf("run_%03d.mat",runIndex)))
                complete = false;
                break
            end
        end

        if ~complete
            continue
        end

        summaryFiles(caseIndex) = candidateFile;
        [~,folderName] = fileparts(candidateDirectory);
        campaignTimes(caseIndex) = extractStudyTimestamp(folderName);
        matchFound = true;
        break
    end

    assert(matchFound, ...
        ["Could not find a complete production study for N=%d, %s. " ...
         "Expected %d runs, %d FE/run, population %d, base seed %d."], ...
        expectedNetworkSize,expectedObjectiveMode,config.numberOfRuns, ...
        config.functionEvaluationBudget,config.populationSize,config.baseSeed);
end

assert(numel(unique(summaryFiles)) == numberOfCases, ...
    "The same study summary was selected for more than one production case.");

end

function tf = matchesStudyConfiguration( ...
    studyState,expectedNetworkSize,expectedObjectiveMode,config)

tf = isstruct(studyState) && isscalar(studyState) && ...
    isfield(studyState,"config") && ...
    isfield(studyState,"numberOfRuns");

if ~tf
    return
end

studyConfig = studyState.config;
requiredConfigFields = { ...
    'networkSize', ...
    'objectiveMode', ...
    'functionEvaluationBudget', ...
    'populationSize', ...
    'baseSeed', ...
    'studyName'};

for fieldIndex = 1:numel(requiredConfigFields)
    if ~isfield(studyConfig,requiredConfigFields{fieldIndex})
        tf = false;
        return
    end
end

tf = ...
    studyState.numberOfRuns == config.numberOfRuns && ...
    studyConfig.networkSize == expectedNetworkSize && ...
    lower(string(studyConfig.objectiveMode)) == expectedObjectiveMode && ...
    studyConfig.functionEvaluationBudget == config.functionEvaluationBudget && ...
    studyConfig.populationSize == config.populationSize && ...
    studyConfig.baseSeed == config.baseSeed && ...
    string(studyConfig.studyName) == config.studyName;

end

function verifyStudyConfiguration( ...
    studyState,expectedNetworkSize,expectedObjectiveMode,config)

assert(matchesStudyConfiguration( ...
    studyState,expectedNetworkSize,expectedObjectiveMode,config), ...
    "Study summary configuration does not match the expected production case.");

requiredFields = [ ...
    "runStates", ...
    "bestObjectives", ...
    "runTimesSeconds", ...
    "meanBestObjective", ...
    "stdBestObjective", ...
    "meanRuntimeSeconds", ...
    "stdRuntimeSeconds", ...
    "overallBestRunIndex", ...
    "overallBestObjective", ...
    "overallBestSensorIndices", ...
    "overallBestInformationScore", ...
    "overallBestCoverageScore", ...
    "parallelRetryCounts"];

requireFields(studyState,requiredFields,"studyState");

end

function verifyRunStateBasics( ...
    runState,runIndex,networkSize,objectiveMode, ...
    numberOfCandidates,numberOfObjects,config,runFile)

requiredFields = [ ...
    "runIndex", ...
    "seed", ...
    "optimizer", ...
    "objectiveMode", ...
    "networkSize", ...
    "numberOfCandidates", ...
    "numberOfObjects", ...
    "functionEvaluationBudget", ...
    "populationSize", ...
    "searchFunctionEvaluations", ...
    "bestSensorIndices", ...
    "bestSensorLatitudesRad", ...
    "bestSensorLongitudesRad", ...
    "bestSensorTable", ...
    "bestObjective", ...
    "bestInformationScore", ...
    "bestCoverageScore", ...
    "informationByObject", ...
    "coverageByObject", ...
    "runtimeSeconds", ...
    "exitFlag", ...
    "finalPopulation", ...
    "finalScores", ...
    "usedParallel", ...
    "parallelRetryCount", ...
    "parallelPoolRestarted", ...
    "history", ...
    "config"];

requireFields(runState,requiredFields,sprintf("runState in %s",runFile));

assert(runState.runIndex == runIndex, ...
    "Unexpected run index in %s.",runFile);
assert(runState.seed == config.baseSeed + runIndex - 1, ...
    "Unexpected optimizer seed in %s.",runFile);
assert(upper(string(runState.optimizer)) == "GA", ...
    "Unexpected optimizer in %s.",runFile);
assert(lower(string(runState.objectiveMode)) == objectiveMode, ...
    "Unexpected objective mode in %s.",runFile);
assert(runState.networkSize == networkSize, ...
    "Unexpected network size in %s.",runFile);
assert(runState.numberOfCandidates == numberOfCandidates, ...
    "Candidate count does not match frozen database in %s.",runFile);
assert(runState.numberOfObjects == numberOfObjects, ...
    "RSO count does not match frozen database in %s.",runFile);
assert(runState.functionEvaluationBudget == config.functionEvaluationBudget, ...
    "Unexpected FE budget in %s.",runFile);
assert(runState.populationSize == config.populationSize, ...
    "Unexpected GA population size in %s.",runFile);
assert(runState.searchFunctionEvaluations == config.functionEvaluationBudget, ...
    "Search did not reach the requested FE budget in %s.",runFile);

sensorIndices = double(runState.bestSensorIndices(:));
assert(numel(sensorIndices) == networkSize, ...
    "Wrong number of saved sensors in %s.",runFile);
assert(all(isfinite(sensorIndices)), ...
    "Sensor indices contain nonfinite values in %s.",runFile);
assert(all(sensorIndices == round(sensorIndices)), ...
    "Sensor indices contain nonintegers in %s.",runFile);
assert(all(sensorIndices >= 1 & sensorIndices <= numberOfCandidates), ...
    "Sensor indices are outside the candidate range in %s.",runFile);
assert(numel(unique(sensorIndices)) == networkSize, ...
    "Duplicate sensor indices were saved in %s.",runFile);
assert(all(diff(sensorIndices) > 0), ...
    "Sensor indices are not stored in canonical increasing order in %s.",runFile);

assert(isfinite(runState.bestObjective), ...
    "Best objective is nonfinite in %s.",runFile);
assert(isfinite(runState.bestInformationScore), ...
    "Information score is nonfinite in %s.",runFile);
assert(isfinite(runState.bestCoverageScore), ...
    "Coverage score is nonfinite in %s.",runFile);
assert(numel(runState.informationByObject) == numberOfObjects && ...
    all(isfinite(runState.informationByObject),"all"), ...
    "Per-RSO information results are invalid in %s.",runFile);
assert(numel(runState.coverageByObject) == numberOfObjects && ...
    all(isfinite(runState.coverageByObject),"all"), ...
    "Per-RSO coverage results are invalid in %s.",runFile);
assert(isfinite(runState.runtimeSeconds) && runState.runtimeSeconds > 0, ...
    "Runtime is invalid in %s.",runFile);

if config.requireParallel
    assert(logical(runState.usedParallel), ...
        "Production run was not marked as parallel in %s.",runFile);
end

assert(isscalar(runState.parallelRetryCount) && ...
    ismember(runState.parallelRetryCount,[0 1]), ...
    "Unexpected parallel retry count in %s.",runFile);
assert(logical(runState.parallelPoolRestarted) == ...
    (runState.parallelRetryCount > 0), ...
    "Parallel restart metadata is inconsistent in %s.",runFile);

requireFields(runState.history,["fe","bestJ","generation"], ...
    sprintf("history in %s",runFile));

historyFe = double(runState.history.fe(:));
historyBestJ = double(runState.history.bestJ(:));
historyGeneration = double(runState.history.generation(:));

assert(~isempty(historyFe), ...
    "FE history is empty in %s.",runFile);
assert(numel(historyFe) == numel(historyBestJ) && ...
    numel(historyFe) == numel(historyGeneration), ...
    "Convergence-history arrays have inconsistent lengths in %s.",runFile);
assert(all(isfinite(historyFe)) && all(isfinite(historyBestJ)) && ...
    all(isfinite(historyGeneration)), ...
    "Convergence history contains nonfinite values in %s.",runFile);
assert(historyFe(end) == config.functionEvaluationBudget, ...
    "Convergence history does not end at the requested FE budget in %s.",runFile);
assert(all(diff(historyFe) > 0), ...
    "FE history is not strictly increasing in %s.",runFile);
assert(all(diff(historyGeneration) >= 0), ...
    "Generation history is not monotonic in %s.",runFile);
assert(all(diff(historyBestJ) <= ...
    config.relativeTolerance*max(1,max(abs(historyBestJ)))), ...
    "Best-so-far objective is not monotonic in %s.",runFile);
assertRelativeEqual( ...
    historyBestJ(end),runState.bestObjective,config.relativeTolerance, ...
    sprintf("Final convergence value differs from saved best objective in %s",runFile));

assert(size(runState.finalPopulation,1) == config.populationSize && ...
    size(runState.finalPopulation,2) == networkSize, ...
    "Final GA population has unexpected dimensions in %s.",runFile);
assert(numel(runState.finalScores) == config.populationSize && ...
    all(isfinite(runState.finalScores),"all"), ...
    "Final GA scores are invalid in %s.",runFile);

if isfield(runState,"solverFinalBestObjective") && ...
        isfinite(runState.solverFinalBestObjective)
    scale = max([1,abs(runState.bestObjective), ...
        abs(runState.solverFinalBestObjective)]);
    assert(runState.bestObjective <= runState.solverFinalBestObjective + ...
        config.relativeTolerance*scale, ...
        "Saved incumbent is worse than solver final best in %s.",runFile);
end

end

function verifySensorTable( ...
    sensorTable,sensorIndices,latitudesRad,longitudesRad,toleranceRad,runFile)

assert(istable(sensorTable), ...
    "bestSensorTable is not a table in %s.",runFile);
assert(height(sensorTable) == numel(sensorIndices), ...
    "bestSensorTable has the wrong number of rows in %s.",runFile);

requiredVariables = ["Sensor","CandidateIndex","LatitudeDeg","LongitudeDeg"];
assert(all(ismember(requiredVariables,string(sensorTable.Properties.VariableNames))), ...
    "bestSensorTable is missing required columns in %s.",runFile);

assert(all(double(sensorTable.Sensor(:)) == (1:numel(sensorIndices)).'), ...
    "Sensor numbering is inconsistent in %s.",runFile);
assert(all(double(sensorTable.CandidateIndex(:)) == sensorIndices(:)), ...
    "CandidateIndex column is inconsistent in %s.",runFile);

assertAbsoluteEqual( ...
    deg2rad(double(sensorTable.LatitudeDeg(:))),latitudesRad(:), ...
    toleranceRad,sprintf("LatitudeDeg column is inconsistent in %s",runFile));
assertAbsoluteEqual( ...
    deg2rad(double(sensorTable.LongitudeDeg(:))),longitudesRad(:), ...
    toleranceRad,sprintf("LongitudeDeg column is inconsistent in %s",runFile));

end

function requireFields(inputStruct,fieldNames,context)

for fieldIndex = 1:numel(fieldNames)
    fieldName = char(fieldNames(fieldIndex));
    assert(isfield(inputStruct,fieldName), ...
        "%s is missing required field %s.",context,fieldName);
end

end

function assertRelativeEqual(actual,expected,tolerance,message)

actual = double(actual(:));
expected = double(expected(:));

assert(numel(actual) == numel(expected), ...
    "%s Array sizes differ.",message);
assert(all(isfinite(actual)) && all(isfinite(expected)), ...
    "%s Values must be finite.",message);

scale = max([1;abs(actual);abs(expected)]);
maximumDifference = max(abs(actual-expected),[],"all");

assert(maximumDifference <= tolerance*scale, ...
    "%s Maximum difference %.6e exceeds tolerance %.6e.", ...
    message,maximumDifference,tolerance*scale);

end

function assertAbsoluteEqual(actual,expected,tolerance,message)

actual = double(actual(:));
expected = double(expected(:));

assert(numel(actual) == numel(expected), ...
    "%s Array sizes differ.",message);
assert(all(isfinite(actual)) && all(isfinite(expected)), ...
    "%s Values must be finite.",message);

maximumDifference = max(abs(actual-expected),[],"all");
assert(maximumDifference <= tolerance, ...
    "%s Maximum difference %.6e exceeds tolerance %.6e.", ...
    message,maximumDifference,tolerance);

end

function timestamp = extractStudyTimestamp(folderName)

folderName = string(folderName);
tokens = regexp(folderName,"_(\d{8}_\d{6})$","tokens","once");

if isempty(tokens)
    timestamp = NaT;
else
    timestamp = datetime(string(tokens{1}), ...
        "InputFormat","yyyyMMdd_HHmmss");
end

end

function output = mergeStruct(defaults,override)

output = defaults;
fields = fieldnames(override);

for fieldIndex = 1:numel(fields)
    fieldName = fields{fieldIndex};
    output.(fieldName) = override.(fieldName);
end

end
