%% testMultiRsoTerrainRayClearance
% Validates the precomputed terrain-horizon gate against direct,
% range-aware terrain sampling for multiple sensors and RSOs.
%
% RSOs:
%   1. LRO-like 50 km polar orbit.
%   2. Chandrayaan-1-like 100 km polar orbit.
%   3. A 200 km, 60 degree inclined orbit.
%
% The test reports:
%   - Geometric measurement opportunities.
%   - Precomputed horizon-database measurements.
%   - Direct range-aware measurements.
%   - Conservative database rejections.
%   - False database clearances.
%
% False database clearances must be zero.

clear;
close all;
clc;

%% Add source directory

testDirectory = fileparts(mfilename("fullpath"));
repositoryDirectory = fileparts(testDirectory);
sourceDirectory = fullfile(repositoryDirectory, "src");

addpath(sourceDirectory);

requiredFunctions = [
    "orbitDynamics.propagateLunarOrbit"
    "digitalElevationModel.buildMaximumTerrainHorizonDatabase"
    "optimization.buildTerrainAwareLosDatabase"
];

for functionIndex = 1:length(requiredFunctions)

    functionName = requiredFunctions(functionIndex);

    assert(~isempty(which(functionName)), ...
        "%s was not found.", functionName);
end

%% Lunar constants

moonRadius = 1737.4;                  % km
moonMu = 4902.800066;                 % km^3/s^2

moonSiderealPeriod = ...
    27.321661 * 86400;                % s

moonAngularRate = ...
    2*pi / moonSiderealPeriod;        % rad/s

theta0 = 0;                           % rad

%% Load DEM

demFile = fullfile( ...
    repositoryDirectory, ...
    "data", ...
    "new_lunar_interpolant_model.mat");

if ~isfile(demFile)

    demFile = fullfile( ...
        repositoryDirectory, ...
        "new_lunar_interpolant_model.mat");
end

assert(isfile(demFile), ...
    "new_lunar_interpolant_model.mat was not found.");

demData = load(demFile);

assert(isfield(demData, "F"), ...
    "The DEM MAT-file must contain the interpolant F.");

sourceInterpolant = demData.F;

%% Convert DEM coordinates to radians

latitudeGridDegrees = ...
    sourceInterpolant.GridVectors{1}(:);

longitudeGridDegrees = ...
    sourceInterpolant.GridVectors{2}(:);

elevationGrid = ...
    sourceInterpolant.Values;

latitudeGrid = ...
    deg2rad(latitudeGridDegrees);

longitudeGrid = ...
    deg2rad(longitudeGridDegrees);

% Add a periodic longitude seam.

if longitudeGrid(end) - longitudeGrid(1) < ...
        2*pi - 1e-10

    longitudeGrid = [
        longitudeGrid
        longitudeGrid(1) + 2*pi
    ];

    elevationGrid = [
        elevationGrid, elevationGrid(:,1)
    ];
end

dem = griddedInterpolant( ...
    {latitudeGrid, longitudeGrid}, ...
    elevationGrid, ...
    "linear", ...
    "nearest");

%% Construct representative sensor sample

% Six latitude rings with four longitude samples per ring.
% Longitude offsets prevent all rings from sharing the same meridians.

sensorLatitudeLevels = [
    -89.5
    -87.0
    -84.0
    -81.0
    -78.0
    -75.5
];

baseLongitudes = [
    0
    90
    180
    270
];

numberOfLatitudeLevels = ...
    numel(sensorLatitudeLevels);

numberOfLongitudesPerLevel = ...
    numel(baseLongitudes);

numberOfSensors = ...
    numberOfLatitudeLevels * numberOfLongitudesPerLevel;

candidateLatitudes = zeros(numberOfSensors,1);
candidateLongitudes = zeros(numberOfSensors,1);

sensorIndex = 0;

for latitudeIndex = 1:numberOfLatitudeLevels

    longitudeOffset = ...
        15 * (latitudeIndex - 1);

    for longitudeIndex = 1:numberOfLongitudesPerLevel

        sensorIndex = sensorIndex + 1;

        candidateLatitudes(sensorIndex) = ...
            deg2rad( ...
                sensorLatitudeLevels(latitudeIndex));

        candidateLongitudes(sensorIndex) = ...
            deg2rad( ...
                mod( ...
                    baseLongitudes(longitudeIndex) + ...
                    longitudeOffset, ...
                    360));
    end
end

fprintf( ...
    "Representative surface sensors: %d\n", ...
    numberOfSensors);

%% Build terrain-horizon database

maximumTerrainRange = 100;            % km

% The previous single-sensor test used 0.1 km. A 0.5 km step is used here
% because this test evaluates multiple sensors and RSOs.

terrainRangeStep = 0.5;               % km
horizonAzimuthStep = deg2rad(1);      % rad

terrainTimer = tic;

[ ...
    horizonAzimuths, ...
    maximumTerrainElevation, ...
    ~, ...
    sensorElevations, ...
    ~ ...
] = digitalElevationModel.buildMaximumTerrainHorizonDatabase( ...
    candidateLatitudes, ...
    candidateLongitudes, ...
    dem, ...
    maximumTerrainRange, ...
    terrainRangeStep, ...
    horizonAzimuthStep, ...
    moonRadius);

terrainBuildTime = toc(terrainTimer);

assert(all(isfinite(maximumTerrainElevation), "all"), ...
    "The terrain-horizon database contains nonfinite values.");

assert(all(isfinite(sensorElevations)), ...
    "The sensor elevations contain nonfinite values.");

fprintf( ...
    "Terrain database build time: %.2f seconds\n", ...
    terrainBuildTime);

%% Define representative RSO set

objectNames = [
    "LRO-like 50 km polar"
    "Chandrayaan-1-like 100 km polar"
    "200 km, 60 deg inclined"
];

orbitAltitudes = [
    50
    100
    200
];

orbitInclinations = deg2rad([
    90
    90
    60
]);

orbitAscendingNodes = deg2rad([
    37
    120
    250
]);

numberOfObjects = ...
    numel(orbitAltitudes);

%% Common propagation times

observationArc = 6 * 3600;            % s
outputStep = 30;                      % s

requestedTimes = ...
    (0:outputStep:observationArc).';

numberOfTimes = ...
    numel(requestedTimes);

rsoStateHistories = zeros( ...
    6, ...
    numberOfTimes, ...
    numberOfObjects);

rotationZ = @(angle) [
     cos(angle), -sin(angle), 0
     sin(angle),  cos(angle), 0
              0,           0, 1
];

rotationX = @(angle) [
    1,          0,           0
    0, cos(angle), -sin(angle)
    0, sin(angle),  cos(angle)
];

%% Propagate RSO set

for objectIndex = 1:numberOfObjects

    orbitRadius = ...
        moonRadius + orbitAltitudes(objectIndex);

    circularVelocity = ...
        sqrt(moonMu / orbitRadius);

    perifocalPosition = [
        orbitRadius
        0
        0
    ];

    perifocalVelocity = [
        0
        circularVelocity
        0
    ];

    perifocalToMoonInertial = ...
        rotationZ(orbitAscendingNodes(objectIndex)) * ...
        rotationX(orbitInclinations(objectIndex));

    initialState = [
        perifocalToMoonInertial * perifocalPosition
        perifocalToMoonInertial * perifocalVelocity
    ];

    [propagatedTimes, propagatedStates] = ...
        orbitDynamics.propagateLunarOrbit( ...
            initialState, ...
            requestedTimes, ...
            moonMu = moonMu);

    assert( ...
        max(abs(propagatedTimes - requestedTimes)) < 1e-10, ...
        "The propagated time grid is incorrect.");

    if size(propagatedStates,2) == 6

        rsoStateHistories(:,:,objectIndex) = ...
            propagatedStates.';
    else

        rsoStateHistories(:,:,objectIndex) = ...
            propagatedStates;
    end
end

times = requestedTimes;

%% Evaluate precomputed terrain-horizon gate

instrumentMinimumElevation = deg2rad(0);
horizonMargin = deg2rad(0.1);

[ ...
    databaseAvailability, ...
    targetAzimuths, ...
    targetElevations, ...
    targetRanges, ...
    databaseLimitingElevations ...
] = optimization.buildTerrainAwareLosDatabase( ...
    times, ...
    rsoStateHistories, ...
    candidateLatitudes, ...
    candidateLongitudes, ...
    dem, ...
    horizonAzimuths, ...
    maximumTerrainElevation, ...
    instrumentMinimumElevation, ...
    horizonMargin, ...
    moonRadius, ...
    theta0, ...
    moonAngularRate);

geometricAvailability = ...
    targetElevations >= instrumentMinimumElevation;

assert( ...
    ~any( ...
        databaseAvailability & ...
        ~geometricAvailability, ...
        "all"), ...
    "The terrain database created a geometrically invalid measurement.");

%% Direct range-aware terrain sampling

terrainSearchRanges = ...
    (terrainRangeStep: ...
    terrainRangeStep: ...
    maximumTerrainRange).';

directAvailability = false( ...
    numberOfSensors, ...
    numberOfTimes, ...
    numberOfObjects);

directLimitingElevations = nan( ...
    numberOfSensors, ...
    numberOfTimes, ...
    numberOfObjects);

rawGeometryMismatchCount = 0;

clearanceTolerance = 1e-10;           % km
angleTolerance = 1e-12;               % rad

directTimer = tic;

for sensorIndex = 1:numberOfSensors

    sensorLatitude = ...
        candidateLatitudes(sensorIndex);

    sensorLongitude = ...
        candidateLongitudes(sensorIndex);

    sensorRadius = ...
        moonRadius + sensorElevations(sensorIndex);

    sinSensorLatitude = ...
        sin(sensorLatitude);

    cosSensorLatitude = ...
        cos(sensorLatitude);

    for objectIndex = 1:numberOfObjects

        for timeIndex = 1:numberOfTimes

            if ~geometricAvailability( ...
                    sensorIndex, ...
                    timeIndex, ...
                    objectIndex)

                directAvailability( ...
                    sensorIndex, ...
                    timeIndex, ...
                    objectIndex) = false;

                continue;
            end

            targetAzimuth = mod( ...
                targetAzimuths( ...
                    sensorIndex, ...
                    timeIndex, ...
                    objectIndex), ...
                2*pi);

            targetElevation = ...
                targetElevations( ...
                    sensorIndex, ...
                    timeIndex, ...
                    objectIndex);

            targetSlantRange = ...
                targetRanges( ...
                    sensorIndex, ...
                    timeIndex, ...
                    objectIndex);

            %% Target ground distance

            targetHorizontalDistance = ...
                targetSlantRange * ...
                cos(targetElevation);

            targetRadialCoordinate = ...
                sensorRadius + ...
                targetSlantRange * ...
                sin(targetElevation);

            targetCentralAngle = atan2( ...
                targetHorizontalDistance, ...
                targetRadialCoordinate);

            targetSurfaceDistance = ...
                moonRadius * targetCentralAngle;

            directMaximumRange = min( ...
                maximumTerrainRange, ...
                targetSurfaceDistance);

            sampledRanges = ...
                terrainSearchRanges( ...
                    terrainSearchRanges <= ...
                    directMaximumRange + 1e-12);

            if isempty(sampledRanges)

                directMaximumTerrainAngle = -pi/2;
                rawRayIsClear = true;

            else

                centralAngles = ...
                    sampledRanges / moonRadius;

                %% Terrain coordinates along the target azimuth

                sinTerrainLatitudes = ...
                    sinSensorLatitude .* ...
                        cos(centralAngles) + ...
                    cosSensorLatitude .* ...
                        sin(centralAngles) .* ...
                        cos(targetAzimuth);

                sinTerrainLatitudes = max( ...
                    -1, ...
                    min(1, sinTerrainLatitudes));

                terrainLatitudes = ...
                    asin(sinTerrainLatitudes);

                terrainLongitudes = ...
                    sensorLongitude + ...
                    atan2( ...
                        sin(targetAzimuth) .* ...
                            sin(centralAngles) .* ...
                            cosSensorLatitude, ...
                        cos(centralAngles) - ...
                            sinSensorLatitude .* ...
                            sinTerrainLatitudes);

                terrainLongitudesForDem = ...
                    wrapLongitudeForDem( ...
                        terrainLongitudes, ...
                        dem.GridVectors{2});

                terrainElevations = dem( ...
                    terrainLatitudes, ...
                    terrainLongitudesForDem);

                terrainRadii = ...
                    moonRadius + terrainElevations;

                %% Apparent terrain elevation

                terrainHorizontalDistances = ...
                    terrainRadii .* ...
                    sin(centralAngles);

                terrainVerticalDistances = ...
                    terrainRadii .* ...
                    cos(centralAngles) - ...
                    sensorRadius;

                terrainApparentAngles = atan2( ...
                    terrainVerticalDistances, ...
                    terrainHorizontalDistances);

                directMaximumTerrainAngle = ...
                    max(terrainApparentAngles);

                %% Direct ray clearance

                rayRadii = ...
                    sensorRadius * ...
                    cos(targetElevation) ./ ...
                    cos( ...
                        targetElevation + ...
                        centralAngles);

                rayClearances = ...
                    rayRadii - terrainRadii;

                minimumRayClearance = ...
                    min(rayClearances);

                rawRayIsClear = ...
                    minimumRayClearance >= ...
                    -clearanceTolerance;
            end

            %% Verify direct ray and angle formulations

            rawAngleIsClear = ...
                targetElevation >= ...
                directMaximumTerrainAngle - ...
                angleTolerance;

            if rawRayIsClear ~= rawAngleIsClear

                rawGeometryMismatchCount = ...
                    rawGeometryMismatchCount + 1;
            end

            %% Apply instrument minimum and horizon margin

            directLimitingElevation = max( ...
                instrumentMinimumElevation, ...
                directMaximumTerrainAngle + ...
                horizonMargin);

            directLimitingElevations( ...
                sensorIndex, ...
                timeIndex, ...
                objectIndex) = ...
                directLimitingElevation;

            directAvailability( ...
                sensorIndex, ...
                timeIndex, ...
                objectIndex) = ...
                targetElevation >= ...
                directLimitingElevation;
        end
    end
end

directEvaluationTime = toc(directTimer);

assert( ...
    rawGeometryMismatchCount == 0, ...
    ["The direct ray-radius test and direct apparent-angle test " ...
     "do not agree."]);

fprintf( ...
    "Direct ray evaluation time: %.2f seconds\n", ...
    directEvaluationTime);

%% Compare database and direct gates

falseClearances = ...
    databaseAvailability & ...
    ~directAvailability;

conservativeRejections = ...
    ~databaseAvailability & ...
    directAvailability & ...
    geometricAvailability;

gateAgreement = ...
    databaseAvailability == ...
    directAvailability;

geometricCounts = zeros(numberOfObjects,1);
databaseCounts = zeros(numberOfObjects,1);
directCounts = zeros(numberOfObjects,1);
visibleAgreementCounts = zeros(numberOfObjects,1);
conservativeCounts = zeros(numberOfObjects,1);
falseClearanceCounts = zeros(numberOfObjects,1);

for objectIndex = 1:numberOfObjects

    geometricCounts(objectIndex) = sum( ...
        geometricAvailability(:,:,objectIndex), ...
        "all");

    databaseCounts(objectIndex) = sum( ...
        databaseAvailability(:,:,objectIndex), ...
        "all");

    directCounts(objectIndex) = sum( ...
        directAvailability(:,:,objectIndex), ...
        "all");

    visibleAgreementCounts(objectIndex) = sum( ...
        gateAgreement(:,:,objectIndex) & ...
        geometricAvailability(:,:,objectIndex), ...
        "all");

    conservativeCounts(objectIndex) = sum( ...
        conservativeRejections(:,:,objectIndex), ...
        "all");

    falseClearanceCounts(objectIndex) = sum( ...
        falseClearances(:,:,objectIndex), ...
        "all");
end

%% Print per-object results

fprintf("\nMulti-RSO direct terrain comparison\n");

for objectIndex = 1:numberOfObjects

    fprintf( ...
        "\n%s\n", ...
        objectNames(objectIndex));

    fprintf( ...
        "  Geometric sensor-epochs:         %d\n", ...
        geometricCounts(objectIndex));

    fprintf( ...
        "  Horizon-database measurements:   %d\n", ...
        databaseCounts(objectIndex));

    fprintf( ...
        "  Direct range-aware measurements: %d\n", ...
        directCounts(objectIndex));

    fprintf( ...
        "  Visible-epoch gate agreements:   %d of %d\n", ...
        visibleAgreementCounts(objectIndex), ...
        geometricCounts(objectIndex));

    fprintf( ...
        "  Conservative rejections:         %d\n", ...
        conservativeCounts(objectIndex));

    fprintf( ...
        "  False clearances:                %d\n", ...
        falseClearanceCounts(objectIndex));
end

%% Overall results

totalGeometricCount = ...
    sum(geometricCounts);

totalDatabaseCount = ...
    sum(databaseCounts);

totalDirectCount = ...
    sum(directCounts);

totalConservativeCount = ...
    sum(conservativeCounts);

totalFalseClearanceCount = ...
    sum(falseClearanceCounts);

fprintf("\nOverall comparison\n");

fprintf( ...
    "  Sensors tested:                   %d\n", ...
    numberOfSensors);

fprintf( ...
    "  RSOs tested:                      %d\n", ...
    numberOfObjects);

fprintf( ...
    "  Geometric sensor-epochs:          %d\n", ...
    totalGeometricCount);

fprintf( ...
    "  Horizon-database measurements:    %d\n", ...
    totalDatabaseCount);

fprintf( ...
    "  Direct range-aware measurements:  %d\n", ...
    totalDirectCount);

fprintf( ...
    "  Conservative rejections:          %d\n", ...
    totalConservativeCount);

fprintf( ...
    "  False clearances:                 %d\n", ...
    totalFalseClearanceCount);

%% Assertions

assert(all(geometricCounts > 0), ...
    "At least one test RSO has no geometric visibility.");

assert( ...
    totalFalseClearanceCount == 0, ...
    ["The precomputed horizon database accepted at least one " ...
     "measurement that direct terrain sampling found obstructed."]);

%% Plot measurement comparison

% Each row represents one RSO.
% Columns represent:
%   1. Geometric LOS
%   2. Precomputed horizon
%   3. Direct range-aware result

comparisonCounts = [
    geometricCounts, ...
    databaseCounts, ...
    directCounts
];

figure( ...
    Name = "Multi-RSO Terrain Gate Comparison", ...
    Color = "white");

barHandles = bar( ...
    comparisonCounts, ...
    "grouped");

barHandles(1).FaceColor = [0.3010, 0.7450, 0.9330];
barHandles(2).FaceColor = [0.8500, 0.3250, 0.0980];
barHandles(3).FaceColor = [0.4660, 0.6740, 0.1880];

grid on;

xticks(1:numberOfObjects);
xticklabels(cellstr(objectNames));
xtickangle(15);

xlabel("Resident space object");
ylabel("Sensor-epoch opportunities");

title( ...
    sprintf( ...
        "Terrain Gate Validation Across %d Surface Sensors", ...
        numberOfSensors));

legend( ...
    barHandles, ...
    { ...
        "Geometric LOS", ...
        "Precomputed horizon", ...
        "Direct range-aware" ...
    }, ...
    Location = "best");

fprintf("\ntestMultiRsoTerrainRayClearance passed.\n");

%% Local function

function wrappedLongitudes = wrapLongitudeForDem( ...
    longitudes, ...
    demLongitudeGrid)
% Wrap longitude to match a 0-to-2*pi or -pi-to-pi DEM.

demLongitudeGrid = demLongitudeGrid(:);

if demLongitudeGrid(1) >= -1e-10 && ...
        demLongitudeGrid(end) > pi

    wrappedLongitudes = ...
        mod(longitudes, 2*pi);

else

    wrappedLongitudes = ...
        mod(longitudes + pi, 2*pi) - pi;
end
end