%% testOptimizationDatabaseScalability
% 20-RSO / reduced-candidate scalability test.
%
% The pilot uses:
%   - all 20 production RSOs
%   - 100 candidate LOCATIONS sampled from the real south-polar grid
%   - arbitrary configured network sizes
%   - one independent reference IOD for one fixed P0
%   - exactly the requested IOD observation count
%   - full terrain + Earth + Sun visibility
%   - production 8-hour / 60-second tracking definition
%   - selected-sensor objective slicing
%
% An RSO is NOT required to be visible. Zero coverage is a valid physical
% outcome and does not remove the RSO from the population.

clear;
close all;
clc;

%% ========================================================================
%  Paths
%  ========================================================================

testDirectory = ...
    fileparts(mfilename("fullpath"));

projectRoot = ...
    fileparts(testDirectory);

sourceDirectory = ...
    fullfile(projectRoot,"src");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

%% ========================================================================
%  Pilot definition
%  ========================================================================

numberOfPilotCandidates = ...
    100;

expectedNumberOfObjects = ...
    20;

% Current study values. Change only this vector to exercise different
% network sizes; the rest of this test is size agnostic.
networkSizes = ...
    sort(unique([3,5,7]));

%% ========================================================================
%  Constants
%  ========================================================================

moonRadius = ...
    1737.4;

%% ========================================================================
%  Load DEM
%  ========================================================================

demPath = ...
    fullfile( ...
        projectRoot, ...
        "data", ...
        "new_lunar_interpolant_model.mat");

assert(isfile(demPath), ...
    "DEM file was not found.");

demData = ...
    load(demPath,"F");

assert(isfield(demData,"F"), ...
    "DEM file must contain F.");

sourceDem = ...
    demData.F;

latitudeGrid = ...
    deg2rad(sourceDem.GridVectors{1}(:));

longitudeGrid = ...
    deg2rad(sourceDem.GridVectors{2}(:));

elevationGrid = ...
    sourceDem.Values;

if longitudeGrid(end) < 2*pi

    longitudeGrid = [ ...
        longitudeGrid
        2*pi
    ];

    elevationGrid = [ ...
        elevationGrid, ...
        elevationGrid(:,1)
    ];
end

dem = ...
    griddedInterpolant( ...
        {latitudeGrid,longitudeGrid}, ...
        elevationGrid, ...
        "linear", ...
        "nearest");

%% ========================================================================
%  Complete production candidate grid
%  ========================================================================

[fullCandidateLatitudes,fullCandidateLongitudes] = ...
    digitalElevationModel.buildCandidateSensorGrid( ...
        deg2rad([-90,-75]), ...
        deg2rad([0,360]), ...
        15, ...
        moonRadius);

numberOfFullCandidates = ...
    length(fullCandidateLatitudes);

assert(numberOfFullCandidates >= numberOfPilotCandidates, ...
    "Production candidate grid is smaller than the requested pilot.");

fprintf("\n");
fprintf("Full production candidate grid\n");
fprintf("------------------------------\n");
fprintf("Candidate locations: %d\n",numberOfFullCandidates);

%% ========================================================================
%  Spatially distributed pilot subset
%  ========================================================================

pilotCandidateIndices = ...
    selectSpatialPilotCandidates( ...
        fullCandidateLatitudes, ...
        fullCandidateLongitudes, ...
        numberOfPilotCandidates);

pilotCandidateLatitudes = ...
    fullCandidateLatitudes(pilotCandidateIndices);

pilotCandidateLongitudes = ...
    fullCandidateLongitudes(pilotCandidateIndices);

fprintf("Pilot candidate locations: %d\n", ...
    length(pilotCandidateIndices));

%% ========================================================================
%  Temporary output
%  ========================================================================

temporaryFile = ...
    string(tempname) + ".mat";

cleanupObject = ...
    onCleanup(@()cleanupFile(temporaryFile)); %#ok<NASGU>

%% ========================================================================
%  Production-like configuration
%  ========================================================================

config = struct();

config.outputFile = ...
    temporaryFile;

config.overwriteOutput = ...
    false;

config.demSource = ...
    string(demPath);

config.study.networkSizes = ...
    networkSizes;

config.study.objectiveModes = ...
    ["information","coverage"];

%% 20 production RSOs

config.rso.selection = ...
    "generated";

config.rso.numberOfGeneratedObjects = ...
    expectedNumberOfObjects;

config.rso.periapsisAltitudeLimitsKm = ...
    [50,5000];

config.rso.inclinationLimitsRad = ...
    deg2rad([0,180]);

config.rso.eccentricityLimits = ...
    [0,0.8];

%% Pilot candidate locations

config.candidates.customLatitudesRad = ...
    pilotCandidateLatitudes;

config.candidates.customLongitudesRad = ...
    pilotCandidateLongitudes;

config.candidateFilter.enabled = ...
    true;

config.candidateFilter.minimumGeometricEpochsForAnyObject = ...
    41;

config.candidateFilter.minimumFilteredEpochsTotal = ...
    1;

%% Production terrain

config.terrain.maximumRangeKm = ...
    100;

config.terrain.rangeStepKm = ...
    0.5;

config.terrain.horizonAzimuthStepRad = ...
    deg2rad(0.1);

config.terrain.horizonMarginRad = ...
    0;

%% Visibility

config.visibility.minimumElevationRad = ...
    0;

config.visibility.minimumAngularSeparationRad = ...
    deg2rad(20);

config.visibility.earthRadiusKm = ...
    6378.1366;

config.visibility.sunRadiusKm = ...
    695700;

%% Tracking

config.tracking.outputStepSeconds = ...
    60;

config.tracking.finalTimeSeconds = ...
    8*3600;

%% Measurement

config.measurement.rightAscensionSigmaRad = ...
    deg2rad(1/3600);

config.measurement.declinationSigmaRad = ...
    deg2rad(1/3600);

%% One fixed-P0 reference IOD

config.iod.referencePeriapsisAltitudeKm = ...
    50;

config.iod.referenceEccentricity = ...
    0;

config.iod.referenceInclinationRad = ...
    deg2rad(90);

config.iod.referenceRaanRad = ...
    deg2rad(37);

config.iod.referenceArgumentOfPeriapsisRad = ...
    0;

config.iod.referenceTrueAnomalyRad = ...
    0;

config.iod.referenceSensorLatitudeRad = ...
    deg2rad(-89.505332);

config.iod.referenceSensorLongitudeRad = ...
    deg2rad(102.857143);

config.iod.outputStepSeconds = ...
    10;

config.iod.desiredObservationCount = ...
    15;

config.iod.searchEndFraction = ...
    0.40;

config.iod.numberOfMonteCarloSamples = ...
    500;

config.iod.measurementNoiseSeedBase = ...
    1000;

config.iod.monteCarloSeedBase = ...
    2000;

%% Estimation

config.estimation.accelerationNoiseIntensity = ...
    1e-15;

config.estimation.stateScales = ...
    [1;1;1;1e-3;1e-3;1e-3];

config.estimation.objectWeights = ...
    ones(expectedNumberOfObjects,1);

%% ========================================================================
%  Build
%  ========================================================================

fprintf("\n");
fprintf("============================================================\n");
fprintf("Starting 20-RSO scalability database build\n");
fprintf("============================================================\n");

databaseTimer = ...
    tic;

database = ...
    optimization.buildOptimizationDatabase( ...
        dem, ...
        config);

measuredBuildRuntimeSeconds = ...
    toc(databaseTimer);

%% ========================================================================
%  Structural checks
%  ========================================================================

numberOfObjects = ...
    database.meta.numberOfObjects;

numberOfCandidatesRetained = ...
    database.meta.numberOfCandidates;

numberOfOptimizationTimes = ...
    database.meta.numberOfOptimizationEpochs;

assert(numberOfObjects == expectedNumberOfObjects, ...
    "Expected 20 RSOs.");

assert(numberOfCandidatesRetained >= max(networkSizes), ...
    "Too few candidate locations survived screening.");

assert(numberOfOptimizationTimes == ...
    config.tracking.finalTimeSeconds / ...
    config.tracking.outputStepSeconds, ...
    "Unexpected optimization epoch count.");

assert(isequal(database.study.networkSizes,networkSizes), ...
    "Database network-size configuration changed.");

%% ========================================================================
%  Verify single fixed P0 and exact IOD calibration
%  ========================================================================

P0 = ...
    database.prior.initialCovariance;

assert(all(isfinite(P0),"all"), ...
    "Fixed P0 contains nonfinite values.");

[~,positiveDefiniteFlag] = ...
    chol( ...
        0.5*(P0+P0.'), ...
        "lower");

assert(positiveDefiniteFlag == 0, ...
    "Fixed P0 is not positive definite.");

for objectIndex = 1:numberOfObjects

    assert(isequal( ...
        database.prior.initialCovariances(:,:,objectIndex), ...
        P0), ...
        "RSO %d does not use the common fixed P0.", ...
        objectIndex);
end

assert( ...
    length(database.iod.calibration.acquisitionIndices) == ...
    config.iod.desiredObservationCount, ...
    "Reference IOD did not use the requested observation count.");

assert( ...
    database.iod.calibration.desiredObservationCount == ...
    config.iod.desiredObservationCount, ...
    "Stored IOD observation-count metadata is inconsistent.");

assert( ...
    database.iod.calibration.outputStepSeconds == ...
    config.iod.outputStepSeconds, ...
    "Stored IOD cadence is inconsistent.");

assert( ...
    database.iod.calibration.diagnostics.numberOfRequestedSamples == ...
    config.iod.numberOfMonteCarloSamples, ...
    "Reference IOD Monte Carlo sample count changed.");

assert( ...
    database.iod.calibration.diagnostics.numberOfSuccessfulSamples >= ...
    ceil(0.8*config.iod.numberOfMonteCarloSamples), ...
    "Reference IOD Monte Carlo convergence is below 80 percent.");

%% ========================================================================
%  All 20 RSOs remain in population regardless of visibility
%  ========================================================================

assert(height(database.rso.catalog) == ...
    expectedNumberOfObjects, ...
    "An RSO was removed from the population.");

assert(size( ...
    database.visibility.filteredAvailability,3) == ...
    expectedNumberOfObjects, ...
    "Visibility database does not contain all 20 RSOs.");

%% ========================================================================
%  Accepted measurements by RSO
%  ========================================================================

acceptedObservationsByObject = ...
    reshape( ...
        sum( ...
            database.visibility.filteredAvailability, ...
            [1,2]), ...
        numberOfObjects, ...
        1);

unobservableObjectMask = ...
    acceptedObservationsByObject == 0;

numberOfUnobservableObjects = ...
    nnz(unobservableObjectMask);

assert(all(isfinite(acceptedObservationsByObject)), ...
    "Observation counts are invalid.");

%% ========================================================================
%  Numerical database checks
%  ========================================================================

assert(all(isfinite( ...
    database.tracking.referenceStateHistories),"all"));

assert(all(isfinite( ...
    database.tracking.stateTransitionHistories),"all"));

assert(all(isfinite( ...
    database.tracking.processNoiseHistories),"all"));

assert(all(isfinite( ...
    database.tracking.measurementJacobianHistories),"all"));

assert(all( ...
    database.visibility.filteredAvailability <= ...
    database.visibility.terrainAvailability, ...
    "all"));

assert(all( ...
    database.visibility.terrainAvailability <= ...
    database.visibility.geometricAvailability, ...
    "all"));

%% ========================================================================
%  Representative nested networks for every configured size
%  ========================================================================

maximumNetworkSize = ...
    max(networkSizes);

maximumNetwork = ...
    evenlyDistributedIndices( ...
        numberOfCandidatesRetained, ...
        maximumNetworkSize);

numberOfNetworkSizes = ...
    length(networkSizes);

representativeNetworks = ...
    cell(numberOfNetworkSizes,1);

for sizeIndex = 1:numberOfNetworkSizes

    representativeNetworks{sizeIndex} = ...
        maximumNetwork(1:networkSizes(sizeIndex));
end

%% ========================================================================
%  Objective timing for every configured network size
%  ========================================================================

informationObjectives = ...
    zeros(numberOfNetworkSizes,1);

coverageObjectives = ...
    zeros(numberOfNetworkSizes,1);

informationRuntimes = ...
    zeros(numberOfNetworkSizes,1);

coverageRuntimes = ...
    zeros(numberOfNetworkSizes,1);

for sizeIndex = 1:numberOfNetworkSizes

    currentNetwork = ...
        representativeNetworks{sizeIndex};

    timer = tic;

    informationObjectives(sizeIndex) = ...
        optimization.networkObjective( ...
            currentNetwork, ...
            database, ...
            "information");

    informationRuntimes(sizeIndex) = ...
        toc(timer);

    timer = tic;

    coverageObjectives(sizeIndex) = ...
        optimization.networkObjective( ...
            currentNetwork, ...
            database, ...
            "coverage");

    coverageRuntimes(sizeIndex) = ...
        toc(timer);
end

assert(all(isfinite(informationObjectives)), ...
    "At least one information objective is nonfinite.");

assert(all(isfinite(coverageObjectives)), ...
    "At least one coverage objective is nonfinite.");

for sizeIndex = 2:numberOfNetworkSizes

    assert( ...
        coverageObjectives(sizeIndex) <= ...
        coverageObjectives(sizeIndex-1)+1e-12, ...
        "Adding sensors reduced coverage.");
end

%% ========================================================================
%  Slicing equivalence, determinism, and sensor-order invariance
%  ========================================================================

baseNetwork = ...
    representativeNetworks{1};

fullSelectedSensors = ...
    false(numberOfCandidatesRetained,1);

fullSelectedSensors(baseNetwork) = ...
    true;

[directInformationObjective,directInformationByObject] = ...
    optimization.informationObjective( ...
        fullSelectedSensors, ...
        database.prior.initialCovariances, ...
        database.tracking.stateTransitionHistories, ...
        database.tracking.processNoiseHistories, ...
        database.tracking.measurementJacobianHistories, ...
        database.visibility.filteredAvailability, ...
        database.measurement.covariance, ...
        database.estimation.stateScales, ...
        database.estimation.objectWeights);

[directCoverageObjective,directCoverageByObject] = ...
    optimization.coverageObjective( ...
        fullSelectedSensors, ...
        database.visibility.filteredAvailability, ...
        database.estimation.objectWeights);

informationTolerance = ...
    1e-12*max(1,abs(informationObjectives(1)));

assert(abs( ...
    directInformationObjective-informationObjectives(1)) <= ...
    informationTolerance, ...
    "Selected-sensor slicing changed the information objective.");

assert(abs( ...
    directCoverageObjective-coverageObjectives(1)) <= 1e-12, ...
    "Selected-sensor slicing changed the coverage objective.");

informationRepeat = ...
    optimization.networkObjective( ...
        baseNetwork, ...
        database, ...
        "information");

assert(abs( ...
    informationRepeat-informationObjectives(1)) <= ...
    informationTolerance, ...
    "Information objective is not deterministic.");

permutedNetwork = ...
    baseNetwork(end:-1:1);

informationPermuted = ...
    optimization.networkObjective( ...
        permutedNetwork, ...
        database, ...
        "information");

coveragePermuted = ...
    optimization.networkObjective( ...
        permutedNetwork, ...
        database, ...
        "coverage");

assert(abs( ...
    informationPermuted-informationObjectives(1)) <= ...
    informationTolerance, ...
    "Information objective depends on sensor order.");

assert(abs( ...
    coveragePermuted-coverageObjectives(1)) <= 1e-12, ...
    "Coverage objective depends on sensor order.");

[~,details] = ...
    optimization.networkObjective( ...
        baseNetwork, ...
        database, ...
        "information");

assert(max(abs( ...
    details.informationByObject-directInformationByObject)) <= ...
    informationTolerance, ...
    "Information-by-object diagnostics changed after slicing.");

assert(max(abs( ...
    details.coverageByObject-directCoverageByObject)) <= 1e-12, ...
    "Coverage-by-object diagnostics changed after slicing.");

%% ========================================================================
%  Memory accounting
%  ========================================================================

jacobianBytes = ...
    numel( ...
        database.tracking.measurementJacobianHistories) * 8;

stateTransitionBytes = ...
    numel( ...
        database.tracking.stateTransitionHistories) * 8;

processNoiseBytes = ...
    numel( ...
        database.tracking.processNoiseHistories) * 8;

referenceStateBytes = ...
    numel( ...
        database.tracking.referenceStateHistories) * 8;

filteredAvailabilityBytes = ...
    numel( ...
        database.visibility.filteredAvailability);

majorTrackingBytes = ...
    jacobianBytes + ...
    stateTransitionBytes + ...
    processNoiseBytes + ...
    referenceStateBytes + ...
    filteredAvailabilityBytes;

pilotRetentionFraction = ...
    numberOfCandidatesRetained / ...
    numberOfPilotCandidates;

estimatedFullRetainedCandidates = ...
    round( ...
        pilotRetentionFraction * ...
        numberOfFullCandidates);

jacobianBytesPerCandidate = ...
    jacobianBytes / ...
    numberOfCandidatesRetained;

estimatedFullJacobianBytes = ...
    jacobianBytesPerCandidate * ...
    estimatedFullRetainedCandidates;

%% ========================================================================
%  Per-RSO summary
%  ========================================================================

fprintf("\n");
fprintf("20-RSO visibility summary\n");
fprintf("-------------------------\n");

for objectIndex = 1:numberOfObjects

    objectName = ...
        string(database.rso.catalog.Name(objectIndex));

    fprintf( ...
        "%2d  %-18s | accepted sensor-epochs: %8d", ...
        objectIndex, ...
        objectName, ...
        acceptedObservationsByObject(objectIndex));

    if unobservableObjectMask(objectIndex)
        fprintf("  <-- zero coverage allowed");
    end

    fprintf("\n");
end

%% ========================================================================
%  Final scalability summary
%  ========================================================================

fprintf("\n");
fprintf("============================================================\n");
fprintf("Optimization database scalability summary\n");
fprintf("============================================================\n");

fprintf("\nStudy size\n");
fprintf("----------------------------------\n");
fprintf("RSOs:                         %d\n",numberOfObjects);
fprintf("Full production candidates:   %d\n",numberOfFullCandidates);
fprintf("Pilot candidate locations:    %d\n",numberOfPilotCandidates);
fprintf("Pilot candidates retained:    %d\n",numberOfCandidatesRetained);
fprintf("Optimization epochs:          %d\n",numberOfOptimizationTimes);
fprintf("Unobservable RSOs in pilot:   %d\n",numberOfUnobservableObjects);

fprintf("\nFixed P0 calibration\n");
fprintf("----------------------------------\n");
fprintf("IOD cadence:                   %.1f s\n", ...
    database.iod.calibration.outputStepSeconds);
fprintf("IOD observations:              %d/%d\n", ...
    length(database.iod.calibration.acquisitionIndices), ...
    config.iod.desiredObservationCount);
fprintf("IOD MC convergence:            %d/%d\n", ...
    database.iod.calibration.diagnostics.numberOfSuccessfulSamples, ...
    database.iod.calibration.diagnostics.numberOfRequestedSamples);

fprintf("\nBuild performance\n");
fprintf("----------------------------------\n");
fprintf("Measured build runtime:        %.2f min\n", ...
    measuredBuildRuntimeSeconds/60);

fprintf("\nObjective scores\n");
fprintf("----------------------------------\n");

for sizeIndex = 1:numberOfNetworkSizes
    fprintf("%2d-sensor information:        %.8f\n", ...
        networkSizes(sizeIndex), ...
        -informationObjectives(sizeIndex));
end

fprintf("\n");

for sizeIndex = 1:numberOfNetworkSizes
    fprintf("%2d-sensor coverage:           %.0f\n", ...
        networkSizes(sizeIndex), ...
        -coverageObjectives(sizeIndex));
end

fprintf("\nObjective runtime\n");
fprintf("----------------------------------\n");

for sizeIndex = 1:numberOfNetworkSizes
    fprintf("Information, %2d sensors:      %.4f s\n", ...
        networkSizes(sizeIndex), ...
        informationRuntimes(sizeIndex));
end

fprintf("\n");

for sizeIndex = 1:numberOfNetworkSizes
    fprintf("Coverage, %2d sensors:         %.6f s\n", ...
        networkSizes(sizeIndex), ...
        coverageRuntimes(sizeIndex));
end

fprintf("\nMemory\n");
fprintf("----------------------------------\n");
fprintf("Pilot Jacobian memory:         %.2f MB\n", ...
    jacobianBytes/1024^2);
fprintf("Major tracking arrays:         %.2f MB\n", ...
    majorTrackingBytes/1024^2);
fprintf("Estimated retained full grid:  %d\n", ...
    estimatedFullRetainedCandidates);
fprintf("Estimated full Jacobians:      %.2f GB\n", ...
    estimatedFullJacobianBytes/1024^3);

fprintf("\n");
fprintf("Single fixed P0:               passed\n");
fprintf("Exact IOD sample count:        passed\n");
fprintf("All 20 RSOs retained:          passed\n");
fprintf("Selected-sensor slicing:       passed\n");
fprintf("Objective determinism:         passed\n");
fprintf("Sensor-order invariance:       passed\n");
fprintf("Coverage monotonicity:         passed\n");
fprintf("\n");
fprintf("testOptimizationDatabaseScalability passed.\n");

%% ========================================================================
%  Local functions
%  ========================================================================

function selectedIndices = ...
    selectSpatialPilotCandidates( ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        targetCount)

candidateLatitudes = ...
    candidateLatitudes(:);

candidateLongitudes = ...
    candidateLongitudes(:);

numberOfCandidates = ...
    length(candidateLatitudes);

assert(targetCount <= numberOfCandidates);

uniqueLatitudes = ...
    unique(candidateLatitudes);

numberOfLatitudeRings = ...
    length(uniqueLatitudes);

desiredNumberOfRings = ...
    min(12,numberOfLatitudeRings);

ringLocations = ...
    unique(round(linspace( ...
        1, ...
        numberOfLatitudeRings, ...
        desiredNumberOfRings)));

selectedIndices = ...
    zeros(0,1);

numberPerRing = ...
    ceil(targetCount/length(ringLocations));

latitudeTolerance = ...
    1e-12;

for ringIndex = 1:length(ringLocations)

    ringLatitude = ...
        uniqueLatitudes(ringLocations(ringIndex));

    ringIndices = ...
        find(abs( ...
            candidateLatitudes-ringLatitude) < ...
            latitudeTolerance);

    [~,longitudeOrder] = ...
        sort(candidateLongitudes(ringIndices));

    ringIndices = ...
        ringIndices(longitudeOrder);

    numberToTake = ...
        min(numberPerRing,length(ringIndices));

    locations = ...
        unique(round(linspace( ...
            1, ...
            length(ringIndices), ...
            numberToTake)));

    selectedIndices = [ ...
        selectedIndices
        ringIndices(locations)
    ]; %#ok<AGROW>
end

selectedIndices = ...
    unique(selectedIndices,"stable");

if length(selectedIndices) < targetCount

    unused = ...
        setdiff( ...
            (1:numberOfCandidates).', ...
            selectedIndices, ...
            "stable");

    numberNeeded = ...
        targetCount-length(selectedIndices);

    fillLocations = ...
        unique(round(linspace( ...
            1, ...
            length(unused), ...
            numberNeeded)));

    selectedIndices = [ ...
        selectedIndices
        unused(fillLocations)
    ];
end

if length(selectedIndices) > targetCount

    locations = ...
        round(linspace( ...
            1, ...
            length(selectedIndices), ...
            targetCount));

    selectedIndices = ...
        selectedIndices(locations);
end

if length(selectedIndices) < targetCount

    unused = ...
        setdiff( ...
            (1:numberOfCandidates).', ...
            selectedIndices, ...
            "stable");

    numberNeeded = ...
        targetCount-length(selectedIndices);

    selectedIndices = [ ...
        selectedIndices
        unused(1:numberNeeded)
    ];
end

assert(length(selectedIndices) == targetCount);
assert(length(unique(selectedIndices)) == targetCount);

selectedIndices = ...
    sort(selectedIndices);

end

function indices = ...
    evenlyDistributedIndices( ...
        numberOfCandidates, ...
        numberToSelect)

assert(numberToSelect <= numberOfCandidates);

indices = ...
    unique(round(linspace( ...
        1, ...
        numberOfCandidates, ...
        numberToSelect)));

if length(indices) < numberToSelect

    unused = ...
        setdiff( ...
            1:numberOfCandidates, ...
            indices, ...
            "stable");

    indices = [ ...
        indices, ...
        unused(1:numberToSelect-length(indices)) ...
    ];
end

indices = ...
    sort(indices(:));

assert(length(indices) == numberToSelect);
assert(length(unique(indices)) == numberToSelect);

end

function cleanupFile(fileName)

if isfile(fileName)

    try
        delete(fileName);
    catch
    end
end

end
