%% testLroCandidateNetwork
% Test the complete candidate-network workflow:
%
%   1. Generate a representative IOD state and covariance.
%   2. Hold the IOD state and P0 fixed.
%   3. Precompute candidate-dependent Jacobians and LOS gates.
%   4. Evaluate coverage and information objectives.
%   5. Select the best two-sensor network.
%   6. Generate noisy measurements and run the full EKF.
%
% This test currently uses geometric elevation for LOS. The terrain-horizon
% database can later replace the geometric availability matrix.

clear;
close all;
clc;

rng(11,"twister");

%% Project paths

testDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testDirectory);
sourceDirectory = fullfile(projectRoot,"src");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

requiredFunctions = [
    "orbitDynamics.propagateLunarOrbit"
    "orbitDynamics.lunarStateAndStmDynamics"
    "referenceFrames.moonRotating"
    "referenceFrames.topographic"
    "measurements.surfaceRaDecMeasurement"
    "measurements.surfaceRaDecJacobian"
    "iod.anglesOnlyIod"
    "estimation.isotropicProcessNoise"
    "estimation.propagateNetworkCovariance"
    "estimation.lunarSurfaceEkf"
    "optimization.precomputeTrackingData"
    "optimization.informationObjective"
    "optimization.coverageObjective"
    "lsqnonlin"
];

for functionIndex = 1:length(requiredFunctions)

    functionName = requiredFunctions(functionIndex);

    assert(~isempty(which(functionName)), ...
        "%s was not found.",functionName);
end

%% Load and process DEM

demPath = fullfile( ...
    projectRoot, ...
    "data", ...
    "new_lunar_interpolant_model.mat");

if ~isfile(demPath)
    demPath = fullfile( ...
        testDirectory, ...
        "new_lunar_interpolant_model.mat");
end

assert(isfile(demPath), ...
    "DEM file was not found.");

demData = load(demPath,"F");

assert(isfield(demData,"F"), ...
    "DEM file must contain a variable named F.");

assert(isa(demData.F,"griddedInterpolant"), ...
    "F must be a griddedInterpolant.");

sourceDem = demData.F;

latitudeGrid = deg2rad( ...
    sourceDem.GridVectors{1}(:));

longitudeGrid = deg2rad( ...
    sourceDem.GridVectors{2}(:));

elevationGrid = sourceDem.Values;

if longitudeGrid(end) < 2*pi

    longitudeGrid = [
        longitudeGrid
        2*pi
    ];

    elevationGrid = [
        elevationGrid, ...
        elevationGrid(:,1)
    ];
end

dem = griddedInterpolant( ...
    {latitudeGrid,longitudeGrid}, ...
    elevationGrid, ...
    "linear", ...
    "nearest");

%% Lunar constants

moonRadius = 1737.4;                  % km
moonMu = 4902.800066;                 % km^3/s^2

moonSiderealPeriod = ...
    27.321661*86400;                  % s

moonAngularRate = ...
    2*pi/moonSiderealPeriod;          % rad/s

theta0 = 0;                           % rad

%% Measurement and filter settings

minimumElevation = deg2rad(0);

rightAscensionSigma = ...
    deg2rad(1/3600);                  % 1 arcsecond

declinationSigma = ...
    deg2rad(1/3600);                  % 1 arcsecond

measurementCovariance = diag([
    rightAscensionSigma^2
    declinationSigma^2
]);

measurementNoiseFactor = ...
    chol(measurementCovariance,"lower");

accelerationNoiseIntensity = ...
    1e-15;                            % km^2/s^3

stateScales = [
    1
    1
    1
    1e-3
    1e-3
    1e-3
];

%% LRO-like truth orbit

orbitAltitude = 50;                   % km
orbitRadius = moonRadius + orbitAltitude;
orbitInclination = deg2rad(90);

% Align the polar orbit with the representative sensor.
rightAscensionAscendingNode = ...
    deg2rad(37);

rotationZ = [
     cos(rightAscensionAscendingNode), ...
    -sin(rightAscensionAscendingNode), ...
     0
     sin(rightAscensionAscendingNode), ...
     cos(rightAscensionAscendingNode), ...
     0
     0,0,1
];

rotationX = [
    1,0,0
    0,cos(orbitInclination),-sin(orbitInclination)
    0,sin(orbitInclination), cos(orbitInclination)
];

perifocalToMci = ...
    rotationZ*rotationX;

circularSpeed = ...
    sqrt(moonMu/orbitRadius);

truthInitialPosition = ...
    perifocalToMci*[orbitRadius;0;0];

truthInitialVelocity = ...
    perifocalToMci*[0;circularSpeed;0];

truthInitialState = [
    truthInitialPosition
    truthInitialVelocity
];

orbitPeriod = ...
    2*pi*sqrt(orbitRadius^3/moonMu);

numberOfPeriods = 4;
outputStep = 20;                      % s
finalTime = numberOfPeriods*orbitPeriod;

timeSpan = (0:outputStep:finalTime).';

if timeSpan(end) < finalTime
    timeSpan(end+1,1) = finalTime;
end

%% Propagate truth orbit

[times,statesMoonInertial] = ...
    orbitDynamics.propagateLunarOrbit( ...
        truthInitialState, ...
        timeSpan, ...
        moonMu=moonMu);

truthStateHistory = ...
    statesMoonInertial.';

numberOfTimes = length(times);

%% Representative sensor used only to establish the common prior

representativeLatitude = ...
    deg2rad(-84);

representativeLongitude = ...
    deg2rad(37);

[representativeObserverPositions, ...
    representativeAvailability, ...
    representativeElevation, ...
    representativeRightAscension, ...
    representativeDeclination] = ...
    simulateSingleSurfaceSensor( ...
        times, ...
        truthStateHistory, ...
        representativeLatitude, ...
        representativeLongitude, ...
        dem, ...
        minimumElevation, ...
        measurementNoiseFactor, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate);

assert(sum(representativeAvailability) >= 3, ...
    "The representative sensor has fewer than three observations.");

%% Select first continuous pass for representative IOD

availableIndices = ...
    find(representativeAvailability);

firstGapLocation = ...
    find(diff(availableIndices) > 1,1,"first");

if isempty(firstGapLocation)
    firstPassIndices = availableIndices;
else
    firstPassIndices = ...
        availableIndices(1:firstGapLocation);
end

assert(length(firstPassIndices) >= 3, ...
    "The first representative pass has fewer than three observations.");

desiredIodObservationCount = 15;

numberOfIodObservations = min( ...
    desiredIodObservationCount, ...
    length(firstPassIndices));

selectionLocations = unique(round(linspace( ...
    1, ...
    length(firstPassIndices), ...
    numberOfIodObservations)));

acquisitionIndices = ...
    firstPassIndices(selectionLocations);

acquisitionIndices = ...
    acquisitionIndices(:);

%% Generate the representative fixed prior

numberOfMonteCarloSamples = 100;
iodRandomSeed = 21;

[fixedInitialState,fixedInitialCovariance, ...
    fixedReferenceTime,iodDiagnostics] = ...
    iod.anglesOnlyIod( ...
        times, ...
        representativeRightAscension, ...
        representativeDeclination, ...
        representativeObserverPositions, ...
        acquisitionIndices, ...
        measurementCovariance, ...
        numberOfMonteCarloSamples, ...
        iodRandomSeed, ...
        moonMu);

fixedInitialCovariance = ...
    0.5*(fixedInitialCovariance + ...
    fixedInitialCovariance');

[~,initialCovarianceFlag] = ...
    chol(fixedInitialCovariance,"lower");

assert(initialCovarianceFlag == 0, ...
    "The representative IOD covariance is not positive definite.");

fixedReferenceIndex = ...
    acquisitionIndices(end);

assert(abs( ...
    times(fixedReferenceIndex) - ...
    fixedReferenceTime) < 1e-9, ...
    "IOD reference time does not match the acquisition endpoint.");

%% Candidate surface locations

candidateNames = [
    "Candidate 1"
    "Candidate 2"
    "Candidate 3"
];

candidateLatitudes = deg2rad([
    -84
    -86
    -86
]);

candidateLongitudes = deg2rad([
     37
    120
    300
]);

numberOfCandidates = ...
    length(candidateLatitudes);

measurementCovariances = repmat( ...
    measurementCovariance, ...
    1,1,numberOfCandidates);

%% Observation arc after representative IOD

optimizationIndices = ...
    find(times > fixedReferenceTime);

optimizationTimes = ...
    times(optimizationIndices);

truthOptimizationHistory = ...
    truthStateHistory(:,optimizationIndices);

numberOfOptimizationTimes = ...
    length(optimizationTimes);

assert(numberOfOptimizationTimes > 0, ...
    "No tracking arc remains after the representative IOD.");

%% Precompute candidate tracking database

[referenceStateHistory, ...
    stateTransitionHistory, ...
    processNoiseHistory, ...
    measurementJacobianHistory, ...
    measurementAvailability, ...
    candidateElevation] = ...
    optimization.precomputeTrackingData( ...
        fixedReferenceTime, ...
        optimizationTimes, ...
        fixedInitialState, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        minimumElevation, ...
        accelerationNoiseIntensity, ...
        moonMu, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate);

assert(all(any(measurementAvailability,2)), ...
    "At least one candidate sensor never establishes geometric LOS.");

%% Convert single-object data to optimization database dimensions

initialCovariances = reshape( ...
    fixedInitialCovariance, ...
    6,6,1);

stateTransitionHistories = reshape( ...
    stateTransitionHistory, ...
    6,6,numberOfOptimizationTimes,1);

processNoiseHistories = reshape( ...
    processNoiseHistory, ...
    6,6,numberOfOptimizationTimes,1);

measurementJacobianHistories = reshape( ...
    measurementJacobianHistory, ...
    2,6,numberOfCandidates, ...
    numberOfOptimizationTimes,1);

measurementAvailabilityDatabase = reshape( ...
    measurementAvailability, ...
    numberOfCandidates, ...
    numberOfOptimizationTimes,1);

objectWeights = 1;

%% Candidate networks

networkNames = [
    "No sensors"
    "Candidate 1"
    "Candidate 2"
    "Candidate 3"
    "Candidates 1 + 2"
    "Candidates 1 + 3"
    "Candidates 2 + 3"
];

networkSelections = [
    0,1,0,0,1,1,0
    0,0,1,0,1,0,1
    0,0,0,1,0,1,1
];

numberOfNetworks = ...
    size(networkSelections,2);

informationObjectives = ...
    zeros(numberOfNetworks,1);

informationScores = ...
    zeros(numberOfNetworks,1);

coverageObjectives = ...
    zeros(numberOfNetworks,1);

coverageCounts = ...
    zeros(numberOfNetworks,1);

%% Evaluate candidate networks

for networkIndex = 1:numberOfNetworks

    selectedSensors = ...
        networkSelections(:,networkIndex);

    [informationObjectives(networkIndex),~] = ...
        optimization.informationObjective( ...
            selectedSensors, ...
            initialCovariances, ...
            stateTransitionHistories, ...
            processNoiseHistories, ...
            measurementJacobianHistories, ...
            measurementAvailabilityDatabase, ...
            measurementCovariances, ...
            stateScales, ...
            objectWeights);

    informationScores(networkIndex) = ...
        -informationObjectives(networkIndex);

    [coverageObjectives(networkIndex), ...
        objectCoverage] = ...
        optimization.coverageObjective( ...
            selectedSensors, ...
            measurementAvailabilityDatabase, ...
            objectWeights);

    coverageCounts(networkIndex) = ...
        objectCoverage(1);
end

%% Validate candidate comparisons

noSensorIndex = 1;
candidateOneIndex = 2;
candidateTwoIndex = 3;
candidateThreeIndex = 4;
pairOneTwoIndex = 5;
pairOneThreeIndex = 6;
pairTwoThreeIndex = 7;

assert(coverageCounts(noSensorIndex) == 0, ...
    "No-sensor coverage should be zero.");

assert(informationScores(candidateOneIndex) > ...
    informationScores(noSensorIndex), ...
    "Candidate one did not improve information.");

assert(informationScores(candidateTwoIndex) > ...
    informationScores(noSensorIndex), ...
    "Candidate two did not improve information.");

assert(informationScores(candidateThreeIndex) > ...
    informationScores(noSensorIndex), ...
    "Candidate three did not improve information.");

comparisonTolerance = 1e-8;

assert(informationScores(pairOneTwoIndex) >= ...
    max(informationScores([ ...
        candidateOneIndex,candidateTwoIndex])) - ...
    comparisonTolerance, ...
    "Candidates 1 + 2 performed worse than an individual sensor.");

assert(informationScores(pairOneThreeIndex) >= ...
    max(informationScores([ ...
        candidateOneIndex,candidateThreeIndex])) - ...
    comparisonTolerance, ...
    "Candidates 1 + 3 performed worse than an individual sensor.");

assert(informationScores(pairTwoThreeIndex) >= ...
    max(informationScores([ ...
        candidateTwoIndex,candidateThreeIndex])) - ...
    comparisonTolerance, ...
    "Candidates 2 + 3 performed worse than an individual sensor.");

%% Select the best two-sensor network

pairNetworkIndices = [
    pairOneTwoIndex
    pairOneThreeIndex
    pairTwoThreeIndex
];

[~,bestPairLocation] = max( ...
    informationScores(pairNetworkIndices));

bestNetworkIndex = ...
    pairNetworkIndices(bestPairLocation);

bestSensorSelection = ...
    logical(networkSelections(:,bestNetworkIndex));

bestSensorIndices = ...
    find(bestSensorSelection);

%% Recalculate best-network covariance history

[bestCovarianceHistory,bestDOptimalityHistory] = ...
    estimation.propagateNetworkCovariance( ...
        fixedInitialCovariance, ...
        stateTransitionHistory, ...
        processNoiseHistory, ...
        measurementJacobianHistory, ...
        measurementAvailability, ...
        bestSensorSelection, ...
        measurementCovariances, ...
        stateScales);

%% Generate selected-network measurements for the final EKF

[finalObservationTimes, ...
    finalRightAscension, ...
    finalDeclination, ...
    finalSensorLatitudes, ...
    finalSensorLongitudes, ...
    finalMeasurementAvailable] = ...
    simulateSelectedNetwork( ...
        optimizationTimes, ...
        truthOptimizationHistory, ...
        bestSensorIndices, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        minimumElevation, ...
        measurementNoiseFactor, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate);

%% Run final state-updating EKF

[finalStateHistory,finalCovarianceHistory, ...
    finalInnovationHistory, ...
    finalMeasurementInformationHistory] = ...
    estimation.lunarSurfaceEkf( ...
        fixedReferenceTime, ...
        finalObservationTimes, ...
        finalRightAscension, ...
        finalDeclination, ...
        finalSensorLatitudes, ...
        finalSensorLongitudes, ...
        dem, ...
        finalMeasurementAvailable, ...
        fixedInitialState, ...
        fixedInitialCovariance, ...
        measurementCovariance, ...
        accelerationNoiseIntensity, ...
        moonMu, ...
        moonRadius, ...
        theta0, ...
        moonAngularRate);

assert(any(all(isfinite(finalInnovationHistory),1)), ...
    "The final EKF performed no measurement updates.");

assert(all(isfinite(finalStateHistory),"all"), ...
    "The final EKF state history contains nonfinite values.");

assert(all(isfinite(finalCovarianceHistory),"all"), ...
    "The final EKF covariance history contains nonfinite values.");

%% Extract posterior after all sensors at each time

numberOfSelectedSensors = ...
    length(bestSensorIndices);

posteriorIndices = ...
    numberOfSelectedSensors : ...
    numberOfSelectedSensors : ...
    length(finalObservationTimes);

posteriorStateHistory = ...
    finalStateHistory(:,posteriorIndices);

posteriorCovarianceHistory = ...
    finalCovarianceHistory(:,:,posteriorIndices);

assert(size(posteriorStateHistory,2) == ...
    numberOfOptimizationTimes, ...
    "Final EKF posterior indexing is inconsistent.");

%% Final EKF errors

stateError = ...
    posteriorStateHistory - ...
    truthOptimizationHistory;

positionErrorNorm = ...
    vecnorm(stateError(1:3,:),2,1);

velocityErrorNorm = ...
    vecnorm(stateError(4:6,:),2,1);

positionThreeSigmaNorm = ...
    zeros(numberOfOptimizationTimes,1);

velocityThreeSigmaNorm = ...
    zeros(numberOfOptimizationTimes,1);

for timeIndex = 1:numberOfOptimizationTimes

    covariance = ...
        posteriorCovarianceHistory(:,:,timeIndex);

    covariance = ...
        0.5*(covariance + covariance');

    [~,positiveDefiniteFlag] = ...
        chol(covariance,"lower");

    assert(positiveDefiniteFlag == 0, ...
        "Final EKF covariance is not positive definite at index %d.", ...
        timeIndex);

    positionThreeSigmaNorm(timeIndex) = ...
        3*sqrt(trace(covariance(1:3,1:3)));

    velocityThreeSigmaNorm(timeIndex) = ...
        3*sqrt(trace(covariance(4:6,4:6)));
end

%% Print results

networkNames = networkNames(:);
informationScores = informationScores(:);
coverageCounts = coverageCounts(:);

resultsTable = table( ...
    networkNames, ...
    informationScores, ...
    coverageCounts, ...
    'VariableNames', ...
    {'Network','MeanDOptimality','CoverageEpochs'});

disp(resultsTable);

fprintf("Representative IOD observations: %d\n", ...
    length(acquisitionIndices));

fprintf("IOD Monte Carlo success: %d of %d samples\n", ...
    iodDiagnostics.numberOfSuccessfulSamples, ...
    iodDiagnostics.numberOfRequestedSamples);

fprintf("Fixed IOD reference time: %.6f hr\n", ...
    fixedReferenceTime/3600);

fprintf("Selected network: %s\n", ...
    char(networkNames(bestNetworkIndex)));

fprintf("Final position error: %.6f km\n", ...
    positionErrorNorm(end));

fprintf("Final velocity error: %.6e km/s\n", ...
    velocityErrorNorm(end));

fprintf("Final covariance-only D-optimality: %.6f\n", ...
    bestDOptimalityHistory(end));

fprintf("testLroCandidateNetwork passed.\n");

%% Plot candidate-network and final EKF results

optimizationTimeHours = ...
    optimizationTimes/3600;

figure( ...
    "Color","white", ...
    "Name","LRO Candidate Network Test");

layout = tiledlayout( ...
    2,2, ...
    "TileSpacing","compact", ...
    "Padding","compact");

nexttile(layout,1);

networkCategories = categorical( ...
    networkNames, ...
    networkNames);

bar(networkCategories,informationScores);

grid on;
ylabel("Mean -log(det(\bar{P}))");
title("Candidate Network Information");
xtickangle(30);

nexttile(layout,2);

bar(networkCategories,coverageCounts);

grid on;
ylabel("Covered epochs");
title("Candidate Network Coverage");
xtickangle(30);

nexttile(layout,3);

plot( ...
    optimizationTimeHours, ...
    positionErrorNorm, ...
    "b", ...
    "LineWidth",1.3);

hold on;

plot( ...
    optimizationTimeHours, ...
    positionThreeSigmaNorm, ...
    "k--", ...
    "LineWidth",1.2);

grid on;
xlabel("Time (hr)");
ylabel("Position error (km)");
title("Final Network Position Error");

legend( ...
    "Estimation error", ...
    "3\sigma covariance norm", ...
    "Location","best");

nexttile(layout,4);

plot( ...
    optimizationTimeHours, ...
    velocityErrorNorm, ...
    "b", ...
    "LineWidth",1.3);

hold on;

plot( ...
    optimizationTimeHours, ...
    velocityThreeSigmaNorm, ...
    "k--", ...
    "LineWidth",1.2);

grid on;
xlabel("Time (hr)");
ylabel("Velocity error (km/s)");
title("Final Network Velocity Error");

legend( ...
    "Estimation error", ...
    "3\sigma covariance norm", ...
    "Location","best");

figureTitle = sprintf( ...
    "LRO-like %.0f km Orbit | Fixed IOD Prior | %s", ...
    orbitAltitude, ...
    char(networkNames(bestNetworkIndex)));

title(layout,figureTitle);

%% Plot candidate availability

figure( ...
    "Color","white", ...
    "Name","Candidate Sensor Availability");

layout = tiledlayout( ...
    numberOfCandidates,1, ...
    "TileSpacing","compact", ...
    "Padding","compact");

for sensorIndex = 1:numberOfCandidates

    nexttile(layout,sensorIndex);

    plot( ...
        optimizationTimeHours, ...
        rad2deg(candidateElevation(sensorIndex,:)), ...
        "LineWidth",1.2);

    hold on;

    yline( ...
        rad2deg(minimumElevation), ...
        "k--");

    grid on;
    ylabel("Elevation (deg)");

    sensorTitle = sprintf( ...
        "%s: %.1f deg Lat, %.1f deg Lon", ...
        char(candidateNames(sensorIndex)), ...
        rad2deg(candidateLatitudes(sensorIndex)), ...
        rad2deg(candidateLongitudes(sensorIndex)));

    title(sensorTitle);
end

xlabel(layout,"Time (hr)");

%% Local functions

function [observerPositionsMci, ...
    measurementAvailable, ...
    topographicElevation, ...
    rightAscension, ...
    declination] = ...
    simulateSingleSurfaceSensor( ...
        times, ...
        truthStateHistory, ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        minimumElevation, ...
        measurementNoiseFactor, ...
        moonRadius, ...
        theta0, ...
        angularRate)

numberOfTimes = length(times);

sensorLongitude = ...
    mod(sensorLongitude,2*pi);

observerPositionsMci = ...
    zeros(numberOfTimes,3);

measurementAvailable = ...
    false(numberOfTimes,1);

topographicElevation = ...
    zeros(numberOfTimes,1);

rightAscension = ...
    NaN(numberOfTimes,1);

declination = ...
    NaN(numberOfTimes,1);

sensorMoonRotatingState = ...
    referenceFrames.topographic( ...
        zeros(6,1), ...
        sensorLatitude, ...
        sensorLongitude, ...
        dem, ...
        moonRadius, ...
        "toRotating");

for timeIndex = 1:numberOfTimes

    observationTime = ...
        times(timeIndex);

    truthState = ...
        truthStateHistory(:,timeIndex);

    sensorMciState = ...
        referenceFrames.moonRotating( ...
            sensorMoonRotatingState, ...
            observationTime, ...
            theta0, ...
            angularRate, ...
            "toInertial");

    observerPositionsMci(timeIndex,:) = ...
        sensorMciState(1:3).';

    truthMoonRotatingState = ...
        referenceFrames.moonRotating( ...
            truthState, ...
            observationTime, ...
            theta0, ...
            angularRate, ...
            "fromInertial");

    [~,topographicMeasurement] = ...
        referenceFrames.topographic( ...
            truthMoonRotatingState, ...
            sensorLatitude, ...
            sensorLongitude, ...
            dem, ...
            moonRadius, ...
            "fromRotating");

    elevation = ...
        topographicMeasurement(2);

    topographicElevation(timeIndex) = ...
        elevation;

    measurementAvailable(timeIndex) = ...
        elevation >= minimumElevation;

    if ~measurementAvailable(timeIndex)
        continue
    end

    idealMeasurement = ...
        measurements.surfaceRaDecMeasurement( ...
            truthState, ...
            observationTime, ...
            sensorLatitude, ...
            sensorLongitude, ...
            dem, ...
            moonRadius, ...
            theta0, ...
            angularRate);

    noisyMeasurement = ...
        idealMeasurement + ...
        measurementNoiseFactor*randn(2,1);

    noisyMeasurement(1) = ...
        wrapAngle(noisyMeasurement(1));

    rightAscension(timeIndex) = ...
        noisyMeasurement(1);

    declination(timeIndex) = ...
        noisyMeasurement(2);
end

end

function [observationTimes, ...
    rightAscension, ...
    declination, ...
    sensorLatitudes, ...
    sensorLongitudes, ...
    measurementAvailable] = ...
    simulateSelectedNetwork( ...
        times, ...
        truthStateHistory, ...
        selectedSensorIndices, ...
        candidateLatitudes, ...
        candidateLongitudes, ...
        dem, ...
        minimumElevation, ...
        measurementNoiseFactor, ...
        moonRadius, ...
        theta0, ...
        angularRate)

numberOfTimes = length(times);

numberOfSelectedSensors = ...
    length(selectedSensorIndices);

numberOfObservations = ...
    numberOfTimes*numberOfSelectedSensors;

observationTimes = ...
    zeros(numberOfObservations,1);

rightAscension = ...
    NaN(numberOfObservations,1);

declination = ...
    NaN(numberOfObservations,1);

sensorLatitudes = ...
    zeros(numberOfObservations,1);

sensorLongitudes = ...
    zeros(numberOfObservations,1);

measurementAvailable = ...
    false(numberOfObservations,1);

observationIndex = 0;

for timeIndex = 1:numberOfTimes

    observationTime = ...
        times(timeIndex);

    truthState = ...
        truthStateHistory(:,timeIndex);

    truthMoonRotatingState = ...
        referenceFrames.moonRotating( ...
            truthState, ...
            observationTime, ...
            theta0, ...
            angularRate, ...
            "fromInertial");

    for selectedIndex = 1:numberOfSelectedSensors

        observationIndex = ...
            observationIndex + 1;

        sensorIndex = ...
            selectedSensorIndices(selectedIndex);

        sensorLatitude = ...
            candidateLatitudes(sensorIndex);

        sensorLongitude = mod( ...
            candidateLongitudes(sensorIndex), ...
            2*pi);

        observationTimes(observationIndex) = ...
            observationTime;

        sensorLatitudes(observationIndex) = ...
            sensorLatitude;

        sensorLongitudes(observationIndex) = ...
            sensorLongitude;

        [~,topographicMeasurement] = ...
            referenceFrames.topographic( ...
                truthMoonRotatingState, ...
                sensorLatitude, ...
                sensorLongitude, ...
                dem, ...
                moonRadius, ...
                "fromRotating");

        elevation = ...
            topographicMeasurement(2);

        measurementAvailable(observationIndex) = ...
            elevation >= minimumElevation;

        if ~measurementAvailable(observationIndex)
            continue
        end

        idealMeasurement = ...
            measurements.surfaceRaDecMeasurement( ...
                truthState, ...
                observationTime, ...
                sensorLatitude, ...
                sensorLongitude, ...
                dem, ...
                moonRadius, ...
                theta0, ...
                angularRate);

        noisyMeasurement = ...
            idealMeasurement + ...
            measurementNoiseFactor*randn(2,1);

        noisyMeasurement(1) = ...
            wrapAngle(noisyMeasurement(1));

        rightAscension(observationIndex) = ...
            noisyMeasurement(1);

        declination(observationIndex) = ...
            noisyMeasurement(2);
    end
end

end

function wrappedAngle = wrapAngle(angle)

wrappedAngle = atan2( ...
    sin(angle), ...
    cos(angle));

end