%% testOptimizationDatabase
% End-to-end validation of:
%
%   optimization.buildOptimizationDatabase
%   optimization.networkObjective
%
% Validates:
%   - 3 representative RSOs
%   - 8 candidate surface locations
%   - terrain + Earth + Sun screening
%   - one independent reference IOD calibration
%   - exactly the requested IOD observation count
%   - one fixed P0 applied identically to every RSO
%   - nominal truth-state initialization
%   - STM / Q / Jacobian precomputation
%   - arbitrary configured network sizes
%   - reuse of one database for unconfigured network sizes
%   - information and coverage objectives
%   - selected-sensor slicing equivalence
%   - objective determinism
%   - sensor-order invariance
%   - infeasible-network penalties

clear;
close all;
clc;

%% ========================================================================
%  Project paths
%  ========================================================================

testDirectory = ...
    fileparts(mfilename("fullpath"));

projectRoot = ...
    fileparts(testDirectory);

sourceDirectory = ...
    fullfile(projectRoot,"src");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

requiredFunctions = [ ...
    "optimization.buildOptimizationDatabase"
    "optimization.networkObjective"
    "optimization.informationObjective"
    "optimization.coverageObjective"
    "optimization.buildFilteredVisibilityDatabase"
    "orbitDynamics.propagateLunarOrbit"
    "iod.anglesOnlyIod"
    "lsqnonlin"
];

for functionIndex = 1:length(requiredFunctions)

    functionName = ...
        requiredFunctions(functionIndex);

    assert(~isempty(which(functionName)), ...
        "%s was not found.",functionName);
end

%% ========================================================================
%  Test definition
%  ========================================================================

networkSizes = ...
    sort(unique([3,5,7]));

%% ========================================================================
%  Load DEM
%  ========================================================================

demPath = ...
    fullfile( ...
        projectRoot, ...
        "data", ...
        "new_lunar_interpolant_model.mat");

assert(isfile(demPath), ...
    "DEM file was not found.");

demData = ...
    load(demPath,"F");

assert(isfield(demData,"F"), ...
    "DEM file must contain F.");

sourceDem = ...
    demData.F;

latitudeGrid = ...
    deg2rad(sourceDem.GridVectors{1}(:));

longitudeGrid = ...
    deg2rad(sourceDem.GridVectors{2}(:));

elevationGrid = ...
    sourceDem.Values;

if longitudeGrid(end) < 2*pi

    longitudeGrid = [ ...
        longitudeGrid
        2*pi
    ];

    elevationGrid = [ ...
        elevationGrid, ...
        elevationGrid(:,1)
    ];
end

dem = ...
    griddedInterpolant( ...
        {latitudeGrid,longitudeGrid}, ...
        elevationGrid, ...
        "linear", ...
        "nearest");

%% ========================================================================
%  Constants
%  ========================================================================

moonRadius = ...
    1737.4;

moonMu = ...
    4902.800066;

%% ========================================================================
%  Small deterministic RSO population
%  ========================================================================

rsoNames = [ ...
    "LRO-like 50 km polar"
    "Chandrayaan-like 100 km polar"
    "200 km, 60 deg inclined"
];

truthInitialStates = ...
    zeros(6,3);

truthInitialStates(:,1) = ...
    circularOrbitState( ...
        moonRadius+50, ...
        deg2rad(90), ...
        deg2rad(37), ...
        0, ...
        moonMu);

truthInitialStates(:,2) = ...
    circularOrbitState( ...
        moonRadius+100, ...
        deg2rad(90), ...
        deg2rad(120), ...
        deg2rad(35), ...
        moonMu);

truthInitialStates(:,3) = ...
    circularOrbitState( ...
        moonRadius+200, ...
        deg2rad(60), ...
        deg2rad(205.2), ...
        deg2rad(-90), ...
        moonMu);

customCatalog = ...
    table( ...
        rsoNames, ...
        'VariableNames',{'Name'});

%% ========================================================================
%  Eight candidate locations
%  ========================================================================

candidateLatitudes = ...
    deg2rad([ ...
    -84.000000
    -89.505332
    -76.149000
    -76.000000
    -85.000000
    -80.000000
    -88.000000
    -78.000000
    ]);

candidateLongitudes = ...
    deg2rad([ ...
     37.000000
    102.857143
    115.200000
    300.000000
      0.000000
     60.000000
    180.000000
    240.000000
    ]);

assert(length(candidateLatitudes) == 8, ...
    "The test requires eight candidate locations.");

assert(max(networkSizes) <= length(candidateLatitudes), ...
    "The largest configured network exceeds the test candidate set.");

%% ========================================================================
%  Temporary database file
%  ========================================================================

temporaryFile = ...
    string(tempname) + ".mat";

cleanupObject = ...
    onCleanup(@()cleanupFile(temporaryFile)); %#ok<NASGU>

%% ========================================================================
%  Reduced test configuration
%  ========================================================================

config = struct();

config.outputFile = ...
    temporaryFile;

config.overwriteOutput = ...
    false;

config.demSource = ...
    string(demPath);

config.study.networkSizes = ...
    networkSizes;

config.study.objectiveModes = ...
    ["information","coverage"];

%% Custom RSOs

config.rso.customInitialStatesMoonInertial = ...
    truthInitialStates;

config.rso.customCatalog = ...
    customCatalog;

%% Custom candidate set

config.candidates.customLatitudesRad = ...
    candidateLatitudes;

config.candidates.customLongitudesRad = ...
    candidateLongitudes;

config.candidateFilter.enabled = ...
    false;

%% Terrain

config.terrain.maximumRangeKm = ...
    100;

config.terrain.rangeStepKm = ...
    1.0;

config.terrain.horizonAzimuthStepRad = ...
    deg2rad(2);

config.terrain.horizonMarginRad = ...
    0;

%% Visibility

config.visibility.minimumElevationRad = ...
    0;

config.visibility.minimumAngularSeparationRad = ...
    deg2rad(20);

%% Tracking

config.tracking.outputStepSeconds = ...
    30;

config.tracking.finalTimeSeconds = ...
    8*3600;

%% Measurement noise

config.measurement.rightAscensionSigmaRad = ...
    deg2rad(1/3600);

config.measurement.declinationSigmaRad = ...
    deg2rad(1/3600);

%% One reference IOD calibration

config.iod.referencePeriapsisAltitudeKm = ...
    50;

config.iod.referenceEccentricity = ...
    0;

config.iod.referenceInclinationRad = ...
    deg2rad(90);

config.iod.referenceRaanRad = ...
    deg2rad(37);

config.iod.referenceArgumentOfPeriapsisRad = ...
    0;

config.iod.referenceTrueAnomalyRad = ...
    0;

config.iod.referenceSensorLatitudeRad = ...
    deg2rad(-89.505332);

config.iod.referenceSensorLongitudeRad = ...
    deg2rad(102.857143);

config.iod.outputStepSeconds = ...
    10;

config.iod.desiredObservationCount = ...
    15;

config.iod.searchEndFraction = ...
    0.40;

config.iod.numberOfMonteCarloSamples = ...
    20;

config.iod.measurementNoiseSeedBase = ...
    700;

config.iod.monteCarloSeedBase = ...
    900;

%% Estimation

config.estimation.accelerationNoiseIntensity = ...
    1e-15;

config.estimation.stateScales = ...
    [1;1;1;1e-3;1e-3;1e-3];

config.estimation.objectWeights = ...
    ones(3,1);

%% ========================================================================
%  Build database
%  ========================================================================

database = ...
    optimization.buildOptimizationDatabase( ...
        dem, ...
        config);

%% ========================================================================
%  Structural checks
%  ========================================================================

numberOfCandidates = ...
    database.meta.numberOfCandidates;

numberOfObjects = ...
    database.meta.numberOfObjects;

numberOfOptimizationTimes = ...
    database.meta.numberOfOptimizationEpochs;

assert(numberOfObjects == 3, ...
    "Unexpected RSO count.");

assert(numberOfCandidates == 8, ...
    "Unexpected candidate count.");

assert(isequal( ...
    database.study.networkSizes, ...
    networkSizes), ...
    "Network-size configuration changed.");

assert(all(ismember( ...
    ["information","coverage"], ...
    database.study.objectiveModes)), ...
    "Objective-mode configuration is incomplete.");

assert(database.prior.referenceTime == 0, ...
    "Optimization prior reference time should be zero.");

%% ========================================================================
%  Fixed-P0 and IOD calibration checks
%  ========================================================================

P0 = ...
    database.prior.initialCovariance;

assert(isequal(size(P0),[6,6]), ...
    "Fixed P0 is not 6x6.");

assert(all(isfinite(P0),"all"), ...
    "Fixed P0 contains nonfinite values.");

[~,positiveDefiniteFlag] = ...
    chol( ...
        0.5*(P0+P0.'), ...
        "lower");

assert(positiveDefiniteFlag == 0, ...
    "Fixed P0 is not positive definite.");

assert( ...
    length(database.iod.calibration.acquisitionIndices) == ...
    config.iod.desiredObservationCount, ...
    "Reference IOD did not use the requested observation count.");

assert( ...
    database.iod.calibration.desiredObservationCount == ...
    config.iod.desiredObservationCount, ...
    "Stored IOD observation-count metadata is inconsistent.");

assert( ...
    database.iod.calibration.outputStepSeconds == ...
    config.iod.outputStepSeconds, ...
    "Stored IOD cadence is inconsistent.");

assert( ...
    database.iod.calibration.diagnostics.numberOfRequestedSamples == ...
    config.iod.numberOfMonteCarloSamples, ...
    "Reference IOD Monte Carlo sample count changed.");

assert( ...
    database.iod.calibration.diagnostics.numberOfSuccessfulSamples >= ...
    ceil(0.8*config.iod.numberOfMonteCarloSamples), ...
    "Reference IOD Monte Carlo convergence was insufficient.");

for objectIndex = 1:numberOfObjects

    objectP0 = ...
        database.prior.initialCovariances(:,:,objectIndex);

    assert(isequal(objectP0,P0), ...
        "RSO %d does not use the common fixed P0.", ...
        objectIndex);
end

assert(max(abs( ...
    database.prior.initialStates - ...
    truthInitialStates),[],"all") < 1e-12, ...
    "Nominal prior states do not equal truth states at t = 0.");

%% ========================================================================
%  Tracking dimensions and numerical checks
%  ========================================================================

assert( ...
    isequal( ...
        size(database.visibility.filteredAvailability), ...
        [numberOfCandidates,numberOfOptimizationTimes,numberOfObjects]), ...
    "Filtered availability dimensions are incorrect.");

assert(size( ...
    database.tracking.measurementJacobianHistories,3) == ...
    numberOfCandidates, ...
    "Jacobian candidate dimension is incorrect.");

assert(size( ...
    database.tracking.measurementJacobianHistories,4) == ...
    numberOfOptimizationTimes, ...
    "Jacobian time dimension is incorrect.");

assert(size( ...
    database.tracking.measurementJacobianHistories,5) == ...
    numberOfObjects, ...
    "Jacobian RSO dimension is incorrect.");

assert(all(isfinite( ...
    database.tracking.referenceStateHistories),"all"), ...
    "Reference states contain nonfinite values.");

assert(all(isfinite( ...
    database.tracking.stateTransitionHistories),"all"), ...
    "STM history contains nonfinite values.");

assert(all(isfinite( ...
    database.tracking.processNoiseHistories),"all"), ...
    "Process-noise history contains nonfinite values.");

assert(all(isfinite( ...
    database.tracking.measurementJacobianHistories),"all"), ...
    "Measurement Jacobians contain nonfinite values.");

assert(all( ...
    database.visibility.filteredAvailability <= ...
    database.visibility.terrainAvailability, ...
    "all"), ...
    "Filtered visibility exceeds terrain visibility.");

assert(all( ...
    database.visibility.terrainAvailability <= ...
    database.visibility.geometricAvailability, ...
    "all"), ...
    "Terrain visibility exceeds geometric visibility.");

%% ========================================================================
%  Representative nested networks for every configured size
%  ========================================================================

maximumNetworkSize = ...
    max(networkSizes);

maximumNetwork = ...
    (1:maximumNetworkSize).';

numberOfNetworkSizes = ...
    length(networkSizes);

representativeNetworks = ...
    cell(numberOfNetworkSizes,1);

for sizeIndex = 1:numberOfNetworkSizes

    representativeNetworks{sizeIndex} = ...
        maximumNetwork(1:networkSizes(sizeIndex));
end

%% ========================================================================
%  Evaluate both objectives for every configured size
%  ========================================================================

informationObjectives = ...
    zeros(numberOfNetworkSizes,1);

coverageObjectives = ...
    zeros(numberOfNetworkSizes,1);

for sizeIndex = 1:numberOfNetworkSizes

    currentNetwork = ...
        representativeNetworks{sizeIndex};

    informationObjectives(sizeIndex) = ...
        optimization.networkObjective( ...
            currentNetwork, ...
            database, ...
            "information");

    coverageObjectives(sizeIndex) = ...
        optimization.networkObjective( ...
            currentNetwork, ...
            database, ...
            "coverage");
end

assert(all(isfinite(informationObjectives)), ...
    "One or more information objectives are nonfinite.");

assert(all(isfinite(coverageObjectives)), ...
    "One or more coverage objectives are nonfinite.");

for sizeIndex = 2:numberOfNetworkSizes

    assert( ...
        coverageObjectives(sizeIndex) <= ...
        coverageObjectives(sizeIndex-1)+1e-12, ...
        "Adding sensors reduced coverage.");
end

%% ========================================================================
%  Verify selected-sensor slicing is numerically equivalent
%  ========================================================================

baseNetwork = ...
    representativeNetworks{1};

fullSelectedSensors = ...
    false(numberOfCandidates,1);

fullSelectedSensors(baseNetwork) = ...
    true;

[directInformationObjective,directInformationByObject] = ...
    optimization.informationObjective( ...
        fullSelectedSensors, ...
        database.prior.initialCovariances, ...
        database.tracking.stateTransitionHistories, ...
        database.tracking.processNoiseHistories, ...
        database.tracking.measurementJacobianHistories, ...
        database.visibility.filteredAvailability, ...
        database.measurement.covariance, ...
        database.estimation.stateScales, ...
        database.estimation.objectWeights);

[directCoverageObjective,directCoverageByObject] = ...
    optimization.coverageObjective( ...
        fullSelectedSensors, ...
        database.visibility.filteredAvailability, ...
        database.estimation.objectWeights);

informationTolerance = ...
    1e-12*max(1,abs(informationObjectives(1)));

assert(abs( ...
    directInformationObjective-informationObjectives(1)) <= ...
    informationTolerance, ...
    "Selected-sensor slicing changed the information objective.");

assert(abs( ...
    directCoverageObjective-coverageObjectives(1)) <= 1e-12, ...
    "Selected-sensor slicing changed the coverage objective.");

%% ========================================================================
%  Determinism and sensor-order invariance
%  ========================================================================

informationRepeat = ...
    optimization.networkObjective( ...
        baseNetwork, ...
        database, ...
        "information");

assert(abs( ...
    informationRepeat-informationObjectives(1)) <= ...
    informationTolerance, ...
    "Information objective is not deterministic.");

permutedNetwork = ...
    baseNetwork(end:-1:1);

informationPermuted = ...
    optimization.networkObjective( ...
        permutedNetwork, ...
        database, ...
        "information");

coveragePermuted = ...
    optimization.networkObjective( ...
        permutedNetwork, ...
        database, ...
        "coverage");

assert(abs( ...
    informationPermuted-informationObjectives(1)) <= ...
    informationTolerance, ...
    "Information objective depends on sensor ordering.");

assert(abs( ...
    coveragePermuted-coverageObjectives(1)) <= 1e-12, ...
    "Coverage objective depends on sensor ordering.");

%% ========================================================================
%  Detailed objective diagnostics
%  ========================================================================

[detailedObjective,details] = ...
    optimization.networkObjective( ...
        baseNetwork, ...
        database, ...
        "information");

assert(details.feasible, ...
    "Valid network was classified as infeasible.");

assert(isequal( ...
    details.sensorIndices, ...
    sort(baseNetwork(:))), ...
    "Selected candidate indices changed.");

assert(abs( ...
    detailedObjective-informationObjectives(1)) <= ...
    informationTolerance, ...
    "Detailed information result is inconsistent.");

assert(max(abs( ...
    details.informationByObject-directInformationByObject)) <= ...
    informationTolerance, ...
    "Information-by-object diagnostics changed after slicing.");

assert(max(abs( ...
    details.coverageByObject-directCoverageByObject)) <= 1e-12, ...
    "Coverage-by-object diagnostics changed after slicing.");

%% ========================================================================
%  Verify the database can be reused for an unconfigured network size
%  ========================================================================

reusableNetworkSize = ...
    find(~ismember(1:numberOfCandidates,networkSizes),1,"first");

assert(~isempty(reusableNetworkSize), ...
    "The test requires at least one network size outside study metadata.");

reusableNetwork = ...
    (1:reusableNetworkSize).';

[reusableInformationObjective,reusableDetails] = ...
    optimization.networkObjective( ...
        reusableNetwork, ...
        database, ...
        "information");

reusableCoverageObjective = ...
    optimization.networkObjective( ...
        reusableNetwork, ...
        database, ...
        "coverage");

assert(isfinite(reusableInformationObjective), ...
    "An unconfigured network size produced a nonfinite information objective.");

assert(isfinite(reusableCoverageObjective), ...
    "An unconfigured network size produced a nonfinite coverage objective.");

assert(reusableDetails.feasible, ...
    "An unconfigured but valid network size was classified as infeasible.");

assert(reusableDetails.networkSize == reusableNetworkSize, ...
    "Unconfigured network-size diagnostics are inconsistent.");

assert(reusableInformationObjective ~= ...
    database.objective.infeasiblePenalty, ...
    "A valid unconfigured network size was penalized.");

assert(reusableCoverageObjective ~= ...
    database.objective.infeasiblePenalty, ...
    "A valid unconfigured network size was penalized.");

%% ========================================================================
%  Penalty handling
%  ========================================================================

if length(baseNetwork) >= 2

    duplicateNetwork = ...
        baseNetwork;

    duplicateNetwork(2) = ...
        duplicateNetwork(1);

    duplicateObjective = ...
        optimization.networkObjective( ...
            duplicateNetwork, ...
            database, ...
            "coverage");

    assert( ...
        duplicateObjective == ...
        database.objective.infeasiblePenalty, ...
        "Duplicate candidate indices were not penalized.");
end

outOfRangeNetwork = ...
    baseNetwork;

outOfRangeNetwork(end) = ...
    numberOfCandidates+1;

outOfRangeObjective = ...
    optimization.networkObjective( ...
        outOfRangeNetwork, ...
        database, ...
        "information");

assert( ...
    outOfRangeObjective == ...
    database.objective.infeasiblePenalty, ...
    "Out-of-range candidate was not penalized.");

emptyObjective = ...
    optimization.networkObjective( ...
        zeros(0,1), ...
        database, ...
        "coverage");

assert( ...
    emptyObjective == ...
    database.objective.infeasiblePenalty, ...
    "An empty network was not penalized.");

%% ========================================================================
%  Saved database
%  ========================================================================

assert(isfile(temporaryFile), ...
    "Database file was not saved.");

savedData = ...
    load(temporaryFile,"database");

assert(isfield(savedData,"database"), ...
    "Saved MAT file does not contain database.");

assert(isequal( ...
    savedData.database.prior.initialCovariance, ...
    database.prior.initialCovariance), ...
    "Saved fixed P0 differs from returned fixed P0.");

%% ========================================================================
%  Results
%  ========================================================================

fprintf("\n");
fprintf("Optimization database test summary\n");
fprintf("----------------------------------\n");
fprintf("RSOs:                 %d\n",numberOfObjects);
fprintf("Candidates:           %d\n",numberOfCandidates);
fprintf("Optimization epochs:  %d\n",numberOfOptimizationTimes);
fprintf("IOD observations:     %d/%d\n", ...
    length(database.iod.calibration.acquisitionIndices), ...
    config.iod.desiredObservationCount);
fprintf("IOD cadence:          %.1f s\n", ...
    database.iod.calibration.outputStepSeconds);
fprintf("IOD MC convergence:   %d/%d\n", ...
    database.iod.calibration.diagnostics.numberOfSuccessfulSamples, ...
    database.iod.calibration.diagnostics.numberOfRequestedSamples);

fprintf("\nInformation objectives\n");
for sizeIndex = 1:numberOfNetworkSizes
    fprintf("%d sensors: %.8f\n", ...
        networkSizes(sizeIndex), ...
        -informationObjectives(sizeIndex));
end

fprintf("\nCoverage objectives\n");
for sizeIndex = 1:numberOfNetworkSizes
    fprintf("%d sensors: %.0f\n", ...
        networkSizes(sizeIndex), ...
        -coverageObjectives(sizeIndex));
end

fprintf("\n");
fprintf("Single fixed P0:          passed\n");
fprintf("Exact IOD sample count:   passed\n");
fprintf("Selected-sensor slicing:  passed\n");
fprintf("Database size reuse:      passed\n");
fprintf("Objective determinism:    passed\n");
fprintf("Sensor-order invariance:  passed\n");
fprintf("Penalty handling:         passed\n");
fprintf("\n");
fprintf("testOptimizationDatabase passed.\n");

%% ========================================================================
%  Local functions
%  ========================================================================

function state = ...
    circularOrbitState( ...
        orbitRadius, ...
        inclination, ...
        raan, ...
        trueAnomaly, ...
        moonMu)

rotationZ = [ ...
     cos(raan),-sin(raan),0
     sin(raan), cos(raan),0
     0,0,1
];

rotationX = [ ...
    1,0,0
    0,cos(inclination),-sin(inclination)
    0,sin(inclination), cos(inclination)
];

perifocalPosition = ...
    orbitRadius*[ ...
        cos(trueAnomaly)
        sin(trueAnomaly)
        0
    ];

circularSpeed = ...
    sqrt(moonMu/orbitRadius);

perifocalVelocity = ...
    circularSpeed*[ ...
        -sin(trueAnomaly)
         cos(trueAnomaly)
         0
    ];

rotation = ...
    rotationZ*rotationX;

state = [ ...
    rotation*perifocalPosition
    rotation*perifocalVelocity
];

end

function cleanupFile(fileName)

if isfile(fileName)

    try
        delete(fileName);
    catch
    end
end

end
