%% testCelestialVisibility
% Focused validation of the unified Earth/Sun minimum angular separation
% constraint used by constraints.celestialVisibility.
%
% The intended rule for each body is
%
%   thetaRequired = max(thetaOccultation, minimumAngularSeparation).
%
% Therefore:
%   1. minimumAngularSeparation = 0 must reproduce physical occultation.
%   2. A configured minimum separation may reject an otherwise unoccluded LOS.
%   3. Physical occultation still dominates when its angular threshold is larger.
%   4. Increasing the configured separation cannot restore visibility.
%   5. Earth and Sun use the same configured minimum separation.
%
% The Moon is intentionally absent from this test because lunar obstruction
% for surface sensors is handled by the terrain/horizon LOS tests.

clear;
close all;
clc;

%% Project paths and required functions

testDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testDirectory);
sourceDirectory = fullfile(projectRoot,"src");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

requiredFunctions = [
    "constraints.celestialVisibility"
    "constraints.sphericalBodyOcclusion"
];

for functionIndex = 1:length(requiredFunctions)
    functionName = requiredFunctions(functionIndex);

    assert(~isempty(which(functionName)), ...
        "%s was not found.",functionName);
end

%% Simple normalized geometry
% The geometry is deliberately scale-independent so each expected result is
% easy to inspect analytically.

observerPosition = [0;0;0];
earthPosition = [100;0;0];
earthRadius = 10;

% Place the second body well away from the test LOS so Earth tests isolate
% the Earth gate. The same geometry is later swapped to test the Sun gate.
sunPosition = [0;-1000;0];
sunRadius = 10;

angularTolerance = 1e-11;

%% 1. Target in front of body: zero separation reduces to occultation only
% The target and body center have zero angular separation, but the target is
% entirely in front of the Earth. Physical occultation therefore cannot
% occur. With zero configured separation the LOS must remain visible.

targetPosition = [50;0;0];

[visibleZero,earthBlockedZero,sunBlockedZero, ...
    earthSeparationZero,~,earthRequiredZero,~] = ...
    constraints.celestialVisibility( ...
        observerPosition, ...
        targetPosition, ...
        earthPosition, ...
        sunPosition, ...
        earthRadius, ...
        sunRadius, ...
        0);

assert(visibleZero, ...
    "Zero configured separation falsely rejected a target in front of the body.");
assert(~earthBlockedZero && ~sunBlockedZero, ...
    "A target in front of both bodies should not be physically occulted.");
assert(abs(earthSeparationZero) < angularTolerance, ...
    "The expected zero Earth center separation was not recovered.");
assert(abs(earthRequiredZero) < angularTolerance, ...
    "Zero configured separation should require zero angle when occultation is impossible.");

%% 2. Configured minimum separation can reject an unoccluded LOS

minimumAngularSeparation = deg2rad(5);

[visibleKeepOut,earthBlockedKeepOut,~,~,~,earthRequiredKeepOut,~] = ...
    constraints.celestialVisibility( ...
        observerPosition, ...
        targetPosition, ...
        earthPosition, ...
        sunPosition, ...
        earthRadius, ...
        sunRadius, ...
        minimumAngularSeparation);

assert(~visibleKeepOut && earthBlockedKeepOut, ...
    "Configured minimum separation did not reject an otherwise unoccluded LOS.");
assert(abs(earthRequiredKeepOut-minimumAngularSeparation) < angularTolerance, ...
    "Configured minimum separation was not used as the active threshold.");

%% 3. Zero configured separation reproduces physical occultation
% Put the target directly behind the body. Both the angular formulation and
% the legacy segment/sphere calculation must classify the LOS as blocked.

targetPosition = [200;0;0];

[~,legacyEarthOccluded] = ...
    constraints.sphericalBodyOcclusion( ...
        observerPosition, ...
        targetPosition, ...
        earthPosition, ...
        earthRadius, ...
        0);

[visibleOcculted,earthBlockedOcculted] = ...
    constraints.celestialVisibility( ...
        observerPosition, ...
        targetPosition, ...
        earthPosition, ...
        sunPosition, ...
        earthRadius, ...
        sunRadius, ...
        0);

assert(legacyEarthOccluded, ...
    "Reference sphere/segment calculation did not detect the known occultation.");
assert(~visibleOcculted && earthBlockedOcculted, ...
    "Zero configured separation did not reproduce a known physical occultation.");

%% 4. Physical occultation dominates a smaller configured separation
% For a distant target, the occultation half-angle is asin(R/d).

earthOccultationAngle = asin(earthRadius/norm(earthPosition-observerPosition));
minimumAngularSeparation = deg2rad(2);
targetRange = 200;

blockedAngle = earthOccultationAngle - deg2rad(0.05);
clearAngle = earthOccultationAngle + deg2rad(0.05);

blockedTarget = targetRange*[cos(blockedAngle);sin(blockedAngle);0];
clearTarget = targetRange*[cos(clearAngle);sin(clearAngle);0];

[~,earthBlockedPhysical,~,~,~,earthRequiredPhysical] = ...
    constraints.celestialVisibility( ...
        observerPosition, ...
        blockedTarget, ...
        earthPosition, ...
        sunPosition, ...
        earthRadius, ...
        sunRadius, ...
        minimumAngularSeparation);

[visiblePhysicalClear,earthBlockedPhysicalClear] = ...
    constraints.celestialVisibility( ...
        observerPosition, ...
        clearTarget, ...
        earthPosition, ...
        sunPosition, ...
        earthRadius, ...
        sunRadius, ...
        minimumAngularSeparation);

assert(earthBlockedPhysical, ...
    "Physical occultation did not dominate the smaller configured separation.");
assert(abs(earthRequiredPhysical-earthOccultationAngle) < angularTolerance, ...
    "The physical occultation angle was not selected as the active threshold.");
assert(visiblePhysicalClear && ~earthBlockedPhysicalClear, ...
    "LOS just outside the physical occultation cone should be visible when above the configured separation.");

%% 5. Configured separation dominates the physical occultation angle

minimumAngularSeparation = deg2rad(20);
insideConfiguredAngle = deg2rad(10);
outsideConfiguredAngle = minimumAngularSeparation + deg2rad(0.05);

insideConfiguredTarget = ...
    targetRange*[cos(insideConfiguredAngle);sin(insideConfiguredAngle);0];

outsideConfiguredTarget = ...
    targetRange*[cos(outsideConfiguredAngle);sin(outsideConfiguredAngle);0];

[~,earthBlockedConfigured,~,earthSeparationConfigured,~, ...
    earthRequiredConfigured] = ...
    constraints.celestialVisibility( ...
        observerPosition, ...
        insideConfiguredTarget, ...
        earthPosition, ...
        sunPosition, ...
        earthRadius, ...
        sunRadius, ...
        minimumAngularSeparation);

[visibleOutsideConfigured,earthBlockedOutsideConfigured] = ...
    constraints.celestialVisibility( ...
        observerPosition, ...
        outsideConfiguredTarget, ...
        earthPosition, ...
        sunPosition, ...
        earthRadius, ...
        sunRadius, ...
        minimumAngularSeparation);

assert(earthSeparationConfigured > earthOccultationAngle, ...
    "Configured-separation test target should already clear physical occultation.");
assert(earthBlockedConfigured, ...
    "Configured minimum separation failed to reject a physically clear LOS.");
assert(abs(earthRequiredConfigured-minimumAngularSeparation) < angularTolerance, ...
    "Configured minimum separation was not selected as the active threshold.");
assert(visibleOutsideConfigured && ~earthBlockedOutsideConfigured, ...
    "LOS above the configured minimum separation should be visible.");

%% 6. Equality at the configured minimum separation is allowed
% Use pi/3 so the constructed direction has a simple cosine of 1/2.

boundarySeparation = pi/3;
boundaryTarget = ...
    targetRange*[cos(boundarySeparation);sin(boundarySeparation);0];

[visibleBoundary,earthBlockedBoundary,~,earthSeparationBoundary,~, ...
    earthRequiredBoundary] = ...
    constraints.celestialVisibility( ...
        observerPosition, ...
        boundaryTarget, ...
        earthPosition, ...
        sunPosition, ...
        earthRadius, ...
        sunRadius, ...
        boundarySeparation);

assert(abs(earthSeparationBoundary-boundarySeparation) < angularTolerance, ...
    "Boundary target did not reproduce the configured separation angle.");
assert(abs(earthRequiredBoundary-boundarySeparation) < angularTolerance, ...
    "Configured boundary was not the active minimum separation.");
assert(visibleBoundary && ~earthBlockedBoundary, ...
    "Equality at the configured minimum angular separation should be allowed.");

%% 7. Sun uses the same rule
% Swap the nearby test body from Earth to Sun and repeat a known physical
% occultation at zero configured separation.

earthPositionFar = [0;-1000;0];
sunPositionNear = [100;0;0];
targetPosition = [200;0;0];

[visibleSunOcculted,earthBlockedSunCase,sunBlockedSunCase] = ...
    constraints.celestialVisibility( ...
        observerPosition, ...
        targetPosition, ...
        earthPositionFar, ...
        sunPositionNear, ...
        earthRadius, ...
        sunRadius, ...
        0);

assert(~visibleSunOcculted, ...
    "Known Sun occultation should reject the LOS.");
assert(~earthBlockedSunCase && sunBlockedSunCase, ...
    "Earth and Sun body-specific blocked masks are inconsistent.");

%% 8. Random zero-angle comparison against segment/sphere occultation
% This is the strongest degeneration check: with the configured minimum set
% to zero, the new angular test must match the independent geometric
% segment/sphere calculation across many finite target ranges and directions.

rng(17,"twister");
numberOfRandomCases = 5000;
numberAcceptedCases = 0;
numberMismatches = 0;

while numberAcceptedCases < numberOfRandomCases
    randomDirection = randn(3,1);
    randomDirection = randomDirection/norm(randomDirection);
    randomRange = 20 + 280*rand;
    randomTarget = randomRange*randomDirection;

    % Skip targets inside the occulting body, since the intended RSO use
    % case places the target outside Earth and Sun.
    if norm(randomTarget-earthPosition) <= earthRadius
        continue;
    end

    numberAcceptedCases = numberAcceptedCases + 1;

    [~,legacyOccluded] = ...
        constraints.sphericalBodyOcclusion( ...
            observerPosition, ...
            randomTarget, ...
            earthPosition, ...
            earthRadius, ...
            0);

    [~,earthBlocked] = ...
        constraints.celestialVisibility( ...
            observerPosition, ...
            randomTarget, ...
            earthPosition, ...
            sunPosition, ...
            earthRadius, ...
            sunRadius, ...
            0);

    if earthBlocked ~= legacyOccluded
        numberMismatches = numberMismatches + 1;
    end
end

assert(numberMismatches == 0, ...
    "Zero-angle angular screening disagreed with physical occultation in %d of %d random cases.", ...
    numberMismatches,numberOfRandomCases);

%% 9. Monotonicity with increasing minimum angular separation
% Increasing the minimum-separation angle must never turn a blocked Earth
% LOS back into a clear Earth LOS.

rng(23,"twister");
minimumSeparationSweep = deg2rad([0,2,5,10,20]);
numberOfMonotonicityCases = 1000;
numberAcceptedMonotonicityCases = 0;
monotonicityFailures = 0;

while numberAcceptedMonotonicityCases < numberOfMonotonicityCases
    randomDirection = randn(3,1);
    randomDirection = randomDirection/norm(randomDirection);
    randomRange = 20 + 280*rand;
    randomTarget = randomRange*randomDirection;

    if norm(randomTarget-earthPosition) <= earthRadius
        continue;
    end

    numberAcceptedMonotonicityCases = ...
        numberAcceptedMonotonicityCases + 1;

    blockedHistory = false(size(minimumSeparationSweep));
    requiredHistory = zeros(size(minimumSeparationSweep));

    for angleIndex = 1:length(minimumSeparationSweep)
        [~,blockedHistory(angleIndex),~,~,~,requiredHistory(angleIndex)] = ...
            constraints.celestialVisibility( ...
                observerPosition, ...
                randomTarget, ...
                earthPosition, ...
                sunPosition, ...
                earthRadius, ...
                sunRadius, ...
                minimumSeparationSweep(angleIndex));
    end

    blockedIsMonotone = ...
        all(diff(double(blockedHistory)) >= 0);

    requiredIsMonotone = ...
        all(diff(requiredHistory) >= -angularTolerance);

    if ~blockedIsMonotone || ~requiredIsMonotone
        monotonicityFailures = monotonicityFailures + 1;
    end
end

assert(monotonicityFailures == 0, ...
    "Increasing minimum angular separation produced %d monotonicity failures.", ...
    monotonicityFailures);

%% Summary

fprintf("Unified celestial visibility tests\n");
fprintf("  Random zero-angle comparisons: %d\n",numberOfRandomCases);
fprintf("  Zero-angle mismatches:          %d\n",numberMismatches);
fprintf("  Monotonicity cases:             %d\n",numberOfMonotonicityCases);
fprintf("  Monotonicity failures:          %d\n",monotonicityFailures);
fprintf("  Configured-boundary check:      passed\n");
fprintf("  Earth/Sun common-rule check:    passed\n");
fprintf("\ntestCelestialVisibility passed.\n");
