%% testRsoGeneration
% Test operational and element-distributed RSO generation.

clear;
close all;
clc;

%% Project paths

testDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testDirectory);
sourceDirectory = fullfile(projectRoot,"src");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

requiredFunctions = [
    "rsoGeneration.operationalRsos"
    "rsoGeneration.elementDistributedRsos"
    "rsoGeneration.buildRsoSet"
    "orbitDynamics.propagateLunarOrbit"
];

for functionIndex = 1:length(requiredFunctions)

    functionName = requiredFunctions(functionIndex);

    assert(~isempty(which(functionName)), ...
        "%s was not found.",functionName);
end

%% Generation settings

selection = "both";
numberOfGeneratedObjects = 10;

periapsisAltitudeLimitsKm = [50,5000];
inclinationLimitsRad = deg2rad([0,180]);
eccentricityLimits = [0,0.8];

moonRadius = 1737.4;                  % km
moonMu = 4902.800066;                 % km^3/s^2

%% Build selected RSO set

[initialStatesMoonInertial,rsoCatalog] = ...
    rsoGeneration.buildRsoSet( ...
        selection, ...
        numberOfGeneratedObjects, ...
        periapsisAltitudeLimitsKm, ...
        inclinationLimitsRad, ...
        eccentricityLimits, ...
        moonRadius, ...
        moonMu);

numberOfObjects = height(rsoCatalog);

%% Validate wrapper selection

switch selection

    case "operational"
        expectedNumberOfObjects = 4;

    case "generated"
        expectedNumberOfObjects = ...
            numberOfGeneratedObjects;

    case "both"
        expectedNumberOfObjects = ...
            4 + numberOfGeneratedObjects;

    otherwise
        error("Unexpected RSO selection.");
end

assert(numberOfObjects == expectedNumberOfObjects, ...
    "The wrapper returned an unexpected number of RSOs.");

assert(size(initialStatesMoonInertial,1) == 6, ...
    "The state matrix must have six rows.");

assert(size(initialStatesMoonInertial,2) == numberOfObjects, ...
    "The state matrix and catalog have inconsistent object counts.");

assert(all(isfinite(initialStatesMoonInertial),"all"), ...
    "The generated state matrix contains nonfinite values.");

assert(~any(rsoCatalog.Name == "CAPSTONE"), ...
    "CAPSTONE should be excluded from the current two-body set.");

assert(~any(rsoCatalog.RequiresMultiBodyDynamics), ...
    "The current catalog contains a multi-body object.");

%% Recover elements from every initial state

recoveredSemiMajorAxis = zeros(numberOfObjects,1);
recoveredEccentricity = zeros(numberOfObjects,1);
recoveredInclination = zeros(numberOfObjects,1);
recoveredPeriapsisAltitude = zeros(numberOfObjects,1);
recoveredApoapsisAltitude = zeros(numberOfObjects,1);

for objectIndex = 1:numberOfObjects

    [recoveredSemiMajorAxis(objectIndex), ...
        recoveredEccentricity(objectIndex), ...
        recoveredInclination(objectIndex), ...
        recoveredPeriapsisAltitude(objectIndex), ...
        recoveredApoapsisAltitude(objectIndex)] = ...
        stateToOrbitGeometry( ...
            initialStatesMoonInertial(:,objectIndex), ...
            moonRadius, ...
            moonMu);
end

elementTolerance = 1e-7;
angleTolerance = 1e-10;

assert(all(abs( ...
    recoveredSemiMajorAxis - ...
    rsoCatalog.SemiMajorAxisKm) < elementTolerance), ...
    "A recovered semi-major axis is inconsistent.");

assert(all(abs( ...
    recoveredEccentricity - ...
    rsoCatalog.Eccentricity) < angleTolerance), ...
    "A recovered eccentricity is inconsistent.");

assert(all(abs( ...
    recoveredInclination - ...
    rsoCatalog.InclinationRad) < angleTolerance), ...
    "A recovered inclination is inconsistent.");

assert(all(abs( ...
    recoveredPeriapsisAltitude - ...
    rsoCatalog.PeriapsisAltitudeKm) < elementTolerance), ...
    "A recovered periapsis altitude is inconsistent.");

assert(all(abs( ...
    recoveredApoapsisAltitude - ...
    rsoCatalog.ApoapsisAltitudeKm) < elementTolerance), ...
    "A recovered apoapsis altitude is inconsistent.");

%% Validate equally spaced generated elements

generatedMask = ...
    rsoCatalog.SourceType == "Generated";

if sum(generatedMask) > 2

    assertEvenSpacing( ...
        rsoCatalog.PeriapsisAltitudeKm(generatedMask), ...
        "generated periapsis altitude");

    assertEvenSpacing( ...
        rsoCatalog.InclinationRad(generatedMask), ...
        "generated inclination");

    assertEvenSpacing( ...
        rsoCatalog.Eccentricity(generatedMask), ...
        "generated eccentricity");
end

%% Propagate each object for one period

samplesPerOrbit = 500;
trajectoryHistories = cell(numberOfObjects,1);

for objectIndex = 1:numberOfObjects

    orbitPeriod = ...
        rsoCatalog.PeriodSeconds(objectIndex);

    propagationTimes = linspace( ...
        0, ...
        orbitPeriod, ...
        samplesPerOrbit + 1).';

    [~,propagatedStates] = ...
        orbitDynamics.propagateLunarOrbit( ...
            initialStatesMoonInertial(:,objectIndex), ...
            propagationTimes, ...
            moonMu=moonMu);

    assert(all(isfinite(propagatedStates),"all"), ...
        "Propagation failed for %s.", ...
        char(rsoCatalog.Name(objectIndex)));

    positionHistory = propagatedStates(:,1:3);

    minimumRadius = min( ...
        vecnorm(positionHistory,2,2));

    assert(minimumRadius > moonRadius, ...
        "%s intersects the lunar reference sphere.", ...
        char(rsoCatalog.Name(objectIndex)));

    closureError = norm( ...
        propagatedStates(end,:).' - ...
        initialStatesMoonInertial(:,objectIndex));

    assert(closureError < 1e-4, ...
        "%s did not close after one two-body period.", ...
        char(rsoCatalog.Name(objectIndex)));

    trajectoryHistories{objectIndex} = ...
        positionHistory;
end

%% Print catalog summary

displayCatalog = table( ...
    rsoCatalog.Name, ...
    rsoCatalog.SourceType, ...
    rsoCatalog.PeriapsisAltitudeKm, ...
    rsoCatalog.ApoapsisAltitudeKm, ...
    rsoCatalog.Eccentricity, ...
    rad2deg(rsoCatalog.InclinationRad), ...
    rsoCatalog.PeriodSeconds/3600, ...
    'VariableNames',{ ...
        'Name', ...
        'SourceType', ...
        'PeriapsisAltitudeKm', ...
        'ApoapsisAltitudeKm', ...
        'Eccentricity', ...
        'InclinationDeg', ...
        'PeriodHours'});

disp(displayCatalog);

numberOfOperationalObjects = sum( ...
    rsoCatalog.SourceType == ...
    "Operational representative");

numberOfGeneratedObjectsReturned = ...
    sum(generatedMask);

fprintf("Operational RSOs: %d\n", ...
    numberOfOperationalObjects);

fprintf("Generated RSOs:   %d\n", ...
    numberOfGeneratedObjectsReturned);

fprintf("Total RSOs:       %d\n", ...
    numberOfObjects);

fprintf("testRsoGeneration passed.\n");

%% Plot every orbit in a separate subplot

numberOfColumns = ceil(sqrt(numberOfObjects));
numberOfRows = ceil(numberOfObjects/numberOfColumns);

figure( ...
    "Color","white", ...
    "Name","Generated Lunar RSO Set");

layout = tiledlayout( ...
    numberOfRows, ...
    numberOfColumns, ...
    "TileSpacing","compact", ...
    "Padding","compact");

[moonX,moonY,moonZ] = sphere(24);

for objectIndex = 1:numberOfObjects

    axesHandle = ...
        nexttile(layout,objectIndex);

    surface( ...
        axesHandle, ...
        moonRadius*moonX, ...
        moonRadius*moonY, ...
        moonRadius*moonZ, ...
        "FaceColor",[0.72,0.72,0.72], ...
        "EdgeColor","none", ...
        "FaceAlpha",0.75);

    hold(axesHandle,"on");

    trajectory = ...
        trajectoryHistories{objectIndex};

    if generatedMask(objectIndex)
        orbitColor = [0.85,0.33,0.10];
    else
        orbitColor = [0,0.45,0.74];
    end

    plot3( ...
        axesHandle, ...
        trajectory(:,1), ...
        trajectory(:,2), ...
        trajectory(:,3), ...
        "Color",orbitColor, ...
        "LineWidth",1.2);

    scatter3( ...
        axesHandle, ...
        trajectory(1,1), ...
        trajectory(1,2), ...
        trajectory(1,3), ...
        20, ...
        orbitColor, ...
        "filled");

    axis(axesHandle,"equal");
    grid(axesHandle,"on");
    view(axesHandle,35,25);

    xlabel(axesHandle,"x (km)");
    ylabel(axesHandle,"y (km)");
    zlabel(axesHandle,"z (km)");

    orbitDetails = sprintf( ...
        "hp %.0f km | e %.2f | i %.1f deg", ...
        rsoCatalog.PeriapsisAltitudeKm(objectIndex), ...
        rsoCatalog.Eccentricity(objectIndex), ...
        rad2deg(rsoCatalog.InclinationRad(objectIndex)));

    title( ...
        axesHandle, ...
        { ...
            char(rsoCatalog.Name(objectIndex)), ...
            orbitDetails ...
        }, ...
        "FontSize",9);
end

title(layout,sprintf( ...
    "Lunar RSO Set | %d Operational + %d Generated", ...
    numberOfOperationalObjects, ...
    numberOfGeneratedObjectsReturned));

%% Local functions

function [semiMajorAxis,eccentricity,inclination, ...
    periapsisAltitude,apoapsisAltitude] = ...
    stateToOrbitGeometry(state,moonRadius,moonMu)

position = state(1:3);
velocity = state(4:6);

radius = norm(position);
speedSquared = dot(velocity,velocity);

specificEnergy = ...
    0.5*speedSquared - moonMu/radius;

assert(specificEnergy < 0, ...
    "The generated state is not a bound orbit.");

semiMajorAxis = ...
    -moonMu/(2*specificEnergy);

angularMomentum = ...
    cross(position,velocity);

angularMomentumMagnitude = ...
    norm(angularMomentum);

eccentricityVector = ...
    cross(velocity,angularMomentum)/moonMu - ...
    position/radius;

eccentricity = ...
    norm(eccentricityVector);

inclination = acos(max(-1,min(1, ...
    angularMomentum(3)/angularMomentumMagnitude)));

periapsisAltitude = ...
    semiMajorAxis*(1 - eccentricity) - ...
    moonRadius;

apoapsisAltitude = ...
    semiMajorAxis*(1 + eccentricity) - ...
    moonRadius;

end

function assertEvenSpacing(values,description)

sortedValues = sort(values);
spacing = diff(sortedValues);

spacingTolerance = ...
    1e-10*max(1,max(abs(sortedValues)));

assert(max(abs(spacing - spacing(1))) < ...
    spacingTolerance, ...
    "%s levels are not evenly spaced.", ...
    description);

end