%% testLroAnglesOnlyEkf
% Propagate an LRO-like truth orbit, generate noisy RA/Dec measurements
% from a lunar surface sensor, and test the angles-only EKF.
%
% This test intentionally uses a controlled initial-state error and P0.
% IOD should be connected only after this EKF test passes.
%
% Required functions:
%   orbitDynamics.propagateLunarOrbit
%   orbitDynamics.lunarStateAndStmDynamics
%   referenceFrames.moonRotating
%   referenceFrames.topographic
%   measurements.raDecMeasurement
%   measurements.raDecMeasurementJacobian
%   estimation.isotropicProcessNoise
%   estimation.lunarAnglesOnlyEkf

clear;
close all;
clc;

rng(4,"twister");

%% Project paths

testDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testDirectory);
sourceDirectory = fullfile(projectRoot,"src");

assert(isfolder(sourceDirectory), ...
    "Source directory not found: %s",sourceDirectory);

addpath(sourceDirectory);
rehash path;

requiredFunctions = [ ...
    "orbitDynamics.propagateLunarOrbit";
    "measurements.raDecMeasurement";
    "measurements.raDecMeasurementJacobian";
    "estimation.lunarAnglesOnlyEkf"];

for functionIndex = 1:length(requiredFunctions)

    functionName = requiredFunctions(functionIndex);

    if isempty(which(functionName))
        error( ...
            "testLroAnglesOnlyEkf:MissingFunction", ...
            "%s was not found under %s.", ...
            functionName, ...
            sourceDirectory);
    end
end

%% Load DEM

demPath = fullfile( ...
    projectRoot, ...
    "data", ...
    "new_lunar_interpolant_model.mat");

if ~isfile(demPath)
    demPath = fullfile( ...
        testDirectory, ...
        "new_lunar_interpolant_model.mat");
end

assert(isfile(demPath), ...
    "DEM file not found.");

demData = load(demPath,"F");

assert(isfield(demData,"F") && ...
    isa(demData.F,"griddedInterpolant"), ...
    "The DEM file must contain a griddedInterpolant named F.");

sourceDem = demData.F;

latitudeGrid = ...
    deg2rad(sourceDem.GridVectors{1}(:));

longitudeGrid = ...
    deg2rad(sourceDem.GridVectors{2}(:));

elevationGrid = sourceDem.Values;

% Add the periodic longitude seam.
longitudeGrid = [longitudeGrid;2*pi];
elevationGrid = [elevationGrid,elevationGrid(:,1)];

dem = griddedInterpolant( ...
    {latitudeGrid,longitudeGrid}, ...
    elevationGrid, ...
    "linear", ...
    "nearest");

%% Lunar constants

moonRadius = 1737.4;                  % km
moonMu = 4902.800066;                 % km^3/s^2

moonSiderealPeriod = ...
    27.321661*86400;                  % s

moonAngularRate = ...
    2*pi/moonSiderealPeriod;          % rad/s

theta0 = 0;                           % rad

%% LRO-like truth orbit

orbitAltitude = 50;                   % km
orbitRadius = moonRadius + orbitAltitude;
orbitInclination = deg2rad(90);       % rad

sensorLatitude = deg2rad(-84);        % rad
sensorLongitude = deg2rad(37);        % rad

rightAscensionAscendingNode = ...
    sensorLongitude;

rotationZ = [ ...
    cos(rightAscensionAscendingNode), ...
   -sin(rightAscensionAscendingNode), ...
    0; ...
    sin(rightAscensionAscendingNode), ...
    cos(rightAscensionAscendingNode), ...
    0; ...
    0,0,1];

rotationX = [ ...
    1,0,0; ...
    0,cos(orbitInclination),-sin(orbitInclination); ...
    0,sin(orbitInclination), cos(orbitInclination)];

perifocalToMci = rotationZ*rotationX;

circularSpeed = sqrt(moonMu/orbitRadius);

truthInitialPosition = ...
    perifocalToMci*[orbitRadius;0;0];

truthInitialVelocity = ...
    perifocalToMci*[0;circularSpeed;0];

truthInitialState = [ ...
    truthInitialPosition;
    truthInitialVelocity];

orbitPeriod = ...
    2*pi*sqrt(orbitRadius^3/moonMu);

numberOfPeriods = 3;
outputStep = 20;                      % s

finalTime = numberOfPeriods*orbitPeriod;

timeSpan = (0:outputStep:finalTime).';

if timeSpan(end) < finalTime
    timeSpan(end+1,1) = finalTime;
end

%% Propagate truth in MCI

[times,statesMoonInertial] = ...
    orbitDynamics.propagateLunarOrbit( ...
        truthInitialState, ...
        timeSpan, ...
        moonMu=moonMu);

numberOfObservations = length(times);

% Store truth states as 6xN for direct comparison with the EKF.
truthStateHistory = statesMoonInertial.';

%% Sensor position in the Moon-rotating frame

sensorElevation = dem( ...
    sensorLatitude, ...
    mod(sensorLongitude,2*pi));

sensorUp = [ ...
    cos(sensorLatitude)*cos(sensorLongitude); ...
    cos(sensorLatitude)*sin(sensorLongitude); ...
    sin(sensorLatitude)];

sensorPositionMoonRotating = ...
    (moonRadius + sensorElevation)*sensorUp;

sensorStateMoonRotating = [ ...
    sensorPositionMoonRotating;
    zeros(3,1)];

%% Sensor positions and geometric availability

observerPositionsMci = ...
    zeros(numberOfObservations,3);

measurementAvailable = ...
    false(numberOfObservations,1);

topographicElevation = ...
    zeros(numberOfObservations,1);

minimumSensorElevation = deg2rad(0);

for observationIndex = 1:numberOfObservations

    observationTime = times(observationIndex);

    truthStateMci = ...
        truthStateHistory(:,observationIndex);

    % Convert the truth spacecraft state to the Moon-rotating frame.
    truthStateMoonRotating = ...
        referenceFrames.moonRotating( ...
            truthStateMci, ...
            observationTime, ...
            theta0, ...
            moonAngularRate, ...
            "fromInertial");

    % Convert the sensor state to MCI.
    sensorStateMci = ...
        referenceFrames.moonRotating( ...
            sensorStateMoonRotating, ...
            observationTime, ...
            theta0, ...
            moonAngularRate, ...
            "toInertial");

    observerPositionsMci(observationIndex,:) = ...
        sensorStateMci(1:3).';

    % Determine local geometric elevation.
    [~,topographicMeasurement] = ...
        referenceFrames.topographic( ...
            truthStateMoonRotating, ...
            sensorLatitude, ...
            sensorLongitude, ...
            dem, ...
            moonRadius, ...
            "fromRotating");

    topographicElevation(observationIndex) = ...
        topographicMeasurement(2);

    measurementAvailable(observationIndex) = ...
        topographicElevation(observationIndex) >= ...
        minimumSensorElevation;
end

numberOfAvailableMeasurements = ...
    sum(measurementAvailable);

assert(numberOfAvailableMeasurements >= 3, ...
    "Fewer than three measurements are available.");

%% Measurement noise

rightAscensionSigma = ...
    deg2rad(1/3600);                  % 1 arcsecond

declinationSigma = ...
    deg2rad(1/3600);                  % 1 arcsecond

measurementCovariance = diag([ ...
    rightAscensionSigma^2, ...
    declinationSigma^2]);

measurementNoiseFactor = ...
    chol(measurementCovariance,"lower");

%% Generate noisy RA/Dec measurements

rightAscension = ...
    NaN(numberOfObservations,1);

declination = ...
    NaN(numberOfObservations,1);

idealRightAscension = ...
    NaN(numberOfObservations,1);

idealDeclination = ...
    NaN(numberOfObservations,1);

for observationIndex = 1:numberOfObservations

    if ~measurementAvailable(observationIndex)
        continue
    end

    idealMeasurement = ...
        measurements.raDecMeasurement( ...
            truthStateHistory(:,observationIndex), ...
            observerPositionsMci(observationIndex,:).');

    measurementNoise = ...
        measurementNoiseFactor*randn(2,1);

    noisyMeasurement = ...
        idealMeasurement + measurementNoise;

    noisyMeasurement(1) = wrapAngle( ...
        noisyMeasurement(1));

    idealRightAscension(observationIndex) = ...
        idealMeasurement(1);

    idealDeclination(observationIndex) = ...
        idealMeasurement(2);

    rightAscension(observationIndex) = ...
        noisyMeasurement(1);

    declination(observationIndex) = ...
        noisyMeasurement(2);
end

%% Verify the RA/Dec measurement Jacobian

firstAvailableIndex = ...
    find(measurementAvailable,1,"first");

jacobianTestState = ...
    truthStateHistory(:,firstAvailableIndex);

jacobianTestObserver = ...
    observerPositionsMci(firstAvailableIndex,:).';

analyticalJacobian = ...
    measurements.raDecMeasurementJacobian( ...
        jacobianTestState, ...
        jacobianTestObserver);

finiteDifferenceJacobian = ...
    finiteDifferenceMeasurementJacobian( ...
        jacobianTestState, ...
        jacobianTestObserver);

jacobianRelativeError = norm( ...
    analyticalJacobian - finiteDifferenceJacobian, ...
    "fro") / max(1,norm(finiteDifferenceJacobian,"fro"));

assert(jacobianRelativeError < 1e-5, ...
    "RA/Dec Jacobian failed finite-difference testing. Relative error: %.3e", ...
    jacobianRelativeError);

%% Controlled EKF initial condition

% The first EKF test bypasses IOD so that filter performance can be
% isolated from IOD performance.

initialStateEstimate = ...
    truthInitialState + [ ...
     1.0; ...       % km
    -1.0; ...       % km
     0.5; ...       % km
     1.0e-3; ...    % km/s
    -1.0e-3; ...    % km/s
     0.5e-3];       % km/s

initialPositionSigma = 2;             % km
initialVelocitySigma = 2e-3;          % km/s

initialCovariance = diag([ ...
    initialPositionSigma^2, ...
    initialPositionSigma^2, ...
    initialPositionSigma^2, ...
    initialVelocitySigma^2, ...
    initialVelocitySigma^2, ...
    initialVelocitySigma^2]);

% Continuous white-acceleration process-noise intensity.
accelerationNoiseIntensity = 1e-15;   % km^2/s^3

%% Run EKF

[stateEstimateHistory,covarianceHistory, ...
    innovationHistory,measurementInformationHistory] = ...
    estimation.lunarAnglesOnlyEkf( ...
        times(1), ...
        times, ...
        rightAscension, ...
        declination, ...
        observerPositionsMci, ...
        measurementAvailable, ...
        initialStateEstimate, ...
        initialCovariance, ...
        measurementCovariance, ...
        accelerationNoiseIntensity, ...
        moonMu);

%% Estimation errors

stateError = ...
    stateEstimateHistory - truthStateHistory;

positionError = stateError(1:3,:);
velocityError = stateError(4:6,:);

positionErrorNorm = ...
    vecnorm(positionError,2,1);

velocityErrorNorm = ...
    vecnorm(velocityError,2,1);

stateStandardDeviation = ...
    zeros(6,numberOfObservations);

positionThreeSigmaNorm = ...
    zeros(numberOfObservations,1);

velocityThreeSigmaNorm = ...
    zeros(numberOfObservations,1);

dOptimalityHistory = ...
    zeros(numberOfObservations,1);

stateScales = [ ...
    1;1;1; ...
    1e-3;1e-3;1e-3];

normalizationMatrix = ...
    diag(1./stateScales);

for timeIndex = 1:numberOfObservations

    covariance = ...
        covarianceHistory(:,:,timeIndex);

    stateStandardDeviation(:,timeIndex) = ...
        sqrt(max(diag(covariance),0));

    positionThreeSigmaNorm(timeIndex) = ...
        3*sqrt(trace(covariance(1:3,1:3)));

    velocityThreeSigmaNorm(timeIndex) = ...
        3*sqrt(trace(covariance(4:6,4:6)));

    normalizedCovariance = ...
        normalizationMatrix * covariance * ...
        normalizationMatrix';

    normalizedCovariance = ...
        0.5*(normalizedCovariance + normalizedCovariance');

    [covarianceFactor,cholFlag] = ...
        chol(normalizedCovariance,"lower");

    assert(cholFlag == 0, ...
        "Normalized covariance is not positive definite at index %d.", ...
        timeIndex);

    logDetCovariance = ...
        2*sum(log(diag(covarianceFactor)));

    % log(det(information)) = -log(det(covariance)).
    dOptimalityHistory(timeIndex) = ...
        -logDetCovariance;
end

%% Validate EKF results

assert(all(isfinite(stateEstimateHistory),"all"), ...
    "EKF state history contains nonfinite values.");

assert(all(isfinite(covarianceHistory),"all"), ...
    "EKF covariance history contains nonfinite values.");

for timeIndex = 1:numberOfObservations

    covariance = ...
        covarianceHistory(:,:,timeIndex);

    covarianceSymmetryError = norm( ...
        covariance - covariance',"fro");

    assert(covarianceSymmetryError < 1e-8, ...
        "Covariance lost symmetry at index %d.", ...
        timeIndex);

    minimumCovarianceEigenvalue = min(eig( ...
        0.5*(covariance + covariance')));

    assert(minimumCovarianceEigenvalue > 0, ...
        "Covariance is not positive definite at index %d.", ...
        timeIndex);
end

availableInnovationIndices = ...
    all(isfinite(innovationHistory),1);

assert(any(availableInnovationIndices), ...
    "The EKF performed no measurement updates.");

initialPositionError = ...
    norm(initialStateEstimate(1:3) - ...
    truthInitialState(1:3));

finalPositionError = ...
    positionErrorNorm(end);

initialVelocityError = ...
    norm(initialStateEstimate(4:6) - ...
    truthInitialState(4:6));

finalVelocityError = ...
    velocityErrorNorm(end);

fprintf("Available measurements: %d of %d\n", ...
    numberOfAvailableMeasurements, ...
    numberOfObservations);

fprintf("Measurement Jacobian relative error: %.3e\n", ...
    jacobianRelativeError);

fprintf("Initial position error: %.6f km\n", ...
    initialPositionError);

fprintf("Final position error: %.6f km\n", ...
    finalPositionError);

fprintf("Initial velocity error: %.6e km/s\n", ...
    initialVelocityError);

fprintf("Final velocity error: %.6e km/s\n", ...
    finalVelocityError);

%% Plot EKF performance

timeHours = times/3600;

figure( ...
    "Color","white", ...
    "Name","LRO Angles-Only EKF Test");

layout = tiledlayout( ...
    2,2, ...
    "TileSpacing","compact", ...
    "Padding","compact");

% Position error
nexttile(layout,1);

plot( ...
    timeHours, ...
    positionErrorNorm, ...
    "b", ...
    "LineWidth",1.4);

hold on;

plot( ...
    timeHours, ...
    positionThreeSigmaNorm, ...
    "k--", ...
    "LineWidth",1.2);

grid on;
xlabel("Time (hr)");
ylabel("Position error (km)");
title("Position Estimation Error");
legend( ...
    "Estimation error", ...
    "3\sigma covariance norm", ...
    "Location","best");

% Velocity error
nexttile(layout,2);

plot( ...
    timeHours, ...
    velocityErrorNorm, ...
    "b", ...
    "LineWidth",1.4);

hold on;

plot( ...
    timeHours, ...
    velocityThreeSigmaNorm, ...
    "k--", ...
    "LineWidth",1.2);

grid on;
xlabel("Time (hr)");
ylabel("Velocity error (km/s)");
title("Velocity Estimation Error");
legend( ...
    "Estimation error", ...
    "3\sigma covariance norm", ...
    "Location","best");

% Innovations
nexttile(layout,3);

innovationTimes = ...
    timeHours(availableInnovationIndices);

innovationArcseconds = ...
    rad2deg( ...
        innovationHistory(:,availableInnovationIndices).')*3600;

plot( ...
    innovationTimes, ...
    innovationArcseconds(:,1), ...
    "LineWidth",1.1);

hold on;

plot( ...
    innovationTimes, ...
    innovationArcseconds(:,2), ...
    "LineWidth",1.1);

grid on;
xlabel("Time (hr)");
ylabel("Innovation (arcsec)");
title("RA/Dec Innovations");
legend( ...
    "Right ascension", ...
    "Declination", ...
    "Location","best");

% D-optimality
nexttile(layout,4);

plot( ...
    timeHours, ...
    dOptimalityHistory, ...
    "LineWidth",1.4);

grid on;
xlabel("Time (hr)");
ylabel("-log(det(\bar{P}))");
title("Posterior EKF D-Optimality");

figureTitle = sprintf( ...
    "LRO-like %.0f km Orbit | Sensor: %.1f deg Lat, %.1f deg Lon", ...
    orbitAltitude, ...
    rad2deg(sensorLatitude), ...
    rad2deg(sensorLongitude));

title(layout,figureTitle);

%% Plot measurement availability

figure( ...
    "Color","white", ...
    "Name","LRO Measurement Availability");

tiledlayout(2,1, ...
    "TileSpacing","compact", ...
    "Padding","compact");

nexttile;

plot( ...
    timeHours, ...
    rad2deg(topographicElevation), ...
    "LineWidth",1.3);

hold on;

yline( ...
    rad2deg(minimumSensorElevation), ...
    "k--", ...
    "Minimum elevation");

grid on;
xlabel("Time (hr)");
ylabel("Elevation (deg)");
title("Object Elevation from Surface Sensor");

nexttile;

stairs( ...
    timeHours, ...
    double(measurementAvailable), ...
    "LineWidth",1.3);

ylim([-0.1,1.1]);
yticks([0,1]);
yticklabels(["No LOS","LOS"]);
grid on;
xlabel("Time (hr)");
ylabel("Availability");
title("Measurement Availability Gate");

%% Local functions

function wrappedAngle = wrapAngle(angle)

wrappedAngle = atan2( ...
    sin(angle), ...
    cos(angle));

end

function finiteDifferenceJacobian = ...
    finiteDifferenceMeasurementJacobian( ...
        state,observerPositionMci)

numberOfStates = length(state);

finiteDifferenceJacobian = ...
    zeros(2,numberOfStates);

perturbationSizes = [ ...
    1e-3; ...
    1e-3; ...
    1e-3; ...
    1e-6; ...
    1e-6; ...
    1e-6];

for stateIndex = 1:numberOfStates

    statePerturbation = ...
        zeros(numberOfStates,1);

    statePerturbation(stateIndex) = ...
        perturbationSizes(stateIndex);

    measurementPlus = ...
        measurements.raDecMeasurement( ...
            state + statePerturbation, ...
            observerPositionMci);

    measurementMinus = ...
        measurements.raDecMeasurement( ...
            state - statePerturbation, ...
            observerPositionMci);

    measurementDifference = ...
        measurementPlus - measurementMinus;

    measurementDifference(1) = ...
        wrapAngle(measurementDifference(1));

    finiteDifferenceJacobian(:,stateIndex) = ...
        measurementDifference / ...
        (2*perturbationSizes(stateIndex));
end

end