function [isVisible, ...
    earthOccluded,sunOccluded, ...
    earthExcluded,sunExcluded, ...
    earthSeparation,sunSeparation, ...
    earthKeepOutAngle,sunKeepOutAngle] = ...
    celestialVisibility( ...
        observerPosition, ...
        targetPosition, ...
        earthPosition, ...
        sunPosition, ...
        earthRadius, ...
        sunRadius, ...
        keepOutAngle)
% CELESTIALVISIBILITY Apply unified Earth and Sun visibility constraints.
%
% All positions must be expressed in the same reference frame and units.
% keepOutAngle is an absolute minimum LOS separation measured from each
% body's CENTER, in rad.
%
% For each body b,
%
%   thetaKeepOut,b = max(thetaOccultation,b, keepOutAngle).
%
% Physical tangency is blocked. Equality at the configured keep-out angle
% is allowed because it satisfies the minimum angular separation.
%
% The Moon is intentionally not screened here. For a lunar surface sensor,
% lunar obstruction is represented by the local terrain/horizon LOS gate.

arguments
    observerPosition (3,1) double
    targetPosition (3,1) double
    earthPosition (3,1) double
    sunPosition (3,1) double
    earthRadius (1,1) double {mustBePositive} = 6378.1366
    sunRadius (1,1) double {mustBePositive} = 695700
    keepOutAngle (1,1) double {mustBeNonnegative} = 0
end

[earthOccluded,earthExcluded,earthSeparation,earthKeepOutAngle] = ...
    bodyVisibility( ...
        observerPosition, ...
        targetPosition, ...
        earthPosition, ...
        earthRadius, ...
        keepOutAngle);

[sunOccluded,sunExcluded,sunSeparation,sunKeepOutAngle] = ...
    bodyVisibility( ...
        observerPosition, ...
        targetPosition, ...
        sunPosition, ...
        sunRadius, ...
        keepOutAngle);

isVisible = ~( ...
    earthOccluded || ...
    sunOccluded || ...
    earthExcluded || ...
    sunExcluded);

end

function [isOccluded,isExcluded,separation,thetaKeepOut] = ...
    bodyVisibility( ...
        observerPosition, ...
        targetPosition, ...
        bodyPosition, ...
        bodyRadius, ...
        keepOutAngle)

lineOfSight = targetPosition - observerPosition;
targetRange = norm(lineOfSight);

if targetRange <= eps
    error( ...
        "celestialVisibility:CoincidentTarget", ...
        "Observer and target positions must be different.");
end

bodyVector = bodyPosition - observerPosition;
bodyRange = norm(bodyVector);

if bodyRange <= bodyRadius
    separation = NaN;
    thetaKeepOut = pi;
    isOccluded = true;
    isExcluded = false;
    return;
end

lineOfSightDirection = lineOfSight/targetRange;
bodyDirection = bodyVector/bodyRange;

cosSeparation = dot(lineOfSightDirection,bodyDirection);
separation = acos(min(max(cosSeparation,-1),1));

% Finite-target physical occultation threshold. If the target lies wholly
% in front of the body, physical occultation cannot occur.
tangentRange = sqrt((bodyRange-bodyRadius)*(bodyRange+bodyRadius));

if targetRange < bodyRange-bodyRadius
    thetaOccultation = -Inf;
elseif targetRange < tangentRange
    cosOccultation = ...
        (bodyRange^2 + targetRange^2 - bodyRadius^2) / ...
        (2*bodyRange*targetRange);

    thetaOccultation = ...
        acos(min(max(cosOccultation,-1),1));
else
    thetaOccultation = asin(min(bodyRadius/bodyRange,1));
end

thetaKeepOut = max(thetaOccultation,keepOutAngle);

isOccluded = separation <= thetaOccultation;
isExcluded = ~isOccluded && separation < keepOutAngle;

end
