function [isVisible, ...
    earthOccluded,sunOccluded, ...
    earthExcluded,sunExcluded, ...
    earthSeparation,sunSeparation, ...
    earthRequiredSeparation,sunRequiredSeparation] = ...
    celestialVisibility( ...
        observerPosition, ...
        targetPosition, ...
        earthPosition, ...
        sunPosition, ...
        earthRadius, ...
        sunRadius, ...
        earthLimbMargin, ...
        sunLimbMargin, ...
        earthRadiusPadding, ...
        sunRadiusPadding)
% CELESTIALVISIBILITY Apply Earth and Sun visibility constraints.
%
% All positions must be expressed in the same reference frame and units.
%
% limb margins are angular margins beyond the apparent body limb, rad.

arguments
    observerPosition (3,1) double
    targetPosition (3,1) double
    earthPosition (3,1) double
    sunPosition (3,1) double
    earthRadius (1,1) double {mustBePositive} = 6378.1366
    sunRadius (1,1) double {mustBePositive} = 695700
    earthLimbMargin (1,1) double {mustBeNonnegative} = 0
    sunLimbMargin (1,1) double {mustBeNonnegative} = 0
    earthRadiusPadding (1,1) double {mustBeNonnegative} = 0
    sunRadiusPadding (1,1) double {mustBeNonnegative} = 0
end

[~,earthOccluded] = ...
    constraints.sphericalBodyOcclusion( ...
        observerPosition, ...
        targetPosition, ...
        earthPosition, ...
        earthRadius, ...
        earthRadiusPadding);

[~,sunOccluded] = ...
    constraints.sphericalBodyOcclusion( ...
        observerPosition, ...
        targetPosition, ...
        sunPosition, ...
        sunRadius, ...
        sunRadiusPadding);

[~,earthExcluded,earthSeparation,~, ...
    earthRequiredSeparation] = ...
    constraints.brightBodyExclusion( ...
        observerPosition, ...
        targetPosition, ...
        earthPosition, ...
        earthRadius, ...
        earthLimbMargin);

[~,sunExcluded,sunSeparation,~, ...
    sunRequiredSeparation] = ...
    constraints.brightBodyExclusion( ...
        observerPosition, ...
        targetPosition, ...
        sunPosition, ...
        sunRadius, ...
        sunLimbMargin);

isVisible = ~( ...
    earthOccluded || ...
    sunOccluded || ...
    earthExcluded || ...
    sunExcluded);

end