function tableInfo = buildManuscriptTables(campaign,userConfig)
% BUILDMANUSCRIPTTABLES Generate manuscript tables that do not require
% optional comparison/operational studies.
%
% File names mirror the current TeX table labels:
%   completed_clps_landing_sites.csv
%   planned_clps_landing_regions.csv
%   optimization_rso_population.csv
%   lunar_peaks_dem.csv
%   dominant_craters.csv
%   celestial_exclusion_parameters.csv
%   iod_prior_weighting.csv
%   P0_initial_covariance.csv
%   optimization_parameters.csv
%   network_summary.csv

arguments
    campaign (1,1) struct
    userConfig (1,1) struct = struct()
end

config=campaign.configuration;
database=campaign.database;
outputDirectory=string(campaign.outputDirectory);
if isfield(userConfig,"outputDirectory")
    outputDirectory=string(userConfig.outputDirectory);
end
tableDirectory=fullfile(outputDirectory,"tables");
if ~isfolder(tableDirectory), mkdir(tableDirectory); end

tableInfo=struct();

%% Completed CLPS missions

completed=table( ...
    ["Peregrine / TO2-AB";"IM-1 / TO2-IM";"IM-2 / PRIME-1";"Blue Ghost 1 / TO19D"], ...
    ["Astrobotic";"Intuitive Machines";"Intuitive Machines";"Firefly Aerospace"], ...
    ["Sinus Viscositatis";"Near Malapert A";"Mons Mouton";"Mare Crisium"], ...
    [NaN;-80.1277;-84.7754;18.5623], ...
    [NaN;1.4357;29.1264;61.8103], ...
    ["Did not land";"Completed";"Completed";"Completed"], ...
    ["No";"Yes";"Yes";"No"], ...
    'VariableNames',{'MissionTaskOrder','Provider','SiteRegion', ...
    'LatitudeDeg','LongitudeDegE','Status','LspAnchor'});
tableInfo.completedClpsFile=writeTable( ...
    completed,tableDirectory,"completed_clps_landing_sites.csv");

%% Planned CLPS deliveries

planned=table( ...
    ["Griffin / TO20A";"IM-3 / CP-11";"IM-4 / CP-22";"Blue Ghost 2 / CS-3/4"; ...
     "Blue Ghost 3 / CP-21";"SERIES-2 / CP-12";"Blue Moon MK1 / CT-3"; ...
     "Blue Ghost 4 / CS-6";"Nova-D / CT-4";"CS-8";"CX-2"], ...
    ["Astrobotic";"Intuitive Machines";"Intuitive Machines";"Firefly Aerospace"; ...
     "Firefly Aerospace";"Draper";"Blue Origin";"Firefly Aerospace"; ...
     "Intuitive Machines";"--";"--"], ...
    ["Mons Mouton";"Reiner Gamma";"Mons Mouton";"Lunar far side"; ...
     "Mons Gruithuisen Gamma";"Schrodinger Basin";"Lunar South Pole"; ...
     "Lunar South Pole";"Lunar South Pole";"Lunar surface";"Lunar surface"], ...
    [-86.22;6.75;-86.22;-90;36.18;-79.95;-90;-90;-90;-90;-90], ...
    [-83.30;7.91;-83.30;90;36.94;-69.52;-75;-75;-75;90;90], ...
    [11.67;299.95;11.67;90;318.88;112.33;0;0;0;0;0], ...
    [53.03;302.35;53.03;270;319.67;153.44;360;360;360;360;360], ...
    ["Planned";"Planned";"Planned";"Planned";"Planned";"Planned"; ...
     "Planned";"Planned";"Planned";"Planned";"Planned"], ...
    ["Yes";"No";"Yes";"No";"No";"Optional";"Yes";"Yes";"Yes";"--";"--"], ...
    'VariableNames',{'MissionTaskOrder','Provider','SiteRegion', ...
    'LatitudeSouthDeg','LatitudeNorthDeg','LongitudeWestDegE', ...
    'LongitudeEastDegE','Status','LspAnchor'});
tableInfo.plannedClpsFile=writeTable( ...
    planned,tableDirectory,"planned_clps_landing_regions.csv");

%% Representative design RSO population

catalog=database.rso.catalog;
n=height(catalog);
rsoTable=table(compose("RSO %02d",(1:n).'), ...
    round(catalog.PeriapsisAltitudeKm,3), ...
    round(catalog.SemiMajorAxisKm,3), ...
    round(catalog.Eccentricity,4), ...
    round(rad2deg(catalog.InclinationRad),3), ...
    round(mod(rad2deg(catalog.RaanRad),360),3), ...
    round(mod(rad2deg(catalog.ArgumentOfPeriapsisRad),360),3), ...
    round(mod(rad2deg(catalog.TrueAnomalyRad),360),3), ...
    'VariableNames',{'RSO','hp_km','a_km','e','i_deg', ...
    'Omega_deg','omega_deg','nu0_deg'});
tableInfo.rsoPopulationFile=writeTable( ...
    rsoTable,tableDirectory,"optimization_rso_population.csv");

%% Synthetic DEM retained peaks

peaks=table( ...
    ["Mons Dieter";"Mons Ganau";"Mons Andre";"Mons Ardeshir";"Mons Dilip"; ...
     "Mons Cabeus";"Mons Malapert";"Mons Mouton";"Mons Amundsen"], ...
    [20.41;13.49;10.52;7.10;1.37;43.00;67.00;130.00;38.00], ...
    [5.00;4.79;5.18;5.03;5.58;-83.67;-85.98;-84.60;-82.57], ...
    [120.30;120.59;120.56;121.04;120.87;-36.16;-1.67;31.00;75.71], ...
    [0.292;0.170;-0.441;-1.407;-1.973;5.308;4.809;6.363;3.824], ...
    [-1.085;-0.663;-1.032;-1.580;-1.973;1.866;1.004;2.543;2.942], ...
    [-1.956;-1.432;-1.738;-1.800;-1.973;-1.058;-2.735;-1.794;1.153], ...
    'VariableNames',{'FeatureName','DiameterKm','LatitudeDeg','LongitudeDeg', ...
    'MaxElevationKm','MeanElevationKm','MinElevationKm'});
tableInfo.peaksFile=writeTable(peaks,tableDirectory,"lunar_peaks_dem.csv");

%% Synthetic DEM retained craters/depressions

craters=table( ...
    ["Mare Frigoris";"Mare Imbrium";"Mare Australe";"Mare Tranquillitatis"; ...
     "Mare Fecunditatis";"Mare Nubium";"Mare Serenitatis";"Mare Crisium"; ...
     "Hertzsprung";"Apollo"], ...
    [1446.41;1145.53;996.84;875.75;840.35;714.50;674.28;555.92;536.37;524.23], ...
    [57.59;34.72;-47.77;8.35;-7.83;-20.59;27.29;16.18;1.37;-35.69], ...
    [359.99;345.09;91.99;30.83;53.67;342.71;18.36;59.10;231.34;208.52], ...
    [-2.627;-2.335;0.896;-0.961;-2.220;-2.287;-2.533;-3.564;0.860;-5.467], ...
    [-1.581;-1.538;-1.164;-1.524;-1.348;-1.490;-1.879;-1.346;4.720;-1.448], ...
    [1.045;0.797;-2.060;-0.562;0.873;0.798;0.654;2.218;3.860;4.019], ...
    'VariableNames',{'Feature','DiameterKm','CenterLatitudeDeg', ...
    'CenterLongitudeDeg','CenterElevationKm','RimMeanElevationKm','DepthKm'});
tableInfo.cratersFile=writeTable( ...
    craters,tableDirectory,"dominant_craters.csv");

%% Celestial exclusion parameters

exclusion=table( ...
    ["Sun";"Earth"], ...
    ["r_Sun";"r_Earth"], ...
    [695700;6378.1366], ...
    [20;10], ...
    'VariableNames',{'Body','MciPositionSymbol','RadiusKm','MinimumSeparationDeg'});
tableInfo.exclusionFile=writeTable( ...
    exclusion,tableDirectory,"celestial_exclusion_parameters.csv");

%% IOD calibration / P0 / object weighting

successfulSamples=database.iod.calibration.diagnostics.numberOfSuccessfulSamples;
requestedSamples=database.iod.calibration.diagnostics.numberOfRequestedSamples;

iod=table( ...
    ["Reference orbit";"Reference sensor";"IOD cadence and acquisition"; ...
     "IOD solution sequence";"Monte Carlo covariance calibration"; ...
     "Covariance application";"Object weights"], ...
    ["hp=50 km, e=0, i=90 deg, RAAN=37 deg, omega=0 deg, nu0=0 deg"; ...
     "lat=-89.505332 deg, lon=102.857143 deg E"; ...
     sprintf("%.0f s; %d observations; first 40%% of 72-h interval", ...
        database.iod.calibration.outputStepSeconds, ...
        database.iod.calibration.desiredObservationCount); ...
     "Three-observation Gauss IOD -> propagate -> nonlinear least-squares refinement using all 15 RA/Dec measurements"; ...
     sprintf("%d requested, %d successful; 1 arcsec RA/Dec; P0 from sample covariance", ...
        requestedSamples,successfulSamples); ...
     "Same fixed P0 applied to every design RSO, network size, objective, and independent run"; ...
     sprintf("w_j=1; normalized weight=%.6f", ...
        1/database.meta.numberOfObjects)], ...
    'VariableNames',{'Quantity','ValueMethod'});
tableInfo.iodSummaryFile=writeTable( ...
    iod,tableDirectory,"iod_prior_weighting.csv");

P0=array2table(database.prior.initialCovariance, ...
    'VariableNames',compose("c%d",1:6),'RowNames',compose("r%d",1:6));
p0File=fullfile(tableDirectory,"P0_initial_covariance.csv");
writetable(P0,p0File,"WriteRowNames",true);
tableInfo.p0File=string(p0File);

%% GA parameters

ga=table( ...
    ["Optimizer";"Network sizes, N_s";"Objective modes";"Population size"; ...
     "FE budget";"Generations after initialization";"Independent runs"; ...
     "Random-number seeds";"Elite count";"Parallel workers"], ...
    ["GA";"3, 5, 7, 10";"Information, coverage"; ...
     string(config.populationSize);string(config.functionEvaluationBudget); ...
     string(config.functionEvaluationBudget/config.populationSize-1); ...
     string(config.numberOfRuns); ...
     sprintf("%d--%d",config.baseSeed,config.baseSeed+config.numberOfRuns-1); ...
     "0";"7"], ...
    'VariableNames',{'Parameter','Value'});
tableInfo.gaParametersFile=writeTable( ...
    ga,tableDirectory,"optimization_parameters.csv");

%% Results table: exactly the five manuscript columns

numberOfRows=numel(config.networkSizes)*numel(config.objectiveModes);
objective=strings(numberOfRows,1);
sensors=zeros(numberOfRows,1);
bestValue=zeros(numberOfRows,1);
meanFinalValue=zeros(numberOfRows,1);
stdDev=zeros(numberOfRows,1);

row=0;
for objectiveIndex=1:numel(config.objectiveModes)
    for networkIndex=1:numel(config.networkSizes)
        row=row+1;
        study=campaign.studies{networkIndex,objectiveIndex};
        mode=config.objectiveModes(objectiveIndex);
        if mode=="information"
            objective(row)="Information objective";
        else
            objective(row)="Coverage objective";
        end
        sensors(row)=config.networkSizes(networkIndex);
        bestValue(row)=study.overallBestObjective;
        meanFinalValue(row)=mean(study.bestObjectives(:));
        stdDev(row)=std(study.bestObjectives(:));
    end
end

networkSummary=table(objective,sensors,bestValue,meanFinalValue,stdDev, ...
    'VariableNames',{'Objective','Sensors','BestValue','MeanFinalValue','StdDev'});
tableInfo.networkSummaryFile=writeTable( ...
    networkSummary,tableDirectory,"network_summary.csv");
tableInfo.networkSummary=networkSummary;

fprintf("\nManuscript tables written to:\n  %s\n",tableDirectory);
end

function file=writeTable(T,directory,name)
file=string(fullfile(directory,name));
writetable(T,file);
end
