function plotInfo = plotMonteCarloConferenceFigure(userConfig)
% PLOTMONTECARLOCONFERENCEFIGURE Plot discrete-grid Monte Carlo robustness.
%
% Each boxplot contains Monte Carlo network realizations generated by moving
% every nominal sensor to one of its K nearest eligible candidate-grid sites.
% The perturbations therefore use the same spatial discretization as the
% production optimization. The minimized objective J = -score is plotted
% with the nominal optimized objective as a horizontal reference line.

arguments
    userConfig (1,1) struct = struct()
end

scriptDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(scriptDirectory);
resultsDirectory = fullfile(projectRoot,"results");
addpath(scriptDirectory);
style = publicationPlotStyle();

config = struct();
config.resultsDirectory = resultsDirectory;
config.outputDirectory = fullfile(resultsDirectory,"production_figures");
config.monteCarloResultsFile = "";
config.networkSizes = [3 5 7 10];
config.objectiveModes = ["information","coverage"];
config.optimizationCampaignDates = ["20260918","20260919"];
config.neighborCount = 10;
config.requiredSamplingMode = "random_joint_discrete_neighbors";
config = mergeStruct(config,userConfig);
config.resultsDirectory = string(config.resultsDirectory);
config.outputDirectory = string(config.outputDirectory);
config.monteCarloResultsFile = string(config.monteCarloResultsFile);
config.networkSizes = double(config.networkSizes(:).');
config.objectiveModes = lower(string(config.objectiveModes(:).'));
config.optimizationCampaignDates = string(config.optimizationCampaignDates(:));
config.requiredSamplingMode = string(config.requiredSamplingMode);
validateattributes(config.neighborCount,{'numeric'},{'scalar','integer','positive'});

resultsFile = resolveMonteCarloResults(config);
plotInfo = struct();
plotInfo.available = false;
plotInfo.resultsFile = resultsFile;
plotInfo.information = struct();
plotInfo.coverage = struct();
plotInfo.summaryFile = "";

if strlength(resultsFile) == 0
    fprintf("\nNo completed discrete-grid Monte Carlo robustness study found; figures skipped.\n");
    return
end

data = load(resultsFile,"studyState");
assert(isfield(data,"studyState") && data.studyState.completed, ...
    "Selected Monte Carlo result is incomplete: %s",resultsFile);
studyState = data.studyState;

if ~isfolder(config.outputDirectory), mkdir(config.outputDirectory); end
tableDirectory = fullfile(config.outputDirectory,"tables");
if ~isfolder(tableDirectory), mkdir(tableDirectory); end

for objectiveMode = config.objectiveModes
    objectiveField = char(objectiveMode);
    metricField = objectiveMode + "Score";
    modeIndex = find(studyState.config.nominalObjectiveModes == objectiveMode,1);
    assert(~isempty(modeIndex),"MC study does not contain %s objective.",objectiveMode);

    for networkSize = config.networkSizes
        networkIndex = find(double(studyState.config.networkSizes(:).') == networkSize,1);
        assert(~isempty(networkIndex), ...
            "MC study does not contain N_s = %d.",networkSize);

        caseState = studyState.cases{modeIndex,networkIndex};
        values = -double(caseState.rso.(metricField));
        values = values(:);
        nominal = -double(caseState.nominal.rso.(metricField));

        fig = figure("Name",sprintf("Grid-scale Monte Carlo robustness: %s, N_s=%d", ...
            objectiveMode,networkSize), ...
            "Color",style.backgroundColor,"Units","inches", ...
            "Position",[0.5 0.5 7.0 4.8],"Renderer","opengl");
        fig.InvertHardcopy = "off";
        layout = tiledlayout(fig,1,1,"Padding","loose","TileSpacing","loose");
        ax = nexttile(layout);

        [boxHandle,nominalHandle] = makeSingleBoxplot( ...
            ax,values,nominal,networkSize,objectiveMode,style);

        lgd = legend(ax,[boxHandle nominalHandle], ...
            ["Grid-neighbor MC samples","Nominal optimum"], ...
            "Location","none","Orientation","horizontal", ...
            "NumColumns",2,"Box","off");
        lgd.FontName = style.fontName;
        lgd.FontSize = max(20,style.legendFontSize+2);
        lgd.FontWeight = "bold";
        lgd.Layout.Tile = "north";

        outputFile = fullfile(config.outputDirectory, ...
            sprintf("monte_carlo_%s_n%d.eps",objectiveMode,networkSize));
        exportManuscriptFigure(fig,string(outputFile),7.0,4.8);

        networkField = sprintf("n%d",networkSize);
        plotInfo.(objectiveField).(networkField) = struct( ...
            "figure",fig,"outputFile",string(outputFile), ...
            "networkSize",networkSize);
    end
end

summaryTable = buildSummaryTable(studyState);
summaryFile = fullfile(tableDirectory,"monte_carlo_summary.csv");
if ~isfield(config,"exportDiagnosticTables") || config.exportDiagnosticTables
    writetable(summaryTable,summaryFile);
else
    summaryFile = "";
end

plotInfo.available = true;
plotInfo.summaryFile = string(summaryFile);
plotInfo.summaryTable = summaryTable;
plotInfo.resultsFile = resultsFile;

fprintf("Discrete-grid Monte Carlo robustness figures:\n");
for objectiveMode = config.objectiveModes
    objectiveField = char(objectiveMode);
    fields = fieldnames(plotInfo.(objectiveField));
    for fieldIndex = 1:numel(fields)
        fprintf("  %s\n",plotInfo.(objectiveField).(fields{fieldIndex}).outputFile);
    end
end
end

function [boxHandle,nominalHandle] = makeSingleBoxplot( ...
    ax,values,nominal,networkSize,objectiveMode,style)

if objectiveMode == "information"
    boxColor = style.blueColor;
else
    boxColor = style.redColor;
end

hold(ax,"on");
boxHandle = boxchart(ax,ones(size(values)),values, ...
    "BoxFaceColor",boxColor, ...
    "MarkerStyle",".", ...
    "MarkerColor",style.grayColor, ...
    "LineWidth",1.25);
nominalHandle = plot(ax,[0.68 1.32],[nominal nominal], ...
    "-","Color",style.redColor,"LineWidth",3.0);

xticks(ax,1);
xticklabels(ax,sprintf("N_s = %d",networkSize));
xlim(ax,[0.5 1.5]);
ylabel(ax,"Objective, J");
ax.FontName = style.fontName;
ax.FontSize = style.axisFontSize;
ax.FontWeight = "bold";
ax.LineWidth = 1.0;
ax.TickDir = "out";
ax.Box = "on";
ax.XGrid = "off";
ax.YGrid = "off";
ax.YLabel.FontSize = style.labelFontSize;
ax.YLabel.FontWeight = "bold";

valuesForLimits = [values(:);nominal];
span = max(valuesForLimits)-min(valuesForLimits);
if span <= 0
    span = max(1,0.05*max(abs(valuesForLimits)));
end
ylim(ax,[min(valuesForLimits)-0.10*span max(valuesForLimits)+0.10*span]);
end

function summaryTable = buildSummaryTable(studyState)
networkSizes = studyState.config.networkSizes;
objectiveModes = studyState.config.nominalObjectiveModes;
numberOfRows = numel(networkSizes)*numel(objectiveModes);
objective = strings(numberOfRows,1);
networkSize = zeros(numberOfRows,1);
neighborCount = zeros(numberOfRows,1);
meanEligibleNeighborCount = zeros(numberOfRows,1);
maximumEligibleNeighborCount = zeros(numberOfRows,1);
meanNeighborhoodRadiusKm = zeros(numberOfRows,1);
maximumNeighborhoodRadiusKm = zeros(numberOfRows,1);
monteCarloRuns = zeros(numberOfRows,1);
meanSensorDisplacementKm = zeros(numberOfRows,1);
maximumSensorDisplacementKm = zeros(numberOfRows,1);
nominalObjective = zeros(numberOfRows,1);
meanObjective = zeros(numberOfRows,1);
stdObjective = zeros(numberOfRows,1);
medianObjective = zeros(numberOfRows,1);
minimumObjective = zeros(numberOfRows,1);
maximumObjective = zeros(numberOfRows,1);
row = 0;

for modeIndex = 1:numel(objectiveModes)
    objectiveMode = objectiveModes(modeIndex);
    metricField = objectiveMode + "Score";
    for networkIndex = 1:numel(networkSizes)
        row = row + 1;
        caseState = studyState.cases{modeIndex,networkIndex};
        values = -double(caseState.rso.(metricField));
        objective(row) = objectiveMode;
        networkSize(row) = networkSizes(networkIndex);
        neighborCount(row) = studyState.config.neighborCount;
        meanEligibleNeighborCount(row) = mean(double(caseState.neighborCountActual));
        maximumEligibleNeighborCount(row) = max(double(caseState.neighborCountActual));
        meanNeighborhoodRadiusKm(row) = mean(double(caseState.neighborRadiusKm));
        maximumNeighborhoodRadiusKm(row) = max(double(caseState.neighborRadiusKm));
        monteCarloRuns(row) = caseState.completedRuns;
        meanSensorDisplacementKm(row) = mean(double(caseState.meanDisplacementKm));
        maximumSensorDisplacementKm(row) = max(double(caseState.maximumDisplacementKm));
        nominalObjective(row) = -double(caseState.nominal.rso.(metricField));
        meanObjective(row) = mean(values);
        stdObjective(row) = std(values);
        medianObjective(row) = median(values);
        minimumObjective(row) = min(values);
        maximumObjective(row) = max(values);
    end
end

summaryTable = table(objective,networkSize,neighborCount, ...
    meanEligibleNeighborCount,maximumEligibleNeighborCount, ...
    meanNeighborhoodRadiusKm,maximumNeighborhoodRadiusKm, ...
    monteCarloRuns,meanSensorDisplacementKm,maximumSensorDisplacementKm, ...
    nominalObjective,meanObjective,stdObjective,medianObjective, ...
    minimumObjective,maximumObjective, ...
    'VariableNames',{'Objective','NetworkSize','NeighborCount', ...
    'MeanEligibleNeighborCount','MaximumEligibleNeighborCount', ...
    'MeanNeighborhoodRadiusKm','MaximumNeighborhoodRadiusKm', ...
    'MonteCarloRuns','MeanSensorDisplacementKm','MaximumSensorDisplacementKm', ...
    'NominalObjective','MeanObjective','StdObjective','MedianObjective', ...
    'MinimumObjective','MaximumObjective'});
end

function resultsFile = resolveMonteCarloResults(config)
resultsFile = "";
if strlength(config.monteCarloResultsFile) > 0
    if isfile(config.monteCarloResultsFile)
        data = load(config.monteCarloResultsFile,"studyState");
        if isfield(data,"studyState") && isFullStudy(data.studyState,config)
            resultsFile = config.monteCarloResultsFile;
        end
    end
    return
end

files = dir(fullfile(config.resultsDirectory,"monte_carlo_robustness", ...
    "**","monte_carlo_results.mat"));
if isempty(files), return, end
[~,order] = sort([files.datenum],"descend");
files = files(order);
for fileIndex = 1:numel(files)
    candidate = string(fullfile(files(fileIndex).folder,files(fileIndex).name));
    try
        data = load(candidate,"studyState");
        if isfield(data,"studyState") && isFullStudy(data.studyState,config)
            resultsFile = candidate;
            return
        end
    catch
    end
end
end

function tf = isFullStudy(studyState,config)
tf = isstruct(studyState) && isfield(studyState,"completed") && ...
    studyState.completed && isfield(studyState,"version") && ...
    string(studyState.version) == "lunar_surface_monte_carlo_robustness_v6" && ...
    isfield(studyState,"config") && ...
    isfield(studyState.config,"networkSizes") && ...
    isfield(studyState.config,"nominalObjectiveModes") && ...
    isfield(studyState.config,"samplingMode") && ...
    string(studyState.config.samplingMode) == config.requiredSamplingMode && ...
    isfield(studyState.config,"neighborCount") && ...
    double(studyState.config.neighborCount) == double(config.neighborCount);
if ~tf, return, end
networkSizes = double(studyState.config.networkSizes(:).');
objectiveModes = lower(string(studyState.config.nominalObjectiveModes(:).'));
tf = all(ismember(config.networkSizes,networkSizes)) && ...
    all(ismember(config.objectiveModes,objectiveModes));

if tf && ~isempty(config.optimizationCampaignDates)
    if ~isfield(studyState.config,"optimizationCampaignDates")
        tf = false;
        return
    end
    sourceDates = string(studyState.config.optimizationCampaignDates(:));
    tf = isequal(sort(sourceDates),sort(config.optimizationCampaignDates));
end
end

function output = mergeStruct(defaults,override)
output = defaults;
fields = fieldnames(override);
for fieldIndex = 1:numel(fields)
    output.(fields{fieldIndex}) = override.(fields{fieldIndex});
end
end