%% plotAnglesOnlyMeasurementModel
% Create two separate publication-style EPS figures for the angles-only
% measurement model:
%   1. Right-ascension geometry in the MCI x-y plane.
%   2. Declination geometry between a lunar surface sensor and an RSO.
%
% Outputs:
%   angles_only_right_ascension_geometry.eps
%   angles_only_declination_geometry.eps

clear;
close all;
clc;

%% Figure appearance

fontName = "Arial";

axisLabelFontSize = 22;
annotationFontSize = 18;

backgroundColor = [0.00 0.00 0.00];
moonColor = [0.40 0.40 0.43];
moonEdgeColor = [0.68 0.68 0.71];

axisColor = [0.05 0.65 1.00];
projectionColor = [0.82 0.82 0.84];
losColor = [1.00 0.15 0.78];
raColor = [1.00 0.82 0.05];
decColor = [0.15 1.00 0.35];
sensorColor = [1.00 0.20 0.15];

labelBackgroundColor = [0.06 0.06 0.07];

%% Export settings

exportWidthInches = 6.50;
exportHeightInches = 6.50;
exportPaddingInches = 0.25;

scriptDirectory = fileparts(mfilename("fullpath"));

rightAscensionFile = fullfile( ...
    scriptDirectory, ...
    "angles_only_right_ascension_geometry.eps");

declinationFile = fullfile( ...
    scriptDirectory, ...
    "angles_only_declination_geometry.eps");

%% Define illustrative angular measurements

alphaDeg = 38.0;
deltaDeg = 32.0;

alpha = deg2rad(alphaDeg);
delta = deg2rad(deltaDeg);

%% Right-ascension geometry

rightAscensionFigure = figure( ...
    "Color",backgroundColor, ...
    "Units","inches", ...
    "Position",[1 1 exportWidthInches exportHeightInches], ...
    "Renderer","painters");

rightAscensionAxes = axes( ...
    rightAscensionFigure, ...
    "Position",[0.055 0.055 0.89 0.89]);

hold(rightAscensionAxes,"on");
axis(rightAscensionAxes,"equal");
axis(rightAscensionAxes,"off");

rightAscensionAxes.Color = backgroundColor;
rightAscensionAxes.FontName = fontName;

xlim(rightAscensionAxes,[-2.35 2.35]);
ylim(rightAscensionAxes,[-2.35 2.35]);

%% Define the projected sensor-to-RSO geometry

raSensorPosition = [-0.58;-0.48];

raAxisLength = 1.35;
raProjectionLength = 2.05;

raProjectionEndpoint = ...
    raSensorPosition + ...
    raProjectionLength*[cos(alpha);sin(alpha)];

%% Draw the sensor origin

scatter(rightAscensionAxes, ...
    raSensorPosition(1), ...
    raSensorPosition(2), ...
    75, ...
    "o", ...
    "MarkerFaceColor",sensorColor, ...
    "MarkerEdgeColor","white", ...
    "LineWidth",1.3);

raSensorLabelPosition = ...
    raSensorPosition + [-0.15;-0.38];

plot(rightAscensionAxes, ...
    [raSensorLabelPosition(1) raSensorPosition(1)], ...
    [raSensorLabelPosition(2) raSensorPosition(2)], ...
    "Color",projectionColor, ...
    "LineWidth",1.2);

text(rightAscensionAxes, ...
    raSensorLabelPosition(1), ...
    raSensorLabelPosition(2), ...
    "Surface sensor", ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",annotationFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","top", ...
    "BackgroundColor",labelBackgroundColor, ...
    "Margin",2.0);

%% Draw the MCI x- and y-axes

drawArrow2D( ...
    rightAscensionAxes, ...
    raSensorPosition, ...
    raSensorPosition + [raAxisLength;0], ...
    axisColor,2.2,0.095,0.070,"-");

drawArrow2D( ...
    rightAscensionAxes, ...
    raSensorPosition, ...
    raSensorPosition + [0;raAxisLength], ...
    axisColor,2.2,0.095,0.070,"-");

text(rightAscensionAxes, ...
    raSensorPosition(1) + raAxisLength + 0.18, ...
    raSensorPosition(2), ...
    "x_I", ...
    "Interpreter","tex", ...
    "Color",axisColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","left", ...
    "VerticalAlignment","middle");

text(rightAscensionAxes, ...
    raSensorPosition(1), ...
    raSensorPosition(2) + raAxisLength + 0.18, ...
    "y_I", ...
    "Interpreter","tex", ...
    "Color",axisColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","bottom");

%% Draw the projected topocentric LOS vector

drawArrow2D( ...
    rightAscensionAxes, ...
    raSensorPosition, ...
    raProjectionEndpoint, ...
    projectionColor,2.8,0.120,0.085,"-");

raProjectionNormal = [-sin(alpha);cos(alpha)];

raProjectionLabelPosition = ...
    raSensorPosition + ...
    0.68*raProjectionLength*[cos(alpha);sin(alpha)] + ...
    0.22*raProjectionNormal;

text(rightAscensionAxes, ...
    raProjectionLabelPosition(1), ...
    raProjectionLabelPosition(2), ...
    "\rho_{xy,k}", ...
    "Interpreter","tex", ...
    "Color",projectionColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "BackgroundColor",labelBackgroundColor, ...
    "Margin",1.5);

scatter(rightAscensionAxes, ...
    raProjectionEndpoint(1), ...
    raProjectionEndpoint(2), ...
    125, ...
    "p", ...
    "MarkerFaceColor",losColor, ...
    "MarkerEdgeColor","white", ...
    "LineWidth",1.4);

text(rightAscensionAxes, ...
    raProjectionEndpoint(1), ...
    raProjectionEndpoint(2) + 0.22, ...
    "RSO projection", ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",annotationFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","bottom", ...
    "BackgroundColor",labelBackgroundColor, ...
    "Margin",2.0);

%% Draw the right-ascension angle

raArcRadius = 0.67;
raValues = linspace(0,alpha,100);

raArcPoints = ...
    raSensorPosition + ...
    raArcRadius*[cos(raValues);sin(raValues)];

plot(rightAscensionAxes, ...
    raArcPoints(1,:), ...
    raArcPoints(2,:), ...
    "Color",raColor, ...
    "LineWidth",2.7);

raTangent = [-sin(alpha);cos(alpha)];

drawArrowHead2D( ...
    rightAscensionAxes, ...
    raArcPoints(:,end), ...
    raTangent, ...
    raColor,0.075,0.060);

raAngleLabelPosition = ...
    raSensorPosition + ...
    0.94*[cos(alpha/2);sin(alpha/2)];

text(rightAscensionAxes, ...
    raAngleLabelPosition(1), ...
    raAngleLabelPosition(2), ...
    "\alpha_k", ...
    "Interpreter","tex", ...
    "Color",raColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center");

%% Declination geometry

declinationFigure = figure( ...
    "Color",backgroundColor, ...
    "Units","inches", ...
    "Position",[8 1 exportWidthInches exportHeightInches], ...
    "Renderer","painters");

declinationAxes = axes( ...
    declinationFigure, ...
    "Position",[0.055 0.055 0.89 0.89]);

hold(declinationAxes,"on");
axis(declinationAxes,"equal");
axis(declinationAxes,"off");

declinationAxes.Color = backgroundColor;
declinationAxes.FontName = fontName;

xlim(declinationAxes,[-2.60 2.60]);
ylim(declinationAxes,[-2.60 2.60]);

%% Define the lunar sensor-to-RSO geometry

moonRadius = 1.03;
moonCenter = [-0.72;-0.66];

decSensorPosition = ...
    moonCenter + [0;moonRadius];

decProjectionLength = 2.18;

decProjectionEndpoint = ...
    decSensorPosition + [decProjectionLength;0];

decRsoHeight = ...
    decProjectionLength*tan(delta);

decRsoPosition = ...
    decProjectionEndpoint + [0;decRsoHeight];

circleValues = linspace(0,2*pi,500);

moonX = ...
    moonCenter(1) + moonRadius*cos(circleValues);

moonY = ...
    moonCenter(2) + moonRadius*sin(circleValues);

fill(declinationAxes, ...
    moonX,moonY, ...
    moonColor, ...
    "EdgeColor",moonEdgeColor, ...
    "LineWidth",1.2);

%% Draw the lunar surface sensor

scatter(declinationAxes, ...
    decSensorPosition(1), ...
    decSensorPosition(2), ...
    80, ...
    "o", ...
    "MarkerFaceColor",sensorColor, ...
    "MarkerEdgeColor","white", ...
    "LineWidth",1.3);

decSensorLabelPosition = ...
    decSensorPosition + [-0.46;-0.28];

plot(declinationAxes, ...
    [decSensorLabelPosition(1) decSensorPosition(1)], ...
    [decSensorLabelPosition(2) decSensorPosition(2)], ...
    "Color",projectionColor, ...
    "LineWidth",1.2);

text(declinationAxes, ...
    decSensorLabelPosition(1), ...
    decSensorLabelPosition(2), ...
    "Surface sensor", ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",annotationFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","right", ...
    "VerticalAlignment","top", ...
    "BackgroundColor",labelBackgroundColor, ...
    "Margin",2.0);

%% Draw the MCI z-axis

decZAxisLength = 0.92;

drawArrow2D( ...
    declinationAxes, ...
    decSensorPosition, ...
    decSensorPosition + [0;decZAxisLength], ...
    axisColor,2.2,0.095,0.070,"-");

text(declinationAxes, ...
    decSensorPosition(1), ...
    decSensorPosition(2) + decZAxisLength + 0.18, ...
    "z_I", ...
    "Interpreter","tex", ...
    "Color",axisColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","bottom");

%% Draw the projected and full LOS vectors

projectionCornerExtension = 0.09;

horizontalProjectionEnd = ...
    decProjectionEndpoint + [projectionCornerExtension;0];

verticalProjectionStart = ...
    decProjectionEndpoint - [0;projectionCornerExtension];

plot(declinationAxes, ...
    [decSensorPosition(1) horizontalProjectionEnd(1)], ...
    [decSensorPosition(2) horizontalProjectionEnd(2)], ...
    "Color",projectionColor, ...
    "LineStyle","--", ...
    "LineWidth",1.8);

plot(declinationAxes, ...
    [verticalProjectionStart(1) decRsoPosition(1)], ...
    [verticalProjectionStart(2) decRsoPosition(2)], ...
    "Color",projectionColor, ...
    "LineStyle",":", ...
    "LineWidth",1.5);

decProjectionLabelPosition = ...
    decSensorPosition + [0.60*decProjectionLength;-0.24];

text(declinationAxes, ...
    decProjectionLabelPosition(1), ...
    decProjectionLabelPosition(2), ...
    "\rho_{xy,k}", ...
    "Interpreter","tex", ...
    "Color",projectionColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "BackgroundColor",labelBackgroundColor, ...
    "Margin",1.5);

drawArrow2D( ...
    declinationAxes, ...
    decSensorPosition, ...
    decRsoPosition, ...
    losColor,3.0,0.120,0.085,"-");

decLosVector = ...
    decRsoPosition - decSensorPosition;

decLosNormal = ...
    [-decLosVector(2);decLosVector(1)]/norm(decLosVector);

decLosLabelPosition = ...
    decSensorPosition + ...
    0.61*decLosVector + ...
    0.22*decLosNormal;

text(declinationAxes, ...
    decLosLabelPosition(1), ...
    decLosLabelPosition(2), ...
    "\rho_{I,k}", ...
    "Interpreter","tex", ...
    "Color",losColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "BackgroundColor",labelBackgroundColor, ...
    "Margin",1.5);

%% Draw and label the RSO

scatter(declinationAxes, ...
    decRsoPosition(1), ...
    decRsoPosition(2), ...
    135, ...
    "p", ...
    "MarkerFaceColor",losColor, ...
    "MarkerEdgeColor","white", ...
    "LineWidth",1.4);

text(declinationAxes, ...
    decRsoPosition(1) + 0.19, ...
    decRsoPosition(2) + 0.06, ...
    "RSO", ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",annotationFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","left", ...
    "VerticalAlignment","middle", ...
    "BackgroundColor",labelBackgroundColor, ...
    "Margin",2.0);

%% Draw the declination angle

decArcRadius = 0.78;
decValues = linspace(0,delta,100);

decArcPoints = ...
    decSensorPosition + ...
    decArcRadius*[cos(decValues);sin(decValues)];

plot(declinationAxes, ...
    decArcPoints(1,:), ...
    decArcPoints(2,:), ...
    "Color",decColor, ...
    "LineWidth",2.7);

decTangent = [-sin(delta);cos(delta)];

drawArrowHead2D( ...
    declinationAxes, ...
    decArcPoints(:,end), ...
    decTangent, ...
    decColor,0.075,0.060);

decAngleLabelPosition = ...
    decSensorPosition + ...
    1.10*[cos(delta/2);sin(delta/2)];

text(declinationAxes, ...
    decAngleLabelPosition(1), ...
    decAngleLabelPosition(2), ...
    "\delta_k", ...
    "Interpreter","tex", ...
    "Color",decColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center");

%% Export both EPS panels

drawnow;

exportgraphics( ...
    rightAscensionAxes, ...
    rightAscensionFile, ...
    "ContentType","vector", ...
    "BackgroundColor",backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",exportWidthInches, ...
    "Height",exportHeightInches, ...
    "Padding",exportPaddingInches, ...
    "PreserveAspectRatio","on");

exportgraphics( ...
    declinationAxes, ...
    declinationFile, ...
    "ContentType","vector", ...
    "BackgroundColor",backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",exportWidthInches, ...
    "Height",exportHeightInches, ...
    "Padding",exportPaddingInches, ...
    "PreserveAspectRatio","on");

fprintf("Exported: %s\n",rightAscensionFile);
fprintf("Exported: %s\n",declinationFile);
fprintf("Right ascension: %.3f deg\n",alphaDeg);
fprintf("Declination: %.3f deg\n",deltaDeg);
fprintf("plotAnglesOnlyMeasurementModel completed.\n");

%% Local plotting functions

function drawArrow2D( ...
    axesHandle,startPoint,endPoint,arrowColor, ...
    lineWidth,headLength,headWidth,lineStyle)

direction = endPoint - startPoint;
directionLength = norm(direction);

assert(directionLength > headLength, ...
    "The arrow is too short for the requested arrowhead.");

unitDirection = direction/directionLength;

normalDirection = [
   -unitDirection(2)
    unitDirection(1)
];

arrowBase = ...
    endPoint - headLength*unitDirection;

plot(axesHandle, ...
    [startPoint(1) arrowBase(1)], ...
    [startPoint(2) arrowBase(2)], ...
    "Color",arrowColor, ...
    "LineStyle",lineStyle, ...
    "LineWidth",lineWidth);

trianglePoints = [
    endPoint, ...
    arrowBase + 0.5*headWidth*normalDirection, ...
    arrowBase - 0.5*headWidth*normalDirection
];

patch(axesHandle, ...
    trianglePoints(1,:), ...
    trianglePoints(2,:), ...
    arrowColor, ...
    "EdgeColor","none");

end

function drawArrowHead2D( ...
    axesHandle,endPoint,direction,arrowColor, ...
    headLength,headWidth)

unitDirection = ...
    direction/norm(direction);

normalDirection = [
   -unitDirection(2)
    unitDirection(1)
];

arrowBase = ...
    endPoint - headLength*unitDirection;

trianglePoints = [
    endPoint, ...
    arrowBase + 0.5*headWidth*normalDirection, ...
    arrowBase - 0.5*headWidth*normalDirection
];

patch(axesHandle, ...
    trianglePoints(1,:), ...
    trianglePoints(2,:), ...
    arrowColor, ...
    "EdgeColor","none");

end