%% plotReferenceFrameTransformations
% Create separate publication figures for:
%   1. Moon-Centered Inertial and Moon-rotating frames.
%   2. Local east-north-up frame at a surface sensor.
%
% The figures are schematic and are not drawn to physical scale.
%
% Outputs:
%   reference_frame_moon_centered.eps
%   reference_frame_sensor_centered.eps

clear;
close all;
clc;

%% Figure appearance

fontName = "Arial";

axisLabelFontSize = 12;
annotationFontSize = 10;

backgroundColor = [0.00 0.00 0.00];
moonColor = [0.40 0.40 0.43];
moonEdgeColor = [0.68 0.68 0.71];

mciColor = [0.05 0.65 1.00];
mrColor = [1.00 0.43 0.05];
angleColor = [1.00 0.82 0.05];

eastColor = [0.15 1.00 0.35];
northColor = [0.05 0.85 1.00];
upColor = [1.00 0.82 0.05];

relativePositionColor = [1.00 0.15 0.78];
sensorColor = [1.00 0.20 0.15];

%% Export settings

exportWidthInches = 6.5;
exportHeightInches = 6.5;

% Padding applied on all four EPS edges.
exportPaddingInches = 0.25;

%% Output filenames

scriptDirectory = fileparts(mfilename("fullpath"));

moonCenteredFile = fullfile( ...
    scriptDirectory, ...
    "reference_frame_moon_centered.eps");

sensorCenteredFile = fullfile( ...
    scriptDirectory, ...
    "reference_frame_sensor_centered.eps");

%% Example MCI-to-MR rotation

thetaDeg = 35.0;
thetaRad = deg2rad(thetaDeg);

xInertial = [1;0];
yInertial = [0;1];

xRotating = [
    cos(thetaRad)
    sin(thetaRad)
];

yRotating = [
   -sin(thetaRad)
    cos(thetaRad)
];

circleAngle = linspace(0,2*pi,500);

%% Moon-centered figure

moonCenteredFigure = figure( ...
    "Color",backgroundColor, ...
    "Units","inches", ...
    "Position",[1 1 exportWidthInches exportHeightInches], ...
    "Renderer","painters");

moonCenteredAxes = axes( ...
    moonCenteredFigure, ...
    "Position",[0.05 0.05 0.90 0.90]);

hold(moonCenteredAxes,"on");
axis(moonCenteredAxes,"equal");
axis(moonCenteredAxes,"off");

moonCenteredAxes.Color = backgroundColor;
moonCenteredAxes.FontName = fontName;

xlim(moonCenteredAxes,[-1.35 1.35]);
ylim(moonCenteredAxes,[-1.35 1.35]);

%% Draw the Moon

globalOrigin = [0;-0.05];
globalMoonRadius = 0.72;

globalMoonX = ...
    globalOrigin(1) + ...
    globalMoonRadius*cos(circleAngle);

globalMoonY = ...
    globalOrigin(2) + ...
    globalMoonRadius*sin(circleAngle);

fill(moonCenteredAxes, ...
    globalMoonX,globalMoonY, ...
    moonColor, ...
    "EdgeColor",moonEdgeColor, ...
    "LineWidth",1.0);

%% Draw the MCI axes

globalAxisLength = 1.08;

globalArrowLength = 0.085;
globalArrowWidth = 0.065;
globalLineWidth = 2.0;

xInertialEnd = ...
    globalOrigin + globalAxisLength*xInertial;

yInertialEnd = ...
    globalOrigin + globalAxisLength*yInertial;

drawArrow2D( ...
    moonCenteredAxes, ...
    globalOrigin, ...
    xInertialEnd, ...
    mciColor, ...
    globalLineWidth, ...
    globalArrowLength, ...
    globalArrowWidth, ...
    "-");

drawArrow2D( ...
    moonCenteredAxes, ...
    globalOrigin, ...
    yInertialEnd, ...
    mciColor, ...
    globalLineWidth, ...
    globalArrowLength, ...
    globalArrowWidth, ...
    "-");

%% Draw the MR axes

xRotatingEnd = ...
    globalOrigin + globalAxisLength*xRotating;

yRotatingEnd = ...
    globalOrigin + globalAxisLength*yRotating;

drawArrow2D( ...
    moonCenteredAxes, ...
    globalOrigin, ...
    xRotatingEnd, ...
    mrColor, ...
    globalLineWidth, ...
    globalArrowLength, ...
    globalArrowWidth, ...
    "--");

drawArrow2D( ...
    moonCenteredAxes, ...
    globalOrigin, ...
    yRotatingEnd, ...
    mrColor, ...
    globalLineWidth, ...
    globalArrowLength, ...
    globalArrowWidth, ...
    "--");

%% Label the MCI axes

mciLabelRadius = 1.20;

xInertialLabel = ...
    globalOrigin + mciLabelRadius*xInertial;

yInertialLabel = ...
    globalOrigin + mciLabelRadius*yInertial;

text(moonCenteredAxes, ...
    xInertialLabel(1), ...
    xInertialLabel(2), ...
    "x_I", ...
    "Interpreter","tex", ...
    "Color",mciColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle");

text(moonCenteredAxes, ...
    yInertialLabel(1), ...
    yInertialLabel(2), ...
    "y_I", ...
    "Interpreter","tex", ...
    "Color",mciColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle");

%% Label the MR axes

mrLabelRadius = 1.21;

xRotatingLabel = ...
    globalOrigin + mrLabelRadius*xRotating;

yRotatingLabel = ...
    globalOrigin + mrLabelRadius*yRotating;

text(moonCenteredAxes, ...
    xRotatingLabel(1), ...
    xRotatingLabel(2), ...
    "x_R", ...
    "Interpreter","tex", ...
    "Color",mrColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle");

text(moonCenteredAxes, ...
    yRotatingLabel(1), ...
    yRotatingLabel(2), ...
    "y_R", ...
    "Interpreter","tex", ...
    "Color",mrColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle");

%% Show the common z-axis

plot(moonCenteredAxes, ...
    globalOrigin(1), ...
    globalOrigin(2), ...
    "o", ...
    "MarkerSize",10, ...
    "MarkerFaceColor",backgroundColor, ...
    "MarkerEdgeColor","white", ...
    "LineWidth",1.3);

plot(moonCenteredAxes, ...
    globalOrigin(1), ...
    globalOrigin(2), ...
    ".", ...
    "Color","white", ...
    "MarkerSize",12);

text(moonCenteredAxes, ...
    globalOrigin(1) - 0.08, ...
    globalOrigin(2) - 0.13, ...
    "z_I = z_R", ...
    "Interpreter","tex", ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",annotationFontSize, ...
    "HorizontalAlignment","right", ...
    "VerticalAlignment","top");

%% Draw the angular displacement

angleRadius = 0.37;
angleValues = linspace(0,thetaRad,100);

angleX = ...
    globalOrigin(1) + ...
    angleRadius*cos(angleValues);

angleY = ...
    globalOrigin(2) + ...
    angleRadius*sin(angleValues);

plot(moonCenteredAxes, ...
    angleX,angleY, ...
    "Color",angleColor, ...
    "LineWidth",1.8);

angleTangent = [
   -sin(thetaRad)
    cos(thetaRad)
];

drawArrowHead2D( ...
    moonCenteredAxes, ...
    [angleX(end);angleY(end)], ...
    angleTangent, ...
    angleColor, ...
    0.065, ...
    0.055);

angleLabelPosition = ...
    globalOrigin + ...
    0.49*[
    cos(thetaRad/2)
    sin(thetaRad/2)
    ];

text(moonCenteredAxes, ...
    angleLabelPosition(1), ...
    angleLabelPosition(2), ...
    "\theta(t)", ...
    "Interpreter","tex", ...
    "Color",angleColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center");

%% Sensor-centered figure

sensorCenteredFigure = figure( ...
    "Color",backgroundColor, ...
    "Units","inches", ...
    "Position",[5 1 exportWidthInches exportHeightInches], ...
    "Renderer","painters");

sensorCenteredAxes = axes( ...
    sensorCenteredFigure, ...
    "Position",[0.05 0.05 0.90 0.90]);

hold(sensorCenteredAxes,"on");
axis(sensorCenteredAxes,"equal");
axis(sensorCenteredAxes,"off");

sensorCenteredAxes.Color = backgroundColor;
sensorCenteredAxes.FontName = fontName;

xlim(sensorCenteredAxes,[-1.35 1.35]);
ylim(sensorCenteredAxes,[-0.55 2.15]);

%% Draw the local lunar surface

localMoonRadius = 1.22;
localMoonCenter = [0;-1.14];

localMoonX = ...
    localMoonCenter(1) + ...
    localMoonRadius*cos(circleAngle);

localMoonY = ...
    localMoonCenter(2) + ...
    localMoonRadius*sin(circleAngle);

fill(sensorCenteredAxes, ...
    localMoonX,localMoonY, ...
    moonColor, ...
    "EdgeColor",moonEdgeColor, ...
    "LineWidth",1.0);

%% Define the surface sensor

sensorPosition = [
    0
    localMoonCenter(2) + localMoonRadius
];

scatter(sensorCenteredAxes, ...
    sensorPosition(1), ...
    sensorPosition(2), ...
    65, ...
    "o", ...
    "MarkerFaceColor",sensorColor, ...
    "MarkerEdgeColor","white", ...
    "LineWidth",1.2);

%% Add the surface-sensor callout

sensorLabelPosition = ...
    sensorPosition + [-0.14;-0.16];

% Draw a leader line from the text box to the sensor marker.
plot(sensorCenteredAxes, ...
    [sensorLabelPosition(1) sensorPosition(1)], ...
    [sensorLabelPosition(2) sensorPosition(2)], ...
    "Color",[0.88 0.88 0.88], ...
    "LineWidth",1.0);

text(sensorCenteredAxes, ...
    sensorLabelPosition(1), ...
    sensorLabelPosition(2), ...
    "Surface sensor", ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",annotationFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","right", ...
    "VerticalAlignment","top", ...
    "BackgroundColor",[0.06 0.06 0.07], ...
    "Margin",2.0);

%% Draw the sensor radial-position vector

plot(sensorCenteredAxes, ...
    [localMoonCenter(1) sensorPosition(1)], ...
    [localMoonCenter(2) sensorPosition(2)], ...
    "Color",[0.82 0.82 0.82], ...
    "LineStyle",":", ...
    "LineWidth",1.2);

text(sensorCenteredAxes, ...
    sensorPosition(1) + 0.08, ...
    sensorPosition(2) - 0.43, ...
    "r_{s,R}", ...
    "Interpreter","tex", ...
    "Color",[0.88 0.88 0.88], ...
    "FontName",fontName, ...
    "FontSize",annotationFontSize);

%% Define the projected ENU directions

eastDirection = [1;0];

northDirection = [-0.72;0.55];
northDirection = ...
    northDirection/norm(northDirection);

upDirection = [0;1];

localAxisLength = 0.58;

localArrowLength = 0.070;
localArrowWidth = 0.058;
localLineWidth = 2.0;

%% Draw the east axis

eastEnd = ...
    sensorPosition + ...
    localAxisLength*eastDirection;

drawArrow2D( ...
    sensorCenteredAxes, ...
    sensorPosition, ...
    eastEnd, ...
    eastColor, ...
    localLineWidth, ...
    localArrowLength, ...
    localArrowWidth, ...
    "-");

eastLabelPosition = ...
    sensorPosition + 0.70*eastDirection;

text(sensorCenteredAxes, ...
    eastLabelPosition(1), ...
    eastLabelPosition(2), ...
    "E", ...
    "Color",eastColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center");

%% Draw the north axis

northEnd = ...
    sensorPosition + ...
    localAxisLength*northDirection;

drawArrow2D( ...
    sensorCenteredAxes, ...
    sensorPosition, ...
    northEnd, ...
    northColor, ...
    localLineWidth, ...
    localArrowLength, ...
    localArrowWidth, ...
    "-");

northLabelPosition = ...
    sensorPosition + 0.70*northDirection;

text(sensorCenteredAxes, ...
    northLabelPosition(1), ...
    northLabelPosition(2), ...
    "N", ...
    "Color",northColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center");

%% Draw the up axis

upEnd = ...
    sensorPosition + ...
    localAxisLength*upDirection;

drawArrow2D( ...
    sensorCenteredAxes, ...
    sensorPosition, ...
    upEnd, ...
    upColor, ...
    localLineWidth, ...
    localArrowLength, ...
    localArrowWidth, ...
    "-");

upLabelPosition = ...
    sensorPosition + 0.70*upDirection;

text(sensorCenteredAxes, ...
    upLabelPosition(1), ...
    upLabelPosition(2), ...
    "U", ...
    "Color",upColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center");

%% Define and plot an example RSO

rsoPosition = [0.80;1.50];

relativePositionVector = ...
    rsoPosition - sensorPosition;

drawArrow2D( ...
    sensorCenteredAxes, ...
    sensorPosition, ...
    rsoPosition, ...
    relativePositionColor, ...
    2.2, ...
    0.095, ...
    0.072, ...
    "-");

scatter(sensorCenteredAxes, ...
    rsoPosition(1), ...
    rsoPosition(2), ...
    90, ...
    "p", ...
    "MarkerFaceColor",relativePositionColor, ...
    "MarkerEdgeColor","white", ...
    "LineWidth",1.2);

text(sensorCenteredAxes, ...
    rsoPosition(1) + 0.09, ...
    rsoPosition(2) + 0.03, ...
    "RSO", ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",annotationFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",[0.06 0.06 0.07], ...
    "Margin",2.0);

rhoLabelPosition = ...
    sensorPosition + ...
    0.57*relativePositionVector;

text(sensorCenteredAxes, ...
    rhoLabelPosition(1) + 0.09, ...
    rhoLabelPosition(2), ...
    "\rho_T", ...
    "Interpreter","tex", ...
    "Color",relativePositionColor, ...
    "FontName",fontName, ...
    "FontSize",axisLabelFontSize, ...
    "FontWeight","bold");

%% Export both EPS subfigures

drawnow;

exportgraphics( ...
    moonCenteredAxes, ...
    moonCenteredFile, ...
    "ContentType","vector", ...
    "BackgroundColor",backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",exportWidthInches, ...
    "Height",exportHeightInches, ...
    "Padding",exportPaddingInches, ...
    "PreserveAspectRatio","on");

exportgraphics( ...
    sensorCenteredAxes, ...
    sensorCenteredFile, ...
    "ContentType","vector", ...
    "BackgroundColor",backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",exportWidthInches, ...
    "Height",exportHeightInches, ...
    "Padding",exportPaddingInches, ...
    "PreserveAspectRatio","on");

fprintf("Exported: %s\n",moonCenteredFile);
fprintf("Exported: %s\n",sensorCenteredFile);
fprintf("plotReferenceFrameTransformations completed.\n");

%% Local plotting functions

function drawArrow2D( ...
    axesHandle,startPoint,endPoint,arrowColor, ...
    lineWidth,headLength,headWidth,lineStyle)

direction = endPoint - startPoint;
directionLength = norm(direction);

assert(directionLength > headLength, ...
    "The arrow is too short for the requested arrowhead.");

unitDirection = direction/directionLength;

normalDirection = [
   -unitDirection(2)
    unitDirection(1)
];

arrowBase = ...
    endPoint - headLength*unitDirection;

plot(axesHandle, ...
    [startPoint(1) arrowBase(1)], ...
    [startPoint(2) arrowBase(2)], ...
    "Color",arrowColor, ...
    "LineStyle",lineStyle, ...
    "LineWidth",lineWidth);

trianglePoints = [
    endPoint, ...
    arrowBase + 0.5*headWidth*normalDirection, ...
    arrowBase - 0.5*headWidth*normalDirection
];

patch(axesHandle, ...
    trianglePoints(1,:), ...
    trianglePoints(2,:), ...
    arrowColor, ...
    "EdgeColor","none");

end

function drawArrowHead2D( ...
    axesHandle,endPoint,direction,arrowColor, ...
    headLength,headWidth)

unitDirection = ...
    direction/norm(direction);

normalDirection = [
   -unitDirection(2)
    unitDirection(1)
];

arrowBase = ...
    endPoint - headLength*unitDirection;

trianglePoints = [
    endPoint, ...
    arrowBase + 0.5*headWidth*normalDirection, ...
    arrowBase - 0.5*headWidth*normalDirection
];

patch(axesHandle, ...
    trianglePoints(1,:), ...
    trianglePoints(2,:), ...
    arrowColor, ...
    "EdgeColor","none");

end