function figureInfo = plotOptimizationPilotResults(studyState)
% PLOTOPTIMIZATIONPILOTRESULTS Plot completed pilot results.
%
% Figures:
%   1. Overall-best optimized sensor locations in the lunar south-polar band.
%   2. Conference-style representative RSO geometry with optimized sensors.
%   3. Best-so-far minimization objective across independent runs.
%
% Styling follows the manuscript plotting scripts in this repository:
% dark background, Arial typography, minimum 12-pt text, 6.5-in manuscript
% width, high-contrast annotations, and 0.25-in export padding.
%
% The RSO geometry figure deliberately emphasizes a small representative
% subset of the full population so orbital structure remains legible. Other
% in-scale RSOs are shown faintly for context. A single extreme-scale object
% may be omitted from the conference figure when it would otherwise dominate
% the axis scale; the omitted object is still retained in the study and is
% reported in the console diagnostics.
%
% Usage:
%   plotOptimizationPilotResults(studyState)
%
% If studyState is omitted, the newest completed 10 x 1200-FE pilot is used.

arguments
    studyState (1,1) struct = struct()
end

%% Project paths and study loading

scriptDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(scriptDirectory);
resultsDirectory = fullfile(projectRoot,"results");

if isempty(fieldnames(studyState))
    summaryFile = findLatestPilotSummary(resultsDirectory);
    loadedStudy = load(summaryFile,"studyState");
    assert(isfield(loadedStudy,"studyState"), ...
        "Pilot summary does not contain studyState.");
    studyState = loadedStudy.studyState;
end

assert(isfield(studyState,"validation") && ...
    isfield(studyState.validation,"overallBest"), ...
    "studyState does not contain overall-best EKF validation results.");
assert(isfield(studyState,"overallBestSensorIndices"), ...
    "studyState does not contain the overall-best sensor network.");
assert(isfield(studyState,"studyDirectory"), ...
    "studyState does not identify its output directory.");

validation = studyState.validation.overallBest;

databaseFile = string(studyState.config.databaseFile);
assert(isfile(databaseFile), ...
    "Optimization database was not found: %s",databaseFile);

databaseData = load(databaseFile,"database");
assert(isfield(databaseData,"database"), ...
    "Optimization database MAT file does not contain database.");
database = databaseData.database;

%% Figure styling

style = struct();
style.fontName = "Arial";
style.axisFontSize = 12;
style.labelFontSize = 12;
style.annotationFontSize = 12;
style.legendFontSize = 12;

style.backgroundColor = [0.015 0.020 0.030];
style.textColor = [0.96 0.97 0.99];
style.mutedTextColor = [0.72 0.75 0.80];
style.boxColor = [0.035 0.042 0.055];
style.boxEdgeColor = [0.36 0.40 0.46];
style.gridColor = [0.16 0.18 0.22];

style.candidateColor = [0.28 0.30 0.35];
style.boundaryColor = [0.12 0.82 0.95];
style.sensorColor = [1.00 0.27 0.23];
style.moonColor = [0.58 0.59 0.62];

style.traceBaseColor = [0.56 0.24 0.82];
style.contextTraceColor = ...
    blendColor(style.traceBaseColor,style.backgroundColor,0.24);
style.runTraceColor = ...
    blendColor(style.traceBaseColor,style.backgroundColor,0.34);
style.meanColor = [1.00 0.72 0.06];
style.sigmaBandColor = ...
    blendColor(style.traceBaseColor,style.backgroundColor,0.20);
style.sigmaEdgeColor = ...
    blendColor([0.84 0.84 0.88],style.backgroundColor,0.70);

style.representativeColors = [ ...
    0.05 0.78 0.62
    1.00 0.34 0.27
    1.00 0.70 0.06
    0.18 0.68 1.00
    0.69 0.39 1.00
    0.96 0.43 0.72];

style.exportWidthInches = 6.50;
style.sensorHeightInches = 6.50;
style.rsoHeightInches = 6.50;
style.convergenceHeightInches = 4.60;
style.exportPaddingInches = 0.25;

%% Output directory

figureDirectory = fullfile(string(studyState.studyDirectory),"figures");
if ~isfolder(figureDirectory)
    mkdir(figureDirectory);
end

sensorOutputFile = fullfile( ...
    figureDirectory,"optimized_sensor_network.eps");
rsoOutputFile = fullfile( ...
    figureDirectory,"representative_rso_geometry.eps");
convergenceOutputFile = fullfile( ...
    figureDirectory,"optimization_convergence.eps");

%% Common geometry

moonRadiusKm = database.config.moon.radiusKm;

candidateLatitudeDeg = ...
    rad2deg(database.candidates.latitudesRad(:));
candidateLongitudeDeg = ...
    rad2deg(database.candidates.longitudesRad(:));

bestSensorIndices = studyState.overallBestSensorIndices(:);
bestSensorLatitudeDeg = candidateLatitudeDeg(bestSensorIndices);
bestSensorLongitudeDeg = candidateLongitudeDeg(bestSensorIndices);

%% Figure 1: optimized sensor locations

sensorFigure = figure( ...
    "Name","Optimized Sensor Network", ...
    "Color",style.backgroundColor, ...
    "Units","inches", ...
    "Position",[1 1 style.exportWidthInches style.sensorHeightInches], ...
    "Renderer","painters");
sensorFigure.InvertHardcopy = "off";

sensorLayout = tiledlayout( ...
    sensorFigure,1,1, ...
    "TileSpacing","compact", ...
    "Padding","compact");

sensorAxes = nexttile(sensorLayout,1);
hold(sensorAxes,"on");
axis(sensorAxes,"equal");
axis(sensorAxes,"off");
sensorAxes.Color = style.backgroundColor;
sensorAxes.FontName = style.fontName;
sensorAxes.FontSize = style.axisFontSize;

candidateRadiusKm = ...
    moonRadiusKm .* deg2rad(90.0 + candidateLatitudeDeg);
candidateXKm = candidateRadiusKm .* sind(candidateLongitudeDeg);
candidateYKm = candidateRadiusKm .* cosd(candidateLongitudeDeg);

candidateHandle = scatter( ...
    sensorAxes,candidateXKm,candidateYKm,7,style.candidateColor,"filled", ...
    "DisplayName","Candidates");

circleAngleDeg = linspace(0,360,721);
latitudeGridDeg = [-85 -80 -75];
boundaryHandle = gobjects(1);

for latitudeIndex = 1:numel(latitudeGridDeg)
    currentLatitudeDeg = latitudeGridDeg(latitudeIndex);
    currentRadiusKm = moonRadiusKm*deg2rad(90.0 + currentLatitudeDeg);
    circleXKm = currentRadiusKm*sind(circleAngleDeg);
    circleYKm = currentRadiusKm*cosd(circleAngleDeg);

    if currentLatitudeDeg == -75
        boundaryHandle = plot( ...
            sensorAxes,circleXKm,circleYKm, ...
            "Color",style.boundaryColor, ...
            "LineWidth",2.2, ...
            "DisplayName","75^{\circ}S boundary");
    else
        plot( ...
            sensorAxes,circleXKm,circleYKm,"--", ...
            "Color",style.gridColor, ...
            "LineWidth",1.0, ...
            "HandleVisibility","off");
    end
end

outerRadiusKm = moonRadiusKm*deg2rad(15.0);
longitudeGridDeg = [0 90 180 270];

for longitudeIndex = 1:numel(longitudeGridDeg)
    currentLongitudeDeg = longitudeGridDeg(longitudeIndex);
    radialDistanceKm = [0 outerRadiusKm];

    plot( ...
        sensorAxes, ...
        radialDistanceKm*sind(currentLongitudeDeg), ...
        radialDistanceKm*cosd(currentLongitudeDeg), ...
        "--", ...
        "Color",style.gridColor, ...
        "LineWidth",1.0, ...
        "HandleVisibility","off");
end

longitudeLabelRadiusKm = outerRadiusKm + 34;
longitudeLabelText = [ ...
    "0^{\circ}E" ...
    "90^{\circ}E" ...
    "180^{\circ}E" ...
    "270^{\circ}E"];

for longitudeIndex = 1:numel(longitudeGridDeg)
    currentLongitudeDeg = longitudeGridDeg(longitudeIndex);

    text( ...
        sensorAxes, ...
        longitudeLabelRadiusKm*sind(currentLongitudeDeg), ...
        longitudeLabelRadiusKm*cosd(currentLongitudeDeg), ...
        longitudeLabelText(longitudeIndex), ...
        "Interpreter","tex", ...
        "Color",style.textColor, ...
        "FontName",style.fontName, ...
        "FontSize",style.annotationFontSize, ...
        "FontWeight","bold", ...
        "BackgroundColor",style.boxColor, ...
        "EdgeColor","none", ...
        "Margin",1.5, ...
        "HorizontalAlignment","center", ...
        "VerticalAlignment","middle");
end

latitudeLabelLongitudeDeg = 225;
for latitudeIndex = 1:2
    currentLatitudeDeg = latitudeGridDeg(latitudeIndex);
    currentRadiusKm = moonRadiusKm*deg2rad(90.0 + currentLatitudeDeg);

    text( ...
        sensorAxes, ...
        currentRadiusKm*sind(latitudeLabelLongitudeDeg) - 7, ...
        currentRadiusKm*cosd(latitudeLabelLongitudeDeg) + 7, ...
        sprintf("%d^{\\circ}S",abs(currentLatitudeDeg)), ...
        "Interpreter","tex", ...
        "Color",style.textColor, ...
        "FontName",style.fontName, ...
        "FontSize",style.annotationFontSize, ...
        "FontWeight","bold", ...
        "BackgroundColor",style.boxColor, ...
        "EdgeColor","none", ...
        "Margin",1.5, ...
        "HorizontalAlignment","right", ...
        "VerticalAlignment","middle");
end

scatter( ...
    sensorAxes,0,0,28,".", ...
    "MarkerEdgeColor",style.textColor, ...
    "HandleVisibility","off");

text( ...
    sensorAxes,-16,-16,"90^{\circ}S", ...
    "Interpreter","tex", ...
    "Color",style.textColor, ...
    "FontName",style.fontName, ...
    "FontSize",style.annotationFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",style.boxColor, ...
    "EdgeColor","none", ...
    "Margin",1.5, ...
    "HorizontalAlignment","right", ...
    "VerticalAlignment","top");

bestSensorRadiusKm = ...
    moonRadiusKm .* deg2rad(90.0 + bestSensorLatitudeDeg);
bestSensorXKm = bestSensorRadiusKm .* sind(bestSensorLongitudeDeg);
bestSensorYKm = bestSensorRadiusKm .* cosd(bestSensorLongitudeDeg);

sensorHandle = scatter( ...
    sensorAxes,bestSensorXKm,bestSensorYKm,115,"o", ...
    "MarkerFaceColor",style.sensorColor, ...
    "MarkerEdgeColor",style.textColor, ...
    "LineWidth",1.5, ...
    "DisplayName","Optimized sensors");

for sensorIndex = 1:numel(bestSensorIndices)
    sensorPosition = [bestSensorXKm(sensorIndex);bestSensorYKm(sensorIndex)];
    sensorPositionNorm = norm(sensorPosition);

    if sensorPositionNorm > 1
        labelDirection = sensorPosition/sensorPositionNorm;
    else
        labelDirection = [1;0];
    end

    labelPosition = sensorPosition + 26*labelDirection;

    text( ...
        sensorAxes,labelPosition(1),labelPosition(2), ...
        sprintf("S%d",sensorIndex), ...
        "Color",style.textColor, ...
        "FontName",style.fontName, ...
        "FontSize",style.annotationFontSize, ...
        "FontWeight","bold", ...
        "BackgroundColor",style.boxColor, ...
        "EdgeColor",style.boxEdgeColor, ...
        "Margin",2.0, ...
        "HorizontalAlignment","center", ...
        "VerticalAlignment","middle");
end

sensorLimitKm = outerRadiusKm + 82;
xlim(sensorAxes,[-sensorLimitKm sensorLimitKm]);
ylim(sensorAxes,[-sensorLimitKm sensorLimitKm]);

sensorLegend = legend( ...
    sensorAxes, ...
    [candidateHandle boundaryHandle sensorHandle], ...
    "Candidates", ...
    "75^{\circ}S boundary", ...
    "Optimized sensors", ...
    "Orientation","horizontal");
styleLegend(sensorLegend,style);
sensorLegend.Layout.Tile = "south";

%% Figure 2: conference-style representative RSO geometry

truthStateHistories = validation.truthStateHistories;
assert(ndims(truthStateHistories) == 3 && size(truthStateHistories,1) >= 3, ...
    "Validation truth-state histories have an unexpected size.");
assert(all(isfinite(truthStateHistories(1:3,:,:)),"all"), ...
    "RSO truth trajectories contain nonfinite values.");

numberOfObjects = size(truthStateHistories,3);
coordinateScaleKm = 1.0e4;
radiusHistoriesKm = squeeze(sqrt(sum(truthStateHistories(1:3,:,:).^2,1)));
maxRadiusByObjectKm = max(radiusHistoriesKm,[],1);
[farthestRadiusKm,farthestObjectIndex] = max(maxRadiusByObjectKm);

if isfield(database,"rso") && isfield(database.rso,"catalog")
    rsoCatalog = database.rso.catalog;
else
    rsoCatalog = table();
end

[representativeIndices,scaleOutlierIndex] = ...
    selectRepresentativeRsos(rsoCatalog,maxRadiusByObjectKm);

representativePositions = ...
    truthStateHistories(1:3,:,representativeIndices)/coordinateScaleKm;
plotLimit = 1.12*max(abs(representativePositions),[],"all");
plotLimit = max(plotLimit,4.0*moonRadiusKm/coordinateScaleKm);

rsoFigure = figure( ...
    "Name","Representative RSO Geometry", ...
    "Color",style.backgroundColor, ...
    "Units","inches", ...
    "Position",[1 1 style.exportWidthInches style.rsoHeightInches], ...
    "Renderer","opengl");
rsoFigure.InvertHardcopy = "off";

rsoAxes = axes( ...
    rsoFigure, ...
    "Units","normalized", ...
    "Position",[0.045 0.045 0.91 0.84]);
hold(rsoAxes,"on");
axis(rsoAxes,"equal");
axis(rsoAxes,"vis3d");
axis(rsoAxes,"off");
rsoAxes.Color = style.backgroundColor;

[moonX,moonY,moonZ] = sphere(100);
moonHandle = surf( ...
    rsoAxes, ...
    (moonRadiusKm/coordinateScaleKm)*moonX, ...
    (moonRadiusKm/coordinateScaleKm)*moonY, ...
    (moonRadiusKm/coordinateScaleKm)*moonZ, ...
    "FaceColor",style.moonColor, ...
    "EdgeColor","none", ...
    "FaceAlpha",1.0, ...
    "AmbientStrength",0.35, ...
    "DiffuseStrength",0.78, ...
    "SpecularStrength",0.12, ...
    "DisplayName","Moon");

view(rsoAxes,34,20);
camproj(rsoAxes,"orthographic");
camlight(rsoAxes,"headlight");
lighting(rsoAxes,"gouraud");

% Faint context trajectories are shown only when they fit within the
% representative scale. This preserves population context without allowing
% a single very distant orbit to shrink the Moon and all other trajectories.
contextHandle = gobjects(1);
contextCount = 0;

for objectIndex = 1:numberOfObjects
    if ismember(objectIndex,representativeIndices)
        continue
    end

    currentPosition = truthStateHistories(1:3,:,objectIndex)/coordinateScaleKm;

    if max(abs(currentPosition),[],"all") > 1.02*plotLimit
        continue
    end

    contextCount = contextCount + 1;

    if contextCount == 1
        contextHandle = plot3( ...
            rsoAxes,currentPosition(1,:),currentPosition(2,:),currentPosition(3,:), ...
            "Color",style.contextTraceColor, ...
            "LineWidth",0.75, ...
            "DisplayName","Other RSOs");
    else
        plot3( ...
            rsoAxes,currentPosition(1,:),currentPosition(2,:),currentPosition(3,:), ...
            "Color",style.contextTraceColor, ...
            "LineWidth",0.75, ...
            "HandleVisibility","off");
    end
end

representativeHandle = gobjects(1);
representativeColors = style.representativeColors;

for representativeNumber = 1:numel(representativeIndices)
    objectIndex = representativeIndices(representativeNumber);
    currentColor = representativeColors( ...
        1 + mod(representativeNumber-1,size(representativeColors,1)),:);
    currentPosition = truthStateHistories(1:3,:,objectIndex)/coordinateScaleKm;

    if representativeNumber == 1
        representativeHandle = plot3( ...
            rsoAxes,currentPosition(1,:),currentPosition(2,:),currentPosition(3,:), ...
            "Color",currentColor, ...
            "LineWidth",2.15, ...
            "DisplayName","Representative RSOs");
    else
        plot3( ...
            rsoAxes,currentPosition(1,:),currentPosition(2,:),currentPosition(3,:), ...
            "Color",currentColor, ...
            "LineWidth",2.15, ...
            "HandleVisibility","off");
    end

    scatter3( ...
        rsoAxes,currentPosition(1,1),currentPosition(2,1),currentPosition(3,1), ...
        42,"o", ...
        "MarkerFaceColor",currentColor, ...
        "MarkerEdgeColor",currentColor, ...
        "HandleVisibility","off");

    currentRadius = sqrt(sum(currentPosition.^2,1));
    [~,labelEpoch] = max(currentRadius);
    labelPosition = 1.045*currentPosition(:,labelEpoch);

    if max(abs(labelPosition)) > 0.91*plotLimit
        labelPosition = labelPosition .* ...
            (0.91*plotLimit/max(abs(labelPosition)));
    end

    text( ...
        rsoAxes,labelPosition(1),labelPosition(2),labelPosition(3), ...
        representativeRsoLabel(rsoCatalog,objectIndex), ...
        "Interpreter","tex", ...
        "Color",currentColor, ...
        "FontName",style.fontName, ...
        "FontSize",11, ...
        "FontWeight","bold", ...
        "HorizontalAlignment","left", ...
        "VerticalAlignment","middle");
end

sensorDisplayRadius = (moonRadiusKm + 18)/coordinateScaleKm;
sensorX = sensorDisplayRadius*cosd(bestSensorLatitudeDeg).*cosd(bestSensorLongitudeDeg);
sensorY = sensorDisplayRadius*cosd(bestSensorLatitudeDeg).*sind(bestSensorLongitudeDeg);
sensorZ = sensorDisplayRadius*sind(bestSensorLatitudeDeg);

rsoSensorHandle = scatter3( ...
    rsoAxes,sensorX,sensorY,sensorZ,65,"o", ...
    "MarkerFaceColor",style.sensorColor, ...
    "MarkerEdgeColor",style.textColor, ...
    "LineWidth",1.4, ...
    "DisplayName","Optimized sensors");

for sensorIndex = 1:numel(bestSensorIndices)
    sensorPosition = [sensorX(sensorIndex);sensorY(sensorIndex);sensorZ(sensorIndex)];
    sensorLabelPosition = 1.45*sensorPosition;
    text( ...
        rsoAxes,sensorLabelPosition(1),sensorLabelPosition(2),sensorLabelPosition(3), ...
        sprintf("S%d",sensorIndex), ...
        "Color",style.textColor, ...
        "FontName",style.fontName, ...
        "FontSize",10.5, ...
        "FontWeight","bold");
end

xlim(rsoAxes,[-plotLimit plotLimit]);
ylim(rsoAxes,[-plotLimit plotLimit]);
zlim(rsoAxes,[-plotLimit plotLimit]);
daspect(rsoAxes,[1 1 1]);
pbaspect(rsoAxes,[1 1 1]);

% Compact MCI coordinate triad replaces the dominant 3-D box while keeping
% the frame and scale explicit and fully inside the export boundary.
triadOrigin = [-0.80 -0.79 -0.72].'*plotLimit;
triadLength = 0.20*plotLimit;
triadColor = blendColor(style.textColor,style.backgroundColor,0.78);

quiver3(rsoAxes,triadOrigin(1),triadOrigin(2),triadOrigin(3), ...
    triadLength,0,0,0,"Color",triadColor,"LineWidth",1.5,"MaxHeadSize",0.45);
quiver3(rsoAxes,triadOrigin(1),triadOrigin(2),triadOrigin(3), ...
    0,triadLength,0,0,"Color",triadColor,"LineWidth",1.5,"MaxHeadSize",0.45);
quiver3(rsoAxes,triadOrigin(1),triadOrigin(2),triadOrigin(3), ...
    0,0,triadLength,0,"Color",triadColor,"LineWidth",1.5,"MaxHeadSize",0.45);

text(rsoAxes,triadOrigin(1)+1.12*triadLength,triadOrigin(2),triadOrigin(3), ...
    "x","Color",style.textColor,"FontName",style.fontName, ...
    "FontSize",style.annotationFontSize,"FontWeight","bold");
text(rsoAxes,triadOrigin(1),triadOrigin(2)+1.12*triadLength,triadOrigin(3), ...
    "y","Color",style.textColor,"FontName",style.fontName, ...
    "FontSize",style.annotationFontSize,"FontWeight","bold");
text(rsoAxes,triadOrigin(1),triadOrigin(2),triadOrigin(3)+1.12*triadLength, ...
    "z","Color",style.textColor,"FontName",style.fontName, ...
    "FontSize",style.annotationFontSize,"FontWeight","bold");
text(rsoAxes,triadOrigin(1),triadOrigin(2)-0.10*plotLimit,triadOrigin(3), ...
    "MCI [10^4 km]", ...
    "Interpreter","tex", ...
    "Color",style.mutedTextColor, ...
    "FontName",style.fontName, ...
    "FontSize",10.5, ...
    "FontWeight","bold");

legendHandles = [moonHandle representativeHandle rsoSensorHandle];
legendLabels = ["Moon","Representative RSOs","Optimized sensors"];

if contextCount > 0
    legendHandles = [moonHandle contextHandle representativeHandle rsoSensorHandle];
    legendLabels = ["Moon","Other RSOs","Representative RSOs","Optimized sensors"];
end

rsoLegend = legend( ...
    rsoAxes,legendHandles,cellstr(legendLabels), ...
    "Orientation","horizontal", ...
    "NumColumns",2, ...
    "Units","normalized");
styleLegend(rsoLegend,style);
rsoLegend.Position = [0.24 0.885 0.52 0.085];

%% Figure 3: cleaned convergence versus function evaluations

referenceFe = studyState.runStates{1}.history.fe(:);
numberOfRuns = studyState.numberOfRuns;
numberOfHistoryPoints = numel(referenceFe);
objectiveHistory = NaN(numberOfHistoryPoints,numberOfRuns);

for runIndex = 1:numberOfRuns
    currentRun = studyState.runStates{runIndex};
    assert(isequal(currentRun.history.fe(:),referenceFe), ...
        "Run %d does not share the common FE grid.",runIndex);
    objectiveHistory(:,runIndex) = currentRun.history.bestJ(:);
end

meanObjective = mean(objectiveHistory,2);
stdObjective = std(objectiveHistory,0,2);

convergenceFigure = figure( ...
    "Name","Optimization Convergence", ...
    "Color",style.backgroundColor, ...
    "Units","inches", ...
    "Position",[1 1 style.exportWidthInches style.convergenceHeightInches], ...
    "Renderer","painters");
convergenceFigure.InvertHardcopy = "off";

convergenceAxes = axes( ...
    convergenceFigure, ...
    "Units","normalized", ...
    "Position",[0.13 0.16 0.82 0.77]);
hold(convergenceAxes,"on");
box(convergenceAxes,"off");
grid(convergenceAxes,"on");

convergenceAxes.Color = style.backgroundColor;
convergenceAxes.FontName = style.fontName;
convergenceAxes.FontSize = style.axisFontSize;
convergenceAxes.FontWeight = "bold";
convergenceAxes.XColor = style.textColor;
convergenceAxes.YColor = style.textColor;
convergenceAxes.GridColor = style.gridColor;
convergenceAxes.GridAlpha = 0.60;
convergenceAxes.LineWidth = 1.0;
convergenceAxes.TickDir = "out";

lowerSigma = meanObjective - stdObjective;
upperSigma = meanObjective + stdObjective;
bandX = [referenceFe;flipud(referenceFe)];
bandY = [lowerSigma;flipud(upperSigma)];

sigmaHandle = fill( ...
    convergenceAxes,bandX,bandY,style.sigmaBandColor, ...
    "EdgeColor","none", ...
    "DisplayName","Mean \pm 1\sigma");

runHandle = gobjects(1);
for runIndex = 1:numberOfRuns
    if runIndex == 1
        runHandle = plot( ...
            convergenceAxes,referenceFe,objectiveHistory(:,runIndex), ...
            "Color",style.runTraceColor, ...
            "LineWidth",0.95, ...
            "DisplayName","Independent runs");
    else
        plot( ...
            convergenceAxes,referenceFe,objectiveHistory(:,runIndex), ...
            "Color",style.runTraceColor, ...
            "LineWidth",0.95, ...
            "HandleVisibility","off");
    end
end

plot( ...
    convergenceAxes,referenceFe,lowerSigma,"--", ...
    "Color",style.sigmaEdgeColor,"LineWidth",1.0,"HandleVisibility","off");
plot( ...
    convergenceAxes,referenceFe,upperSigma,"--", ...
    "Color",style.sigmaEdgeColor,"LineWidth",1.0,"HandleVisibility","off");

meanHandle = plot( ...
    convergenceAxes,referenceFe,meanObjective, ...
    "Color",style.meanColor, ...
    "LineWidth",2.8, ...
    "DisplayName","Mean best-so-far J");

scatter( ...
    convergenceAxes,referenceFe(end),meanObjective(end),48,"o", ...
    "MarkerFaceColor",style.meanColor, ...
    "MarkerEdgeColor",style.backgroundColor, ...
    "LineWidth",0.8, ...
    "HandleVisibility","off");

xlabel(convergenceAxes,"Function Evaluations", ...
    "Color",style.textColor, ...
    "FontName",style.fontName, ...
    "FontSize",style.labelFontSize, ...
    "FontWeight","bold");
ylabel(convergenceAxes,"Best Objective, J", ...
    "Color",style.textColor, ...
    "FontName",style.fontName, ...
    "FontSize",style.labelFontSize, ...
    "FontWeight","bold");

xlim(convergenceAxes,[referenceFe(1) referenceFe(end)]);

yAll = [objectiveHistory(:);lowerSigma;upperSigma];
yRange = max(yAll)-min(yAll);
if yRange <= 0
    yRange = max(1,abs(mean(yAll)))*0.05;
end
ylim(convergenceAxes,[min(yAll)-0.06*yRange max(yAll)+0.08*yRange]);

convergenceLegend = legend( ...
    convergenceAxes,[runHandle meanHandle sigmaHandle], ...
    "Independent runs", ...
    "Mean best-so-far J", ...
    "Mean \pm 1\sigma", ...
    "Location","northeast");
styleLegend(convergenceLegend,style);

%% Export

drawnow;

exportgraphics( ...
    sensorLayout,sensorOutputFile, ...
    "ContentType","vector", ...
    "BackgroundColor",style.backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",style.exportWidthInches, ...
    "Height",style.sensorHeightInches, ...
    "Padding",style.exportPaddingInches, ...
    "PreserveAspectRatio","on");

exportgraphics( ...
    rsoFigure,rsoOutputFile, ...
    "ContentType","image", ...
    "Resolution",600, ...
    "BackgroundColor",style.backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",style.exportWidthInches, ...
    "Height",style.rsoHeightInches, ...
    "Padding",style.exportPaddingInches, ...
    "PreserveAspectRatio","on");

exportgraphics( ...
    convergenceFigure,convergenceOutputFile, ...
    "ContentType","vector", ...
    "BackgroundColor",style.backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",style.exportWidthInches, ...
    "Height",style.convergenceHeightInches, ...
    "Padding",style.exportPaddingInches, ...
    "PreserveAspectRatio","on");

%% Return handles and diagnostics

figureInfo = struct();
figureInfo.sensorNetwork = sensorFigure;
figureInfo.rsoPopulation = rsoFigure;
figureInfo.convergence = convergenceFigure;
figureInfo.sensorOutputFile = string(sensorOutputFile);
figureInfo.rsoOutputFile = string(rsoOutputFile);
figureInfo.convergenceOutputFile = string(convergenceOutputFile);
figureInfo.representativeRsoIndices = representativeIndices(:);
figureInfo.farthestRsoIndex = farthestObjectIndex;
figureInfo.farthestRsoMaximumRadiusKm = farthestRadiusKm;
figureInfo.scaleOutlierIndex = scaleOutlierIndex;

fprintf("\nOptimization-pilot figures exported.\n");
fprintf("  Sensors:         %s\n",sensorOutputFile);
fprintf("  RSO geometry:    %s\n",rsoOutputFile);
fprintf("  Convergence:     %s\n",convergenceOutputFile);
fprintf("  Representative RSOs: %s\n",mat2str(representativeIndices(:).'));
fprintf("  Farthest RSO:    %d (max radius %.3f km)\n", ...
    farthestObjectIndex,farthestRadiusKm);

if ~isnan(scaleOutlierIndex)
    fprintf("  Conference-scale outlier omitted: RSO %d\n",scaleOutlierIndex);
end

if ~isempty(rsoCatalog) && height(rsoCatalog) >= farthestObjectIndex
    catalogRow = rsoCatalog(farthestObjectIndex,:);
    fprintf("  Farthest object: %s\n",string(catalogRow.Name));

    if ismember("PeriapsisAltitudeKm",catalogRow.Properties.VariableNames)
        fprintf("  Periapsis alt.:  %.3f km\n",catalogRow.PeriapsisAltitudeKm);
    end
    if ismember("ApoapsisAltitudeKm",catalogRow.Properties.VariableNames)
        fprintf("  Apoapsis alt.:   %.3f km\n",catalogRow.ApoapsisAltitudeKm);
    end
    if ismember("Eccentricity",catalogRow.Properties.VariableNames)
        fprintf("  Eccentricity:    %.6f\n",catalogRow.Eccentricity);
    end
end

end

%% Local helpers

function [representativeIndices,scaleOutlierIndex] = ...
    selectRepresentativeRsos(rsoCatalog,maxRadiusByObjectKm)
% Select a compact set spanning orbital size and inclination.

numberOfObjects = numel(maxRadiusByObjectKm);
allIndices = (1:numberOfObjects).';
scaleOutlierIndex = NaN;
availableIndices = allIndices;

if numberOfObjects >= 4
    [sortedRadii,sortedRadiusIndices] = sort(maxRadiusByObjectKm(:));
    if sortedRadii(end) > 1.25*sortedRadii(end-1)
        scaleOutlierIndex = sortedRadiusIndices(end);
        availableIndices(availableIndices == scaleOutlierIndex) = [];
    end
end

if isempty(availableIndices)
    availableIndices = allIndices;
    scaleOutlierIndex = NaN;
end

representativeIndices = zeros(0,1);

hasCatalog = ...
    ~isempty(rsoCatalog) && ...
    height(rsoCatalog) >= numberOfObjects;

if hasCatalog && ...
        all(ismember(["ApoapsisAltitudeKm","InclinationRad"], ...
        string(rsoCatalog.Properties.VariableNames)))

    apoapsis = rsoCatalog.ApoapsisAltitudeKm;
    inclination = rsoCatalog.InclinationRad;

    [~,apoOrderLocal] = sort(apoapsis(availableIndices));
    apoOrder = availableIndices(apoOrderLocal);
    apoRanks = unique(round(linspace(1,numel(apoOrder),3)));
    representativeIndices = apoOrder(apoRanks);

    [~,minimumInclinationLocal] = min(inclination(availableIndices));
    [~,polarInclinationLocal] = min(abs(inclination(availableIndices)-pi/2));
    [~,maximumInclinationLocal] = max(inclination(availableIndices));

    representativeIndices = unique([ ...
        representativeIndices(:)
        availableIndices(minimumInclinationLocal)
        availableIndices(polarInclinationLocal)
        availableIndices(maximumInclinationLocal)],"stable");
else
    rankIndices = unique(round(linspace(1,numel(availableIndices),6)));
    representativeIndices = availableIndices(rankIndices);
end

maximumRepresentatives = min(6,numel(availableIndices));

if numel(representativeIndices) > maximumRepresentatives
    representativeIndices = representativeIndices(1:maximumRepresentatives);
end

if numel(representativeIndices) < maximumRepresentatives
    fillRanks = unique(round(linspace(1,numel(availableIndices),maximumRepresentatives)));
    fillIndices = availableIndices(fillRanks);
    representativeIndices = unique([representativeIndices(:);fillIndices(:)],"stable");
    representativeIndices = representativeIndices(1:maximumRepresentatives);
end

end

function labelText = representativeRsoLabel(rsoCatalog,objectIndex)

labelText = sprintf("RSO %02d",objectIndex);

if isempty(rsoCatalog) || height(rsoCatalog) < objectIndex
    return
end

variableNames = string(rsoCatalog.Properties.VariableNames);

if all(ismember(["PeriapsisAltitudeKm","Eccentricity","InclinationRad"], ...
        variableNames))
    labelText = sprintf( ...
        "RSO %02d\nh_p = %.0f km, e = %.2f, i = %.0f^{\\circ}", ...
        objectIndex, ...
        rsoCatalog.PeriapsisAltitudeKm(objectIndex), ...
        rsoCatalog.Eccentricity(objectIndex), ...
        rad2deg(rsoCatalog.InclinationRad(objectIndex)));
elseif ismember("Name",variableNames)
    labelText = string(rsoCatalog.Name(objectIndex));
end

end

function blendedColor = blendColor(foregroundColor,backgroundColor,alphaValue)

blendedColor = ...
    alphaValue.*foregroundColor + ...
    (1.0-alphaValue).*backgroundColor;

end

function styleLegend(legendHandle,style)

legendHandle.Color = style.boxColor;
legendHandle.EdgeColor = style.boxEdgeColor;
legendHandle.TextColor = style.textColor;
legendHandle.FontName = style.fontName;
legendHandle.FontSize = style.legendFontSize;
legendHandle.Box = "on";

end

function summaryFile = findLatestPilotSummary(resultsDirectory)

runRoot = fullfile(resultsDirectory,"optimization_runs");
assert(isfolder(runRoot), ...
    "Optimization run directory was not found: %s",runRoot);

summaryFiles = dir(fullfile(runRoot,"**","study_summary.mat"));
assert(~isempty(summaryFiles), ...
    "No optimization study summaries were found under %s.",runRoot);

[~,sortOrder] = sort([summaryFiles.datenum],"descend");
summaryFiles = summaryFiles(sortOrder);

summaryFile = "";

for fileIndex = 1:numel(summaryFiles)
    candidateFile = fullfile( ...
        summaryFiles(fileIndex).folder,summaryFiles(fileIndex).name);

    candidateData = load(candidateFile,"studyState");

    if ~isfield(candidateData,"studyState")
        continue
    end

    candidateStudy = candidateData.studyState;

    isPilot = ...
        isfield(candidateStudy,"numberOfRuns") && ...
        candidateStudy.numberOfRuns == 10 && ...
        isfield(candidateStudy,"config") && ...
        isfield(candidateStudy.config,"functionEvaluationBudget") && ...
        candidateStudy.config.functionEvaluationBudget == 1200 && ...
        isfield(candidateStudy,"validation") && ...
        isfield(candidateStudy.validation,"overallBest");

    if isPilot
        summaryFile = string(candidateFile);
        break
    end
end

assert(strlength(summaryFile) > 0, ...
    "No completed 10-run, 1200-FE pilot summary was found.");

end
