%% plotClpsLsp
% Generate the detailed CLPS lunar south-polar figure.
%
% Output:
%   CLPS_LSP_Detail.eps
%
% The figure shows:
%   - DEM elevation over the lunar south-polar optimization domain
%   - Completed CLPS landing sites
%   - Planned Mons Mouton deployment region
%   - Optional Schrodinger Basin overlap
%   - LSP-wide planned deployment anchors
%
% Optimization domain:
%   -90 deg <= latitude <= -75 deg
%      0 deg <= longitude < 360 deg

clear;
close all;
clc;

%% ========================================================================
%  Figure typography and styling
%  ========================================================================

fontName = "Arial";

% Minimum font size: 12 pt
siteFontSize = 12;
calloutFontSize = 12;
gridFontSize = 12;
boundaryFontSize = 12;
legendFontSize = 12;
colorbarFontSize = 12;

% Colors
boxColor = [0.045 0.045 0.055];
boxEdgeColor = [0.55 0.55 0.55];

completedColor = [1.00 0.08 0.08];
plannedColor = [1.00 0.00 0.85];
optionalColor = [1.00 0.55 0.05];
boundaryColor = [0.10 0.85 1.00];

% Grid styling
gridColor = [0.15 0.15 0.15];

% Callout arrows
arrowLineWidth = 2.2;
arrowHeadSize = 1.0;

%% ========================================================================
%  Load DEM
%  ========================================================================

scriptDirectory = fileparts(mfilename("fullpath"));
repositoryRoot = fileparts(scriptDirectory);

demFile = fullfile( ...
    repositoryRoot, ...
    "data", ...
    "new_lunar_interpolant_model.mat");

assert(isfile(demFile), ...
    "DEM file was not found: %s",demFile);

loadedData = load(demFile);
variableNames = fieldnames(loadedData);

demInterpolant = [];

for variableIndex = 1:numel(variableNames)

    currentVariable = ...
        loadedData.(variableNames{variableIndex});

    if isa(currentVariable,"griddedInterpolant")
        demInterpolant = currentVariable;
        break;
    end

end

assert(~isempty(demInterpolant), ...
    "No griddedInterpolant was found in %s.",demFile);

%% ========================================================================
%  Constants
%  ========================================================================

moonRadiusKm = 1737.4;

domainSouthDeg = -90.0;
domainNorthDeg = -75.0;

%% ========================================================================
%  Evaluate south-polar DEM
%  ========================================================================

longitudeDeg = linspace(0.0,360.0,721);

latitudeDeg = linspace( ...
    domainSouthDeg, ...
    domainNorthDeg, ...
    301);

[longitudeMeshDeg,latitudeMeshDeg] = meshgrid( ...
    longitudeDeg, ...
    latitudeDeg);

% Repository convention:
%
%   elevation = F(latitude,longitude)

elevationKm = double(demInterpolant( ...
    latitudeMeshDeg, ...
    longitudeMeshDeg));

finiteElevationKm = elevationKm(isfinite(elevationKm));

elevationLimitsKm = [ ...
    min(finiteElevationKm), ...
    max(finiteElevationKm)];

%% ========================================================================
%  Completed CLPS landing sites
%  ========================================================================

% IM-1 / TO2-IM
% Near Malapert A
%
% IM-2 / PRIME-1
% Mons Mouton

completedLatitudeDeg = [
    -80.1277
    -84.7754
];

completedLongitudeDeg = [
      1.4357
     29.1264
];

%% ========================================================================
%  Mons Mouton planned region
%  ========================================================================

% Griffin / TO20A
% IM-4 / CP-22

monsLatitudeSouthDeg = -86.22;
monsLatitudeNorthDeg = -83.30;

monsLongitudeWestDeg = 11.67;
monsLongitudeEastDeg = 53.03;

%% ========================================================================
%  Schrodinger Basin overlap
%  ========================================================================

% Published regional extent:
%
%   latitude  = [-79.95,-69.52] deg
%   longitude = [112.33,153.44] deg E
%
% Only the portion overlapping the optimization domain is displayed.

schrodingerLatitudeSouthDeg = -79.95;
schrodingerLatitudeNorthDeg = domainNorthDeg;

schrodingerLongitudeWestDeg = 112.33;
schrodingerLongitudeEastDeg = 153.44;

%% ========================================================================
%  Create figure
%  ========================================================================

detailFigure = figure( ...
    "Color","black", ...
    "Units","inches", ...
    "Position",[1 1 10.5 6.8]);

detailFigure.InvertHardcopy = "off";

detailAxes = axes( ...
    detailFigure, ...
    "Position",[0.055 0.115 0.80 0.83]);

hold(detailAxes,"on");

detailAxes.Color = "black";
detailAxes.FontName = fontName;
detailAxes.SortMethod = "childorder";

%% ========================================================================
%  Convert DEM to south-polar coordinates
%
%  Orientation:
%
%       0 E   = top
%       90 E  = right
%       180 E = bottom
%       270 E = left
%  ========================================================================

polarDistanceKm = ...
    moonRadiusKm .* ...
    deg2rad(90.0 + latitudeMeshDeg);

detailXKm = ...
    polarDistanceKm .* ...
    sind(longitudeMeshDeg);

detailYKm = ...
    polarDistanceKm .* ...
    cosd(longitudeMeshDeg);

outerRadiusKm = ...
    moonRadiusKm * ...
    deg2rad(15.0);

%% ========================================================================
%  Plot DEM
%  ========================================================================

surf(detailAxes, ...
    detailXKm, ...
    detailYKm, ...
    zeros(size(detailXKm)), ...
    elevationKm, ...
    "EdgeColor","none", ...
    "FaceColor","interp");

view(detailAxes,2);

colormap(detailAxes,turbo(256));
clim(detailAxes,elevationLimitsKm);

%% ========================================================================
%  Latitude circles
%  ========================================================================

circleAngleDeg = linspace(0,360,721);

latitudeGridDeg = [
    -85
    -80
    -75
];

for latitudeIndex = 1:numel(latitudeGridDeg)

    currentLatitudeDeg = ...
        latitudeGridDeg(latitudeIndex);

    currentRadiusKm = ...
        moonRadiusKm * ...
        deg2rad(90 + currentLatitudeDeg);

    circleXKm = ...
        currentRadiusKm .* ...
        sind(circleAngleDeg);

    circleYKm = ...
        currentRadiusKm .* ...
        cosd(circleAngleDeg);

    if currentLatitudeDeg == domainNorthDeg

        % Optimization boundary
        plot(detailAxes, ...
            circleXKm, ...
            circleYKm, ...
            "Color",boundaryColor, ...
            "LineWidth",2.4);

    else

        % Internal latitude grid
        plot(detailAxes, ...
            circleXKm, ...
            circleYKm, ...
            "--", ...
            "Color",gridColor, ...
            "LineWidth",1.0);

    end

end

%% ========================================================================
%  Longitude spokes
%  ========================================================================

longitudeGridDeg = [
      0
     90
    180
    270
];

for longitudeIndex = 1:numel(longitudeGridDeg)

    currentLongitudeDeg = ...
        longitudeGridDeg(longitudeIndex);

    radialDistanceKm = [
        0
        outerRadiusKm
    ];

    spokeXKm = ...
        radialDistanceKm .* ...
        sind(currentLongitudeDeg);

    spokeYKm = ...
        radialDistanceKm .* ...
        cosd(currentLongitudeDeg);

    plot(detailAxes, ...
        spokeXKm, ...
        spokeYKm, ...
        "--", ...
        "Color",gridColor, ...
        "LineWidth",1.0);

end

%% ========================================================================
%  Longitude labels
%
%  Place these slightly farther outside the cyan optimization boundary and
%  add a dark backing so white text remains readable regardless of the DEM.
%  ========================================================================

longitudeLabelRadiusKm = ...
    outerRadiusKm + 38;

longitudeLabelText = [
    "0^{\circ}E"
    "90^{\circ}E"
    "180^{\circ}E"
    "270^{\circ}E"
];

for longitudeIndex = 1:numel(longitudeGridDeg)

    currentLongitudeDeg = ...
        longitudeGridDeg(longitudeIndex);

    labelXKm = ...
        longitudeLabelRadiusKm .* ...
        sind(currentLongitudeDeg);

    labelYKm = ...
        longitudeLabelRadiusKm .* ...
        cosd(currentLongitudeDeg);

    text(detailAxes, ...
        labelXKm, ...
        labelYKm, ...
        longitudeLabelText(longitudeIndex), ...
        "Interpreter","tex", ...
        "Color","white", ...
        "FontName",fontName, ...
        "FontSize",gridFontSize, ...
        "FontWeight","bold", ...
        "BackgroundColor",boxColor, ...
        "EdgeColor","none", ...
        "Margin",1.5, ...
        "HorizontalAlignment","center", ...
        "VerticalAlignment","middle");

end

%% ========================================================================
%  Latitude labels
%
%  Dark backing is used because these labels lie directly on the DEM.
%  ========================================================================

latitudeLabelLongitudeDeg = 225;

latitudeLabelOffsetXKm = -8;
latitudeLabelOffsetYKm = 7;

for latitudeIndex = 1:2

    currentLatitudeDeg = ...
        latitudeGridDeg(latitudeIndex);

    currentRadiusKm = ...
        moonRadiusKm * ...
        deg2rad(90 + currentLatitudeDeg);

    labelXKm = ...
        currentRadiusKm .* ...
        sind(latitudeLabelLongitudeDeg);

    labelYKm = ...
        currentRadiusKm .* ...
        cosd(latitudeLabelLongitudeDeg);

    text(detailAxes, ...
        labelXKm + latitudeLabelOffsetXKm, ...
        labelYKm + latitudeLabelOffsetYKm, ...
        sprintf("%d^{\\circ}S", ...
        abs(currentLatitudeDeg)), ...
        "Interpreter","tex", ...
        "Color","white", ...
        "FontName",fontName, ...
        "FontSize",gridFontSize, ...
        "FontWeight","bold", ...
        "BackgroundColor",boxColor, ...
        "EdgeColor","none", ...
        "Margin",1.5, ...
        "HorizontalAlignment","right", ...
        "VerticalAlignment","middle");

end

%% ========================================================================
%  South Pole
%  ========================================================================

plot(detailAxes, ...
    0, ...
    0, ...
    ".", ...
    "Color","white", ...
    "MarkerSize",14);

text(detailAxes, ...
    -18, ...
    -18, ...
    "South Pole", ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",gridFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "EdgeColor","none", ...
    "Margin",1.5, ...
    "HorizontalAlignment","right", ...
    "VerticalAlignment","top");

%% ========================================================================
%  Mons Mouton planned region
%  ========================================================================

[monsRegionXKm,monsRegionYKm] = ...
    rectangularPolarRegion( ...
        monsLatitudeSouthDeg, ...
        monsLatitudeNorthDeg, ...
        monsLongitudeWestDeg, ...
        monsLongitudeEastDeg, ...
        moonRadiusKm);

monsRegionHandle = patch( ...
    detailAxes, ...
    monsRegionXKm, ...
    monsRegionYKm, ...
    plannedColor, ...
    "FaceAlpha",0.23, ...
    "EdgeColor",plannedColor, ...
    "LineWidth",2.8, ...
    "DisplayName","Planned LSP anchor region");

%% ========================================================================
%  Schrodinger Basin overlap
%  ========================================================================

[schrodingerRegionXKm,schrodingerRegionYKm] = ...
    rectangularPolarRegion( ...
        schrodingerLatitudeSouthDeg, ...
        schrodingerLatitudeNorthDeg, ...
        schrodingerLongitudeWestDeg, ...
        schrodingerLongitudeEastDeg, ...
        moonRadiusKm);

schrodingerRegionHandle = patch( ...
    detailAxes, ...
    schrodingerRegionXKm, ...
    schrodingerRegionYKm, ...
    optionalColor, ...
    "FaceAlpha",0.24, ...
    "EdgeColor",optionalColor, ...
    "LineWidth",2.6, ...
    "DisplayName","Optional regional overlap");

%% ========================================================================
%  Completed landing sites
%  ========================================================================

[completedXKm,completedYKm] = ...
    polarCoordinates( ...
        completedLatitudeDeg, ...
        completedLongitudeDeg, ...
        moonRadiusKm);

completedHandle = scatter( ...
    detailAxes, ...
    completedXKm, ...
    completedYKm, ...
    95, ...
    "o", ...
    "MarkerFaceColor","none", ...
    "MarkerEdgeColor",completedColor, ...
    "LineWidth",2.5, ...
    "DisplayName","Completed landing");

%% ========================================================================
%  IM-1 callout
%  ========================================================================

im1CalloutXKm = -815;
im1CalloutYKm = 190;

im1ArrowStartXKm = -505;
im1ArrowStartYKm = im1CalloutYKm;

quiver(detailAxes, ...
    im1ArrowStartXKm, ...
    im1ArrowStartYKm, ...
    completedXKm(1) - im1ArrowStartXKm, ...
    completedYKm(1) - im1ArrowStartYKm, ...
    0, ...
    "Color",[1.00 0.25 0.20], ...
    "LineWidth",arrowLineWidth, ...
    "MaxHeadSize",arrowHeadSize, ...
    "AutoScale","off", ...
    "HandleVisibility","off");

text(detailAxes, ...
    im1CalloutXKm, ...
    im1CalloutYKm, ...
    { ...
    "IM-1 / TO2-IM", ...
    "Completed - Near Malapert A" ...
    }, ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",calloutFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "EdgeColor",boxEdgeColor, ...
    "Margin",3, ...
    "HorizontalAlignment","left", ...
    "VerticalAlignment","middle");

%% ========================================================================
%  IM-2 local label
%  ========================================================================

text(detailAxes, ...
    completedXKm(2) + 16, ...
    completedYKm(2) - 20, ...
    "IM-2", ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",siteFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "EdgeColor","none", ...
    "Margin",1.8, ...
    "HorizontalAlignment","left", ...
    "VerticalAlignment","top");

%% ========================================================================
%  LSP-wide planned anchors
%  ========================================================================

[lspAnchorXKm,lspAnchorYKm] = ...
    polarCoordinates( ...
        domainNorthDeg, ...
        315, ...
        moonRadiusKm);

lspCalloutXKm = -815;
lspCalloutYKm = 470;

lspArrowStartXKm = -505;
lspArrowStartYKm = lspCalloutYKm - 20;

quiver(detailAxes, ...
    lspArrowStartXKm, ...
    lspArrowStartYKm, ...
    lspAnchorXKm - lspArrowStartXKm, ...
    lspAnchorYKm - lspArrowStartYKm, ...
    0, ...
    "Color",[1.00 0.15 0.90], ...
    "LineWidth",arrowLineWidth, ...
    "MaxHeadSize",arrowHeadSize, ...
    "AutoScale","off", ...
    "HandleVisibility","off");

text(detailAxes, ...
    lspCalloutXKm, ...
    lspCalloutYKm, ...
    { ...
    "LSP-wide planned anchors", ...
    "Blue Moon MK1 / CT-3", ...
    "Blue Ghost 4 / CS-6", ...
    "Nova-D / CT-4" ...
    }, ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",calloutFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "EdgeColor",boxEdgeColor, ...
    "Margin",3, ...
    "HorizontalAlignment","left", ...
    "VerticalAlignment","middle");

%% ========================================================================
%  Mons Mouton callout
%  ========================================================================

monsCenterLatitudeDeg = ...
    0.5*( ...
    monsLatitudeSouthDeg + ...
    monsLatitudeNorthDeg);

monsCenterLongitudeDeg = ...
    0.5*( ...
    monsLongitudeWestDeg + ...
    monsLongitudeEastDeg);

[monsCenterXKm,monsCenterYKm] = ...
    polarCoordinates( ...
        monsCenterLatitudeDeg, ...
        monsCenterLongitudeDeg, ...
        moonRadiusKm);

monsCalloutXKm = 500;
monsCalloutYKm = 420;

monsArrowStartXKm = 475;
monsArrowStartYKm = monsCalloutYKm - 25;

quiver(detailAxes, ...
    monsArrowStartXKm, ...
    monsArrowStartYKm, ...
    monsCenterXKm - monsArrowStartXKm, ...
    monsCenterYKm - monsArrowStartYKm, ...
    0, ...
    "Color",[1.00 0.15 0.90], ...
    "LineWidth",arrowLineWidth, ...
    "MaxHeadSize",arrowHeadSize, ...
    "AutoScale","off", ...
    "HandleVisibility","off");

text(detailAxes, ...
    monsCalloutXKm, ...
    monsCalloutYKm, ...
    { ...
    "Mons Mouton", ...
    "Completed: IM-2 / PRIME-1", ...
    "Planned: Griffin / TO20A", ...
    "Planned: IM-4 / CP-22" ...
    }, ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",calloutFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "EdgeColor",boxEdgeColor, ...
    "Margin",3, ...
    "HorizontalAlignment","left", ...
    "VerticalAlignment","middle");

%% ========================================================================
%  Schrodinger Basin callout
%  ========================================================================

schrodingerCenterLatitudeDeg = ...
    0.5*( ...
    schrodingerLatitudeSouthDeg + ...
    schrodingerLatitudeNorthDeg);

schrodingerCenterLongitudeDeg = ...
    0.5*( ...
    schrodingerLongitudeWestDeg + ...
    schrodingerLongitudeEastDeg);

[schrodingerCenterXKm,schrodingerCenterYKm] = ...
    polarCoordinates( ...
        schrodingerCenterLatitudeDeg, ...
        schrodingerCenterLongitudeDeg, ...
        moonRadiusKm);

schrodingerCalloutXKm = 500;
schrodingerCalloutYKm = -300;

schrodingerArrowStartXKm = 475;
schrodingerArrowStartYKm = ...
    schrodingerCalloutYKm + 15;

quiver(detailAxes, ...
    schrodingerArrowStartXKm, ...
    schrodingerArrowStartYKm, ...
    schrodingerCenterXKm - schrodingerArrowStartXKm, ...
    schrodingerCenterYKm - schrodingerArrowStartYKm, ...
    0, ...
    "Color",[1.00 0.60 0.12], ...
    "LineWidth",arrowLineWidth, ...
    "MaxHeadSize",arrowHeadSize, ...
    "AutoScale","off", ...
    "HandleVisibility","off");

text(detailAxes, ...
    schrodingerCalloutXKm, ...
    schrodingerCalloutYKm, ...
    { ...
    "Schrodinger Basin", ...
    "SERIES-2 / CP-12 - planned", ...
    "Optional LSP anchor" ...
    }, ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",calloutFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "EdgeColor",boxEdgeColor, ...
    "Margin",3, ...
    "HorizontalAlignment","left", ...
    "VerticalAlignment","middle");

%% ========================================================================
%  Optimization boundary label
%  ========================================================================

boundaryLabelXKm = -150;
boundaryLabelYKm = -540;

text(detailAxes, ...
    boundaryLabelXKm, ...
    boundaryLabelYKm, ...
    "75^{\circ}S optimization boundary", ...
    "Interpreter","tex", ...
    "Color",boundaryColor, ...
    "FontName",fontName, ...
    "FontSize",boundaryFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "EdgeColor","none", ...
    "Margin",2, ...
    "HorizontalAlignment","left", ...
    "VerticalAlignment","middle");

%% ========================================================================
%  Colorbar
%  ========================================================================

detailColorbar = colorbar(detailAxes);

detailColorbar.Position = ...
    [0.925 0.19 0.018 0.64];

detailColorbar.Color = "white";
detailColorbar.FontName = fontName;
detailColorbar.FontSize = colorbarFontSize;

detailColorbar.Label.String = ...
    "DEM elevation (km)";

detailColorbar.Label.Color = "white";
detailColorbar.Label.FontName = fontName;
detailColorbar.Label.FontSize = 13;
detailColorbar.Label.FontWeight = "bold";

%% ========================================================================
%  Legend
%  ========================================================================

detailLegend = legend( ...
    detailAxes, ...
    [ ...
    completedHandle, ...
    monsRegionHandle, ...
    schrodingerRegionHandle ...
    ], ...
    "Completed landing", ...
    "Planned LSP anchor region", ...
    "Optional regional overlap");

detailLegend.Color = boxColor;
detailLegend.EdgeColor = boxEdgeColor;
detailLegend.TextColor = "white";

detailLegend.FontName = fontName;
detailLegend.FontSize = legendFontSize;

detailLegend.Orientation = "horizontal";
detailLegend.Units = "normalized";

detailLegend.Position = ...
    [0.195 0.022 0.590 0.055];

%% ========================================================================
%  Formatting
%  ========================================================================

axis(detailAxes,"equal");
axis(detailAxes,"off");

xlim(detailAxes,[-880 880]);
ylim(detailAxes,[-610 610]);

%% ========================================================================
%  Export
%  ========================================================================

detailOutputFile = fullfile( ...
    scriptDirectory, ...
    "CLPS_LSP_Detail.eps");

exportgraphics( ...
    detailFigure, ...
    detailOutputFile, ...
    "ContentType","image", ...
    "Resolution",600, ...
    "BackgroundColor","black");

fprintf("plotClpsLsp completed.\n");
fprintf("Saved: %s\n",detailOutputFile);

%% ========================================================================
%  Local functions
%  ========================================================================

function [xKm,yKm] = polarCoordinates( ...
    latitudeDeg, ...
    longitudeDeg, ...
    moonRadiusKm)

radialDistanceKm = ...
    moonRadiusKm .* ...
    deg2rad(90 + latitudeDeg);

xKm = ...
    radialDistanceKm .* ...
    sind(longitudeDeg);

yKm = ...
    radialDistanceKm .* ...
    cosd(longitudeDeg);

end

function [regionXKm,regionYKm] = ...
    rectangularPolarRegion( ...
        latitudeSouthDeg, ...
        latitudeNorthDeg, ...
        longitudeWestDeg, ...
        longitudeEastDeg, ...
        moonRadiusKm)

numberOfArcPoints = 160;
numberOfEdgePoints = 80;

%% Northern boundary

northLongitudeDeg = linspace( ...
    longitudeWestDeg, ...
    longitudeEastDeg, ...
    numberOfArcPoints);

northLatitudeDeg = ...
    latitudeNorthDeg .* ...
    ones(size(northLongitudeDeg));

%% Eastern boundary

eastLatitudeDeg = linspace( ...
    latitudeNorthDeg, ...
    latitudeSouthDeg, ...
    numberOfEdgePoints);

eastLongitudeDeg = ...
    longitudeEastDeg .* ...
    ones(size(eastLatitudeDeg));

%% Southern boundary

southLongitudeDeg = linspace( ...
    longitudeEastDeg, ...
    longitudeWestDeg, ...
    numberOfArcPoints);

southLatitudeDeg = ...
    latitudeSouthDeg .* ...
    ones(size(southLongitudeDeg));

%% Western boundary

westLatitudeDeg = linspace( ...
    latitudeSouthDeg, ...
    latitudeNorthDeg, ...
    numberOfEdgePoints);

westLongitudeDeg = ...
    longitudeWestDeg .* ...
    ones(size(westLatitudeDeg));

%% Assemble polygon

regionLatitudeDeg = [ ...
    northLatitudeDeg, ...
    eastLatitudeDeg, ...
    southLatitudeDeg, ...
    westLatitudeDeg ...
];

regionLongitudeDeg = [ ...
    northLongitudeDeg, ...
    eastLongitudeDeg, ...
    southLongitudeDeg, ...
    westLongitudeDeg ...
];

[regionXKm,regionYKm] = ...
    polarCoordinates( ...
        regionLatitudeDeg, ...
        regionLongitudeDeg, ...
        moonRadiusKm);

end