%% plotExclusionConstraint
% Generate a compact celestial-body exclusion-constraint schematic for
% the lunar surface sensor network study.
%
% This version is sized for manuscript display at approximately
% 0.50\columnwidth.
%
% The schematic illustrates:
%   - Physical occultation boundary, theta_occ,b
%   - Configured minimum angular separation, theta_min
%   - Actual sensor-to-target angular separation, theta_b
%
% Output:
%   Exclusion_Constraint_Schematic.eps

clear;
close all;
clc;

%% ========================================================================
%  Figure styling
%  ========================================================================

fontName = "Arial";

% Larger text is intentional because the final LaTeX figure is displayed
% at approximately 0.50 column width.
objectFontSize = 16;
angleFontSize = 18;

backgroundColor = [0.00 0.00 0.00];

sensorColor = [1.00 0.15 0.12];
targetColor = [0.10 0.80 1.00];
bodyColor = [0.62 0.62 0.65];

occultationColor = [0.78 0.78 0.80];
minimumAngleColor = [1.00 0.55 0.05];
targetAngleColor = [0.10 0.80 1.00];

lineOfSightColor = [0.95 0.95 0.97];
bodyDirectionColor = [0.62 0.62 0.66];

occultationShade = [0.20 0.20 0.22];
exclusionShade = [0.40 0.24 0.05];

boxColor = [0.035 0.035 0.045];

leaderLineWidth = 2.4;
leaderHeadSize = 0.90;

%% ========================================================================
%  Representative schematic geometry
%  ========================================================================

sensor = [-2.20,0.00];

body = [0.95,0.00];
bodyRadius = 0.66;

bodyRange = norm(body-sensor);

thetaOcc = asin(bodyRadius/bodyRange);

% Common center-referenced minimum angular separation used in this study.
thetaMin = deg2rad(20);

thetaRequired = max(thetaOcc,thetaMin);

% Place the example RSO outside the exclusion region.
thetaTarget = thetaRequired + deg2rad(14);

targetRange = 4.15;

target = ...
    sensor + ...
    targetRange*[ ...
    cos(thetaTarget), ...
    sin(thetaTarget)];

%% ========================================================================
%  Create figure
%  ========================================================================

figureHandle = figure( ...
    "Color",backgroundColor, ...
    "Units","inches", ...
    "Position",[1 1 5.4 4.1]);

figureHandle.InvertHardcopy = "off";

axesHandle = axes( ...
    figureHandle, ...
    "Units","normalized", ...
    "Position",[0.03 0.04 0.94 0.92]);

hold(axesHandle,"on");

axesHandle.Color = backgroundColor;

axis(axesHandle,"equal");
axis(axesHandle,"off");

%% ========================================================================
%  Shaded physical-occultation region
%  ========================================================================

sectorRadius = 3.35;

occultationAngles = linspace( ...
    -thetaOcc, ...
     thetaOcc, ...
     240);

patch( ...
    axesHandle, ...
    [ ...
    sensor(1), ...
    sensor(1) + sectorRadius*cos(occultationAngles), ...
    sensor(1) ...
    ], ...
    [ ...
    sensor(2), ...
    sensor(2) + sectorRadius*sin(occultationAngles), ...
    sensor(2) ...
    ], ...
    occultationShade, ...
    "EdgeColor","none", ...
    "FaceAlpha",0.98, ...
    "HandleVisibility","off");

%% ========================================================================
%  Additional keep-out region
%  ========================================================================

if thetaRequired > thetaOcc

    upperAngles = linspace( ...
        thetaOcc, ...
        thetaRequired, ...
        160);

    patch( ...
        axesHandle, ...
        [ ...
        sensor(1), ...
        sensor(1) + sectorRadius*cos(upperAngles), ...
        sensor(1) ...
        ], ...
        [ ...
        sensor(2), ...
        sensor(2) + sectorRadius*sin(upperAngles), ...
        sensor(2) ...
        ], ...
        exclusionShade, ...
        "EdgeColor","none", ...
        "FaceAlpha",0.98, ...
        "HandleVisibility","off");

    lowerAngles = linspace( ...
        -thetaRequired, ...
        -thetaOcc, ...
        160);

    patch( ...
        axesHandle, ...
        [ ...
        sensor(1), ...
        sensor(1) + sectorRadius*cos(lowerAngles), ...
        sensor(1) ...
        ], ...
        [ ...
        sensor(2), ...
        sensor(2) + sectorRadius*sin(lowerAngles), ...
        sensor(2) ...
        ], ...
        exclusionShade, ...
        "EdgeColor","none", ...
        "FaceAlpha",0.98, ...
        "HandleVisibility","off");

end

%% ========================================================================
%  Celestial body
%  ========================================================================

bodyAngle = linspace(0,2*pi,300);

fill( ...
    axesHandle, ...
    body(1) + bodyRadius*cos(bodyAngle), ...
    body(2) + bodyRadius*sin(bodyAngle), ...
    bodyColor, ...
    "EdgeColor",[0.95 0.95 0.95], ...
    "LineWidth",1.8);

%% ========================================================================
%  Body-center reference direction
%  ========================================================================

plot( ...
    axesHandle, ...
    [sensor(1),body(1)], ...
    [sensor(2),body(2)], ...
    "--", ...
    "Color",bodyDirectionColor, ...
    "LineWidth",2.0);

%% ========================================================================
%  Physical occultation boundaries
%  ========================================================================

boundaryLength = 3.52;

upperOccultationPoint = ...
    sensor + ...
    boundaryLength*[ ...
    cos(thetaOcc), ...
    sin(thetaOcc)];

lowerOccultationPoint = ...
    sensor + ...
    boundaryLength*[ ...
    cos(-thetaOcc), ...
    sin(-thetaOcc)];

plot( ...
    axesHandle, ...
    [sensor(1),upperOccultationPoint(1)], ...
    [sensor(2),upperOccultationPoint(2)], ...
    ":", ...
    "Color",occultationColor, ...
    "LineWidth",2.5);

plot( ...
    axesHandle, ...
    [sensor(1),lowerOccultationPoint(1)], ...
    [sensor(2),lowerOccultationPoint(2)], ...
    ":", ...
    "Color",occultationColor, ...
    "LineWidth",2.5);

%% ========================================================================
%  Minimum angular-separation boundaries
%  ========================================================================

upperMinimumPoint = ...
    sensor + ...
    boundaryLength*[ ...
    cos(thetaRequired), ...
    sin(thetaRequired)];

lowerMinimumPoint = ...
    sensor + ...
    boundaryLength*[ ...
    cos(-thetaRequired), ...
    sin(-thetaRequired)];

plot( ...
    axesHandle, ...
    [sensor(1),upperMinimumPoint(1)], ...
    [sensor(2),upperMinimumPoint(2)], ...
    "--", ...
    "Color",minimumAngleColor, ...
    "LineWidth",3.0);

plot( ...
    axesHandle, ...
    [sensor(1),lowerMinimumPoint(1)], ...
    [sensor(2),lowerMinimumPoint(2)], ...
    "--", ...
    "Color",minimumAngleColor, ...
    "LineWidth",3.0);

%% ========================================================================
%  Accepted target LOS
%  ========================================================================

plot( ...
    axesHandle, ...
    [sensor(1),target(1)], ...
    [sensor(2),target(2)], ...
    "-", ...
    "Color",lineOfSightColor, ...
    "LineWidth",3.1);

%% ========================================================================
%  Sensor and RSO markers
%  ========================================================================

plot( ...
    axesHandle, ...
    sensor(1), ...
    sensor(2), ...
    "o", ...
    "MarkerSize",12, ...
    "MarkerFaceColor",sensorColor, ...
    "MarkerEdgeColor","white", ...
    "LineWidth",1.3);

plot( ...
    axesHandle, ...
    target(1), ...
    target(2), ...
    "o", ...
    "MarkerSize",12, ...
    "MarkerFaceColor",targetColor, ...
    "MarkerEdgeColor","white", ...
    "LineWidth",1.3);

%% ========================================================================
%  Angle arcs
%  ========================================================================

occultationArcRadius = 0.88;
minimumArcRadius = 1.30;
targetArcRadius = 1.72;

drawAngleArc( ...
    axesHandle, ...
    sensor, ...
    0, ...
    thetaOcc, ...
    occultationArcRadius, ...
    occultationColor, ...
    2.7);

drawAngleArc( ...
    axesHandle, ...
    sensor, ...
    0, ...
    thetaRequired, ...
    minimumArcRadius, ...
    minimumAngleColor, ...
    3.0);

drawAngleArc( ...
    axesHandle, ...
    sensor, ...
    0, ...
    thetaTarget, ...
    targetArcRadius, ...
    targetAngleColor, ...
    3.0);

%% ========================================================================
%  Object labels
%  ========================================================================

text( ...
    axesHandle, ...
    sensor(1) + 0.05, ...
    sensor(2) - 0.37, ...
    "Surface sensor", ...
    "Color",sensorColor, ...
    "FontName",fontName, ...
    "FontSize",objectFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","top");

text( ...
    axesHandle, ...
    target(1)+0.12, ...
    target(2), ...
    "RSO", ...
    "Color",targetColor, ...
    "FontName",fontName, ...
    "FontSize",objectFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","left", ...
    "VerticalAlignment","middle");

text( ...
    axesHandle, ...
    body(1), ...
    body(2)-0.90, ...
    "Celestial body $b$", ...
    "Interpreter","latex", ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",objectFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "Margin",2.2, ...
    "HorizontalAlignment","center");

%% ========================================================================
%  Angular labels with external leader arrows
%  ========================================================================

% -------------------------------------------------------------------------
% theta_occ,b
% -------------------------------------------------------------------------

occultationAnchorAngle = ...
    0.58*thetaOcc;

occultationAnchor = ...
    sensor + ...
    occultationArcRadius*[ ...
    cos(occultationAnchorAngle), ...
    sin(occultationAnchorAngle)];

occultationLabelPosition = ...
    occultationAnchor + [0.86,-0.44];

text( ...
    axesHandle, ...
    occultationLabelPosition(1), ...
    occultationLabelPosition(2), ...
    "$\theta_{\mathrm{occ},b}$", ...
    "Interpreter","latex", ...
    "Color",occultationColor, ...
    "FontName",fontName, ...
    "FontSize",angleFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "Margin",1.8, ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle");

occultationArrowStart = ...
    occultationLabelPosition + ...
    [-0.20,0.12];

drawLeaderArrow( ...
    axesHandle, ...
    occultationArrowStart, ...
    occultationAnchor, ...
    occultationColor, ...
    leaderLineWidth, ...
    leaderHeadSize);

% -------------------------------------------------------------------------
% theta_min
% -------------------------------------------------------------------------

minimumAnchorAngle = ...
    0.72*thetaRequired;

minimumAnchor = ...
    sensor + ...
    minimumArcRadius*[ ...
    cos(minimumAnchorAngle), ...
    sin(minimumAnchorAngle)];

minimumLabelPosition = ...
    minimumAnchor + [0.68,0.49];

text( ...
    axesHandle, ...
    minimumLabelPosition(1), ...
    minimumLabelPosition(2), ...
    "$\theta_{\min}$", ...
    "Interpreter","latex", ...
    "Color",minimumAngleColor, ...
    "FontName",fontName, ...
    "FontSize",angleFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "Margin",1.8, ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle");

minimumArrowStart = ...
    minimumLabelPosition + ...
    [-0.20,-0.12];

drawLeaderArrow( ...
    axesHandle, ...
    minimumArrowStart, ...
    minimumAnchor, ...
    minimumAngleColor, ...
    leaderLineWidth, ...
    leaderHeadSize);

% -------------------------------------------------------------------------
% theta_b
% -------------------------------------------------------------------------

targetAnchorAngle = ...
    0.82*thetaTarget;

targetAnchor = ...
    sensor + ...
    targetArcRadius*[ ...
    cos(targetAnchorAngle), ...
    sin(targetAnchorAngle)];

targetLabelPosition = ...
    targetAnchor + [0.62,0.46];

text( ...
    axesHandle, ...
    targetLabelPosition(1), ...
    targetLabelPosition(2), ...
    "$\theta_b$", ...
    "Interpreter","latex", ...
    "Color",targetAngleColor, ...
    "FontName",fontName, ...
    "FontSize",angleFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "Margin",1.8, ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle");

targetArrowStart = ...
    targetLabelPosition + ...
    [-0.18,-0.12];

drawLeaderArrow( ...
    axesHandle, ...
    targetArrowStart, ...
    targetAnchor, ...
    targetAngleColor, ...
    leaderLineWidth, ...
    leaderHeadSize);

%% ========================================================================
%  Final formatting
%  ========================================================================

% Leave enough room for the Surface sensor and celestial-body labels while
% retaining a compact manuscript crop.
xlim(axesHandle,[-2.90 1.90]);
ylim(axesHandle,[-1.32 2.48]);

axesHandle.LooseInset = ...
    max(axesHandle.TightInset,0.005);

%% ========================================================================
%  Export
%  ========================================================================

scriptDirectory = ...
    fileparts(mfilename("fullpath"));

outputFile = fullfile( ...
    scriptDirectory, ...
    "Exclusion_Constraint_Schematic.eps");

% Export the axes rather than the full figure for tight cropping.
exportgraphics( ...
    axesHandle, ...
    outputFile, ...
    "ContentType","image", ...
    "Resolution",600, ...
    "BackgroundColor","black");

fprintf( ...
    "Saved exclusion-constraint schematic:\n  %s\n", ...
    outputFile);

%% ========================================================================
%  Local functions
%  ========================================================================

function drawAngleArc( ...
    axesHandle, ...
    origin, ...
    startAngle, ...
    endAngle, ...
    radius, ...
    lineColor, ...
    lineWidth)

angleSamples = linspace( ...
    startAngle, ...
    endAngle, ...
    120);

plot( ...
    axesHandle, ...
    origin(1) + radius*cos(angleSamples), ...
    origin(2) + radius*sin(angleSamples), ...
    "-", ...
    "Color",lineColor, ...
    "LineWidth",lineWidth);

end

function drawLeaderArrow( ...
    axesHandle, ...
    startPoint, ...
    endPoint, ...
    lineColor, ...
    lineWidth, ...
    headSize)

quiver( ...
    axesHandle, ...
    startPoint(1), ...
    startPoint(2), ...
    endPoint(1)-startPoint(1), ...
    endPoint(2)-startPoint(2), ...
    0, ...
    "Color",lineColor, ...
    "LineWidth",lineWidth, ...
    "MaxHeadSize",headSize, ...
    "AutoScale","off", ...
    "HandleVisibility","off");

end