function plotInfo = plotClpsDesignDomain(userConfig)
% PLOTCLPSDESIGNDOMAIN Southern-hemisphere design domain with CLPS context.
%
% The full primary optimization domain (-90 <= latitude <= 0 deg) is shown
% using the same polar-map styling and mission callout treatment as the
% original CLPS_LSP_Detail manuscript figure. The restricted -90 to -75 deg
% comparison region is retained as a highlighted inner disk.
%
% Output:
%   CLPS_Southern_Hemisphere_Design_Domain.eps

arguments
    userConfig (1,1) struct = struct()
end

scriptDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(scriptDirectory);
dataDirectory = fullfile(projectRoot,"data");
sourceDirectory = fullfile(projectRoot,"src");
addpath(scriptDirectory);
addpath(sourceDirectory);
rehash path;

defaults = struct();
defaults.outputDirectory = fullfile(projectRoot,"results","manuscript_artifacts");
defaults.demFile = fullfile(dataDirectory,"Full_Resolution_DEM.mat");
defaults.moonRadiusKm = 1737.4;
config = mergeStruct(defaults,userConfig);
style = publicationPlotStyle();

assert(isfile(config.demFile), ...
    sprintf("Full DEM was not found: %s",config.demFile));

[demInterpolant,~] = digitalElevationModel.loadTriaxialLunarDem( ...
    string(config.demFile),config.moonRadiusKm,24,48);

% Full southern hemisphere.
domainSouthDeg = -90;
domainNorthDeg = 0;
restrictedNorthDeg = -75;

longitudeDeg = linspace(0,360,721);
latitudeDeg = linspace(domainSouthDeg,domainNorthDeg,541);
[longitudeMeshDeg,latitudeMeshDeg] = meshgrid(longitudeDeg,latitudeDeg);

elevationKm = double(demInterpolant( ...
    deg2rad(latitudeMeshDeg),deg2rad(longitudeMeshDeg)));
finiteElevationKm = elevationKm(isfinite(elevationKm));
assert(~isempty(finiteElevationKm), ...
    "The lunar DEM produced no finite southern-hemisphere samples.");
elevationLimitsKm = [min(finiteElevationKm),max(finiteElevationKm)];

theme = struct( ...
    "backgroundColor",[1 1 1], ...
    "textColor",style.textColor, ...
    "boxColor",[1 1 1], ...
    "boxEdgeColor",[0.62 0.62 0.64], ...
    "boundaryColor",style.boundaryColor, ...
    "completedColor",style.redColor, ...
    "plannedColor",style.magentaColor, ...
    "optionalColor",style.orangeColor, ...
    "markerEdgeColor",[1 1 1]);

fontName = style.fontName;
calloutFontSize = 15;
coordinateFontSize = 15;
boundaryFontSize = 15;
legendFontSize = 15;
colorbarFontSize = 15;

% This is a full-width conference-paper figure. The source canvas is large
% enough for the original callout density without making the map itself small.
figureWidth = 11.5;
figureHeight = 7.3;

fig = figure("Name","CLPS deployment context and southern design domain", ...
    "Color",theme.backgroundColor,"Units","inches", ...
    "Position",[0.5 0.5 figureWidth figureHeight], ...
    "Renderer","opengl");
fig.InvertHardcopy = "off";

ax = axes(fig);
hold(ax,"on");
ax.Color = theme.backgroundColor;
ax.FontName = fontName;
ax.SortMethod = "childorder";

polarDistanceKm = config.moonRadiusKm .* deg2rad(90 + latitudeMeshDeg);
xKm = polarDistanceKm .* sind(longitudeMeshDeg);
yKm = polarDistanceKm .* cosd(longitudeMeshDeg);
outerRadiusKm = config.moonRadiusKm*pi/2;
restrictedRadiusKm = config.moonRadiusKm*deg2rad(15);

surf(ax,xKm,yKm,zeros(size(xKm)),elevationKm, ...
    "EdgeColor","none","FaceColor","interp");
view(ax,2);
colormap(ax,turbo(256));
clim(ax,elevationLimitsKm);

circleAngleDeg = linspace(0,360,721);

% Outer boundary of the complete southern-hemisphere design domain.
plot(ax,outerRadiusKm*sind(circleAngleDeg), ...
    outerRadiusKm*cosd(circleAngleDeg), ...
    "Color",theme.boundaryColor,"LineWidth",2.8, ...
    "HandleVisibility","off");

% Highlight only the restricted comparison domain; this is a study boundary,
% not a plotting grid line.
restrictedPatch = patch(ax, ...
    restrictedRadiusKm*sind(circleAngleDeg), ...
    restrictedRadiusKm*cosd(circleAngleDeg), ...
    theme.boundaryColor, ...
    "FaceAlpha",0.07,"EdgeColor",theme.boundaryColor, ...
    "LineWidth",2.3,"DisplayName","Restricted south-polar comparison");

% Cardinal labels around the full hemisphere.
longitudeLabelRadiusKm = outerRadiusKm + 65;
longitudeGridDeg = [0 90 180 270];
longitudeLabelText = ["0^{\circ}E","90^{\circ}E","180^{\circ}E","270^{\circ}E"];
for longitudeIndex = 1:numel(longitudeGridDeg)
    longitudeValue = longitudeGridDeg(longitudeIndex);
    xLabel = longitudeLabelRadiusKm*sind(longitudeValue);
    yLabel = longitudeLabelRadiusKm*cosd(longitudeValue);
    text(ax,xLabel,yLabel, ...
        longitudeLabelText(longitudeIndex), ...
        "Interpreter","tex","Color",theme.textColor, ...
        "FontName",fontName,"FontSize",coordinateFontSize, ...
        "FontWeight","bold","BackgroundColor",theme.boxColor, ...
        "Margin",1.2,"HorizontalAlignment","center", ...
        "VerticalAlignment","middle");
end

% Geographic reference labels without grid rings.
for latitudeValue = -45
    radiusKm = config.moonRadiusKm*deg2rad(90 + latitudeValue);
    labelLongitudeDeg = 200;
    labelText = sprintf("%d^{\\circ}S",abs(latitudeValue));
    text(ax,radiusKm*sind(labelLongitudeDeg)-20, ...
        radiusKm*cosd(labelLongitudeDeg)+18, ...
        labelText,"Tag","clpsMovableLabel","Interpreter","tex","Color",theme.textColor, ...
        "FontName",fontName,"FontSize",coordinateFontSize, ...
        "FontWeight","bold","BackgroundColor",theme.boxColor, ...
        "Margin",1.2,"HorizontalAlignment","right", ...
        "VerticalAlignment","middle");
end

plot(ax,0,0,".","Color",theme.textColor,"MarkerSize",16, ...
    "HandleVisibility","off");
text(ax,-145,-110,"South Pole","Tag","clpsMovableLabel", ...
    "Color",theme.textColor,"FontName",fontName, ...
    "FontSize",coordinateFontSize,"FontWeight","bold", ...
    "BackgroundColor",theme.boxColor,"Margin",1.2, ...
    "HorizontalAlignment","right","VerticalAlignment","top");

% Completed south-polar CLPS landings.
completedLatitudeDeg = [-80.1277;-84.7754];
completedLongitudeDeg = [1.4357;29.1264];
[completedX,completedY] = polarCoordinates( ...
    completedLatitudeDeg,completedLongitudeDeg,config.moonRadiusKm);
completedHandle = scatter(ax,completedX,completedY,95,"o", ...
    "MarkerFaceColor",theme.backgroundColor, ...
    "MarkerEdgeColor",theme.completedColor,"LineWidth",2.4, ...
    "DisplayName","Completed landing");

% Mons Mouton region.
[monsX,monsY] = rectangularPolarRegion( ...
    -86.22,-83.30,11.67,53.03,config.moonRadiusKm);
monsHandle = patch(ax,monsX,monsY,theme.plannedColor, ...
    "FaceAlpha",0.20,"EdgeColor",theme.plannedColor,"LineWidth",2.7, ...
    "DisplayName","Planned LSP anchor region");

% Schrodinger Basin overlap.
[schX,schY] = rectangularPolarRegion( ...
    -79.95,-69.52,112.33,153.44,config.moonRadiusKm);
schHandle = patch(ax,schX,schY,theme.optionalColor, ...
    "FaceAlpha",0.18,"EdgeColor",theme.optionalColor,"LineWidth",2.5, ...
    "DisplayName","Optional regional overlap");

% Representative LSP-wide planned anchor marker.
[lspAnchorX,lspAnchorY] = polarCoordinates( ...
    -78.0,315.0,config.moonRadiusKm);
plannedHandle = scatter(ax,lspAnchorX,lspAnchorY,105,"d", ...
    "MarkerFaceColor",theme.plannedColor, ...
    "MarkerEdgeColor",theme.markerEdgeColor,"LineWidth",1.0, ...
    "DisplayName","Planned LSP anchor");

% Keep the original detailed mission information, with compact white
% callout boxes immediately outside the polar disk. The map remains the
% dominant element rather than being shrunk to accommodate the annotations.
mapLimit = outerRadiusKm + 120;

axis(ax,"equal");
axis(ax,"off");
xlim(ax,[-mapLimit mapLimit]);
ylim(ax,[-mapLimit mapLimit]);

% Text determines the callout sizes; physical map geometry determines leaders.
calloutText = { ...
    {"LSP-wide planned anchors","Blue Moon MK1 / CT-3", ...
     "Blue Ghost 4 / CS-6","Nova-D / CT-4"}, ...
    {"IM-1 / TO2-IM","Completed","Near Malapert A"}, ...
    {"Mons Mouton","Completed: IM-2 / PRIME-1", ...
     "Planned: Griffin / TO20A","Planned: IM-4 / CP-22"}, ...
    {"Schrodinger Basin","SERIES-2 / CP-12 - planned", ...
     "Optional LSP anchor"}};
targets = [lspAnchorX lspAnchorY; completedX(1) completedY(1); ...
    mean(monsX) mean(monsY); mean(schX) mean(schY)];
leaderColors = [theme.plannedColor; theme.completedColor; ...
    theme.plannedColor; theme.optionalColor];
callouts = gobjects(4,1);
leaders = gobjects(4,1);
for k = 1:numel(callouts)
    callouts(k) = annotation(fig,"textbox", ...
        "String",calloutText{k},"Interpreter","none", ...
        "Color",theme.textColor,"FontName",fontName, ...
        "FontSize",calloutFontSize,"FontWeight","bold", ...
        "BackgroundColor",theme.boxColor,"EdgeColor",theme.boxEdgeColor, ...
        "Margin",4,"FitBoxToText","on", ...
        "HorizontalAlignment","left","VerticalAlignment","middle");
    leaders(k) = annotation(fig,"arrow", ...
        "Color",leaderColors(k,:),"LineWidth",2);
end

% Move the restricted-domain label up and to the right of the central cluster.
text(ax,restrictedRadiusKm+110,0.18*restrictedRadiusKm, ...
    "75^{\circ}S","Tag","clpsMovableLabel", ...
    "Interpreter","tex","Color",theme.boundaryColor, ...
    "FontName",fontName,"FontSize",boundaryFontSize, ...
    "FontWeight","bold","BackgroundColor",theme.boxColor, ...
    "Margin",1.3,"HorizontalAlignment","left","VerticalAlignment","middle");

% Put the primary-domain label higher, completely outside the map.
domainTitle = annotation(fig,"textbox", ...
    "FitBoxToText","on", ...
    "String","","Visible","off", ...
    "Interpreter","tex","Color",theme.boundaryColor, ...
    "FontName",fontName,"FontSize",boundaryFontSize, ...
    "FontWeight","bold","EdgeColor","none", ...
    "HorizontalAlignment","center","VerticalAlignment","middle");

colorbarHandle = colorbar(ax,"southoutside");
colorbarHandle.FontName = fontName;
colorbarHandle.FontSize = colorbarFontSize;
colorbarHandle.FontWeight = "bold";
colorbarHandle.Color = theme.textColor;
colorbarHandle.Label.String = "DEM elevation (km)";
colorbarHandle.Label.FontName = fontName;
colorbarHandle.Label.FontSize = colorbarFontSize;
colorbarHandle.Label.FontWeight = "bold";
colorbarHandle.Label.Color = theme.textColor;

legendHandle = legend(ax, ...
    [completedHandle plannedHandle monsHandle schHandle restrictedPatch], ...
    "Completed landing","Planned LSP anchor", ...
    "Planned LSP anchor region","Optional regional overlap", ...
    "Restricted comparison region", ...
    "Orientation","horizontal","NumColumns",3,"Box","on");

legendHandle.FontName = fontName;
legendHandle.FontSize = legendFontSize;
legendHandle.FontWeight = "bold";
legendHandle.TextColor = theme.textColor;
legendHandle.Color = theme.boxColor;
legendHandle.EdgeColor = theme.boxEdgeColor;
legendHandle.ItemTokenSize = [18 10];

layoutClpsContext(fig,ax,callouts,leaders,targets, ...
    domainTitle,colorbarHandle,legendHandle);
fig.Units = "inches";
figureWidth = fig.Position(3);
figureHeight = fig.Position(4);

outputFile = fullfile(config.outputDirectory, ...
    "CLPS_Southern_Hemisphere_Design_Domain.eps");
exportManuscriptFigure(fig,string(outputFile),figureWidth,figureHeight);

plotInfo = struct("figure",fig,"outputFile",string(outputFile));
end

function [xKm,yKm] = polarCoordinates(latitudeDeg,longitudeDeg,moonRadiusKm)
radiusKm = moonRadiusKm.*deg2rad(90+latitudeDeg);
xKm = radiusKm.*sind(longitudeDeg);
yKm = radiusKm.*cosd(longitudeDeg);
end

function [xKm,yKm] = rectangularPolarRegion( ...
    latitudeSouthDeg,latitudeNorthDeg,longitudeWestDeg,longitudeEastDeg,moonRadiusKm)
numberOfSamples = 120;
longitudeSouth = linspace(longitudeWestDeg,longitudeEastDeg,numberOfSamples);
latitudeEast = linspace(latitudeSouthDeg,latitudeNorthDeg,numberOfSamples);
longitudeNorth = linspace(longitudeEastDeg,longitudeWestDeg,numberOfSamples);
latitudeWest = linspace(latitudeNorthDeg,latitudeSouthDeg,numberOfSamples);

latitudeBoundary = [ ...
    latitudeSouthDeg*ones(1,numberOfSamples), ...
    latitudeEast, ...
    latitudeNorthDeg*ones(1,numberOfSamples), ...
    latitudeWest];

longitudeBoundary = [ ...
    longitudeSouth, ...
    longitudeEastDeg*ones(1,numberOfSamples), ...
    longitudeNorth, ...
    longitudeWestDeg*ones(1,numberOfSamples)];

[xKm,yKm] = polarCoordinates( ...
    latitudeBoundary,longitudeBoundary,moonRadiusKm);
end

function out = mergeStruct(defaults,override)
out = defaults;
fields = fieldnames(override);
for k = 1:numel(fields)
    out.(fields{k}) = override.(fields{k});
end
end