function figureInfo = plotOptimizationPilotResults(studyState)
% PLOTOPTIMIZATIONPILOTRESULTS Plot the completed optimization pilot.
%
% Repository-style figures are generated for:
%   1. Overall-best optimized sensor locations in the lunar south-polar band.
%   2. All RSO truth trajectories together with the optimized network.
%   3. Best-so-far minimization objective versus function evaluations.
%
% Styling follows the manuscript plotting scripts in this repository:
% black background, Arial typography, high-contrast annotations, minimum
% 12-pt text, 6.5-in manuscript width, and 0.25-in export padding.
%
% The RSO population figure reserves explicit space for the 3-D axes labels
% and legend, and exports the complete figure so neither can be clipped. The
% convergence plot retains the native minimization objective J, including its
% negative sign, so improvement is shown in the conventional downward
% direction.
%
% Usage:
%   plotOptimizationPilotResults(studyState)
%
% If studyState is omitted, the newest completed 10 x 1200-FE pilot is used.

arguments
    studyState (1,1) struct = struct()
end

%% ========================================================================
%  Project paths and study loading
%  ========================================================================

scriptDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(scriptDirectory);
resultsDirectory = fullfile(projectRoot,"results");

if isempty(fieldnames(studyState))
    summaryFile = findLatestPilotSummary(resultsDirectory);
    loadedStudy = load(summaryFile,"studyState");
    assert(isfield(loadedStudy,"studyState"), ...
        "Pilot summary does not contain studyState.");
    studyState = loadedStudy.studyState;
end

assert(isfield(studyState,"validation") && ...
    isfield(studyState.validation,"overallBest"), ...
    "studyState does not contain overall-best EKF validation results.");
assert(isfield(studyState,"overallBestSensorIndices"), ...
    "studyState does not contain the overall-best sensor network.");
assert(isfield(studyState,"studyDirectory"), ...
    "studyState does not identify its output directory.");

validation = studyState.validation.overallBest;

databaseFile = string(studyState.config.databaseFile);
assert(isfile(databaseFile), ...
    "Optimization database was not found: %s",databaseFile);

databaseData = load(databaseFile,"database");
assert(isfield(databaseData,"database"), ...
    "Optimization database MAT file does not contain database.");
database = databaseData.database;

%% ========================================================================
%  Figure typography and styling
%  ========================================================================

fontName = "Arial";

axisFontSize = 12;
labelFontSize = 12;
annotationFontSize = 12;
legendFontSize = 12;

backgroundColor = [0.00 0.00 0.00];
textColor = [1.00 1.00 1.00];
boxColor = [0.045 0.045 0.055];
boxEdgeColor = [0.55 0.55 0.55];

gridColor = [0.20 0.20 0.22];
candidateColor = [0.34 0.34 0.38];
boundaryColor = [0.10 0.85 1.00];
sensorColor = [1.00 0.20 0.15];
moonColor = [0.40 0.40 0.43];
meanColor = [1.00 0.82 0.05];
standardDeviationColor = [0.82 0.82 0.84];

exportWidthInches = 6.50;
exportHeightInches = 6.50;
convergenceHeightInches = 4.75;
exportPaddingInches = 0.25;

%% ========================================================================
%  Output directory
%  ========================================================================

figureDirectory = fullfile(string(studyState.studyDirectory),"figures");

if ~isfolder(figureDirectory)
    mkdir(figureDirectory);
end

sensorOutputFile = fullfile( ...
    figureDirectory,"optimized_sensor_network.eps");
rsoOutputFile = fullfile( ...
    figureDirectory,"rso_population.eps");
convergenceOutputFile = fullfile( ...
    figureDirectory,"optimization_convergence.eps");

%% ========================================================================
%  Common geometry
%  ========================================================================

moonRadiusKm = database.config.moon.radiusKm;

candidateLatitudeDeg = ...
    rad2deg(database.candidates.latitudesRad(:));
candidateLongitudeDeg = ...
    rad2deg(database.candidates.longitudesRad(:));

bestSensorIndices = studyState.overallBestSensorIndices(:);
bestSensorLatitudeDeg = candidateLatitudeDeg(bestSensorIndices);
bestSensorLongitudeDeg = candidateLongitudeDeg(bestSensorIndices);
networkSize = numel(bestSensorIndices);

%% ========================================================================
%  Figure 1: optimized sensor locations
%  ========================================================================

sensorFigure = figure( ...
    "Name","Optimized Sensor Network", ...
    "Color",backgroundColor, ...
    "Units","inches", ...
    "Position",[1 1 exportWidthInches exportHeightInches], ...
    "Renderer","painters");

sensorFigure.InvertHardcopy = "off";

sensorLayout = tiledlayout( ...
    sensorFigure,1,1, ...
    "TileSpacing","compact", ...
    "Padding","compact");

sensorAxes = nexttile(sensorLayout,1);
hold(sensorAxes,"on");
axis(sensorAxes,"equal");
axis(sensorAxes,"off");

sensorAxes.Color = backgroundColor;
sensorAxes.FontName = fontName;
sensorAxes.FontSize = axisFontSize;

candidateRadiusKm = ...
    moonRadiusKm .* deg2rad(90.0 + candidateLatitudeDeg);
candidateXKm = candidateRadiusKm .* sind(candidateLongitudeDeg);
candidateYKm = candidateRadiusKm .* cosd(candidateLongitudeDeg);

candidateHandle = scatter( ...
    sensorAxes,candidateXKm,candidateYKm,7,candidateColor,"filled", ...
    "DisplayName","Candidates");

circleAngleDeg = linspace(0,360,721);
latitudeGridDeg = [-85 -80 -75];
boundaryHandle = gobjects(1);

for latitudeIndex = 1:numel(latitudeGridDeg)
    currentLatitudeDeg = latitudeGridDeg(latitudeIndex);
    currentRadiusKm = moonRadiusKm*deg2rad(90.0 + currentLatitudeDeg);
    circleXKm = currentRadiusKm*sind(circleAngleDeg);
    circleYKm = currentRadiusKm*cosd(circleAngleDeg);

    if currentLatitudeDeg == -75
        boundaryHandle = plot( ...
            sensorAxes,circleXKm,circleYKm, ...
            "Color",boundaryColor, ...
            "LineWidth",2.4, ...
            "DisplayName","75^{\circ}S boundary");
    else
        plot( ...
            sensorAxes,circleXKm,circleYKm,"--", ...
            "Color",gridColor, ...
            "LineWidth",1.0, ...
            "HandleVisibility","off");
    end
end

outerRadiusKm = moonRadiusKm*deg2rad(15.0);
longitudeGridDeg = [0 90 180 270];

for longitudeIndex = 1:numel(longitudeGridDeg)
    currentLongitudeDeg = longitudeGridDeg(longitudeIndex);
    radialDistanceKm = [0 outerRadiusKm];

    plot( ...
        sensorAxes, ...
        radialDistanceKm*sind(currentLongitudeDeg), ...
        radialDistanceKm*cosd(currentLongitudeDeg), ...
        "--", ...
        "Color",gridColor, ...
        "LineWidth",1.0, ...
        "HandleVisibility","off");
end

longitudeLabelRadiusKm = outerRadiusKm + 34;
longitudeLabelText = [ ...
    "0^{\circ}E" ...
    "90^{\circ}E" ...
    "180^{\circ}E" ...
    "270^{\circ}E"];

for longitudeIndex = 1:numel(longitudeGridDeg)
    currentLongitudeDeg = longitudeGridDeg(longitudeIndex);

    text( ...
        sensorAxes, ...
        longitudeLabelRadiusKm*sind(currentLongitudeDeg), ...
        longitudeLabelRadiusKm*cosd(currentLongitudeDeg), ...
        longitudeLabelText(longitudeIndex), ...
        "Interpreter","tex", ...
        "Color",textColor, ...
        "FontName",fontName, ...
        "FontSize",annotationFontSize, ...
        "FontWeight","bold", ...
        "BackgroundColor",boxColor, ...
        "EdgeColor","none", ...
        "Margin",1.5, ...
        "HorizontalAlignment","center", ...
        "VerticalAlignment","middle");
end

latitudeLabelLongitudeDeg = 225;

for latitudeIndex = 1:2
    currentLatitudeDeg = latitudeGridDeg(latitudeIndex);
    currentRadiusKm = moonRadiusKm*deg2rad(90.0 + currentLatitudeDeg);

    text( ...
        sensorAxes, ...
        currentRadiusKm*sind(latitudeLabelLongitudeDeg) - 7, ...
        currentRadiusKm*cosd(latitudeLabelLongitudeDeg) + 7, ...
        sprintf("%d^{\\circ}S",abs(currentLatitudeDeg)), ...
        "Interpreter","tex", ...
        "Color",textColor, ...
        "FontName",fontName, ...
        "FontSize",annotationFontSize, ...
        "FontWeight","bold", ...
        "BackgroundColor",boxColor, ...
        "EdgeColor","none", ...
        "Margin",1.5, ...
        "HorizontalAlignment","right", ...
        "VerticalAlignment","middle");
end

scatter( ...
    sensorAxes,0,0,28,".", ...
    "MarkerEdgeColor",textColor, ...
    "HandleVisibility","off");

text( ...
    sensorAxes,-16,-16,"South Pole", ...
    "Color",textColor, ...
    "FontName",fontName, ...
    "FontSize",annotationFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "EdgeColor","none", ...
    "Margin",1.5, ...
    "HorizontalAlignment","right", ...
    "VerticalAlignment","top");

bestSensorRadiusKm = ...
    moonRadiusKm .* deg2rad(90.0 + bestSensorLatitudeDeg);
bestSensorXKm = bestSensorRadiusKm .* sind(bestSensorLongitudeDeg);
bestSensorYKm = bestSensorRadiusKm .* cosd(bestSensorLongitudeDeg);

sensorHandle = scatter( ...
    sensorAxes,bestSensorXKm,bestSensorYKm,115,"o", ...
    "MarkerFaceColor",sensorColor, ...
    "MarkerEdgeColor",textColor, ...
    "LineWidth",1.5, ...
    "DisplayName","Optimized sensors");

for sensorIndex = 1:networkSize
    sensorPosition = [bestSensorXKm(sensorIndex);bestSensorYKm(sensorIndex)];
    sensorPositionNorm = norm(sensorPosition);

    if sensorPositionNorm > 1
        labelDirection = sensorPosition/sensorPositionNorm;
    else
        labelDirection = [1;0];
    end

    labelPosition = sensorPosition + 26*labelDirection;

    text( ...
        sensorAxes,labelPosition(1),labelPosition(2), ...
        sprintf("S%d",sensorIndex), ...
        "Color",textColor, ...
        "FontName",fontName, ...
        "FontSize",annotationFontSize, ...
        "FontWeight","bold", ...
        "BackgroundColor",boxColor, ...
        "EdgeColor",boxEdgeColor, ...
        "Margin",2.0, ...
        "HorizontalAlignment","center", ...
        "VerticalAlignment","middle");
end

sensorLimitKm = outerRadiusKm + 82;
xlim(sensorAxes,[-sensorLimitKm sensorLimitKm]);
ylim(sensorAxes,[-sensorLimitKm sensorLimitKm]);

sensorLegend = legend( ...
    sensorAxes, ...
    [candidateHandle boundaryHandle sensorHandle], ...
    "Candidates", ...
    "75^{\circ}S boundary", ...
    "Optimized sensors", ...
    "Orientation","horizontal");

styleLegend(sensorLegend,boxColor,boxEdgeColor,textColor,fontName,legendFontSize);
sensorLegend.Layout.Tile = "south";

%% ========================================================================
%  Figure 2: all RSO truth trajectories and optimized sensors
%  ========================================================================

truthStateHistories = validation.truthStateHistories;
assert(ndims(truthStateHistories) == 3 && ...
    size(truthStateHistories,1) >= 3, ...
    "Validation truth-state histories have an unexpected size.");
assert(all(isfinite(truthStateHistories(1:3,:,:)),"all"), ...
    "RSO truth trajectories contain nonfinite values.");

numberOfObjects = size(truthStateHistories,3);
trajectoryColors = turbo(max(numberOfObjects,2));
trajectoryColors = trajectoryColors(1:numberOfObjects,:);

radiusHistoriesKm = squeeze( ...
    sqrt(sum(truthStateHistories(1:3,:,:).^2,1)));
maxRadiusByObjectKm = max(radiusHistoriesKm,[],1);
[farthestRadiusKm,farthestObjectIndex] = max(maxRadiusByObjectKm);

rsoFigure = figure( ...
    "Name","RSO Population", ...
    "Color",backgroundColor, ...
    "Units","inches", ...
    "Position",[1 1 exportWidthInches exportHeightInches], ...
    "Renderer","opengl");

rsoFigure.InvertHardcopy = "off";

% Use explicit axes and legend positions for this 3-D figure. This reserves
% space for tick labels, x/y/z labels, and the legend in both the interactive
% figure and exported EPS image.
rsoAxes = axes( ...
    rsoFigure, ...
    "Units","normalized", ...
    "Position",[0.14 0.18 0.80 0.76]);

hold(rsoAxes,"on");
axis(rsoAxes,"on");
axis(rsoAxes,"equal");
axis(rsoAxes,"vis3d");
box(rsoAxes,"on");
grid(rsoAxes,"on");

rsoAxes.Visible = "on";
rsoAxes.Color = backgroundColor;
rsoAxes.FontName = fontName;
rsoAxes.FontSize = axisFontSize;
rsoAxes.FontWeight = "bold";
rsoAxes.XColor = textColor;
rsoAxes.YColor = textColor;
rsoAxes.ZColor = textColor;
rsoAxes.GridColor = gridColor;
rsoAxes.MinorGridColor = gridColor;
rsoAxes.GridAlpha = 0.60;
rsoAxes.LineWidth = 1.0;
rsoAxes.TickDir = "out";

[moonX,moonY,moonZ] = sphere(64);
moonHandle = surf( ...
    rsoAxes, ...
    moonRadiusKm*moonX, ...
    moonRadiusKm*moonY, ...
    moonRadiusKm*moonZ, ...
    "FaceColor",moonColor, ...
    "EdgeColor","none", ...
    "FaceAlpha",0.96, ...
    "DisplayName","Moon");

trajectoryHandle = gobjects(1);

for objectIndex = 1:numberOfObjects
    currentPositionHistory = truthStateHistories(1:3,:,objectIndex);

    if objectIndex == 1
        trajectoryHandle = plot3( ...
            rsoAxes, ...
            currentPositionHistory(1,:), ...
            currentPositionHistory(2,:), ...
            currentPositionHistory(3,:), ...
            "Color",trajectoryColors(objectIndex,:), ...
            "LineWidth",1.35, ...
            "DisplayName",sprintf("RSO trajectories (%d)",numberOfObjects));
    else
        plot3( ...
            rsoAxes, ...
            currentPositionHistory(1,:), ...
            currentPositionHistory(2,:), ...
            currentPositionHistory(3,:), ...
            "Color",trajectoryColors(objectIndex,:), ...
            "LineWidth",1.35, ...
            "HandleVisibility","off");
    end

    scatter3( ...
        rsoAxes, ...
        currentPositionHistory(1,1), ...
        currentPositionHistory(2,1), ...
        currentPositionHistory(3,1), ...
        18,"o", ...
        "MarkerFaceColor",trajectoryColors(objectIndex,:), ...
        "MarkerEdgeColor",trajectoryColors(objectIndex,:), ...
        "HandleVisibility","off");
end

sensorDisplayRadiusKm = moonRadiusKm + 10;
sensorXKm = ...
    sensorDisplayRadiusKm*cosd(bestSensorLatitudeDeg).* ...
    cosd(bestSensorLongitudeDeg);
sensorYKm = ...
    sensorDisplayRadiusKm*cosd(bestSensorLatitudeDeg).* ...
    sind(bestSensorLongitudeDeg);
sensorZKm = ...
    sensorDisplayRadiusKm*sind(bestSensorLatitudeDeg);

rsoSensorHandle = scatter3( ...
    rsoAxes,sensorXKm,sensorYKm,sensorZKm,75,"o", ...
    "MarkerFaceColor",sensorColor, ...
    "MarkerEdgeColor",textColor, ...
    "LineWidth",1.4, ...
    "DisplayName","Optimized sensors");

xlabel(rsoAxes,"MCI x [km]", ...
    "Color",textColor,"FontName",fontName, ...
    "FontSize",labelFontSize,"FontWeight","bold");
ylabel(rsoAxes,"MCI y [km]", ...
    "Color",textColor,"FontName",fontName, ...
    "FontSize",labelFontSize,"FontWeight","bold");
zlabel(rsoAxes,"MCI z [km]", ...
    "Color",textColor,"FontName",fontName, ...
    "FontSize",labelFontSize,"FontWeight","bold");

view(rsoAxes,35,22);
camproj(rsoAxes,"orthographic");

rsoLegend = legend( ...
    rsoAxes, ...
    [moonHandle trajectoryHandle rsoSensorHandle], ...
    "Moon", ...
    sprintf("RSO trajectories (%d)",numberOfObjects), ...
    "Optimized sensors", ...
    "Orientation","horizontal", ...
    "Units","normalized");

styleLegend(rsoLegend,boxColor,boxEdgeColor,textColor,fontName,legendFontSize);
rsoLegend.Position = [0.19 0.025 0.62 0.065];

%% ========================================================================
%  Figure 3: native minimization objective versus function evaluations
%  ========================================================================

referenceFe = studyState.runStates{1}.history.fe(:);
numberOfRuns = studyState.numberOfRuns;
numberOfHistoryPoints = numel(referenceFe);
objectiveHistory = NaN(numberOfHistoryPoints,numberOfRuns);

for runIndex = 1:numberOfRuns
    currentRun = studyState.runStates{runIndex};

    assert(isequal(currentRun.history.fe(:),referenceFe), ...
        "Run %d does not share the common FE grid.",runIndex);

    % Keep the native minimization objective. For the current coverage and
    % information formulations, better solutions are more negative.
    objectiveHistory(:,runIndex) = currentRun.history.bestJ(:);
end

meanObjective = mean(objectiveHistory,2);
stdObjective = std(objectiveHistory,0,2);
runColors = turbo(max(numberOfRuns,2));
runColors = runColors(1:numberOfRuns,:);

convergenceFigure = figure( ...
    "Name","Optimization Convergence", ...
    "Color",backgroundColor, ...
    "Units","inches", ...
    "Position",[1 1 exportWidthInches convergenceHeightInches], ...
    "Renderer","painters");

convergenceFigure.InvertHardcopy = "off";

convergenceLayout = tiledlayout( ...
    convergenceFigure,1,1, ...
    "TileSpacing","compact", ...
    "Padding","compact");

convergenceAxes = nexttile(convergenceLayout,1);
hold(convergenceAxes,"on");
box(convergenceAxes,"on");
grid(convergenceAxes,"on");

convergenceAxes.Color = backgroundColor;
convergenceAxes.FontName = fontName;
convergenceAxes.FontSize = axisFontSize;
convergenceAxes.XColor = textColor;
convergenceAxes.YColor = textColor;
convergenceAxes.GridColor = gridColor;
convergenceAxes.GridAlpha = 0.70;
convergenceAxes.LineWidth = 1.0;

for runIndex = 1:numberOfRuns
    plot( ...
        convergenceAxes,referenceFe,objectiveHistory(:,runIndex), ...
        "Color",runColors(runIndex,:), ...
        "LineWidth",1.0, ...
        "HandleVisibility","off");
end

meanHandle = plot( ...
    convergenceAxes,referenceFe,meanObjective, ...
    "Color",meanColor, ...
    "LineWidth",2.6, ...
    "DisplayName","Mean best-so-far J");

stdHandle = plot( ...
    convergenceAxes,referenceFe,meanObjective + stdObjective, ...
    "--", ...
    "Color",standardDeviationColor, ...
    "LineWidth",1.5, ...
    "DisplayName","Mean \pm 1 std");

plot( ...
    convergenceAxes,referenceFe,meanObjective - stdObjective, ...
    "--", ...
    "Color",standardDeviationColor, ...
    "LineWidth",1.5, ...
    "HandleVisibility","off");

xlabel(convergenceAxes,"Function Evaluations", ...
    "Color",textColor,"FontName",fontName, ...
    "FontSize",labelFontSize,"FontWeight","bold");

ylabel(convergenceAxes,"Best Objective J", ...
    "Color",textColor,"FontName",fontName, ...
    "FontSize",labelFontSize,"FontWeight","bold");

xlim(convergenceAxes,[referenceFe(1) referenceFe(end)]);

convergenceLegend = legend( ...
    convergenceAxes,[meanHandle stdHandle], ...
    "Mean best-so-far J", ...
    "Mean \pm 1 std", ...
    "Orientation","horizontal");

styleLegend( ...
    convergenceLegend,boxColor,boxEdgeColor,textColor,fontName,legendFontSize);
convergenceLegend.Layout.Tile = "south";

%% ========================================================================
%  Export complete figure/layout containers so annotations are retained
%  ========================================================================

drawnow;

exportgraphics( ...
    sensorLayout, ...
    sensorOutputFile, ...
    "ContentType","vector", ...
    "BackgroundColor",backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",exportWidthInches, ...
    "Height",exportHeightInches, ...
    "Padding",exportPaddingInches, ...
    "PreserveAspectRatio","on");

exportgraphics( ...
    rsoFigure, ...
    rsoOutputFile, ...
    "ContentType","image", ...
    "Resolution",600, ...
    "BackgroundColor",backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",exportWidthInches, ...
    "Height",exportHeightInches, ...
    "Padding",exportPaddingInches, ...
    "PreserveAspectRatio","on");

exportgraphics( ...
    convergenceLayout, ...
    convergenceOutputFile, ...
    "ContentType","vector", ...
    "BackgroundColor",backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",exportWidthInches, ...
    "Height",convergenceHeightInches, ...
    "Padding",exportPaddingInches, ...
    "PreserveAspectRatio","on");

%% ========================================================================
%  Return handles, paths, and RSO scale diagnostic
%  ========================================================================

figureInfo = struct();
figureInfo.sensorNetwork = sensorFigure;
figureInfo.rsoPopulation = rsoFigure;
figureInfo.convergence = convergenceFigure;
figureInfo.sensorOutputFile = string(sensorOutputFile);
figureInfo.rsoOutputFile = string(rsoOutputFile);
figureInfo.convergenceOutputFile = string(convergenceOutputFile);
figureInfo.farthestRsoIndex = farthestObjectIndex;
figureInfo.farthestRsoMaximumRadiusKm = farthestRadiusKm;

fprintf("\nOptimization-pilot figures exported.\n");
fprintf("  Sensors:        %s\n",sensorOutputFile);
fprintf("  RSO population: %s\n",rsoOutputFile);
fprintf("  Convergence:    %s\n",convergenceOutputFile);
fprintf("  Farthest RSO:   %d (max radius %.3f km)\n", ...
    farthestObjectIndex,farthestRadiusKm);

if isfield(database,"rso") && isfield(database.rso,"catalog") && ...
        height(database.rso.catalog) >= farthestObjectIndex

    catalogRow = database.rso.catalog(farthestObjectIndex,:);
    fprintf("  Farthest object: %s\n",string(catalogRow.Name));

    if ismember("PeriapsisAltitudeKm",catalogRow.Properties.VariableNames)
        fprintf("  Periapsis alt.:  %.3f km\n",catalogRow.PeriapsisAltitudeKm);
    end
    if ismember("ApoapsisAltitudeKm",catalogRow.Properties.VariableNames)
        fprintf("  Apoapsis alt.:   %.3f km\n",catalogRow.ApoapsisAltitudeKm);
    end
    if ismember("Eccentricity",catalogRow.Properties.VariableNames)
        fprintf("  Eccentricity:    %.6f\n",catalogRow.Eccentricity);
    end
end

end

%% ========================================================================
%  Local helpers
%  ========================================================================

function styleLegend( ...
    legendHandle,boxColor,boxEdgeColor,textColor,fontName,fontSize)

legendHandle.Color = boxColor;
legendHandle.EdgeColor = boxEdgeColor;
legendHandle.TextColor = textColor;
legendHandle.FontName = fontName;
legendHandle.FontSize = fontSize;
legendHandle.Box = "on";

end

function summaryFile = findLatestPilotSummary(resultsDirectory)

runRoot = fullfile(resultsDirectory,"optimization_runs");
assert(isfolder(runRoot), ...
    "Optimization run directory was not found: %s",runRoot);

summaryFiles = dir(fullfile(runRoot,"**","study_summary.mat"));
assert(~isempty(summaryFiles), ...
    "No optimization study summaries were found under %s.",runRoot);

[~,sortOrder] = sort([summaryFiles.datenum],"descend");
summaryFiles = summaryFiles(sortOrder);

summaryFile = "";

for fileIndex = 1:numel(summaryFiles)
    candidateFile = fullfile( ...
        summaryFiles(fileIndex).folder,summaryFiles(fileIndex).name);

    candidateData = load(candidateFile,"studyState");

    if ~isfield(candidateData,"studyState")
        continue
    end

    candidateStudy = candidateData.studyState;

    isPilot = ...
        isfield(candidateStudy,"numberOfRuns") && ...
        candidateStudy.numberOfRuns == 10 && ...
        isfield(candidateStudy,"config") && ...
        isfield(candidateStudy.config,"functionEvaluationBudget") && ...
        candidateStudy.config.functionEvaluationBudget == 1200 && ...
        isfield(candidateStudy,"validation") && ...
        isfield(candidateStudy.validation,"overallBest");

    if isPilot
        summaryFile = string(candidateFile);
        break
    end
end

assert(strlength(summaryFile) > 0, ...
    "No completed 10-run, 1200-FE pilot summary was found.");

end