%% plotClpsLsp
% One contextual lunar plot showing:
%   1. The Moon for geographic scale.
%   2. The -90 to -75 degree south-polar target band using the DEM.
%   3. Completed CLPS landing sites.
%   4. Announced future CLPS target regions.

clear;
close all;
clc;

%% Figure typography

fontName = "Arial";
calloutFontSize = 12;
boundaryFontSize = 12;
legendFontSize = 13;
colorbarFontSize = 12;

%% Load the DEM

scriptDirectory = fileparts(mfilename("fullpath"));
repositoryRoot = fileparts(scriptDirectory);

demFile = fullfile( ...
    repositoryRoot, ...
    "data", ...
    "new_lunar_interpolant_model.mat");

assert(isfile(demFile), ...
    "DEM file was not found: %s",demFile);

loadedData = load(demFile);
variableNames = fieldnames(loadedData);
demInterpolant = [];

for variableIndex = 1:numel(variableNames)

    currentVariable = loadedData.(variableNames{variableIndex});

    if isa(currentVariable,"griddedInterpolant")
        demInterpolant = currentVariable;
        break;
    end
end

assert(~isempty(demInterpolant), ...
    "No griddedInterpolant was found in %s.",demFile);

%% Evaluate the south-polar DEM

moonRadiusKm = 1737.4;

longitudeDeg = linspace(0.0,360.0,721);
latitudeDeg = linspace(-90.0,-75.0,301);

[longitudeMeshDeg,latitudeMeshDeg] = meshgrid( ...
    longitudeDeg,latitudeDeg);

% Repository convention:
% elevation = F(latitude,longitude)
elevationKm = double(demInterpolant( ...
    latitudeMeshDeg,longitudeMeshDeg));

% Lift the DEM slightly above the reference sphere so negative terrain
% remains visible. Colors still represent the true DEM elevation.
demDisplayOffsetKm = 5.0;

demRadiusKm = ...
    moonRadiusKm + demDisplayOffsetKm + elevationKm;

demXKm = demRadiusKm .* ...
    cosd(latitudeMeshDeg) .* cosd(longitudeMeshDeg);

demYKm = demRadiusKm .* ...
    cosd(latitudeMeshDeg) .* sind(longitudeMeshDeg);

demZKm = demRadiusKm .* sind(latitudeMeshDeg);

%% Completed landing sites and planned target regions

% Completed sites with confirmed coordinates.
completedLatitudeDeg = [-80.13; -84.79];
completedLongitudeDeg = [1.44; 29.20];

% Planned missions do not yet have final coordinates.
%
% The Mons Mouton marker uses the IM-2 coordinate as a regional reference.
% The broad South Pole marker is placed at the pole, where longitude is
% arbitrary.
plannedLatitudeDeg = [-84.79; -90.00];
plannedLongitudeDeg = [29.20; 0.00];

completedElevationKm = double(demInterpolant( ...
    completedLatitudeDeg,completedLongitudeDeg));

plannedElevationKm = double(demInterpolant( ...
    plannedLatitudeDeg,plannedLongitudeDeg));

markerLiftKm = 18.0;

completedRadiusKm = ...
    moonRadiusKm + ...
    demDisplayOffsetKm + ...
    completedElevationKm + ...
    markerLiftKm;

plannedRadiusKm = ...
    moonRadiusKm + ...
    demDisplayOffsetKm + ...
    plannedElevationKm + ...
    markerLiftKm;

completedXKm = completedRadiusKm .* ...
    cosd(completedLatitudeDeg) .* ...
    cosd(completedLongitudeDeg);

completedYKm = completedRadiusKm .* ...
    cosd(completedLatitudeDeg) .* ...
    sind(completedLongitudeDeg);

completedZKm = completedRadiusKm .* ...
    sind(completedLatitudeDeg);

plannedXKm = plannedRadiusKm .* ...
    cosd(plannedLatitudeDeg) .* ...
    cosd(plannedLongitudeDeg);

plannedYKm = plannedRadiusKm .* ...
    cosd(plannedLatitudeDeg) .* ...
    sind(plannedLongitudeDeg);

plannedZKm = plannedRadiusKm .* ...
    sind(plannedLatitudeDeg);

%% Create the contextual lunar figure

figureHandle = figure( ...
    "Color","black");

axesHandle = axes(figureHandle);
hold(axesHandle,"on");

%% Draw the Moon

[moonX,moonY,moonZ] = sphere(240);

moonColor = repmat( ...
    reshape([0.43 0.43 0.45],1,1,3), ...
    size(moonX,1), ...
    size(moonX,2), ...
    1);

surf(axesHandle, ...
    moonRadiusKm .* moonX, ...
    moonRadiusKm .* moonY, ...
    moonRadiusKm .* moonZ, ...
    moonColor, ...
    "EdgeColor","none", ...
    "FaceColor","texturemap");

%% Overlay the DEM target band

surf(axesHandle, ...
    demXKm, ...
    demYKm, ...
    demZKm, ...
    elevationKm, ...
    "EdgeColor","none", ...
    "FaceColor","interp");

colormap(axesHandle,turbo(256));

finiteElevationKm = elevationKm(isfinite(elevationKm));

clim(axesHandle,[ ...
    min(finiteElevationKm) ...
    max(finiteElevationKm)]);

colorbarHandle = colorbar(axesHandle);

colorbarHandle.Color = "white";
colorbarHandle.FontName = fontName;
colorbarHandle.FontSize = colorbarFontSize;

colorbarHandle.Label.String = "DEM elevation (km)";
colorbarHandle.Label.Color = "white";
colorbarHandle.Label.FontName = fontName;
colorbarHandle.Label.FontSize = colorbarFontSize + 1;
colorbarHandle.Label.FontWeight = "bold";

%% Draw the -75 degree target-band boundary

boundaryLongitudeDeg = linspace(0.0,360.0,721);
boundaryLatitudeDeg = ...
    -75.0 .* ones(size(boundaryLongitudeDeg));

boundaryElevationKm = double(demInterpolant( ...
    boundaryLatitudeDeg,boundaryLongitudeDeg));

boundaryRadiusKm = ...
    moonRadiusKm + ...
    demDisplayOffsetKm + ...
    boundaryElevationKm + ...
    2.0;

boundaryXKm = boundaryRadiusKm .* ...
    cosd(boundaryLatitudeDeg) .* ...
    cosd(boundaryLongitudeDeg);

boundaryYKm = boundaryRadiusKm .* ...
    cosd(boundaryLatitudeDeg) .* ...
    sind(boundaryLongitudeDeg);

boundaryZKm = boundaryRadiusKm .* ...
    sind(boundaryLatitudeDeg);

plot3(axesHandle, ...
    boundaryXKm, ...
    boundaryYKm, ...
    boundaryZKm, ...
    "Color",[0.10 0.85 1.00], ...
    "LineWidth",2.2);

%% Plot completed and planned locations

completedHandle = scatter3(axesHandle, ...
    completedXKm, ...
    completedYKm, ...
    completedZKm, ...
    150, ...
    "o", ...
    "MarkerFaceColor","none", ...
    "MarkerEdgeColor",[1.00 0.20 0.12], ...
    "LineWidth",3.0, ...
    "DisplayName","Completed landing");

plannedHandle = scatter3(axesHandle, ...
    plannedXKm, ...
    plannedYKm, ...
    plannedZKm, ...
    175, ...
    "x", ...
    "MarkerEdgeColor",[1.00 0.15 0.90], ...
    "LineWidth",3.5, ...
    "DisplayName","Planned target region");

%% Add callouts outside the DEM cap

calloutZKm = -moonRadiusKm - 45.0;

%% IM-1 callout

% Positive y moves this callout lower in the south-pole view.
im1CalloutXKm = 820.0;
im1CalloutYKm = 470.0;

plot3(axesHandle, ...
    [completedXKm(1) im1CalloutXKm], ...
    [completedYKm(1) im1CalloutYKm], ...
    [completedZKm(1) calloutZKm], ...
    "Color",[1.00 0.35 0.30], ...
    "LineWidth",1.3);

text(axesHandle, ...
    im1CalloutXKm, ...
    im1CalloutYKm, ...
    calloutZKm, ...
    "IM-1", ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",calloutFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",[0.06 0.06 0.07], ...
    "Margin",2.0);

%% Mons Mouton callout

% Negative y moves this callout higher in the south-pole view.
monsCalloutXKm = 790.0;
monsCalloutYKm = -430.0;

plot3(axesHandle, ...
    [completedXKm(2) monsCalloutXKm], ...
    [completedYKm(2) monsCalloutYKm], ...
    [completedZKm(2) calloutZKm], ...
    "Color",[0.95 0.55 0.85], ...
    "LineWidth",1.3);

text(axesHandle, ...
    monsCalloutXKm, ...
    monsCalloutYKm, ...
    calloutZKm, ...
    { ...
    "Mons Mouton", ...
    "IM-2 — completed", ...
    "Griffin + IM-4 — planned" ...
    }, ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",calloutFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",[0.06 0.06 0.07], ...
    "Margin",2.0);

%% Broad lunar South Pole callout

lspCalloutXKm = -850.0;
lspCalloutYKm = -390.0;

plot3(axesHandle, ...
    [plannedXKm(2) lspCalloutXKm], ...
    [plannedYKm(2) lspCalloutYKm], ...
    [plannedZKm(2) calloutZKm], ...
    "Color",[1.00 0.25 0.90], ...
    "LineWidth",1.3);

text(axesHandle, ...
    lspCalloutXKm, ...
    lspCalloutYKm, ...
    calloutZKm, ...
    { ...
    "Planned LSP region", ...
    "Blue Moon MK1", ...
    "Blue Ghost 4", ...
    "Nova-D" ...
    }, ...
    "Color","white", ...
    "FontName",fontName, ...
    "FontSize",calloutFontSize, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","right", ...
    "BackgroundColor",[0.06 0.06 0.07], ...
    "Margin",2.0);

%% Label the target-band boundary

% Use the zero-degree-longitude point as the callout anchor.
boundaryAnchorIndex = 1;

boundaryLabelXKm = 610.0;
boundaryLabelYKm = 40.0;

plot3(axesHandle, ...
    [boundaryXKm(boundaryAnchorIndex) boundaryLabelXKm], ...
    [boundaryYKm(boundaryAnchorIndex) boundaryLabelYKm], ...
    [boundaryZKm(boundaryAnchorIndex) calloutZKm], ...
    "Color",[0.25 0.90 1.00], ...
    "LineWidth",1.3);

text(axesHandle, ...
    boundaryLabelXKm, ...
    boundaryLabelYKm, ...
    calloutZKm, ...
    "-75 deg boundary", ...
    "Color",[0.25 0.90 1.00], ...
    "FontName",fontName, ...
    "FontSize",boundaryFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",[0.06 0.06 0.07], ...
    "Margin",2.0);

%% Format the south-pole view

axis(axesHandle,"equal");
axis(axesHandle,"off");

axesHandle.Color = "black";
axesHandle.FontName = fontName;

% Looking directly toward the lunar south pole makes the DEM band circular.
view(axesHandle,0,-90);
camproj(axesHandle,"orthographic");

camlight(axesHandle,"headlight");
lighting(axesHandle,"gouraud");
material(axesHandle,"dull");

legendHandle = legend(axesHandle, ...
    [completedHandle plannedHandle], ...
    "Location","northwest");

legendHandle.Color = [0.06 0.06 0.07];
legendHandle.EdgeColor = [0.65 0.65 0.65];
legendHandle.TextColor = "white";
legendHandle.FontName = fontName;
legendHandle.FontSize = legendFontSize;

fprintf("plotClpsLsp completed.\n");