%% plotClpsLsp
% Generate both manuscript-white and presentation-dark CLPS south-polar maps.
%
% Outputs:
%   CLPS_LSP_Detail.eps       - white manuscript version
%   CLPS_LSP_Detail_dark.eps  - dark presentation/map version
%
% Both versions retain the detailed callouts from the original figure:
%   - completed IM-1 and IM-2 landings
%   - Mons Mouton planned missions
%   - LSP-wide planned anchors
%   - Schrodinger Basin optional overlap
%   - latitude/longitude references and the 75 deg S optimization boundary

clear;
clc;

scriptDirectory = fileparts(mfilename("fullpath"));
repositoryRoot = fileparts(scriptDirectory);
sourceDirectory = fullfile(repositoryRoot,"src");

addpath(scriptDirectory);
addpath(sourceDirectory);
rehash path;

style = publicationPlotStyle();

%% Load final production DEM

moonRadiusKm = 1737.4;
demFile = fullfile(repositoryRoot,"data","Final_Lunar_DEM.mat");

assert(isfile(demFile), ...
    "Final lunar DEM was not found: %s",demFile);
assert(~isempty(which("digitalElevationModel.loadTriaxialLunarDem")), ...
    "digitalElevationModel.loadTriaxialLunarDem was not found after adding src to path.");

[demInterpolant,~] = ...
    digitalElevationModel.loadTriaxialLunarDem( ...
        string(demFile),moonRadiusKm,24,48);

domainSouthDeg = -90;
domainNorthDeg = -75;
longitudeDeg = linspace(0,360,721);
latitudeDeg = linspace(domainSouthDeg,domainNorthDeg,301);
[longitudeMeshDeg,latitudeMeshDeg] = meshgrid(longitudeDeg,latitudeDeg);

elevationKm = double(demInterpolant( ...
    deg2rad(latitudeMeshDeg),deg2rad(longitudeMeshDeg)));
finiteElevationKm = elevationKm(isfinite(elevationKm));
assert(~isempty(finiteElevationKm), ...
    "The final lunar DEM produced no finite samples over the LSP domain.");
elevationLimitsKm = [min(finiteElevationKm),max(finiteElevationKm)];

%% CLPS / deployment geometry

completedLatitudeDeg = [-80.1277;-84.7754];
completedLongitudeDeg = [1.4357;29.1264];

monsLatitudeSouthDeg = -86.22;
monsLatitudeNorthDeg = -83.30;
monsLongitudeWestDeg = 11.67;
monsLongitudeEastDeg = 53.03;

schrodingerLatitudeSouthDeg = -79.95;
schrodingerLatitudeNorthDeg = domainNorthDeg;
schrodingerLongitudeWestDeg = 112.33;
schrodingerLongitudeEastDeg = 153.44;

% Representative location used only to point to the LSP-wide planned-anchor
% group in the schematic. The callout text identifies the missions.
lspAnchorLatitudeDeg = domainNorthDeg;
lspAnchorLongitudeDeg = 315;

%% Build both figure variants

whiteTheme = struct( ...
    "name","CLPS south-polar map - manuscript", ...
    "backgroundColor",[1 1 1], ...
    "textColor",style.textColor, ...
    "boxColor",[1 1 1], ...
    "boxEdgeColor",[0.62 0.62 0.64], ...
    "gridColor",[0.20 0.20 0.22], ...
    "boundaryColor",style.boundaryColor, ...
    "completedColor",style.redColor, ...
    "plannedColor",style.magentaColor, ...
    "optionalColor",style.orangeColor, ...
    "markerEdgeColor",[1 1 1]);

darkTheme = struct( ...
    "name","CLPS south-polar map - dark", ...
    "backgroundColor",[0.015 0.018 0.025], ...
    "textColor",[0.97 0.97 0.98], ...
    "boxColor",[0.035 0.040 0.050], ...
    "boxEdgeColor",[0.48 0.50 0.56], ...
    "gridColor",[0.08 0.08 0.09], ...
    "boundaryColor",[0.05 0.86 0.98], ...
    "completedColor",[1.00 0.12 0.12], ...
    "plannedColor",[1.00 0.00 0.82], ...
    "optionalColor",[1.00 0.52 0.05], ...
    "markerEdgeColor",[0.98 0.98 0.99]);

whiteFigure = createClpsFigure( ...
    whiteTheme,style,moonRadiusKm, ...
    longitudeMeshDeg,latitudeMeshDeg,elevationKm,elevationLimitsKm, ...
    completedLatitudeDeg,completedLongitudeDeg, ...
    monsLatitudeSouthDeg,monsLatitudeNorthDeg, ...
    monsLongitudeWestDeg,monsLongitudeEastDeg, ...
    schrodingerLatitudeSouthDeg,schrodingerLatitudeNorthDeg, ...
    schrodingerLongitudeWestDeg,schrodingerLongitudeEastDeg, ...
    lspAnchorLatitudeDeg,lspAnchorLongitudeDeg,domainNorthDeg);

darkFigure = createClpsFigure( ...
    darkTheme,style,moonRadiusKm, ...
    longitudeMeshDeg,latitudeMeshDeg,elevationKm,elevationLimitsKm, ...
    completedLatitudeDeg,completedLongitudeDeg, ...
    monsLatitudeSouthDeg,monsLatitudeNorthDeg, ...
    monsLongitudeWestDeg,monsLongitudeEastDeg, ...
    schrodingerLatitudeSouthDeg,schrodingerLatitudeNorthDeg, ...
    schrodingerLongitudeWestDeg,schrodingerLongitudeEastDeg, ...
    lspAnchorLatitudeDeg,lspAnchorLongitudeDeg,domainNorthDeg);

whiteOutputFile = fullfile(scriptDirectory,"CLPS_LSP_Detail.eps");
darkOutputFile = fullfile(scriptDirectory,"CLPS_LSP_Detail_dark.eps");

exportgraphics(whiteFigure,whiteOutputFile, ...
    "ContentType","image","Resolution",600, ...
    "BackgroundColor",whiteTheme.backgroundColor,"Colorspace","rgb");
exportgraphics(darkFigure,darkOutputFile, ...
    "ContentType","image","Resolution",600, ...
    "BackgroundColor",darkTheme.backgroundColor,"Colorspace","rgb");

fprintf("Saved CLPS south-polar figures:\n");
fprintf("  White: %s\n",whiteOutputFile);
fprintf("  Dark:  %s\n",darkOutputFile);

%% Local helpers

function fig = createClpsFigure( ...
    theme,style,moonRadiusKm, ...
    longitudeMeshDeg,latitudeMeshDeg,elevationKm,elevationLimitsKm, ...
    completedLatitudeDeg,completedLongitudeDeg, ...
    monsLatitudeSouthDeg,monsLatitudeNorthDeg, ...
    monsLongitudeWestDeg,monsLongitudeEastDeg, ...
    schrodingerLatitudeSouthDeg,schrodingerLatitudeNorthDeg, ...
    schrodingerLongitudeWestDeg,schrodingerLongitudeEastDeg, ...
    lspAnchorLatitudeDeg,lspAnchorLongitudeDeg,domainNorthDeg)

fontName = style.fontName;
siteFontSize = 12;
calloutFontSize = 12;
gridFontSize = 12;
boundaryFontSize = 12;
legendFontSize = 12;
colorbarFontSize = 12;

% Use a slightly wider canvas so the map, callouts, colorbar, and one-row
% legend can be centered without any clipping at the figure boundaries.
fig = figure("Name",theme.name, ...
    "Color",theme.backgroundColor,"Units","inches", ...
    "Position",[1 1 12.0 7.4],"Renderer","opengl");
fig.InvertHardcopy = "off";

mapAxesPosition = [0.055 0.16 0.755 0.78];
ax = axes(fig,"Position",mapAxesPosition);
hold(ax,"on");
ax.Color = theme.backgroundColor;
ax.FontName = fontName;
ax.SortMethod = "childorder";

polarDistanceKm = moonRadiusKm .* deg2rad(90 + latitudeMeshDeg);
xKm = polarDistanceKm .* sind(longitudeMeshDeg);
yKm = polarDistanceKm .* cosd(longitudeMeshDeg);
outerRadiusKm = moonRadiusKm*deg2rad(15);

surf(ax,xKm,yKm,zeros(size(xKm)),elevationKm, ...
    "EdgeColor","none","FaceColor","interp");
view(ax,2);
colormap(ax,turbo(256));
clim(ax,elevationLimitsKm);

%% Coordinate references

circleAngleDeg = linspace(0,360,721);
latitudeGridDeg = [-85 -80 -75];
for latitudeValue = latitudeGridDeg
    radiusKm = moonRadiusKm*deg2rad(90 + latitudeValue);
    xGrid = radiusKm*sind(circleAngleDeg);
    yGrid = radiusKm*cosd(circleAngleDeg);
    if latitudeValue == domainNorthDeg
        plot(ax,xGrid,yGrid,"Color",theme.boundaryColor,"LineWidth",2.4);
    else
        plot(ax,xGrid,yGrid,"--","Color",theme.gridColor,"LineWidth",1.1);
    end
end

longitudeGridDeg = [0 90 180 270];
for longitudeValue = longitudeGridDeg
    radialDistanceKm = [0 outerRadiusKm];
    plot(ax,radialDistanceKm*sind(longitudeValue), ...
        radialDistanceKm*cosd(longitudeValue),"--", ...
        "Color",theme.gridColor,"LineWidth",1.1);
end

longitudeLabelRadiusKm = outerRadiusKm + 24;
longitudeLabelText = ["0^{\circ}E","90^{\circ}E","180^{\circ}E","270^{\circ}E"];
for longitudeIndex = 1:numel(longitudeGridDeg)
    longitudeValue = longitudeGridDeg(longitudeIndex);
    text(ax,longitudeLabelRadiusKm*sind(longitudeValue), ...
        longitudeLabelRadiusKm*cosd(longitudeValue), ...
        longitudeLabelText(longitudeIndex), ...
        "Interpreter","tex","Color",theme.textColor, ...
        "FontName",fontName,"FontSize",gridFontSize,"FontWeight","bold", ...
        "BackgroundColor",theme.boxColor,"Margin",1.2, ...
        "HorizontalAlignment","center","VerticalAlignment","middle");
end

latitudeLabelLongitudeDeg = 225;
for latitudeValue = latitudeGridDeg(1:2)
    radiusKm = moonRadiusKm*deg2rad(90 + latitudeValue);
    text(ax,radiusKm*sind(latitudeLabelLongitudeDeg)-8, ...
        radiusKm*cosd(latitudeLabelLongitudeDeg)+7, ...
        sprintf("%d^{\\circ}S",abs(latitudeValue)), ...
        "Interpreter","tex","Color",theme.textColor, ...
        "FontName",fontName,"FontSize",gridFontSize,"FontWeight","bold", ...
        "BackgroundColor",theme.boxColor,"Margin",1.2, ...
        "HorizontalAlignment","right","VerticalAlignment","middle");
end

plot(ax,0,0,".","Color",theme.textColor,"MarkerSize",14);
text(ax,-18,-17,"South Pole", ...
    "Color",theme.textColor,"FontName",fontName, ...
    "FontSize",gridFontSize,"FontWeight","bold", ...
    "BackgroundColor",theme.boxColor,"Margin",1.3, ...
    "HorizontalAlignment","right","VerticalAlignment","top");

boundaryLabelY = -outerRadiusKm - 34;
text(ax,0,boundaryLabelY,"75^{\circ}S optimization boundary", ...
    "Interpreter","tex","Color",theme.boundaryColor, ...
    "FontName",fontName,"FontSize",boundaryFontSize,"FontWeight","bold", ...
    "BackgroundColor",theme.boxColor,"Margin",1.3, ...
    "HorizontalAlignment","center","VerticalAlignment","top");

%% Regions and mission markers

[monsX,monsY] = rectangularPolarRegion( ...
    monsLatitudeSouthDeg,monsLatitudeNorthDeg, ...
    monsLongitudeWestDeg,monsLongitudeEastDeg,moonRadiusKm);
monsHandle = patch(ax,monsX,monsY,theme.plannedColor, ...
    "FaceAlpha",0.17,"EdgeColor",theme.plannedColor,"LineWidth",2.6, ...
    "DisplayName","Planned LSP anchor region");

[schX,schY] = rectangularPolarRegion( ...
    schrodingerLatitudeSouthDeg,schrodingerLatitudeNorthDeg, ...
    schrodingerLongitudeWestDeg,schrodingerLongitudeEastDeg,moonRadiusKm);
schHandle = patch(ax,schX,schY,theme.optionalColor, ...
    "FaceAlpha",0.16,"EdgeColor",theme.optionalColor,"LineWidth",2.4, ...
    "DisplayName","Optional regional overlap");

[completedX,completedY] = polarCoordinates( ...
    completedLatitudeDeg,completedLongitudeDeg,moonRadiusKm);
completedHandle = scatter(ax,completedX,completedY,86,"o", ...
    "MarkerFaceColor",theme.backgroundColor, ...
    "MarkerEdgeColor",theme.completedColor,"LineWidth",2.2, ...
    "DisplayName","Completed landing");

[lspAnchorX,lspAnchorY] = polarCoordinates( ...
    lspAnchorLatitudeDeg,lspAnchorLongitudeDeg,moonRadiusKm);
plannedHandle = scatter(ax,lspAnchorX,lspAnchorY,92,"d", ...
    "MarkerFaceColor",theme.plannedColor, ...
    "MarkerEdgeColor",theme.markerEdgeColor,"LineWidth",1.0, ...
    "DisplayName","Planned LSP anchor");

text(ax,completedX(2)+16,completedY(2)-18,"IM-2", ...
    "Color",theme.textColor,"FontName",fontName,"FontSize",siteFontSize, ...
    "FontWeight","bold","BackgroundColor",theme.boxColor,"Margin",1.3, ...
    "HorizontalAlignment","left","VerticalAlignment","top");

%% Detailed callouts

% IM-1 / TO2-IM
im1TextPosition = [-900,210];
im1ArrowStart = [-540,210];
drawDataArrow(ax,im1ArrowStart,[completedX(1),completedY(1)], ...
    theme.completedColor,2.0);
text(ax,im1TextPosition(1),im1TextPosition(2), ...
    {"IM-1 / TO2-IM","Completed - Near Malapert A"}, ...
    "Color",theme.textColor,"FontName",fontName,"FontSize",calloutFontSize, ...
    "FontWeight","bold","BackgroundColor",theme.boxColor, ...
    "EdgeColor",theme.boxEdgeColor,"Margin",3.0, ...
    "HorizontalAlignment","left","VerticalAlignment","middle");

% LSP-wide planned anchors
lspTextPosition = [-900,485];
lspArrowStart = [-540,430];
drawDataArrow(ax,lspArrowStart,[lspAnchorX,lspAnchorY], ...
    theme.plannedColor,2.0);
text(ax,lspTextPosition(1),lspTextPosition(2), ...
    {"LSP-wide planned anchors", ...
     "Blue Moon MK1 / CT-3", ...
     "Blue Ghost 4 / CS-6", ...
     "Nova-D / CT-4"}, ...
    "Color",theme.textColor,"FontName",fontName,"FontSize",calloutFontSize, ...
    "FontWeight","bold","BackgroundColor",theme.boxColor, ...
    "EdgeColor",theme.boxEdgeColor,"Margin",3.0, ...
    "HorizontalAlignment","left","VerticalAlignment","middle");

% Mons Mouton
monsAnchor = [mean(monsX),mean(monsY)];
monsTextPosition = [545,475];
monsArrowStart = [535,390];
drawDataArrow(ax,monsArrowStart,monsAnchor,theme.plannedColor,2.0);
text(ax,monsTextPosition(1),monsTextPosition(2), ...
    {"Mons Mouton", ...
     "Completed: IM-2 / PRIME-1", ...
     "Planned: Griffin / TO20A", ...
     "Planned: IM-4 / CP-22"}, ...
    "Color",theme.textColor,"FontName",fontName,"FontSize",calloutFontSize, ...
    "FontWeight","bold","BackgroundColor",theme.boxColor, ...
    "EdgeColor",theme.boxEdgeColor,"Margin",3.0, ...
    "HorizontalAlignment","left","VerticalAlignment","middle");

% Schrodinger Basin
schAnchor = [mean(schX),mean(schY)];
schTextPosition = [545,-300];
schArrowStart = [530,-245];
drawDataArrow(ax,schArrowStart,schAnchor,theme.optionalColor,2.0);
text(ax,schTextPosition(1),schTextPosition(2), ...
    {"Schrodinger Basin", ...
     "SERIES-2 / CP-12 - planned", ...
     "Optional LSP anchor"}, ...
    "Color",theme.textColor,"FontName",fontName,"FontSize",calloutFontSize, ...
    "FontWeight","bold","BackgroundColor",theme.boxColor, ...
    "EdgeColor",theme.boxEdgeColor,"Margin",3.0, ...
    "HorizontalAlignment","left","VerticalAlignment","middle");

%% Final formatting

axis(ax,"equal");
axis(ax,"off");
xlim(ax,[-1000 1000]);
ylim(ax,[-650 650]);

% Explicit placement prevents the colorbar from squeezing the axes and keeps
% it clear of the right-side mission callouts in both theme variants.
colorbarHandle = colorbar(ax,"eastoutside");
colorbarHandle.Units = "normalized";
colorbarHandle.Position = [0.865 0.18 0.020 0.68];
colorbarHandle.FontName = fontName;
colorbarHandle.FontSize = colorbarFontSize;
colorbarHandle.FontWeight = "bold";
colorbarHandle.Color = theme.textColor;
colorbarHandle.Label.String = "DEM elevation (km)";
colorbarHandle.Label.FontName = fontName;
colorbarHandle.Label.FontSize = colorbarFontSize;
colorbarHandle.Label.FontWeight = "bold";
colorbarHandle.Label.Color = theme.textColor;

% Restore the desired map framing after MATLAB allocates colorbar space.
ax.Position = mapAxesPosition;

% Center the complete four-item legend beneath the map/callout composition.
legendHandle = legend(ax, ...
    [completedHandle plannedHandle monsHandle schHandle], ...
    "Completed landing","Planned LSP anchor", ...
    "Planned LSP anchor region","Optional regional overlap", ...
    "Orientation","horizontal","NumColumns",4);
legendHandle.Units = "normalized";
legendHandle.Position = [0.075 0.025 0.85 0.070];
legendHandle.FontName = fontName;
legendHandle.FontSize = legendFontSize;
legendHandle.FontWeight = "bold";
legendHandle.TextColor = theme.textColor;
legendHandle.Color = theme.boxColor;
legendHandle.EdgeColor = theme.boxEdgeColor;
legendHandle.ItemTokenSize = [18 10];

end

function drawDataArrow(ax,startPoint,endPoint,color,lineWidth)
quiver(ax,startPoint(1),startPoint(2), ...
    endPoint(1)-startPoint(1),endPoint(2)-startPoint(2),0, ...
    "Color",color,"LineWidth",lineWidth,"MaxHeadSize",0.70, ...
    "AutoScale","off","HandleVisibility","off");
end

function [xKm,yKm] = polarCoordinates(latitudeDeg,longitudeDeg,moonRadiusKm)
radiusKm = moonRadiusKm.*deg2rad(90+latitudeDeg);
xKm = radiusKm.*sind(longitudeDeg);
yKm = radiusKm.*cosd(longitudeDeg);
end

function [xKm,yKm] = rectangularPolarRegion( ...
    latitudeSouthDeg,latitudeNorthDeg,longitudeWestDeg,longitudeEastDeg,moonRadiusKm)
numberOfSamples = 120;
longitudeSouth = linspace(longitudeWestDeg,longitudeEastDeg,numberOfSamples);
latitudeEast = linspace(latitudeSouthDeg,latitudeNorthDeg,numberOfSamples);
longitudeNorth = linspace(longitudeEastDeg,longitudeWestDeg,numberOfSamples);
latitudeWest = linspace(latitudeNorthDeg,latitudeSouthDeg,numberOfSamples);
latitudeBoundary = [ ...
    latitudeSouthDeg*ones(1,numberOfSamples), ...
    latitudeEast, ...
    latitudeNorthDeg*ones(1,numberOfSamples), ...
    latitudeWest];
longitudeBoundary = [ ...
    longitudeSouth, ...
    longitudeEastDeg*ones(1,numberOfSamples), ...
    longitudeNorth, ...
    longitudeWestDeg*ones(1,numberOfSamples)];
[xKm,yKm] = polarCoordinates(latitudeBoundary,longitudeBoundary,moonRadiusKm);
end
