function plotInfo = plotClpsDesignDomain(userConfig)
% PLOTCLPSDESIGNDOMAIN Southern-hemisphere design domain with CLPS context.
%
% The full primary optimization domain (-90 <= latitude <= 0 deg) is shown
% using the same polar-map styling and mission callout treatment as the
% original CLPS_LSP_Detail manuscript figure. The restricted -90 to -75 deg
% comparison region is retained as a highlighted inner disk.
%
% Output:
%   CLPS_Southern_Hemisphere_Design_Domain.eps

arguments
    userConfig (1,1) struct = struct()
end

scriptDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(scriptDirectory);
dataDirectory = fullfile(projectRoot,"data");
sourceDirectory = fullfile(projectRoot,"src");
addpath(scriptDirectory);
addpath(sourceDirectory);
rehash path;

defaults = struct();
defaults.outputDirectory = fullfile(projectRoot,"results","manuscript_artifacts");
defaults.demFile = fullfile(dataDirectory,"Full_Resolution_DEM.mat");
defaults.moonRadiusKm = 1737.4;
config = mergeStruct(defaults,userConfig);
style = publicationPlotStyle();

assert(isfile(config.demFile), ...
    sprintf("Full DEM was not found: %s",config.demFile));

[demInterpolant,~] = digitalElevationModel.loadTriaxialLunarDem( ...
    string(config.demFile),config.moonRadiusKm,24,48);

% Full southern hemisphere.
domainSouthDeg = -90;
domainNorthDeg = 0;
restrictedNorthDeg = -75;

longitudeDeg = linspace(0,360,721);
latitudeDeg = linspace(domainSouthDeg,domainNorthDeg,541);
[longitudeMeshDeg,latitudeMeshDeg] = meshgrid(longitudeDeg,latitudeDeg);

elevationKm = double(demInterpolant( ...
    deg2rad(latitudeMeshDeg),deg2rad(longitudeMeshDeg)));
finiteElevationKm = elevationKm(isfinite(elevationKm));
assert(~isempty(finiteElevationKm), ...
    "The lunar DEM produced no finite southern-hemisphere samples.");
elevationLimitsKm = [min(finiteElevationKm),max(finiteElevationKm)];

theme = struct( ...
    "backgroundColor",[1 1 1], ...
    "textColor",style.textColor, ...
    "boxColor",[1 1 1], ...
    "boxEdgeColor",[0.62 0.62 0.64], ...
    "boundaryColor",style.boundaryColor, ...
    "completedColor",style.redColor, ...
    "plannedColor",style.magentaColor, ...
    "optionalColor",style.orangeColor, ...
    "markerEdgeColor",[1 1 1]);

fontName = style.fontName;
siteFontSize = 16;
calloutFontSize = 15;
coordinateFontSize = 15;
boundaryFontSize = 15;
legendFontSize = 15;
colorbarFontSize = 15;

% This is a full-width conference-paper figure. The source canvas is large
% enough for the original callout density without making the map itself small.
figureWidth = 11.5;
figureHeight = 7.3;

fig = figure("Name","CLPS deployment context and southern design domain", ...
    "Color",theme.backgroundColor,"Units","inches", ...
    "Position",[0.5 0.5 figureWidth figureHeight], ...
    "Renderer","opengl");
fig.InvertHardcopy = "off";

mapAxesPosition = [0.055 0.13 0.76 0.79];
ax = axes(fig,"Position",mapAxesPosition);
hold(ax,"on");
ax.Color = theme.backgroundColor;
ax.FontName = fontName;
ax.SortMethod = "childorder";

polarDistanceKm = config.moonRadiusKm .* deg2rad(90 + latitudeMeshDeg);
xKm = polarDistanceKm .* sind(longitudeMeshDeg);
yKm = polarDistanceKm .* cosd(longitudeMeshDeg);
outerRadiusKm = config.moonRadiusKm*pi/2;
restrictedRadiusKm = config.moonRadiusKm*deg2rad(15);

surf(ax,xKm,yKm,zeros(size(xKm)),elevationKm, ...
    "EdgeColor","none","FaceColor","interp");
view(ax,2);
colormap(ax,turbo(256));
clim(ax,elevationLimitsKm);

circleAngleDeg = linspace(0,360,721);

% Outer boundary of the complete southern-hemisphere design domain.
plot(ax,outerRadiusKm*sind(circleAngleDeg), ...
    outerRadiusKm*cosd(circleAngleDeg), ...
    "Color",theme.boundaryColor,"LineWidth",2.8, ...
    "HandleVisibility","off");

% Highlight only the restricted comparison domain; this is a study boundary,
% not a plotting grid line.
restrictedPatch = patch(ax, ...
    restrictedRadiusKm*sind(circleAngleDeg), ...
    restrictedRadiusKm*cosd(circleAngleDeg), ...
    theme.boundaryColor, ...
    "FaceAlpha",0.07,"EdgeColor",theme.boundaryColor, ...
    "LineWidth",2.3,"DisplayName","Restricted south-polar comparison");

% Cardinal labels around the full hemisphere.
longitudeLabelRadiusKm = outerRadiusKm + 65;
longitudeGridDeg = [0 90 180 270];
longitudeLabelText = ["0^{\circ}E","90^{\circ}E","180^{\circ}E","270^{\circ}E"];
for longitudeIndex = 1:numel(longitudeGridDeg)
    longitudeValue = longitudeGridDeg(longitudeIndex);
    xLabel = longitudeLabelRadiusKm*sind(longitudeValue);
    yLabel = longitudeLabelRadiusKm*cosd(longitudeValue);
    if longitudeValue == 0
        xLabel = xLabel + 115;
        yLabel = yLabel - 45;
    end
    text(ax,xLabel,yLabel, ...
        longitudeLabelText(longitudeIndex), ...
        "Interpreter","tex","Color",theme.textColor, ...
        "FontName",fontName,"FontSize",coordinateFontSize, ...
        "FontWeight","bold","BackgroundColor",theme.boxColor, ...
        "Margin",1.2,"HorizontalAlignment","center", ...
        "VerticalAlignment","middle");
end

% Geographic reference labels without grid rings.
for latitudeValue = -45
    radiusKm = config.moonRadiusKm*deg2rad(90 + latitudeValue);
    labelLongitudeDeg = 225;
    labelText = sprintf("%d^{\\circ}S",abs(latitudeValue));
    text(ax,radiusKm*sind(labelLongitudeDeg)-20, ...
        radiusKm*cosd(labelLongitudeDeg)+18, ...
        labelText,"Interpreter","tex","Color",theme.textColor, ...
        "FontName",fontName,"FontSize",coordinateFontSize, ...
        "FontWeight","bold","BackgroundColor",theme.boxColor, ...
        "Margin",1.2,"HorizontalAlignment","right", ...
        "VerticalAlignment","middle");
end

plot(ax,0,0,".","Color",theme.textColor,"MarkerSize",16, ...
    "HandleVisibility","off");
text(ax,-105,-75,"South Pole", ...
    "Color",theme.textColor,"FontName",fontName, ...
    "FontSize",coordinateFontSize,"FontWeight","bold", ...
    "BackgroundColor",theme.boxColor,"Margin",1.2, ...
    "HorizontalAlignment","right","VerticalAlignment","top");

% Completed south-polar CLPS landings.
completedLatitudeDeg = [-80.1277;-84.7754];
completedLongitudeDeg = [1.4357;29.1264];
[completedX,completedY] = polarCoordinates( ...
    completedLatitudeDeg,completedLongitudeDeg,config.moonRadiusKm);
completedHandle = scatter(ax,completedX,completedY,95,"o", ...
    "MarkerFaceColor",theme.backgroundColor, ...
    "MarkerEdgeColor",theme.completedColor,"LineWidth",2.4, ...
    "DisplayName","Completed landing");

% Mons Mouton region.
[monsX,monsY] = rectangularPolarRegion( ...
    -86.22,-83.30,11.67,53.03,config.moonRadiusKm);
monsHandle = patch(ax,monsX,monsY,theme.plannedColor, ...
    "FaceAlpha",0.20,"EdgeColor",theme.plannedColor,"LineWidth",2.7, ...
    "DisplayName","Planned LSP anchor region");

% Schrodinger Basin overlap.
[schX,schY] = rectangularPolarRegion( ...
    -79.95,-69.52,112.33,153.44,config.moonRadiusKm);
schHandle = patch(ax,schX,schY,theme.optionalColor, ...
    "FaceAlpha",0.18,"EdgeColor",theme.optionalColor,"LineWidth",2.5, ...
    "DisplayName","Optional regional overlap");

% Representative LSP-wide planned anchor marker.
[lspAnchorX,lspAnchorY] = polarCoordinates( ...
    -78.0,315.0,config.moonRadiusKm);
plannedHandle = scatter(ax,lspAnchorX,lspAnchorY,105,"d", ...
    "MarkerFaceColor",theme.plannedColor, ...
    "MarkerEdgeColor",theme.markerEdgeColor,"LineWidth",1.0, ...
    "DisplayName","Planned LSP anchor");

% Keep the original detailed mission information, but place every
% white callout box outside the polar disk so the terrain and sensor geometry
% remain unobstructed. Straight leaders connect each box to its feature.
mapLimit = outerRadiusKm + 120;
leftBoxX = -1.36*outerRadiusKm;
rightBoxX = 1.04*outerRadiusKm;

lspTextPosition = [leftBoxX, 0.88*outerRadiusKm];
drawDataArrow(ax,[-1.01*outerRadiusKm,0.73*outerRadiusKm], ...
    [lspAnchorX,lspAnchorY],theme.plannedColor,2.0);
text(ax,lspTextPosition(1),lspTextPosition(2), ...
    {"LSP-wide planned anchors", ...
     "Blue Moon MK1 / CT-3", ...
     "Blue Ghost 4 / CS-6", ...
     "Nova-D / CT-4"}, ...
    "Color",theme.textColor,"FontName",fontName, ...
    "FontSize",calloutFontSize,"FontWeight","bold", ...
    "BackgroundColor",theme.boxColor,"EdgeColor",theme.boxEdgeColor, ...
    "Margin",3.0,"HorizontalAlignment","left","VerticalAlignment","middle");

im1TextPosition = [leftBoxX, 0.42*outerRadiusKm];
drawDataArrow(ax,[-1.01*outerRadiusKm,0.38*outerRadiusKm], ...
    [completedX(1),completedY(1)],theme.completedColor,2.0);
text(ax,im1TextPosition(1),im1TextPosition(2), ...
    {"IM-1 / TO2-IM","Completed - Near Malapert A"}, ...
    "Color",theme.textColor,"FontName",fontName, ...
    "FontSize",calloutFontSize,"FontWeight","bold", ...
    "BackgroundColor",theme.boxColor,"EdgeColor",theme.boxEdgeColor, ...
    "Margin",3.0,"HorizontalAlignment","left","VerticalAlignment","middle");

monsAnchor = [mean(monsX),mean(monsY)];
monsTextPosition = [rightBoxX, 0.48*outerRadiusKm];
drawDataArrow(ax,[1.01*outerRadiusKm,0.40*outerRadiusKm], ...
    monsAnchor,theme.plannedColor,2.0);
text(ax,monsTextPosition(1),monsTextPosition(2), ...
    {"Mons Mouton", ...
     "Completed: IM-2 / PRIME-1", ...
     "Planned: Griffin / TO20A", ...
     "Planned: IM-4 / CP-22"}, ...
    "Color",theme.textColor,"FontName",fontName, ...
    "FontSize",calloutFontSize,"FontWeight","bold", ...
    "BackgroundColor",theme.boxColor,"EdgeColor",theme.boxEdgeColor, ...
    "Margin",3.0,"HorizontalAlignment","left","VerticalAlignment","middle");

schAnchor = [mean(schX),mean(schY)];
schTextPosition = [rightBoxX,-0.58*outerRadiusKm];
drawDataArrow(ax,[1.01*outerRadiusKm,-0.50*outerRadiusKm], ...
    schAnchor,theme.optionalColor,2.0);
text(ax,schTextPosition(1),schTextPosition(2), ...
    {"Schrodinger Basin", ...
     "SERIES-2 / CP-12 - planned", ...
     "Optional LSP anchor"}, ...
    "Color",theme.textColor,"FontName",fontName, ...
    "FontSize",calloutFontSize,"FontWeight","bold", ...
    "BackgroundColor",theme.boxColor,"EdgeColor",theme.boxEdgeColor, ...
    "Margin",3.0,"HorizontalAlignment","left","VerticalAlignment","middle");

% Move the restricted-domain label up and right so it clears the South Pole
% annotation and the 45-deg latitude reference.
text(ax,0.32*outerRadiusKm,-restrictedRadiusKm-45, ...
    "75^{\circ}S restricted comparison boundary", ...
    "Interpreter","tex","Color",theme.boundaryColor, ...
    "FontName",fontName,"FontSize",boundaryFontSize, ...
    "FontWeight","bold","BackgroundColor",theme.boxColor, ...
    "Margin",1.3,"HorizontalAlignment","center","VerticalAlignment","top");

% Make the full design domain explicit.
text(ax,0,outerRadiusKm+155, ...
    "Primary optimization domain: 90^{\circ}S--0^{\circ}", ...
    "Interpreter","tex","Color",theme.boundaryColor, ...
    "FontName",fontName,"FontSize",boundaryFontSize, ...
    "FontWeight","bold","BackgroundColor",theme.boxColor, ...
    "Margin",1.3,"HorizontalAlignment","center","VerticalAlignment","bottom");

axis(ax,"equal");
axis(ax,"off");
xlim(ax,[-1.55*mapLimit 1.55*mapLimit]);
ylim(ax,[-1.08*mapLimit 1.08*mapLimit]);

colorbarHandle = colorbar(ax,"eastoutside");
colorbarHandle.Units = "normalized";
colorbarHandle.Position = [0.855 0.19 0.020 0.61];
colorbarHandle.FontName = fontName;
colorbarHandle.FontSize = colorbarFontSize;
colorbarHandle.FontWeight = "bold";
colorbarHandle.Color = theme.textColor;
colorbarHandle.Label.String = "DEM elevation (km)";
colorbarHandle.Label.FontName = fontName;
colorbarHandle.Label.FontSize = colorbarFontSize;
colorbarHandle.Label.FontWeight = "bold";
colorbarHandle.Label.Color = theme.textColor;
ax.Position = mapAxesPosition;

legendHandle = legend(ax, ...
    [completedHandle plannedHandle monsHandle schHandle restrictedPatch], ...
    "Completed landing","Planned LSP anchor", ...
    "Planned LSP anchor region","Optional regional overlap", ...
    "Restricted comparison region", ...
    "Orientation","horizontal","NumColumns",3,"Box","on");
legendHandle.Units = "normalized";
legendHandle.Position = [0.10 0.018 0.78 0.082];
legendHandle.FontName = fontName;
legendHandle.FontSize = legendFontSize;
legendHandle.FontWeight = "bold";
legendHandle.TextColor = theme.textColor;
legendHandle.Color = theme.boxColor;
legendHandle.EdgeColor = theme.boxEdgeColor;
legendHandle.ItemTokenSize = [18 10];

outputFile = fullfile(config.outputDirectory, ...
    "CLPS_Southern_Hemisphere_Design_Domain.eps");
exportManuscriptFigure(fig,string(outputFile),figureWidth,figureHeight);

plotInfo = struct("figure",fig,"outputFile",string(outputFile));
end

function drawDataArrow(ax,startPoint,endPoint,color,lineWidth)
quiver(ax,startPoint(1),startPoint(2), ...
    endPoint(1)-startPoint(1),endPoint(2)-startPoint(2),0, ...
    "Color",color,"LineWidth",lineWidth,"MaxHeadSize",0.70, ...
    "AutoScale","off","HandleVisibility","off");
end

function [xKm,yKm] = polarCoordinates(latitudeDeg,longitudeDeg,moonRadiusKm)
radiusKm = moonRadiusKm.*deg2rad(90+latitudeDeg);
xKm = radiusKm.*sind(longitudeDeg);
yKm = radiusKm.*cosd(longitudeDeg);
end

function [xKm,yKm] = rectangularPolarRegion( ...
    latitudeSouthDeg,latitudeNorthDeg,longitudeWestDeg,longitudeEastDeg,moonRadiusKm)
numberOfSamples = 120;
longitudeSouth = linspace(longitudeWestDeg,longitudeEastDeg,numberOfSamples);
latitudeEast = linspace(latitudeSouthDeg,latitudeNorthDeg,numberOfSamples);
longitudeNorth = linspace(longitudeEastDeg,longitudeWestDeg,numberOfSamples);
latitudeWest = linspace(latitudeNorthDeg,latitudeSouthDeg,numberOfSamples);

latitudeBoundary = [ ...
    latitudeSouthDeg*ones(1,numberOfSamples), ...
    latitudeEast, ...
    latitudeNorthDeg*ones(1,numberOfSamples), ...
    latitudeWest];

longitudeBoundary = [ ...
    longitudeSouth, ...
    longitudeEastDeg*ones(1,numberOfSamples), ...
    longitudeNorth, ...
    longitudeWestDeg*ones(1,numberOfSamples)];

[xKm,yKm] = polarCoordinates( ...
    latitudeBoundary,longitudeBoundary,moonRadiusKm);
end

function out = mergeStruct(defaults,override)
out = defaults;
fields = fieldnames(override);
for k = 1:numel(fields)
    out.(fields{k}) = override.(fields{k});
end
end