function figureInfo = plotOptimizationPilotResults(studyState)
% PLOTOPTIMIZATIONPILOTRESULTS Plot the completed optimization pilot.
%
% The figures follow the styling used by the other manuscript plotting
% scripts in this repository: black background, Arial typography, high-
% contrast annotations, minimum 12-pt text, 6.5-in manuscript width, and
% 0.25-in export padding.
%
% Figures:
%   1. South-polar map of the overall-best optimized sensor network.
%   2. Three-dimensional visualization of all RSO truth trajectories.
%   3. Best-so-far convergence for all independent optimization runs.
%
% The figures are exported to a figures subdirectory inside the completed
% optimization-study directory. The generated EPS files are ignored by Git.
%
% Usage:
%   plotOptimizationPilotResults(studyState)
%
% If studyState is omitted, the newest completed 10 x 1200-FE pilot is used.

arguments
    studyState (1,1) struct = struct()
end

%% ========================================================================
%  Project paths and study loading
%  ========================================================================

scriptDirectory = fileparts(mfilename("fullpath"));
projectRoot = fileparts(scriptDirectory);
resultsDirectory = fullfile(projectRoot,"results");

if isempty(fieldnames(studyState))
    summaryFile = findLatestPilotSummary(resultsDirectory);
    loadedStudy = load(summaryFile,"studyState");
    assert(isfield(loadedStudy,"studyState"), ...
        "Pilot summary does not contain studyState.");
    studyState = loadedStudy.studyState;
end

assert(isfield(studyState,"validation") && ...
    isfield(studyState.validation,"overallBest"), ...
    "studyState does not contain overall-best EKF validation results.");
assert(isfield(studyState,"overallBestSensorIndices"), ...
    "studyState does not contain the overall-best sensor network.");
assert(isfield(studyState,"studyDirectory"), ...
    "studyState does not identify its output directory.");

validation = studyState.validation.overallBest;

databaseFile = string(studyState.config.databaseFile);
assert(isfile(databaseFile), ...
    "Optimization database was not found: %s",databaseFile);

databaseData = load(databaseFile,"database");
assert(isfield(databaseData,"database"), ...
    "Optimization database MAT file does not contain database.");
database = databaseData.database;

%% ========================================================================
%  Figure typography and styling
%  ========================================================================

fontName = "Arial";

axisFontSize = 12;
labelFontSize = 12;
annotationFontSize = 12;
legendFontSize = 12;

backgroundColor = [0.00 0.00 0.00];
textColor = [1.00 1.00 1.00];
boxColor = [0.045 0.045 0.055];
boxEdgeColor = [0.55 0.55 0.55];

gridColor = [0.20 0.20 0.22];
candidateColor = [0.34 0.34 0.38];
boundaryColor = [0.10 0.85 1.00];
sensorColor = [1.00 0.20 0.15];
moonColor = [0.40 0.40 0.43];
moonEdgeColor = [0.68 0.68 0.71];
meanColor = [1.00 0.82 0.05];
standardDeviationColor = [0.82 0.82 0.84];

exportWidthInches = 6.50;
exportHeightInches = 6.50;
convergenceHeightInches = 4.75;
exportPaddingInches = 0.25;

%% ========================================================================
%  Output directory
%  ========================================================================

figureDirectory = fullfile(string(studyState.studyDirectory),"figures");

if ~isfolder(figureDirectory)
    mkdir(figureDirectory);
end

sensorOutputFile = fullfile( ...
    figureDirectory,"optimized_sensor_network.eps");
rsoOutputFile = fullfile( ...
    figureDirectory,"rso_population.eps");
convergenceOutputFile = fullfile( ...
    figureDirectory,"optimization_convergence.eps");

%% ========================================================================
%  Common geometry
%  ========================================================================

moonRadiusKm = database.config.moon.radiusKm;

candidateLatitudeDeg = ...
    rad2deg(database.candidates.latitudesRad(:));
candidateLongitudeDeg = ...
    rad2deg(database.candidates.longitudesRad(:));

bestSensorIndices = studyState.overallBestSensorIndices(:);
bestSensorLatitudeDeg = candidateLatitudeDeg(bestSensorIndices);
bestSensorLongitudeDeg = candidateLongitudeDeg(bestSensorIndices);
networkSize = numel(bestSensorIndices);

%% ========================================================================
%  Figure 1: optimized sensor locations in south-polar coordinates
%  ========================================================================

sensorFigure = figure( ...
    "Name","Optimized Sensor Network", ...
    "Color",backgroundColor, ...
    "Units","inches", ...
    "Position",[1 1 exportWidthInches exportHeightInches], ...
    "Renderer","painters");

sensorFigure.InvertHardcopy = "off";

sensorAxes = axes( ...
    sensorFigure, ...
    "Position",[0.055 0.055 0.89 0.89]);

hold(sensorAxes,"on");
axis(sensorAxes,"equal");
axis(sensorAxes,"off");

sensorAxes.Color = backgroundColor;
sensorAxes.FontName = fontName;
sensorAxes.FontSize = axisFontSize;

candidateRadiusKm = ...
    moonRadiusKm .* deg2rad(90.0 + candidateLatitudeDeg);
candidateXKm = candidateRadiusKm .* sind(candidateLongitudeDeg);
candidateYKm = candidateRadiusKm .* cosd(candidateLongitudeDeg);

candidateHandle = scatter( ...
    sensorAxes, ...
    candidateXKm, ...
    candidateYKm, ...
    7, ...
    candidateColor, ...
    "filled", ...
    "DisplayName","Candidate sites");

circleAngleDeg = linspace(0,360,721);
latitudeGridDeg = [-85 -80 -75];

for latitudeIndex = 1:numel(latitudeGridDeg)
    currentLatitudeDeg = latitudeGridDeg(latitudeIndex);
    currentRadiusKm = ...
        moonRadiusKm*deg2rad(90.0 + currentLatitudeDeg);

    circleXKm = currentRadiusKm*sind(circleAngleDeg);
    circleYKm = currentRadiusKm*cosd(circleAngleDeg);

    if currentLatitudeDeg == -75
        boundaryHandle = plot( ...
            sensorAxes,circleXKm,circleYKm, ...
            "Color",boundaryColor, ...
            "LineWidth",2.4, ...
            "DisplayName","75^{\circ}S boundary");
    else
        plot( ...
            sensorAxes,circleXKm,circleYKm,"--", ...
            "Color",gridColor, ...
            "LineWidth",1.0, ...
            "HandleVisibility","off");
    end
end

outerRadiusKm = moonRadiusKm*deg2rad(15.0);
longitudeGridDeg = [0 90 180 270];

for longitudeIndex = 1:numel(longitudeGridDeg)
    currentLongitudeDeg = longitudeGridDeg(longitudeIndex);
    radialDistanceKm = [0 outerRadiusKm];

    plot( ...
        sensorAxes, ...
        radialDistanceKm*sind(currentLongitudeDeg), ...
        radialDistanceKm*cosd(currentLongitudeDeg), ...
        "--", ...
        "Color",gridColor, ...
        "LineWidth",1.0, ...
        "HandleVisibility","off");
end

longitudeLabelRadiusKm = outerRadiusKm + 34;
longitudeLabelText = [ ...
    "0^{\circ}E" ...
    "90^{\circ}E" ...
    "180^{\circ}E" ...
    "270^{\circ}E"];

for longitudeIndex = 1:numel(longitudeGridDeg)
    currentLongitudeDeg = longitudeGridDeg(longitudeIndex);

    text( ...
        sensorAxes, ...
        longitudeLabelRadiusKm*sind(currentLongitudeDeg), ...
        longitudeLabelRadiusKm*cosd(currentLongitudeDeg), ...
        longitudeLabelText(longitudeIndex), ...
        "Interpreter","tex", ...
        "Color",textColor, ...
        "FontName",fontName, ...
        "FontSize",annotationFontSize, ...
        "FontWeight","bold", ...
        "BackgroundColor",boxColor, ...
        "EdgeColor","none", ...
        "Margin",1.5, ...
        "HorizontalAlignment","center", ...
        "VerticalAlignment","middle");
end

latitudeLabelLongitudeDeg = 225;

for latitudeIndex = 1:2
    currentLatitudeDeg = latitudeGridDeg(latitudeIndex);
    currentRadiusKm = ...
        moonRadiusKm*deg2rad(90.0 + currentLatitudeDeg);

    text( ...
        sensorAxes, ...
        currentRadiusKm*sind(latitudeLabelLongitudeDeg) - 7, ...
        currentRadiusKm*cosd(latitudeLabelLongitudeDeg) + 7, ...
        sprintf("%d^{\\circ}S",abs(currentLatitudeDeg)), ...
        "Interpreter","tex", ...
        "Color",textColor, ...
        "FontName",fontName, ...
        "FontSize",annotationFontSize, ...
        "FontWeight","bold", ...
        "BackgroundColor",boxColor, ...
        "EdgeColor","none", ...
        "Margin",1.5, ...
        "HorizontalAlignment","right", ...
        "VerticalAlignment","middle");
end

scatter( ...
    sensorAxes,0,0,28,".", ...
    "MarkerEdgeColor",textColor, ...
    "HandleVisibility","off");

text( ...
    sensorAxes,-16,-16,"South Pole", ...
    "Color",textColor, ...
    "FontName",fontName, ...
    "FontSize",annotationFontSize, ...
    "FontWeight","bold", ...
    "BackgroundColor",boxColor, ...
    "EdgeColor","none", ...
    "Margin",1.5, ...
    "HorizontalAlignment","right", ...
    "VerticalAlignment","top");

bestSensorRadiusKm = ...
    moonRadiusKm .* deg2rad(90.0 + bestSensorLatitudeDeg);
bestSensorXKm = bestSensorRadiusKm .* sind(bestSensorLongitudeDeg);
bestSensorYKm = bestSensorRadiusKm .* cosd(bestSensorLongitudeDeg);

sensorHandle = scatter( ...
    sensorAxes, ...
    bestSensorXKm, ...
    bestSensorYKm, ...
    115, ...
    "o", ...
    "MarkerFaceColor",sensorColor, ...
    "MarkerEdgeColor",textColor, ...
    "LineWidth",1.5, ...
    "DisplayName","Optimized sensors");

for sensorIndex = 1:networkSize
    sensorPosition = [bestSensorXKm(sensorIndex);bestSensorYKm(sensorIndex)];
    sensorPositionNorm = norm(sensorPosition);

    if sensorPositionNorm > 1
        labelDirection = sensorPosition/sensorPositionNorm;
    else
        labelDirection = [1;0];
    end

    labelPosition = sensorPosition + 26*labelDirection;

    text( ...
        sensorAxes, ...
        labelPosition(1), ...
        labelPosition(2), ...
        sprintf("S%d",sensorIndex), ...
        "Color",textColor, ...
        "FontName",fontName, ...
        "FontSize",annotationFontSize, ...
        "FontWeight","bold", ...
        "BackgroundColor",boxColor, ...
        "EdgeColor",boxEdgeColor, ...
        "Margin",2.0, ...
        "HorizontalAlignment","center", ...
        "VerticalAlignment","middle");
end

sensorLegend = legend( ...
    sensorAxes, ...
    [candidateHandle boundaryHandle sensorHandle], ...
    "Candidate sites", ...
    "75^{\circ}S optimization boundary", ...
    "Overall-best sensors", ...
    "Location","southoutside", ...
    "Orientation","horizontal");

sensorLegend.Color = boxColor;
sensorLegend.EdgeColor = boxEdgeColor;
sensorLegend.TextColor = textColor;
sensorLegend.FontName = fontName;
sensorLegend.FontSize = legendFontSize;

sensorLimitKm = outerRadiusKm + 78;
xlim(sensorAxes,[-sensorLimitKm sensorLimitKm]);
ylim(sensorAxes,[-sensorLimitKm sensorLimitKm]);

%% ========================================================================
%  Figure 2: all RSO truth trajectories and optimized sensors
%  ========================================================================

truthStateHistories = validation.truthStateHistories;
assert(ndims(truthStateHistories) == 3 && ...
    size(truthStateHistories,1) >= 3, ...
    "Validation truth-state histories have an unexpected size.");
assert(all(isfinite(truthStateHistories(1:3,:,:)),"all"), ...
    "RSO truth trajectories contain nonfinite values.");

numberOfObjects = size(truthStateHistories,3);
trajectoryColors = turbo(max(numberOfObjects,2));
trajectoryColors = trajectoryColors(1:numberOfObjects,:);

rsoFigure = figure( ...
    "Name","RSO Population", ...
    "Color",backgroundColor, ...
    "Units","inches", ...
    "Position",[1 1 exportWidthInches exportHeightInches], ...
    "Renderer","opengl");

rsoFigure.InvertHardcopy = "off";

rsoAxes = axes( ...
    rsoFigure, ...
    "Position",[0.13 0.12 0.74 0.80]);

hold(rsoAxes,"on");
axis(rsoAxes,"equal");
box(rsoAxes,"on");
grid(rsoAxes,"on");

rsoAxes.Color = backgroundColor;
rsoAxes.FontName = fontName;
rsoAxes.FontSize = axisFontSize;
rsoAxes.XColor = textColor;
rsoAxes.YColor = textColor;
rsoAxes.ZColor = textColor;
rsoAxes.GridColor = gridColor;
rsoAxes.MinorGridColor = gridColor;
rsoAxes.GridAlpha = 0.65;
rsoAxes.LineWidth = 1.0;

[moonX,moonY,moonZ] = sphere(64);
moonHandle = surf( ...
    rsoAxes, ...
    moonRadiusKm*moonX, ...
    moonRadiusKm*moonY, ...
    moonRadiusKm*moonZ, ...
    "FaceColor",moonColor, ...
    "EdgeColor","none", ...
    "FaceAlpha",0.96, ...
    "DisplayName","Moon");

for objectIndex = 1:numberOfObjects
    currentPositionHistory = ...
        truthStateHistories(1:3,:,objectIndex);

    if objectIndex == 1
        trajectoryHandle = plot3( ...
            rsoAxes, ...
            currentPositionHistory(1,:), ...
            currentPositionHistory(2,:), ...
            currentPositionHistory(3,:), ...
            "Color",trajectoryColors(objectIndex,:), ...
            "LineWidth",1.35, ...
            "DisplayName",sprintf("RSO trajectories (%d)",numberOfObjects));
    else
        plot3( ...
            rsoAxes, ...
            currentPositionHistory(1,:), ...
            currentPositionHistory(2,:), ...
            currentPositionHistory(3,:), ...
            "Color",trajectoryColors(objectIndex,:), ...
            "LineWidth",1.35, ...
            "HandleVisibility","off");
    end

    scatter3( ...
        rsoAxes, ...
        currentPositionHistory(1,1), ...
        currentPositionHistory(2,1), ...
        currentPositionHistory(3,1), ...
        18, ...
        "o", ...
        "MarkerFaceColor",trajectoryColors(objectIndex,:), ...
        "MarkerEdgeColor",trajectoryColors(objectIndex,:), ...
        "HandleVisibility","off");
end

sensorDisplayRadiusKm = moonRadiusKm + 10;
sensorXKm = ...
    sensorDisplayRadiusKm*cosd(bestSensorLatitudeDeg).* ...
    cosd(bestSensorLongitudeDeg);
sensorYKm = ...
    sensorDisplayRadiusKm*cosd(bestSensorLatitudeDeg).* ...
    sind(bestSensorLongitudeDeg);
sensorZKm = ...
    sensorDisplayRadiusKm*sind(bestSensorLatitudeDeg);

rsoSensorHandle = scatter3( ...
    rsoAxes, ...
    sensorXKm, ...
    sensorYKm, ...
    sensorZKm, ...
    75, ...
    "o", ...
    "MarkerFaceColor",sensorColor, ...
    "MarkerEdgeColor",textColor, ...
    "LineWidth",1.4, ...
    "DisplayName","Optimized sensors");

xlabel(rsoAxes,"MCI x [km]", ...
    "Color",textColor, ...
    "FontName",fontName, ...
    "FontSize",labelFontSize, ...
    "FontWeight","bold");
ylabel(rsoAxes,"MCI y [km]", ...
    "Color",textColor, ...
    "FontName",fontName, ...
    "FontSize",labelFontSize, ...
    "FontWeight","bold");
zlabel(rsoAxes,"MCI z [km]", ...
    "Color",textColor, ...
    "FontName",fontName, ...
    "FontSize",labelFontSize, ...
    "FontWeight","bold");

view(rsoAxes,35,-22);

rsoLegend = legend( ...
    rsoAxes, ...
    [moonHandle trajectoryHandle rsoSensorHandle], ...
    "Moon", ...
    sprintf("RSO trajectories (%d)",numberOfObjects), ...
    "Optimized sensors", ...
    "Location","northeast");

rsoLegend.Color = boxColor;
rsoLegend.EdgeColor = boxEdgeColor;
rsoLegend.TextColor = textColor;
rsoLegend.FontName = fontName;
rsoLegend.FontSize = legendFontSize;

%% ========================================================================
%  Figure 3: convergence versus function evaluations
%  ========================================================================

referenceFe = studyState.runStates{1}.history.fe(:);
numberOfRuns = studyState.numberOfRuns;
numberOfHistoryPoints = numel(referenceFe);
scoreHistory = NaN(numberOfHistoryPoints,numberOfRuns);

for runIndex = 1:numberOfRuns
    currentRun = studyState.runStates{runIndex};

    assert(isequal(currentRun.history.fe(:),referenceFe), ...
        "Run %d does not share the common FE grid.",runIndex);

    scoreHistory(:,runIndex) = -currentRun.history.bestJ(:);
end

meanScore = mean(scoreHistory,2);
stdScore = std(scoreHistory,0,2);
runColors = turbo(max(numberOfRuns,2));
runColors = runColors(1:numberOfRuns,:);

convergenceFigure = figure( ...
    "Name","Optimization Convergence", ...
    "Color",backgroundColor, ...
    "Units","inches", ...
    "Position",[1 1 exportWidthInches convergenceHeightInches], ...
    "Renderer","painters");

convergenceFigure.InvertHardcopy = "off";

convergenceAxes = axes( ...
    convergenceFigure, ...
    "Position",[0.14 0.17 0.81 0.77]);

hold(convergenceAxes,"on");
box(convergenceAxes,"on");
grid(convergenceAxes,"on");

convergenceAxes.Color = backgroundColor;
convergenceAxes.FontName = fontName;
convergenceAxes.FontSize = axisFontSize;
convergenceAxes.XColor = textColor;
convergenceAxes.YColor = textColor;
convergenceAxes.GridColor = gridColor;
convergenceAxes.GridAlpha = 0.70;
convergenceAxes.LineWidth = 1.0;

for runIndex = 1:numberOfRuns
    plot( ...
        convergenceAxes, ...
        referenceFe, ...
        scoreHistory(:,runIndex), ...
        "Color",runColors(runIndex,:), ...
        "LineWidth",1.0, ...
        "HandleVisibility","off");
end

meanHandle = plot( ...
    convergenceAxes, ...
    referenceFe,meanScore, ...
    "Color",meanColor, ...
    "LineWidth",2.6, ...
    "DisplayName","Mean best-so-far score");

stdHandle = plot( ...
    convergenceAxes, ...
    referenceFe,meanScore + stdScore, ...
    "--", ...
    "Color",standardDeviationColor, ...
    "LineWidth",1.5, ...
    "DisplayName","Mean \pm 1 std");

plot( ...
    convergenceAxes, ...
    referenceFe,meanScore - stdScore, ...
    "--", ...
    "Color",standardDeviationColor, ...
    "LineWidth",1.5, ...
    "HandleVisibility","off");

xlabel(convergenceAxes,"Function Evaluations", ...
    "Color",textColor, ...
    "FontName",fontName, ...
    "FontSize",labelFontSize, ...
    "FontWeight","bold");

if string(studyState.config.objectiveMode) == "coverage"
    yLabelText = "Best Coverage Score";
else
    yLabelText = "Best Information Score";
end

ylabel(convergenceAxes,yLabelText, ...
    "Color",textColor, ...
    "FontName",fontName, ...
    "FontSize",labelFontSize, ...
    "FontWeight","bold");

xlim(convergenceAxes,[referenceFe(1) referenceFe(end)]);

convergenceLegend = legend( ...
    convergenceAxes,[meanHandle stdHandle], ...
    "Mean best-so-far score", ...
    "Mean \pm 1 std", ...
    "Location","southeast");

convergenceLegend.Color = boxColor;
convergenceLegend.EdgeColor = boxEdgeColor;
convergenceLegend.TextColor = textColor;
convergenceLegend.FontName = fontName;
convergenceLegend.FontSize = legendFontSize;

%% ========================================================================
%  Export
%  ========================================================================

drawnow;

exportgraphics( ...
    sensorAxes, ...
    sensorOutputFile, ...
    "ContentType","vector", ...
    "BackgroundColor",backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",exportWidthInches, ...
    "Height",exportHeightInches, ...
    "Padding",exportPaddingInches, ...
    "PreserveAspectRatio","on");

exportgraphics( ...
    rsoAxes, ...
    rsoOutputFile, ...
    "ContentType","image", ...
    "Resolution",600, ...
    "BackgroundColor",backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",exportWidthInches, ...
    "Height",exportHeightInches, ...
    "Padding",exportPaddingInches, ...
    "PreserveAspectRatio","on");

exportgraphics( ...
    convergenceAxes, ...
    convergenceOutputFile, ...
    "ContentType","vector", ...
    "BackgroundColor",backgroundColor, ...
    "Colorspace","rgb", ...
    "Units","inches", ...
    "Width",exportWidthInches, ...
    "Height",convergenceHeightInches, ...
    "Padding",exportPaddingInches, ...
    "PreserveAspectRatio","on");

%% ========================================================================
%  Return handles and paths
%  ========================================================================

figureInfo = struct();
figureInfo.sensorNetwork = sensorFigure;
figureInfo.rsoPopulation = rsoFigure;
figureInfo.convergence = convergenceFigure;
figureInfo.sensorOutputFile = string(sensorOutputFile);
figureInfo.rsoOutputFile = string(rsoOutputFile);
figureInfo.convergenceOutputFile = string(convergenceOutputFile);

fprintf("\nOptimization-pilot figures exported.\n");
fprintf("  Sensors:     %s\n",sensorOutputFile);
fprintf("  RSO population: %s\n",rsoOutputFile);
fprintf("  Convergence: %s\n",convergenceOutputFile);

end

%% ========================================================================
%  Local helper
%  ========================================================================

function summaryFile = findLatestPilotSummary(resultsDirectory)

runRoot = fullfile(resultsDirectory,"optimization_runs");
assert(isfolder(runRoot), ...
    "Optimization run directory was not found: %s",runRoot);

summaryFiles = dir(fullfile(runRoot,"**","study_summary.mat"));
assert(~isempty(summaryFiles), ...
    "No optimization study summaries were found under %s.",runRoot);

[~,sortOrder] = sort([summaryFiles.datenum],"descend");
summaryFiles = summaryFiles(sortOrder);

summaryFile = "";

for fileIndex = 1:numel(summaryFiles)
    candidateFile = fullfile( ...
        summaryFiles(fileIndex).folder,summaryFiles(fileIndex).name);

    candidateData = load(candidateFile,"studyState");

    if ~isfield(candidateData,"studyState")
        continue
    end

    candidateStudy = candidateData.studyState;

    isPilot = ...
        isfield(candidateStudy,"numberOfRuns") && ...
        candidateStudy.numberOfRuns == 10 && ...
        isfield(candidateStudy,"config") && ...
        isfield(candidateStudy.config,"functionEvaluationBudget") && ...
        candidateStudy.config.functionEvaluationBudget == 1200 && ...
        isfield(candidateStudy,"validation") && ...
        isfield(candidateStudy.validation,"overallBest");

    if isPilot
        summaryFile = string(candidateFile);
        break
    end
end

assert(strlength(summaryFile) > 0, ...
    "No completed 10-run, 1200-FE pilot summary was found.");

end
