function manifest = validateManuscriptArtifacts(outputDirectory,userConfig)
% VALIDATEMANUSCRIPTARTIFACTS Check generated products against the paper.
%
% The manifest mirrors the attached AAS TeX source (2026-09-20). Products
% whose underlying study is optional are reported but do not raise an error.

arguments
    outputDirectory (1,1) string
    userConfig (1,1) struct = struct()
end

tableDirectory=fullfile(outputDirectory,"tables");

figureFiles=[ ...
    "CLPS_Southern_Hemisphere_Design_Domain.eps"; ...
    "reference_frame_moon_centered.eps"; ...
    "reference_frame_sensor_centered.eps"; ...
    "angles_only_right_ascension_geometry.eps"; ...
    "angles_only_declination_geometry.eps"; ...
    "LOLA_Global_DEM.eps"; ...
    "Synthetic_Lunar_DEM.eps"; ...
    "Exclusion_Constraint_Schematic.eps"; ...
    "optimization_workflow.tex"; ...
    "convergence_information.eps"; ...
    "convergence_coverage.eps"; ...
    "network_locations_vs_ns_information.eps"; ...
    "network_locations_vs_ns_coverage.eps"; ...
    "design_rso_tracking_heatmaps.eps"; ...
    "monte_carlo_information_n3.eps"; ...
    "monte_carlo_coverage_n3.eps"; ...
    "monte_carlo_information_n5.eps"; ...
    "monte_carlo_coverage_n5.eps"; ...
    "monte_carlo_information_n7.eps"; ...
    "monte_carlo_coverage_n7.eps"; ...
    "monte_carlo_information_n10.eps"; ...
    "monte_carlo_coverage_n10.eps"; ...
    "domain_comparison_locations.eps"; ...
    "domain_comparison_metrics.eps"; ...
    "operational_rso_tracking_heatmaps.eps"];

tableFiles=[ ...
    "completed_clps_landing_sites.csv"; ...
    "planned_clps_landing_regions.csv"; ...
    "optimization_rso_population.csv"; ...
    "lunar_peaks_dem.csv"; ...
    "dominant_craters.csv"; ...
    "celestial_exclusion_parameters.csv"; ...
    "iod_prior_weighting.csv"; ...
    "P0_initial_covariance.csv"; ...
    "optimization_parameters.csv"; ...
    "network_summary.csv"; ...
    "domain_comparison.csv"; ...
    "spacecraft_tracking.csv"];

optionalFigures=startsWith(figureFiles,"monte_carlo_") | ...
    startsWith(figureFiles,"domain_comparison_") | ...
    figureFiles=="operational_rso_tracking_heatmaps.eps";
optionalTables=tableFiles=="domain_comparison.csv" | ...
    tableFiles=="spacecraft_tracking.csv";

kind=[repmat("figure",numel(figureFiles),1); ...
    repmat("table",numel(tableFiles),1)];
file=[figureFiles;tableFiles];
optional=[optionalFigures;optionalTables];
exists=false(size(file));
path=strings(size(file));

for k=1:numel(file)
    if kind(k)=="figure"
        path(k)=fullfile(outputDirectory,file(k));
    else
        path(k)=fullfile(tableDirectory,file(k));
    end
    exists(k)=isfile(path(k));
end

status=repmat("present",numel(file),1);
status(~exists & ~optional)="MISSING";
status(~exists & optional)="missing optional";

manifest=table(kind,file,optional,exists,status,path, ...
    'VariableNames',{'Kind','File','Optional','Exists','Status','Path'});

manifestFile=fullfile(outputDirectory,"manuscript_artifact_manifest.csv");
writetable(manifest,manifestFile);

missingRequired=manifest(~manifest.Optional & ~manifest.Exists,:);
if ~isempty(missingRequired)
    fprintf("\nMissing required manuscript artifacts:\n");
    disp(missingRequired(:,{'Kind','File'}));
    if isfield(userConfig,"strictArtifactValidation") && ...
            logical(userConfig.strictArtifactValidation)
        error("validateManuscriptArtifacts:MissingRequired", ...
            "%d required manuscript artifacts are missing.", ...
            height(missingRequired));
    end
else
    fprintf("\nAll required manuscript artifacts are present.\n");
end

missingOptional=manifest(manifest.Optional & ~manifest.Exists,:);
if ~isempty(missingOptional)
    fprintf("Optional manuscript artifacts not yet available:\n");
    disp(missingOptional(:,{'Kind','File'}));
end

fprintf("Artifact manifest:\n  %s\n",manifestFile);
end
