function outputFile = writeOptimizationWorkflowTikz(userConfig)
% WRITEOPTIMIZATIONWORKFLOWTIKZ Write the manuscript optimization workflow.
%
% The optimization workflow is intentionally kept in TikZ because it is a
% process diagram rather than a numerical MATLAB plot. This generator keeps
% the diagram source under the same manuscript-artifact workflow.

arguments
    userConfig (1,1) struct = struct()
end

scriptDirectory=fileparts(mfilename("fullpath"));
projectRoot=fileparts(scriptDirectory);
outputDirectory=fullfile(projectRoot,"results","manuscript_artifacts");
if isfield(userConfig,"outputDirectory")
    outputDirectory=string(userConfig.outputDirectory);
end
if ~isfolder(outputDirectory), mkdir(outputDirectory); end

outputFile=fullfile(outputDirectory,"optimization_workflow.tex");
fid=fopen(outputFile,"w");
assert(fid>=0,"Could not open optimization workflow output file.");
cleanup=onCleanup(@()fclose(fid));

fprintf(fid,"%s\n", ...
"\\begin{figure*}[htbp]", ...
"    \\centering", ...
"    \\begin{tikzpicture}[", ...
"        font=\\footnotesize,", ...
"        >=Latex,", ...
"        pre/.style={draw,rounded corners=1.2pt,align=center,minimum height=10mm,text width=25mm,inner sep=2pt},", ...
"        search/.style={draw,rounded corners=1.2pt,align=center,minimum height=10mm,text width=31mm,inner sep=2pt},", ...
"        db/.style={draw,rounded corners=1.2pt,align=center,minimum height=10mm,text width=25mm,inner sep=2pt,very thick},", ...
"        decision/.style={draw,diamond,aspect=2.1,align=center,inner sep=1pt,text width=21mm},", ...
"        line/.style={->,thick}", ...
"    ]", ...
"    \\node[font=\\bfseries,anchor=west] at (-1.05,1.08) {Precomputation};", ...
"    \\node[pre] (terrain) at (0,0) {Lunar DEM and\\\\candidate grid};", ...
"    \\node[pre] (rso) at (3.4,0) {RSO population and\\\\orbit propagation};", ...
"    \\node[pre] (screen) at (6.8,0) {Terrain and Earth/Sun\\\\visibility screening};", ...
"    \\node[db] (database) at (10.2,0) {Frozen optimization\\\\database};", ...
"    \\draw[line] (terrain.east)--(rso.west);", ...
"    \\draw[line] (rso.east)--(screen.west);", ...
"    \\draw[line] (screen.east)--(database.west);", ...
"    \\node[font=\\bfseries,anchor=west] at (-1.05,-1.15) {Genetic-algorithm search};", ...
"    \\node[search] (config) at (0,-2.15) {Define $N_s$, objective,\\\\and FE budget};", ...
"    \\node[search] (init) at (4.0,-2.15) {Initialize integer-feasible\\\\GA population};", ...
"    \\node[search] (candidate) at (8.0,-2.15) {Generate candidate\\\\network $\\mathbf{x}$};", ...
"    \\node[search] (retrieve) at (11.9,-2.15) {Retrieve selected-site\\\\data};", ...
"    \\draw[line] (config.east)--(init.west);", ...
"    \\draw[line] (init.east)--(candidate.west);", ...
"    \\draw[line] (candidate.east)--(retrieve.west);", ...
"    \\draw[line] (database.south)--(retrieve.north);", ...
"    \\node[search] (objective) at (0,-4.55) {Evaluate coverage or\\\\information cost};", ...
"    \\node[search] (update) at (4.0,-4.55) {Update population and\\\\best-so-far incumbent};", ...
"    \\node[decision] (stop) at (8.9,-4.55) {FE budget\\\\reached?};", ...
"    \\node[search] (result) at (12.8,-4.55) {Return best feasible\\\\sensor network};", ...
"    \\coordinate (shared) at (8.0,-3.35);", ...
"    \\draw[line] (retrieve.south)--++(0,-4mm)-|(objective.north);", ...
"    \\draw[line] (shared)--(candidate.south);", ...
"    \\draw[line] (objective.east)--(update.west);", ...
"    \\draw[line] (update.east)--(stop.west);", ...
"    \\draw[line] (stop.east)--(result.west);", ...
"    \\node[font=\\scriptsize,fill=white,inner sep=0.8pt] at ($(stop.east)!0.5!(result.west)+(0,4mm)$) {Yes};", ...
"    \\coordinate (loopbottom) at ($(stop.south)+(0,-8mm)$);", ...
"    \\coordinate (loopleft) at ($(loopbottom)+(-18mm,0)$);", ...
"    \\draw[thick] (stop.south)--(loopbottom)--(loopleft)|-(shared);", ...
"    \\node[font=\\scriptsize,fill=white,inner sep=0.8pt] at ($(loopbottom)!0.5!(loopleft)+(0,-3mm)$) {No};", ...
"    \\end{tikzpicture}", ...
"    \\caption{Lunar-surface sensor-network optimization workflow.}", ...
"    \\label{fig:optimization_workflow}", ...
"\\end{figure*}");
end
