function [initialState, initialCovariance, referenceTime, diagnostics] = anglesOnlyIod(times, rightAscension, declination, observerPositionsMci, acquisitionIndices, measurementCovariance, numberOfSamples, randomSeed, moonMu)
% ANGLESONLYIOD Run Gauss IOD, full refinement, and Monte Carlo P0.
%
% Inputs:
%   times                 - Nx1 observation times, s
%   rightAscension        - Nx1 right ascension measurements, rad
%   declination           - Nx1 declination measurements, rad
%   observerPositionsMci  - Nx3 observer positions in MCI, km
%   acquisitionIndices    - LOS-established acquisition observations
%   measurementCovariance - 2x2 RA/Dec covariance, rad^2
%   numberOfSamples       - Number of Monte Carlo samples
%   randomSeed            - Monte Carlo random-number seed
%   moonMu                - Lunar gravitational parameter, km^3/s^2
%
% Outputs:
%   initialState      - 6x1 refined state at referenceTime
%   initialCovariance - 6x6 Monte Carlo covariance, P0
%   referenceTime     - End of the acquisition arc, s
%   diagnostics       - Gauss, refinement, and Monte Carlo information

arguments
    times (:,1) double
    rightAscension (:,1) double
    declination (:,1) double
    observerPositionsMci (:,3) double
    acquisitionIndices (:,1) double {mustBeInteger,mustBePositive}
    measurementCovariance (2,2) double
    numberOfSamples (1,1) double ...
        {mustBeInteger,mustBePositive} = 500
    randomSeed (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 1
    moonMu (1,1) double {mustBePositive} = 4902.800066
end

numberOfObservations = length(times);

if length(rightAscension) ~= numberOfObservations || ...
        length(declination) ~= numberOfObservations || ...
        size(observerPositionsMci,1) ~= numberOfObservations

    error("anglesOnlyIod:InvalidDimensions", ...
        "Observation arrays must contain the same number of rows.");
end

if any(acquisitionIndices > numberOfObservations)
    error("anglesOnlyIod:InvalidIndices", ...
        "An acquisition index exceeds the observation array.");
end

acquisitionIndices = sort(unique(acquisitionIndices));

% Gauss requires three distinct observation epochs.
[~,uniqueTimeLocations] = unique( ...
    times(acquisitionIndices),"stable");

distinctTimeIndices = ...
    acquisitionIndices(uniqueTimeLocations);

numberOfDistinctTimes = length(distinctTimeIndices);

if numberOfDistinctTimes < 3
    error("anglesOnlyIod:InsufficientTimes", ...
        "IOD requires at least three distinct observation times.");
end

middleLocation = round((numberOfDistinctTimes + 1)/2);

gaussIndices = distinctTimeIndices([ ...
    1;
    middleLocation;
    numberOfDistinctTimes]);

gaussMiddleTime = times(gaussIndices(2));
referenceTime = times(acquisitionIndices(end));

%% Nominal IOD

lineOfSightMci = raDecToLineOfSight( ...
    rightAscension,declination);

[gaussState,gaussDiagnostics] = ...
    iod.gaussAnglesOnly( ...
        times(gaussIndices), ...
        observerPositionsMci(gaussIndices,:), ...
        lineOfSightMci(gaussIndices,:), ...
        moonMu);

refinementGuess = propagateState( ...
    gaussMiddleTime, ...
    referenceTime, ...
    gaussState, ...
    moonMu);

[initialState,refinementDiagnostics] = ...
    iod.refineAnglesOnly( ...
        referenceTime, ...
        times(acquisitionIndices), ...
        rightAscension(acquisitionIndices), ...
        declination(acquisitionIndices), ...
        observerPositionsMci(acquisitionIndices,:), ...
        refinementGuess, ...
        measurementCovariance, ...
        moonMu);

%% Monte Carlo P0

rng(randomSeed,"twister");

noiseFactor = chol(measurementCovariance,"lower");

stateSamples = NaN(6,numberOfSamples);
successfulSamples = false(numberOfSamples,1);

numberOfAcquisitionObservations = ...
    length(acquisitionIndices);

for sampleIndex = 1:numberOfSamples

    measurementNoise = noiseFactor * ...
        randn(2,numberOfAcquisitionObservations);

    sampledRightAscension = rightAscension;
    sampledDeclination = declination;

    sampledRightAscension(acquisitionIndices) = ...
        rightAscension(acquisitionIndices) + ...
        measurementNoise(1,:).';

    sampledRightAscension(acquisitionIndices) = atan2( ...
        sin(sampledRightAscension(acquisitionIndices)), ...
        cos(sampledRightAscension(acquisitionIndices)));

    sampledDeclination(acquisitionIndices) = ...
        declination(acquisitionIndices) + ...
        measurementNoise(2,:).';

    sampledLineOfSight = raDecToLineOfSight( ...
        sampledRightAscension,sampledDeclination);

    try
        sampledGaussState = iod.gaussAnglesOnly( ...
            times(gaussIndices), ...
            observerPositionsMci(gaussIndices,:), ...
            sampledLineOfSight(gaussIndices,:), ...
            moonMu);

        sampledRefinementGuess = propagateState( ...
            gaussMiddleTime, ...
            referenceTime, ...
            sampledGaussState, ...
            moonMu);

        [sampledState,sampledDiagnostics] = ...
            iod.refineAnglesOnly( ...
                referenceTime, ...
                times(acquisitionIndices), ...
                sampledRightAscension(acquisitionIndices), ...
                sampledDeclination(acquisitionIndices), ...
                observerPositionsMci(acquisitionIndices,:), ...
                sampledRefinementGuess, ...
                measurementCovariance, ...
                moonMu);

        if sampledDiagnostics.exitFlag > 0 && ...
                all(isfinite(sampledState))

            stateSamples(:,sampleIndex) = sampledState;
            successfulSamples(sampleIndex) = true;
        end
    catch
        successfulSamples(sampleIndex) = false;
    end
end

stateSamples = stateSamples(:,successfulSamples);

numberOfSuccessfulSamples = size(stateSamples,2);
minimumSuccessfulSamples = max(10,ceil(0.8*numberOfSamples));

if numberOfSuccessfulSamples < minimumSuccessfulSamples
    error("anglesOnlyIod:InsufficientMonteCarloSolutions", ...
        "Only %d of %d Monte Carlo samples converged.", ...
        numberOfSuccessfulSamples,numberOfSamples);
end

initialCovariance = cov(stateSamples.',0);

diagnostics = struct( ...
    "gaussIndices",gaussIndices, ...
    "gauss",gaussDiagnostics, ...
    "refinement",refinementDiagnostics, ...
    "numberOfRequestedSamples",numberOfSamples, ...
    "numberOfSuccessfulSamples",numberOfSuccessfulSamples, ...
    "successfulFraction", ...
        numberOfSuccessfulSamples/numberOfSamples, ...
    "stateSamples",stateSamples);

end

function lineOfSightMci = raDecToLineOfSight( ...
    rightAscension,declination)

lineOfSightMci = [ ...
    cos(declination).*cos(rightAscension), ...
    cos(declination).*sin(rightAscension), ...
    sin(declination)];

end

function propagatedState = propagateState( ...
    initialTime,finalTime,initialState,moonMu)

if finalTime == initialTime
    propagatedState = initialState;
    return
end

odeOptions = odeset( ...
    "RelTol",1e-11, ...
    "AbsTol",1e-12);

[~,stateHistory] = ode45( ...
    @(time,state) orbitDynamics.lunarTwoBodyDynamics( ...
        time,state,moonMu), ...
    [initialTime,finalTime], ...
    initialState, ...
    odeOptions);

propagatedState = stateHistory(end,:).';

end